### PR TITLE
remove lazy from TraversalBuilder field

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by jrudolph** [comment]
What's the rationale? Is it that the lazy val introduces that volatile var internally? Because otherwise, this change is basically a manual expansion of the lazy val semantics, it seems.

**Comment by ktoso** [comment]
> Is it that the lazy val introduces that volatile var internally? Because otherwise, this change is basically a manual expansion of the lazy val semantics, it seems.

Not a volatile but a double `synchronized` (locks, aaaa!). This reimpls lazy val however ignoring synchronisation, which is fine since the emitted value is immutable and always the same anyway

For reference, discussed in https://github.com/akka/akka/pull/22526

**Comment by patriknw** [comment]
yes, the rationale is the small overhead of `lazy` (we normally don't use `lazy` unless we have to)

**Comment by jrudolph** [comment]
> Not a volatile but a double synchronized (locks, aaaa!).

Ah, right, the fast path is free of locks but the initialization path will have locks.

**Comment by jrudolph** [comment]
I see, thanks for the explanation.

**Review by 2m — APPROVED** [review]
LGTM

**Review by ktoso — APPROVED** [review]
LGTM

**Pull request merged**
