### PR TITLE
Allowing arbitrary random number generators

### PR DESCRIPTION
**Pull request by itssunilsid**
References #29188

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @itssunilsid,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by itssunilsid** [comment]
travis CI failed due to removal of GeneratorSha1Prng and GeneratorNativePrng contstants. Shall I add them to mima exclusion filters?

**Comment by raboof** [comment]
Yes, since they are in a `@InternalApi private[akka]` object they're not public API and they may be added to the mima filters :+1:

**Review by raboof — APPROVED** [review]
Thanks!

**Review by ennru — APPROVED** [review]
LGTM.

**Comment by ennru** [comment]
Thank you! And welcome as Akka contributor!

**Pull request merged**
