### PR TITLE
Remove CallerSensitive

### PR DESCRIPTION
**Pull request by raboof**
Having this file at all was a workaround for a problem with building on jdk9
for jdk8, but I can no longer reproduce this problem.

See also https://github.com/akka/akka/pull/25326

Let's make sure our jdk9 jenkins build succeeds before merging this PR.

### CODE REVIEW

**Comment by raboof** [comment]
PLS BUILD

**Comment by raboof** [comment]
Jenkins failure seems to be MiMa issues related to the 2.13 branch?

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/95/

**Comment by raboof** [comment]
Looks like it worked for our jdk11 jenkins job

**Review by johanandren — APPROVED** [review]

**Pull request merged**
