### PR TITLE
chore: remove unnecessary string interpolation

### PR DESCRIPTION
**Pull request by Roiocam**
Accidentally found some chores to do.

The regular expression `[^s]"""(.*\$+.*)"""` is showing that without any incorrect modifications.

Unexpectedly, there have been some line break modifications, and it is uncertain whether these changes were made by scalafmt or IDEA.

### CODE REVIEW

**Comment by johanandren** [comment]
I'd expect at least a few of them, if not all, are because of the Scala compiler warning when it detects something that looks like an expected interpolation in a regular string, fatal warning makes compilation fail for that unless you double-$ and mark as string template.

I guess another option would be a @nowarn instead, but at least for tests, that is more intrusive/noisy.

**Comment by Roiocam** [comment]
PR passed, but unexpected cost of time, close and open to retrigger run.

**Comment by Roiocam** [comment]
After some investigations, it has been found that SBT is unable to provide the execution time for tasks on non-root projects (which is possible with Maven). 
It is made hard to judge whether the execution time of 42 minutes for 'validatePullRequest` is considered slow or within the normal range. 

Park here to await the feedback from the reviewer.

**Comment by johanandren** [comment]
Validate pull requests will try to select tests relevant to the things changed, cutting down time for small changes, with a PR touching lot of modules and tests like this I'd say it is expected to take quite some time.

**Review by johanandren — APPROVED** [review]
LGTM

**Pull request merged**
