### PR TITLE
Clarify leveldb dependencies in docs (#22816)

### PR DESCRIPTION
**Pull request by victornoel**
Hi,

Finally managed to make a PR for #22816 :)

I decided to remove any reference to the immature leveldb dependency from the introduction and to only talk about it in the testing section where non-native mechanism is explained.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @victornoel,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Comment by johanandren** [comment]
OK TO TEST

**Review by patriknw — APPROVED** [review]
LGTM, thanks

**Comment by patriknw** [comment]
Refs #22816

**Pull request merged**
