### PR TITLE
bump: Regenerate with protoc 3.21.12

### PR DESCRIPTION
**Pull request by patriknw**
On top of https://github.com/akka/akka/pull/32149
This commit is with author `Auto Format <nobody>`, which we have used previously.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one commit author (nobody) is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one commit author (nobody) is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one commit author (nobody) is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by patriknw** [comment]
We have used 'nobody` previously for such auto format things so I'm ignoring the cla validator.

**Pull request merged**
