### PR TITLE
Upgrade jackson to 2.11.4 

### PR DESCRIPTION
**Pull request by johanandren**
References #30126

All tests passing with just the version bump (I tried with 2.12 as well but for that there were test failures).

### CODE REVIEW

**Comment by ignasi35** [comment]
Do we have an idea of what default behaviors changed between 2.10 and 2.11 that may sneak into user code unnoticed?

**Comment by johanandren** [comment]
Not really, no. I haven't found a good way to compare either, but I'll dig some more today.
At least the akka-serialization-jackson test suite passed without any changes needed.

**Comment by ignasi35** [comment]
Hmmm, most [changes](https://github.com/FasterXML/jackson-dataformats-binary/blob/master/release-notes/VERSION-2.x#L62-L97) seem to be on the Avro support.

I'm not sure what the `CBORGenerator.Feature.WRITE_MINIMAL_INTS` change in 2.11.0 means, though.

**Comment by johanandren** [comment]
Some more changelogs: 

jackson-core: https://github.com/FasterXML/jackson-core/blob/master/release-notes/VERSION-2.x#L53-L77
jackson-annotations: https://github.com/FasterXML/jackson-annotations/blob/master/release-notes/VERSION-2.x#L36-L39
jackson-module-scala: https://github.com/FasterXML/jackson-module-scala/blob/master/release-notes/VERSION.md#version-2114

jackson-datatype-jdk8, jackson-datatype-jsr310, jackson-module-parameter-names, jackson-dataformat-cbor looks like they contain no changes.

**Comment by johanandren** [comment]
Does not look like there is anything else potentially troublesome featurewise. 

As far as I understand the minimal ints change it is an optimization of how ints/longs are rendered into cbor when that feature is enabled (it is by default). I think that those minimal ints could always be parsed and that also rendering them like that is not a problem for wire compatibility

**Review by octonato — APPROVED** [review]
👍

**Review by patriknw — APPROVED** [review]
LGTM, important that we highlight this change in the release notes, and also link to Jackson release notes

**Pull request merged**
