### PR TITLE
#21466 Wrong protocol name expected in tests when using Artery

### PR DESCRIPTION
**Pull request by drewhk**

### CODE REVIEW

**Comment by drewhk** [comment]
Fixes #21466

**Review by johanandren — APPROVED** [review]

**Comment by patriknw** [comment]
LGTM
I think I saw a lot of failing tests in distributed-data, so is this enough?
Have you ran all of them with Artery?

**Comment by drewhk** [comment]
I only checked the failing test. I can test the whole suite there then.

**Comment by drewhk** [comment]
Ok, fixed another one.

**Comment by ktoso** [comment]
LGTM

**Pull request merged**
