### PR TITLE
Bump shaded protobuf version to 3.16.1 for DoS fix

### PR DESCRIPTION
**Pull request by johanandren**
References #31069

### CODE REVIEW

**Review by patriknw — APPROVED** [review]
LGTM, assuming that it's wire compatible

**Comment by johanandren** [comment]
Yep, only change is "cosmetic" in the TCK

**Comment by johanandren** [comment]
Sorry, that comment was unrelated, multi-repo-tasking :/

**Comment by johanandren** [comment]
Upgrade testing is on travis, last run was tonight, so that should give us some extra certainty.

**Review by ennru — APPROVED** [review]
LGTM.

**Pull request merged**
