### PR TITLE
str #20144 UnzipWith pushed twice when sinks were closing

### PR DESCRIPTION
**Pull request by johanandren**
Backport for #20144, Cherry pick of 2cb0f16

### CODE REVIEW

**Comment by johanandren** [comment]
I have no idea what MiMa is on about here, doesn't report any fails locally and the changes are not incompatible.

**Comment by patriknw** [comment]
PLS BUILD

**Comment by patriknw** [comment]
and that is in `SubstreamSubscriptionTimeoutSpec`

**Comment by patriknw** [comment]
PLS BUILD

**Pull request merged**
