### PR TITLE
Fix ExtensionSpec

### PR DESCRIPTION
**Pull request by raboof**
Error introduced by #27911, likely in combination with
another change that was merged in parallel

## References

References #xxxx

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
Because for those two cases it will always be terminating and wraps the exception?

LGTM

**Comment by raboof** [comment]
> Because for those two cases it will always be terminating and wraps the exception?

I'm assuming so - it could also be a race condition, but I have only seen this behavior so far...

**Comment by patriknw** [comment]
hm, I'll debug this to make sure I understand why the ActorSystem is terminating

**Comment by patriknw** [comment]
No trace of ExtensionSpec in the validation of the other PR: https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/17767/
That is strange since it changed akka.actor.ActorSystem

**Comment by patriknw** [comment]
ah, it's stupid in  #27911, I'll create a better one

**Pull request closed without merging**
