### PR TITLE
Update license year range to 2016

### PR DESCRIPTION
**Pull request by prayagverma**

### CODE REVIEW

**Comment by patriknw** [comment]
I can't see the full diff here, does it also include single year headers, such as https://github.com/akka/akka/blob/master/akka-distributed-data/src/main/scala/akka/cluster/ddata/Key.scala#L2

**Comment by ktoso** [comment]
Fill diff: https://gist.github.com/ktoso/864bad51269c73346abe 
unsure yet if it touches all needed files though

**Comment by patriknw** [comment]
thanks, that Key.scala is not included, so it's not complete

**Comment by pra85** [comment]
@patriknw For files like https://github.com/akka/akka/blob/master/akka-distributed-data/src/main/scala/akka/cluster/ddata/Key.scala#L2

Should the license year be 2015-2016 ?

**Comment by patriknw** [comment]
yes, that is correct

**Comment by patriknw** [comment]
note that there might alread exist other ranges, not starting with 2009, e.g. 2014-2015

**Comment by pra85** [comment]
@patriknw I have updated my pull request to handle files which have  2015 alone in Copyright.

**Comment by patriknw** [comment]
thanks

**Comment by drewhk** [comment]
this does not merge cleanly now unfortunately. I close this PR for now to keep are queue clean, but this should be reopened once it has been fixed (i.e. this is not abandoned just stashed).

**Comment by pra85** [comment]
@drewhk I have updated my pull request to match with the latest `master` branch. But as this pull request is closed, therefore it might not be showing the update here.

I have doubt here, will re-opening this pull request from your end automatically show the updates that I have pushed to my `2016` branch or should I open a new pull request? Please advise, Thanks

**Comment by drewhk** [comment]
Hm, maybe it was a rebase or something that confused GitHub. Anyway, I think it is best to open a new PR, sorry for the caused inconvenience :(

**Pull request closed without merging**
