### PR TITLE
Fix calculating backoff delay in order to prevent IllegalArgumentExce…

### LINKED ISSUE #29568: Bug: Supervisor with SupervisorStrategy.restartWithBackoff strategy throws exception when it calculates delay
It is similar bug to #24419 

`RestartSupervisor.calculateDelay` throws `IllegalArgument exception` if it tries to construct duration with nanos > Long.MaxValue.

```
java.lang.IllegalArgumentException: trying to construct too large duration with 1.610612736E19ns
	at scala.concurrent.duration.Duration$.fromNanos(Duration.scala:130)
	at scala.concurrent.duration.FiniteDuration.$times(Duration.scala:633)
	at akka.actor.typed.internal.RestartSupervisor$.calculateDelay(Supervision.scala:162)
	at akka.actor.typed.internal.RestartSupervisor.akka$actor$typed$internal$RestartSupervisor$$prepareRestart(Supervision.scala:334)
	at akka.actor.typed.internal.RestartSupervisor$$anonfun$handleException$4.applyOrElse(Supervision.scala:313)
	at akka.actor.typed.internal.RestartSupervisor$$anonfun$handleException$4.applyOrElse(Supervision.scala:296)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
```

### PR DESCRIPTION
**Pull request by sturmin**
apply the changes from PR #24420 to akka-typed and fixes #29568

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by patriknw** [comment]
OK TO TEST

**Review by patriknw — APPROVED** [review]
LGTM, thanks

**Review by raboof — APPROVED** [review]
Thanks!

**Pull request merged**
