### PR TITLE
=doc Add the missing closing parenthesis

### PR DESCRIPTION
**Pull request by kryger**
Also, make it clear that `AkkaAppPackaging` is actually deprecated.

### CODE REVIEW

**Comment by ktoso** [comment]
Please prefix the commit message with `=doc` in the next PR, it helps us figure out what a commit was touching (its explained in contributing.md).

Fix LGTM, thanks a lot :) :+1:

**Comment by ktoso** [comment]
(The commit, not the title of the PR needs that marker, thanks!)

**Comment by kryger** [comment]
Whoopsie :see_no_evil:

**Comment by ktoso** [comment]
No problem @kryger, for the next PR would be nice to have it though :)

**Pull request merged**
