### PR TITLE
Note in the docs that the zero value for fold and friends must be immutable (#24971)

### LINKED ISSUE #24971: Stream fold and friends are not usable with mutable collections
Created from this forum question: https://discuss.lightbend.com/t/beginner-question-regarding-splitwhen-groupby-followed-by-fold/804

`fold`, `foldAsync`, `scan` and `scanAsync` all take a zero element that is expected to be immutable, for `scan` this makes sense as the aggregate-object is passed downstream for every element, but for fold where it is only passed downstream when done, a mutable aggregate may make sense (`ArrayList` in the forum question).

For `scan` and `scanAsync` we should make a clear warning in the docs that the zero value must not be mutable.

For fold I'm not sure, should we provide a factory version as well? `fold(() => T)((T, Out) => T)`, especially for the Java side of things where immutable collections require a third party library this would be nice. If not we should clearly document that this zero should be immutable as well.

### PR DESCRIPTION
**Pull request by chunjef**
Resolves #24971

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Comment by johanandren** [comment]
Ci failure is triggered by formatting, you can fix by just compiling (which triggers autoformatting) and then commit the result

**Comment by johanandren** [comment]
Hmm, now it says you need to do the same for the test code: 
```
[error] Unformatted code found. Please run 'test:compile' and commit the reformatted code.
```
However what it lists in the build log looks like the docs markdown, so I'm not sure that is the issue it failed on.

**Review by raboof — APPROVED** [review]
Nice changes!

**Pull request merged**
