### PR TITLE
Fix description of Sink.scala#foreach

### PR DESCRIPTION
**Pull request by spaudanjo**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @spaudanjo,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by ktoso — APPROVED** [review]
LGTM thanks :)

**Comment by ktoso** [comment]
Could you fix the same typo on the Java DSL please?
`/Users/ktoso/code/akka/akka-stream/src/main/scala/akka/stream/javadsl/Sink.scala`

**Comment by spaudanjo** [comment]
Done for the JavaDSL as well, @ktoso :)

**Review by ktoso — APPROVED** [review]
Thanks! Not much to debate, simple typo fix in comment, triple sanity read the thing.

**Comment by ktoso** [comment]
OK TO TEST

**Pull request merged**
