### PR TITLE
Must we use should or should we use must???

### PR DESCRIPTION
**Pull request by raboof**
Both are identical, and we mostly used 'must' already.

### CODE REVIEW

**Review by chbatey — APPROVED** [review]
LGTM

**Review by ktoso — APPROVED** [review]
Meh, I like should but okey ;-)

**Comment by raboof** [comment]
Actually I lean towards 'should' as well, just wanted to be conservative as we appear to have more 'must' in there currently. Will update ;)

**Comment by ktoso** [comment]
Haha okey :) Swap it before anyone else makes us swap again! :D

**Comment by patriknw** [comment]
Well, in the original decision for this (probably 5+ years ago) we said that a test must pass, it's not enough that it should pass. Should sounds like it is sometimes fine that it doesn't pass. Must is more strict.

I know "should" is popular in some test driven communities.

**Comment by jlprat** [comment]
The title of the PR as it is now, it makes no sense 😉
"Use 'should' rather than 'should' consistently"

**Comment by chbatey** [comment]
I prefer must but i really don't mind as long as it is consistent

**Comment by johanandren** [comment]
I think @chbatey should (must) have the last say since he's the only native english speaker in the team. ;)

**Comment by ktoso** [comment]
To me should is simply the traditional word for this kinds of specs, originally from rspec and co ;-)
Must tries to simulate the MUST RFC wording but does not really feel so well as one does not really read those as full sentences most of the time

**Comment by patriknw** [comment]
I don't have a strong opinion (don't care) but I also don't see a strong reason for changing.

**Comment by raboof** [comment]
The scalatest docs appear to be using 'should' consistently as well

**Comment by patriknw** [comment]
What I mean is that ”must” is the old decision and is most used and that is the pick. However, if someone think should is much better I don’t mind.

**Pull request closed without merging**
