### PR TITLE
Remove doclint from javac for docs

### PR DESCRIPTION
**Pull request by chbatey**

### CODE REVIEW

**Review by patriknw — APPROVED** [review]
LGTM

**Review by raboof — APPROVED** [review]
Linting docs sounds like a good idea :) - but I guess they're linted in the 'regular' compile phase already and we want to avoid failures when doing it again in the docs phase?

**Comment by chbatey** [comment]
We musn't lint the docs in any phase as we have java docs that don't pass it that have been there since 2015 :) 
This option is in the default java options, it just seems to get wiped out by the recent fatal java changes

**Comment by chbatey** [comment]
https://github.com/akka/akka/issues/29466

**Pull request merged**
