### PR TITLE
Aeron 1.7.0

### PR DESCRIPTION
**Pull request by patriknw**
Refs https://github.com/akka/akka/issues/24169

### CODE REVIEW

**Comment by chbatey** [comment]
PLS BUILD

**Review by chbatey — APPROVED** [review]
Do we need to document any upgrade steps / concerns? Otherwise lgtm

**Comment by patriknw** [comment]
We could mention when we announce next release that this release of Artery is not binary backwards compatible, i.e. application/library must be recompiled.
```
[JVM-1]   java.lang.NoSuchMethodError: io.aeron.driver.MediaDriver$Context.driverTimeoutMs(J)Lio/aeron/driver/MediaDriver$Context;
[JVM-1]   at akka.remote.artery.ArteryTransport.startMediaDriver(ArteryTransport.scala:497)
[JVM-1]   at akka.remote.artery.ArteryTransport.start(ArteryTransport.scala:416)
```

It seems to be wire compatible though. I tried rolling upgrade with the `SimpleClusterApp` without trouble.

**Review by johanandren — APPROVED** [review]

**Comment by patriknw** [comment]
let's have it in and see if the nightlies have an opinion

**Pull request merged**
