### PR TITLE
Deprecate JavaLogger (java.utl.logging)

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by raboof** [comment]
failure was #27757

**Comment by raboof** [comment]
PLS BUILD

**Comment by raboof** [comment]
Failure is a paradox link that became invalid:
```
[09-30 12:03:41.483] [error] Unknown anchor [logging.html#java-util-logging] at /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-docs/src/main/paradox/logging.md:8
[09-30 12:03:41.484] [error] To use Logging, you must at least use the Akka actors dependency in your project, and will most likely want to configure logging via the SLF4J module (@ref:[see below](#slf4j)), or use `java.util.logging` (@ref:[see below](#java-util-logging)).
```

**Comment by patriknw** [comment]
fixed broken link

**Review by chbatey — APPROVED** [review]
LGTM

**Review by helena — APPROVED** [review]
LGTM

**Pull request merged**
