### PR TITLE
clarifies backoff's "restart" #23406

### PR DESCRIPTION
**Pull request by daniperez**
The doc is using the verb "restart" whereas the supervisor is actually stopping the actor and starting it
again. This might cause some confusion, e.g. if used along with stash, user expects the `preRestart` hook to be called during actor restart, except that if a backoff supervisor is used, that hook will not be called because the actor is going through a full stop-start cycle rather than a restart.

This commit avoids using the "restart" verb as much as possible as well as adding a note regarding the use of a backoff with a stash.

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Comment by raboof** [comment]
Refs #23406

**Review by raboof — APPROVED** [review]

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Comment by daniperez** [comment]
thanks!

**Pull request merged**
