### PR TITLE
fix osgi-dining-hakkers sample

### PR DESCRIPTION
**Pull request by TobiasPfeifer**
#20250

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @TobiasPfeifer,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by patriknw** [comment]
thanks for updating this, @TobiasPfeifer

**Comment by patriknw** [comment]
OK TO TEST

**Comment by patriknw** [comment]
LGTM

**Comment by johanandren** [comment]
LGTM

**Pull request merged**
