### PR TITLE
Optimizes retrieval of mandatoryAttributes by removing potential allo…

### PR DESCRIPTION
**Pull request by viktorklang**
…cation of OptionVal

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
LGTM

Might be better to wait for the compiler fix than to ad hoc fix all OptionVal usages though.

**Comment by patriknw** [comment]
Could you combine all your PRs related to this into one PR?
We want to revert all this when it has been fixed in the Scala compiler and it would be easier if we have one PR/commit to keep track of.

**Comment by viktorklang** [comment]
@patriknw Absolutely. Will open a new PR

**Comment by viktorklang** [comment]
Superseded by #30276

**Pull request closed without merging**
