### PR TITLE
=clut #24311 timer event may arrive after we already identified successfuly

### LINKED ISSUE #24311: Unsafe handling of TryToIdentifySingleton in ClusterSingletonProxy
`ClusterSingletonProxy` internally schedules `TryToIdentifySingleton` to self.
Under some circumstances this leads to 
```
java.io.NotSerializableException: No configured serialization-bindings for class [akka.cluster.singleton.ClusterSingletonProxy$TryToIdentifySingleton$]
    at akka.serialization.Serialization.serializerFor(Serialization.scala:236)
    at akka.serialization.Serialization.findSerializerFor(Serialization.scala:212)
    at akka.remote.MessageSerializer$.serialize(MessageSerializer.scala:44)
    at akka.remote.EndpointWriter.$anonfun$serializeMessage$1(Endpoint.scala:889)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
    at akka.remote.EndpointWriter.serializeMessage(Endpoint.scala:889)
    at akka.remote.EndpointWriter.writeSend(Endpoint.scala:780)
    at akka.remote.EndpointWriter$$anonfun$4.applyOrElse(Endpoint.scala:755)
    at akka.actor.Actor.aroundReceive(Actor.scala:513)
    at akka.actor.Actor.aroundReceive$(Actor.scala:511)
    at akka.remote.EndpointActor.aroundReceive(Endpoint.scala:446)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
    at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:496)
    at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at akka.kamon.instrumentation.ActorMonitors$$anon$1.$anonfun$processMessage$1(ActorMonitor.scala:63)
    at kamon.trace.Tracer$.withContext(TracerModule.scala:58)
    at akka.kamon.instrumentation.ActorMonitors$$anon$1.processMessage(ActorMonitor.scala:63)
    at akka.kamon.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorInstrumentation.scala:45)
    at akka.actor.ActorCell.invoke(ActorCell.scala:489)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
    at akka.dispatch.Mailbox.run(Mailbox.scala:224)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

The reason this happens is not as first guessable `serialize-messages = on` is set (which would also fail. The reason is that the receive checks for `case ClusterSingletonProxy.TryToIdentifySingleton if identifyTimer.isDefined ⇒` where identifyTimer is the Option of the cancellable for the message. Since it is possible that we cancel but the message already made it to the actors mailbox. This means that once `TryToIdentifySingleton` with cancelled `identifyTimer` happens this matches `case msg: Any ⇒` so `ClusterSingletonProxy` will try to send `TryToIdentifySingleton` to the singleton. If the default java serialization is disabled this means a `java.io.NotSerializableException: No configured serialization-bindings` and the proxy will restart or with default serialization the singleton will have an unmatched/unexpected message.

It looks to me that `if identifyTimer.isDefined` should be removed...? Opinions?

### PR DESCRIPTION
**Pull request by ktoso**
Resolves #24311

I think it is indeed right to accept the message and simply ignore it, like Johan has suggested in the ticket.

Could not think of an useful way of testing it, should I try harder?

### CODE REVIEW

**Review by patriknw — APPROVED** [review]
LGTM, no more testing needed for this case
It's only about discarding the unhandled message.
We could use the new timers, but no reason for making big changes.

**Comment by ktoso** [comment]
Yeap, agreed, trying to keep change at a minimum here, at least for now

**Comment by patriknw** [comment]
Perhaps add the NoSerializationVerficationNeeded to `TryToIdentifySingleton`, since that was one of the things mentioned in the ticket.

**Comment by ktoso** [comment]
Yup, added

**Comment by patriknw** [comment]
After reading the ticket again, this actually fixes one somewhat more annoying thing than unhandled: "this matches case msg: Any ⇒ so ClusterSingletonProxy will try to send TryToIdentifySingleton to the singleton"

That is also harmless, apart from that it would actually try to serialize the TryToIdentifySingleton when sending as a real remote message.

**Comment by ktoso** [comment]
Yeah, it guards from it to fall through to that case. Added the no serialization check anyway, good to mark it such.

**Pull request merged**
