### PR TITLE
Adding OSGi metadata to contrib module.

### PR DESCRIPTION
**Pull request by jwcarman**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @jwcarman,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by jwcarman** [comment]
CLA Filed.

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Thanks for the PR, we'll make sure it's the right thing to do shortly :-)

**Comment by jwcarman** [comment]
Any hints on how to run the full build on my local machine?  What do most folks use for SBT_OPTS?  I kept running out of Metaspace

**Comment by ktoso** [comment]
You can find the command we run in the jenkins logs ( https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/2836/consoleFull ), we use:

```
/usr/lib/jvm/java-1.8.0-openjdk/bin/java -XX:+UseParallelGC -XX:+UseParallelOldGC -Xms2g -Xmx2g -XX:-UseBiasedLocking -XX:+UseCompressedOops -XX:MaxPermSize=512M -XX:MetaspaceSize=512M -Xss2m -Djava.security.egd=file:/dev/./urandom -XX:ReservedCodeCacheSize=128m -Dakka.genjavadoc.enabled=true -Dsbt.ivy.home=/localhome/jenkinsakka/.ivy2 -Dakka.build.M2Dir=/localhome/jenkinsakka/.m2/repository -Dakka.test.timefactor=1 -Dakka.cluster.assert=on -Dsbt.override.build.repos=true -Dakka.test.multi-node=true -Dakka.test.multi-node.targetDirName=/localhome/jenkinsakka/$JOB_NAME/$BUILD_NUMBER -Dakka.test.multi-node.java=/usr/lib/jvm/java-1.8.0-openjdk/bin/java -Dmultinode.Xms64M -Dmultinode.Xmx128M -Dmultinode.XX:MetaspaceSize=128M -Dmultinode.XX:+PrintGCDetails -Dmultinode.XX:+PrintGCTimeStamps -jar /home/jenkinsakka/bin/sbt-launch-0.13.0.jar clean update test:compile publishLocal publishM2 validatePullRequest
```

**Comment by jwcarman** [comment]
Ahhhh, didn't think of that!  :)  Thanks I'll try that on my mac.

**Comment by rkuhn** [comment]
Thanks for the contribution! Would be cool to load the resulting bundle also in the «OSGi dining hakkers» sample to have some verification. @jwcarman could you do that?

**Comment by patriknw** [comment]
thanks for the contribution

**Pull request merged**
