### PR TITLE
Fix SurviveNetworkInstabilitySpec

### PR DESCRIPTION
**Pull request by chbatey**

### CODE REVIEW

**Review by raboof — APPROVED** [review]
Ah this pick the right class based on whether artery is enabled, makes sense

**Review by helena — APPROVED** [review]
Great

**Comment by helena** [comment]
We are seeing travis hanging in it's reporting back to GitHub but it passed actually passed https://travis-ci.org/akka/akka/builds/560882379. Merging.

**Comment by chbatey** [comment]
Dont forget to set the milestone when merging

**Pull request merged**
