### PR TITLE
=doc #20133 Fixed doc about futures

### PR DESCRIPTION
**Pull request by szymon-rd**
#20133

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Comment by johanandren** [comment]
LGTM

**Comment by drewhk** [comment]
LGTM, it seems like the Scala version does not have these old parts.

**Comment by ktoso** [comment]
> LGTM, it seems like the Scala version does not have these old parts.
 Show all checks


Yeah, seems so. Even better then.

Thanks for the contrib, LGTM!

**Pull request merged**
