### PR TITLE
- Support for null is mapAsync and fromCompletionStage was added. #25475

### PR DESCRIPTION
**Pull request by mszczygiel**
## Purpose

These are the same changes as https://github.com/akka/akka/pull/25527 rebased onto recent master. 

## References

References #25475

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Comment by johanandren** [comment]
Failure is formatting, please run scalafmt on the changed files (described in the end of this section: https://github.com/akka/akka/blob/master/CONTRIBUTING.md#sbt )

**Review by patriknw — APPROVED** [review]
LGTM

**Review by chbatey — APPROVED** [review]
LGTM

**Comment by He-Pin** [comment]
@patriknw @johanandren The java and scala doc need update too, superising

**Pull request merged**
