### PR TITLE
=doc #19449 new migration guide for streams 2.0 to 2.4

### PR DESCRIPTION
**Pull request by johanandren**
Refs #19449 

Just made it empty for now so we have a common file to fill out for the individual PRs

### CODE REVIEW

**Comment by ktoso** [comment]
great, thanks

**Comment by drewhk** [comment]
LGTM :)

**Comment by drewhk** [comment]
well, before, we had two such guides, one for Java and one for Scala. What is the approach now?

**Comment by johanandren** [comment]
How about we start out with all-in-one since that is how the other akka migration guides are, and split if it becomes to big a guide?

**Comment by drewhk** [comment]
sounds like a good compromise. Won't expect that much stuff as in the previous one anyway.

**Pull request merged**
