### PR TITLE
Expose nowrap parameter in Compression.inflate, #26227

### PR DESCRIPTION
**Pull request by KarlSjostrand**

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Comment by raboof** [comment]
refs #26227

**Comment by raboof** [comment]
PLS BUILD

**Comment by raboof** [comment]
(sorry for the noise, we had some troubles upgrading our Jenkins infrastructure recently)

**Review by johanandren — APPROVED** [review]
LGTM, thanks @KarlSjostrand !

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
