### PR TITLE
Add missing import to the Inbox example

### PR DESCRIPTION
**Pull request by jczuchnowski**
References #13876

### CODE REVIEW

**Comment by chbatey** [comment]
OK TO TEST

**Review by chbatey — APPROVED** [review]
Could also have added #imports to the snippet but this is fine too

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by chbatey** [comment]
@jczuchnowski  this failed due to formatting, if you compile with SBT and push we can merge

**Comment by jczuchnowski** [comment]
Sorry. I must have done some edit after the compilation.

**Pull request merged**
