### PR TITLE
update to sbt-java-formatter to 0.5.0, and sbt 1.3.6

### PR DESCRIPTION
**Pull request by patriknw**
Backport of https://github.com/akka/akka/pull/28411 so that we use the same version, and can use `javafmtCheckAll` in jenkins pr validation job.

Also updated sbt, since that is required by the sbt-java-formatter plugin. Anything else that has to be updated or will break the build because of sbt update to 1.3.6?

### CODE REVIEW

**Review by chbatey — APPROVED** [review]
LGTM

**Review by raboof — APPROVED** [review]
> Anything else that has to be updated or will break the build because of sbt update to 1.3.6?

Not as far as I remember, so LGTM if jenkins agrees.

**Comment by raboof** [comment]
This needs a mima update because of https://github.com/lightbend/mima/issues/389, I'll take that on

**Comment by patriknw** [comment]
thanks for the mima update

**Comment by patriknw** [comment]
also updated whitesource

**Comment by patriknw** [comment]
I have removed `javafmtCheckAll` from PR validation job for now, since this was a more difficult update. We still have the git diff check.

**Comment by raboof** [comment]
looks like there's some specific mima failures to update for 2.11/2.13... will look into those

**Comment by patriknw** [comment]
Would be good to run an adhoc sbt-whitesource update on this before merging to make sure that part still works. Could you do that @raboof ?

**Comment by raboof** [comment]
willdo. I noticed jenkins reported some more mima issues but couldn't reproduce them yet... :|

**Comment by raboof** [comment]
it correctly seems to check locally, and also updating from the branch (to `akka-adhoc`) seems to work fine (https://saas.whitesourcesoftware.com/Wss/WSS.html#!project;id=174331).

**Comment by patriknw** [comment]
thanks

**Comment by patriknw** [comment]
@raboof still some mima issues here, do you know what it is? https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/18650/

**Comment by patriknw** [comment]
PLS BUILD

**Comment by raboof** [comment]
> still some mima issues here, do you know what it is? https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/18650/

This sounds like #27757 - looking at that issue we decided to remove mima checking for the pr validator, but it seems we never actually did that

**Pull request merged**
