### PR TITLE
support HttpEntity.with/withoutSizeLimit in scaladsl HttpEntity

### LINKED ISSUE #20342: Scala Api with/withoutSizeLimit overrides are still missing on scaladsl HttpEntity
https://github.com/akka/akka/issues/19983 didn't fix them all, the base trait still doesn't have the overrides. 

I bumped into this while trying to fix another issue in akka-sse https://github.com/hseeberger/akka-sse/issues/101

I already fixed it on a branch on my fork (https://github.com/akka/akka/compare/master...TrustNoOne:20342-support-httpentity-withSizeLimit).
I copied the scaladoc from the javadsl version because I guess linking javadsl classes from scaladsl is not desirable, please let me know how you handle this otherwise.

It's my first contribution (very tiny but good to learn all the rules I guess) so please excuse me If I made any mistakes. I haven't opened a pull request because the 'contributing' doc says that I have to wait for estimation and scheduling by you, so I'll wait.

Please let me know if there's anything else I need to do in order to contribute. 

Thanks

### PR DESCRIPTION
**Pull request by TrustNoOne**
fixes https://github.com/akka/akka/issues/20342

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @TrustNoOne,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by johanandren** [comment]
OK TO TEST

**Comment by johanandren** [comment]
LGTM!

**Comment by TrustNoOne** [comment]
Does just overriding two abstract methods with a covariant return type break binary compatibility?

**Comment by ktoso** [comment]
I think this is one of the cases where we can ignore the MiMa warnings, please add them to the MiMa.scala file. Thanks for investigating!

**Comment by ktoso** [comment]
Once MiMa filters done this is LGTM

**Comment by TrustNoOne** [comment]
@ktoso done, thanks for letting me find out about MiMa.scala. 

I deduced the key in the exclude map is the version it checks against, i.e. the current release? I put in "2.4.4", mimaReportBinaryIssues now passes.

**Comment by TrustNoOne** [comment]
@ktoso done, thanks for letting me find out about MiMa.scala. 

I deduced the key in the exclude map is the version it checks against, i.e. the current release? I put in "2.4.4", mimaReportBinaryIssues should now pass.

**Comment by johanandren** [comment]
Thank you for the contribution @TrustNoOne

**Pull request merged**
