### PR TITLE
str One overload of emitMultiple misspelled

### PR DESCRIPTION
**Pull request by johanandren**
emitMultipe -> emitMultiple

### CODE REVIEW

**Comment by johanandren** [comment]
Not sure what the right procedure is here, felt a bit silly to open an issue.

**Comment by ktoso** [comment]
No issue needed though let's keep the commit convention of `=str` :)

**Comment by johanandren** [comment]
I already regret thinking I could fix it quickly through the github ui...

**Comment by ktoso** [comment]
most likely used somewhere, needs `meta shift F6` instead ;)

**Comment by johanandren** [comment]
Was actually a totally separate test that failed. (#19109)

**Comment by ktoso** [comment]
Since validation is happy, LGTM

**Comment by ktoso** [comment]
Made a ticket to highlight this change during release

**Comment by ktoso** [comment]
https://github.com/akka/akka/issues/19111

**Comment by johanandren** [comment]
Ah, ok, sorry to give you extra work. :/

**Comment by ktoso** [comment]
Nah, no worry

**Pull request merged**
