### PR TITLE
#18733 provide rejection reason when path matcher throws an exception

### PR DESCRIPTION
**Pull request by kwyczesany**
Refers to #18733 

I've added a new rejection `PathMatcherExtractionFailedRejection`, which should be used when  the `PathMatcher` throws an exception. There is also a new `Matching` result - `Unextracted`. It means that there was some exception thrown. 
To make it possible to recognize this situation I've changed `Matching`'s `flatMap` signature in such way that it takes as parameter function which returns `Option[Try[R]]`. In this case `Try` means that there was parsing exception.
I've tried to change the `NumberMatcher` that it checks if whole segment was parsed and if not there should be `Unextracted` returned. But this have broken tests with `IntNumber.repeat(...)` because it assumes that parsing segment works on "prefix" style. It means that path is being parsed char by char and if it cannot parse some char then path matcher tries to match this char with separator.

Any suggestions if this is the way it should be solved? Some help would be highly appreciated. There is one test that fails, correct me if I'm wrong, but I think this is the case when this feature should be useful.

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Sorry that this has slipped 2.4.8, will make sure to get it into the next one

**Comment by johanandren** [comment]
Seems like an unrelated failure

**Comment by johanandren** [comment]
PLS BUILD

**Comment by patriknw** [comment]
@ktoso @jrudolph Please decide what to do here so that we can close the PR.

**Comment by jrudolph** [comment]
Thanks, @kwyczesany. Sorry for not getting back to this earlier. A few things would need to be fixed before we could merge it:

 * should be ported to new akka-http repo
 * we would need to figure out how to make it binary compatible, changing `flatMap` at this point would break too much
 * the new rejection should carry more information about the error
 * it needs more checks and tests that verify how this new feature plays together with the existing routing / rejection handling infrastructure (Could someone be relying on an empty rejection instead of the new one? Do we need to cancel rejections like this at some points? etc.)

I'm closing this here for now.

**Pull request closed without merging**
