### PR TITLE
=str add latch to ManualProbe to popagate events only when subscription is done

### PR DESCRIPTION
**Pull request by agolubev**
Ref #23272

### CODE REVIEW

**Comment by agolubev** [comment]
seems like failed test relates to the fix - please stand by

**Comment by agolubev** [comment]
OutboundHandshakeSpec test failed in build - seems like not relevant

**Comment by agolubev** [comment]
Ready for review

**Comment by johanandren** [comment]
The last 4 fails are still related to the manual probe?

**Comment by agolubev** [comment]
OutboundHandshakeSpec fails  with expect. It looks suspicious for me now. Let me check first

**Comment by agolubev** [comment]
Ok, now all tests passed and it's ready

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by agolubev** [comment]
need another LGTM

**Review by raboof — APPROVED** [review]
Thanks!

**Pull request merged**
