### PR TITLE
Replace WrappingBehavior with directly access of InterceptorImpl

### PR DESCRIPTION
**Pull request by tisonkun**
## Purpose

`InterceptorImpl` is the only impl of `WrappingBehavior`. As discussion of #26504 we'd better simplify the logic by directly accessing `InterceptorImpl` instead of introduce a redundant wrapping trait.

## References

References #26504 

## Changes

Remove `WrappingBehavior`. Replace it with directly access of `InterceptorImpl`.

## Background Context

Following the discussion.

cc @patriknw @johanandren

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Comment by TisonKun** [comment]
hmmm...cannot reason the failure without test logs.

**Comment by TisonKun** [comment]
website https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/15480/ not reached.

**Comment by johanandren** [comment]
Could be that you have some corporate firewall blocking port 8498?

This is the reason for the failure:
```
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala isn't formatted properly!
[error] (akka-actor-typed / Compile / scalafmtCheck) /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-actor-typed/src/main/scala/akka/actor/typed/Behavior.scala isn't formatted properly!
[error] Total time: 802 s, completed Apr 5, 2019 9:06:42 AM
```

Run scalafmtAll on typed and commit that.

Make sure you also run tests locally first etc. to get a shorter turn around time. You can also run `validatePullRequest` for a more complete pre-validation

**Comment by TisonKun** [comment]
@johanandren Thanks for your guidance! Update and fix fails.

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Comment by TisonKun** [comment]
@johanandren since this pr doesn't go too complex, it is possible to ping another reviewer to nudge the process? As a fresh man I don't know to whom I can ask for help :P

**Comment by johanandren** [comment]
The entire team has been travelling and busy with meetings. I'm sure someone will pick up that second review next week!

**Comment by TisonKun** [comment]
Huh! Gotcha and wish you a nice enjoyable travel.

**Review by patriknw — APPROVED** [review]
LGTM, thanks

**Pull request merged**
