### PR TITLE
Fix typos in HTTP streaming doc

### PR DESCRIPTION
**Pull request by tszym**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @tszym,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
Thanks!

Could you chekc if we have the same typos in `akka-docs/rst/java/http/implications-of-streaming-http-entity.rst`?

**Comment by tszym** [comment]
Didn't thought about it, but sure :)

**Comment by ktoso** [comment]
LGTM and CLA signed, thanks a lot :-)

**Pull request merged**
