### PR TITLE
=act #16536 actor selection now completes ask

### PR DESCRIPTION
**Pull request by kosii**
To implement the feature VirtualPathContainer.! was overridden to handle
ActorSelectionMessages. In ActorSelectionMessages only SelectChildName
elements are supported to disallow counterintuitive behaviors (like
completing all outstanding ask operations).

### CODE REVIEW

**Comment by kosii** [comment]
#16536

**Comment by bantonsson** [comment]
OK TO TEST

**Comment by bantonsson** [comment]
@kosii Thanks for the backport

**Comment by kosii** [comment]
@bantonsson you're welcome

**Pull request merged**
