### PR TITLE
typo, user guardian instead of guardian

### PR DESCRIPTION
**Pull request by robstoll**
# Background Context

Reading https://doc.akka.io/docs/akka/current/typed/guide/tutorial_1.html

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @robstoll,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by patriknw — APPROVED** [review]
LGTM, thanks

**Comment by patriknw** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]
Thanks!

**Pull request merged**
