### PR TITLE
cleanup migration guides toc

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Review by chbatey — APPROVED** [review]
LGTM

**Review by johanandren — COMMENTED** [review]
Will the removals also require redirects to not give us search engine penalties for akka.io?

**Comment by patriknw** [comment]
> Will the removals also require redirects to not give us search engine penalties for akka.io?

There is only one hit when searching for `current/project/migration-guide` in .md files in akka.github.com. Might be better to change that `current` link to `2.5`?

**Review by raboof — APPROVED** [review]
Good to clean those up. Might be good to add those redirect rules, in case there are any links to the migration pages from 'outside', but indeed good to also change the link to point there directly.

**Comment by patriknw** [comment]
@raboof I have added redirects, please confirm that I got the syntax right. 0b69fdc

Also changed the link at akka.io in https://github.com/akka/akka.github.com/pull/602

**Comment by patriknw** [comment]
the travis build was green

**Pull request merged**
