### PR TITLE
=build upgrade to SBT 1.1.3

### PR DESCRIPTION
**Pull request by He-Pin**

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
LGTM

**Review by ktoso — APPROVED** [review]

**Comment by 2m** [comment]
Note that 1.1.3 has a known issue with `console`: https://github.com/sbt/sbt/pull/4082

**Comment by hepin1989** [comment]
Yes,will need to upgrade to 1.1.4 then.

**Comment by ktoso** [comment]
Yeah that's fine; PR https://github.com/akka/akka/pull/24871

**Pull request merged**
