### PR TITLE
Fix TestProbeImpl#receiveN_internal with the receiveOne change

### LINKED ISSUE #26005: Compile error in `akka.actor.testkit.typed.internal.TestProbeImpl#receiveN_internal`
```
  override protected def receiveN_internal(n: Int, max: FiniteDuration): immutable.Seq[M] = {
    val stop = max + now
    for (x ← 1 to n) yield {
      val timeout = stop - now
      val o = receiveOne(timeout)
      assert(o != null, s"timeout ($max) while expecting $n messages (got ${x - 1})")
      o
    }
  }
```

with

```
[error] /Users/kerr/IdeaProjects/akka/akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/TestProbeImpl.scala:194:12: type mismatch;
[error]  found   : scala.collection.immutable.IndexedSeq[Option[M]]
[error]  required: scala.collection.immutable.Seq[M]
[error]     for (x ← 1 to n) yield {
```

@dwijnand

### PR DESCRIPTION
**Pull request by dwijnand**
Semantic conflict between the changes in #25863 and #25801 not being tested together.

Fixes #26005

### CODE REVIEW

**Comment by dwijnand** [comment]
This didn't fail on Travis CI because don't try and compile things there: https://travis-ci.org/akka/akka/builds/461207425

And I'm not sure which is the Jenkins build for master in https://jenkins.akka.io:8498/

But anyways, this is what broke my PR #25966, so I'm submitting this here to fast-track the fix.

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
The job for master is https://jenkins.akka.io:8498/job/akka-multi-node/

**Comment by hepin1989** [comment]
I just came up with a fix too:)

**Pull request merged**
