### PR TITLE
move "#start-stop"'s start line

### PR DESCRIPTION
**Pull request by kajebiii**
Line 118 : val first = system.actorOf(StartStopActor1.props, "first")

Need "object StartStopActor1" to compile well.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @kajebiii,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by raboof** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]
Companion objects are shown for the other actors as well, so makes sense to include it here too

**Review by jrudolph — APPROVED** [review]
Agreed, LGTM.

**Pull request merged**
