### PR TITLE
Fixed a typo in a generic type declaration in tutorial

### PR DESCRIPTION
**Pull request by petermz**
The type parameters should be the other way around

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @petermz,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by raboof** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]
Good observation, LGTM when cla is signed

**Comment by petermz** [comment]
Just signed the CLA

**Comment by raboof** [comment]
Thanks!

**Pull request merged**
