### PR TITLE
cancellable var -> private val

### PR DESCRIPTION
**Pull request by t0t07**
I don't get why these cancellable are vars.

### CODE REVIEW

**Comment by johanandren** [comment]
Makes sense, you'll need to add a mima filter in `akka-distributed-data/src/main/mima-filters/2.6.5.backwards.excludes` though, the binary compatibility check doesn't know that those are methods on an actor that changed but it the change is safe.

**Comment by YikSanChan** [comment]
@johanandren I tried to add that, but run into an unexpected and seem-to-be unrelated failure

```
akka > akka-distributed-data/mimaReportBinaryIssues
[info] Compiling 5 Scala sources and 1 Java source to /Users/echan/source/yiksanchan/akka/akka-actor/target/scala-2.12/classes ...
[info] Compiling 2 Scala sources and 1 Java source to /Users/echan/source/yiksanchan/akka/akka-actor/target/scala-2.12/classes ...
[error] Symbol 'type akka.pattern.AskSupport' is missing from the classpath.
[error] This symbol is required by 'package akka.pattern.package'.
[error] Make sure that type AskSupport is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'package.class' was compiled against an incompatible version of akka.pattern.
[error] one error found
[info] Strategy 'discard' was applied to 2 files (Run the task at debug level to see details)
[info] Assembly up to date: /Users/echan/source/yiksanchan/akka/akka-protobuf-v3/target/scala-2.12/akka-protobuf-v3-assembly-2.6.4+209-bceb3b70.jar
[error] (akka-actor / Compile / compileIncremental) Compilation failed
[error] Total time: 8 s, completed May 7, 2020 8:12:38 AM
```

Can you help?

**Comment by raboof** [comment]
`Symbol 'type akka.pattern.AskSupport' is missing from the classpath.`

akka-actor/clean should help... though I'm surprised to see this error again, I thought we got rid of it on master (and it'd only occur on the release-2.5 branch now)

**Review by johanandren — APPROVED** [review]

**Review by patriknw — APPROVED** [review]
LGTM :-)

**Pull request merged**
