### PR TITLE
Consistent indentation in TraversalBuilder.printTraversal() for Concat

### PR DESCRIPTION
**Pull request by richardimaoka**
Refs #23076 
Let me know if this does not look good. Then I will just cancel the PR as well as the issue.

```scala
TraversalBuilder.printTraversal(Concat(Pop, PushNotUsed))
```

the above code will produce:

```
//Before the code change
 | pop mat
push NotUsed

//After the code change
concat(
 | pop mat
 | push NotUsed
)
```

```scala
val graph = Source.single(1).via(Flow[Int].map(x ⇒ 2 * x)).to(Sink.ignore)
val builder = graph.traversalBuilder
TraversalBuilder.printTraversal(builder.traversal)
```

This will produce:

```
//Before the code change
 | push attr Attributes(List(Name(ignoreSink)))
 |  | materialize GraphStage(akka.stream.impl.fusing.GraphStages$IgnoreSink$@6f80e4d5) [750df7a1] []
 | pop attr
 | pop mat
 | push attr Attributes(List(Name(map)))
 |  | materialize GraphStage(Map(<function1>)) [1cf27183] [-1]
 | pop attr
 | pop mat
 | push NotUsed
 | pop mat
 | push attr Attributes(List(Name(singleSource)))
 | materialize GraphStage(SingleSource) [7280bc6d] [-1]
pop attr

//After the code change
concat(
 | push attr Attributes(List(Name(ignoreSink)))
 | concat(
 |  | concat(
 |  |  | materialize GraphStage(akka.stream.impl.fusing.GraphStages$IgnoreSink$@4cf9b4a6) [7ad502b9] []
 |  |  | pop attr
 |  | )
 |  | concat(
 |  |  | pop mat
 |  |  | concat(
 |  |  |  | push attr Attributes(List(Name(map)))
 |  |  |  | concat(
 |  |  |  |  | concat(
 |  |  |  |  |  | materialize GraphStage(Map(<function1>)) [691dc913] [-1]
 |  |  |  |  |  | pop attr
 |  |  |  |  | )
 |  |  |  |  | concat(
 |  |  |  |  |  | pop mat
 |  |  |  |  |  | concat(
 |  |  |  |  |  |  | push NotUsed
 |  |  |  |  |  |  | concat(
 |  |  |  |  |  |  |  | pop mat
 |  |  |  |  |  |  |  | concat(
 |  |  |  |  |  |  |  |  | push attr Attributes(List(Name(singleSource)))
 |  |  |  |  |  |  |  |  | concat(
 |  |  |  |  |  |  |  |  |  | materialize GraphStage(SingleSource) [5e96986c] [-1]
 |  |  |  |  |  |  |  |  |  | pop attr
 |  |  |  |  |  |  |  |  | )
 |  |  |  |  |  |  |  | )
 |  |  |  |  |  |  | )
 |  |  |  |  |  | )
 |  |  |  |  | )
 |  |  |  | )
 |  |  | )
 |  | )
 | )
)
```

Where the one after the code change is lot more verbose... I can eliminate "concat(" in the output if that is unnecessary.

### CODE REVIEW

**Comment by ktoso** [comment]
I don't think the new format is more readable, the old one takes some getting used to but is quick to read and "get" once you do

**Comment by ktoso** [comment]
cc @drewhk

**Comment by drewhk** [comment]
I used to print the concat nodes explicitly, but the problem was that it became almost impossible to debug larger structures, especially graphs. I strongly prefer the old way of printing.

**Comment by drewhk** [comment]
Maybe add a flag to control printing the concat nodes? (with default being off)

**Comment by richard-imaoka** [comment]
Okay, how about this? (added a new commit)

* `useIndent=false //by default` in `printTraversal()` does not perform indentation
*  `useIndent=true` preserves correct indent levels, and use a little more concise `"|"` for indentation

```
//printTraversal(t, useIndent = false)
push attr Attributes(List(Name(foreachSink)))
push attr Attributes(List(Name(ignoreSink)))
materialize GraphStage(akka.stream.impl.fusing.GraphStages$IgnoreSink$@761e4d94) [7f5e184d] []
pop attr
push attr Attributes(List(Name(map)))
materialize GraphStage(Map(<function1>)) [631d8211] [-1]
pop attr
pop mat
push NotUsed
pop mat
pop attr
pop mat
push attr Attributes(List(Name(map)))
materialize GraphStage(Map(<function1>)) [7b5ed76a] [2]
pop attr
pop mat
push NotUsed
push attr Attributes(List(Name(map)))
materialize GraphStage(Map(<function1>)) [744d243c] [-2]
pop attr
pop mat
push NotUsed
pop mat
pop mat
push NotUsed
push attr Attributes(List(Name(map)))
materialize GraphStage(Map(<function1>)) [70bbb5cc] [2]
pop attr
pop mat
push NotUsed
push attr Attributes(List(Name(map)))
materialize GraphStage(Map(<function1>)) [7fb9acc0] [-2]
pop attr
pop mat
push NotUsed
pop mat
pop mat
push NotUsed
pop mat
push attr Attributes(List(Name(map)))
materialize GraphStage(Map(<function1>)) [7251d1da] [2]
pop attr
pop mat
push NotUsed
push attr Attributes(List(Name(map)))
materialize GraphStage(Map(<function1>)) [6f206768] [-2]
pop attr
pop mat
push NotUsed
pop mat
pop mat
push NotUsed
pop mat
push attr Attributes(List(Name(map)))
materialize GraphStage(Map(<function1>)) [4218ba95] [-1]
pop attr
pop mat
push NotUsed
pop mat
pop mat
push attr Attributes(List(Name(iterableSource)))
push attr Attributes(List(Name(statefulMapConcat)))
materialize GraphStage(StatefulMapConcat) [70f5d1ba] [-7]
pop attr
pop mat
push attr Attributes(List(Name(singleSource)))
materialize GraphStage(SingleSource) [0c56117f] [-1]
pop attr
pop attr
```

```
//printTraversal(t, useIndent = true)
|push attr Attributes(List(Name(foreachSink)))
||||push attr Attributes(List(Name(ignoreSink)))
||||||materialize GraphStage(akka.stream.impl.fusing.GraphStages$IgnoreSink$@25436e61) [656dd908] []
||||||pop attr
||||||push attr Attributes(List(Name(map)))
|||||||||materialize GraphStage(Map(<function1>)) [530f4059] [-1]
|||||||||pop attr
|||||||||pop mat
|||||||||push NotUsed
|||||||pop mat
|||pop attr
|||pop mat
||||push attr Attributes(List(Name(map)))
|||||||||||materialize GraphStage(Map(<function1>)) [79425125] [2]
|||||||||||pop attr
|||||||||||pop mat
|||||||||||push NotUsed
||||||||||push attr Attributes(List(Name(map)))
|||||||||||||materialize GraphStage(Map(<function1>)) [72ec729c] [-2]
|||||||||||||pop attr
|||||||||||||pop mat
|||||||||||||push NotUsed
||||||||||||pop mat
|||||||||||||pop mat
|||||||||||||push NotUsed
|||||||||push attr Attributes(List(Name(map)))
|||||||||||||materialize GraphStage(Map(<function1>)) [4c623ac6] [2]
|||||||||||||pop attr
|||||||||||||pop mat
|||||||||||||push NotUsed
||||||||||||push attr Attributes(List(Name(map)))
|||||||||||||||materialize GraphStage(Map(<function1>)) [6546b69b] [-2]
|||||||||||||||pop attr
|||||||||||||||pop mat
|||||||||||||||push NotUsed
||||||||||||||pop mat
|||||||||||||||pop mat
|||||||||||||||push NotUsed
||||||||||pop mat
||||||||push attr Attributes(List(Name(map)))
||||||||||||materialize GraphStage(Map(<function1>)) [0e66086f] [2]
||||||||||||pop attr
||||||||||||pop mat
||||||||||||push NotUsed
|||||||||||push attr Attributes(List(Name(map)))
||||||||||||||materialize GraphStage(Map(<function1>)) [1f8ff3ad] [-2]
||||||||||||||pop attr
||||||||||||||pop mat
||||||||||||||push NotUsed
|||||||||||||pop mat
||||||||||||||pop mat
||||||||||||||push NotUsed
|||||||||pop mat
|||||||push attr Attributes(List(Name(map)))
||||||||||materialize GraphStage(Map(<function1>)) [42664e90] [-1]
||||||||||pop attr
||||||||||pop mat
||||||||||push NotUsed
||||||||pop mat
||||||pop mat
|||||||push attr Attributes(List(Name(iterableSource)))
|||||||||push attr Attributes(List(Name(statefulMapConcat)))
|||||||||||materialize GraphStage(StatefulMapConcat) [12c4da29] [-7]
|||||||||||pop attr
|||||||||||pop mat
||||||||||||push attr Attributes(List(Name(singleSource)))
|||||||||||||materialize GraphStage(SingleSource) [2c5f8d6e] [-1]
|||||||||||||pop attr
||||||||pop attr

```

**Comment by drewhk** [comment]
Hm, I still prefer the old layout. Also, I would make indentation the default. I might be biased here, but this single method was the most useful for debugging the new materializer while implementing. Maybe instead of changing this method create new ones? There is already a `printWiring` method, I don't think it hurts to add more.

Btw, this is a debug method, why the sudden interest? Just curious :)

**Comment by richard-imaoka** [comment]
Okay sure, then I wouldn't change this and close my pull request.

I have been working on #22899, and have used this method to debug traversal builders. And I thought the output could be bit nicer.

Anyway, thanks for taking time and explaining the intention behind this.

**Pull request closed without merging**
