### PR TITLE
use jackson-scala-module 2.13.2 for akka-jackson-serialization_3

### PR DESCRIPTION
**Pull request by pjfanning**
Relates to #31236

### CODE REVIEW

**Comment by patriknw** [comment]
Thanks, looking good. Something missing or why Draft?

**Review by raboof — APPROVED** [review]
LGTM as well (though CI suggests it needs an `sbt scalafmtSbt`)

**Comment by pjfanning** [comment]
I think I've fixed the scalafmt issue now

**Review by patriknw — APPROVED** [review]
LGTM, thank you

**Pull request merged**
