### PR TITLE
bugfix: Update protobuf

### PR DESCRIPTION
**Pull request by JustinPihony**
Update to the latest 3.16 protobuf to mitigate open CVEs

### CODE REVIEW

**Review by johanandren — APPROVED** [review]

**Comment by johanandren** [comment]
Already bumped in 2.9 and main btw. so easiest way to get access would be to use 2.9.7

**Comment by johanandren** [comment]
Actually, this isn't all that is needed, if you look at https://github.com/akka/akka/pull/32521/files

Maybe easiest to cherrypick that PR commit.

**Comment by johanandren** [comment]
Probably fine like this, protocVersion doesn't need change when it stays on same minor version. And maybe we do not want to bump proto minor in a 2.8 patch anyway

**Comment by JustinPihony** [comment]
Yah, I was looking for the most minimal change in this case. And users who want to stay on Scala 2.12 would need to use 2.8, thus this bump

**Pull request merged**
