### PR TITLE
Ensure DNS resolution is performed for all new connections #20690

### PR DESCRIPTION
**Pull request by kevincdeng**
Pass in an unresolved InetSocketAddress to ensure that each new
TcpOutgoingConnection will perform DNS resolution.

This prevents a connection pool from always using the same IP address for a host
even if the DNS mapping changes (e.g. in a failover).

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @kevincdeng,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Refs #20690

**Comment by ktoso** [comment]
Fix looks good - LGTM, thanks @kevincdeng!
Over ScalaDays we may be a bit slow at reviews etc, sorry about that!

cc @drewhk @johanandren @2beaucoup

**Comment by kevincdeng** [comment]
Yea no worries

**Comment by ktoso** [comment]
Have an opinion here @drewhk @2beaucoup ?

**Comment by ktoso** [comment]
I think the fix makes sense so going forward with merging, others had plenty time to veto here.

**Comment by ktoso** [comment]
Thanks a lot for contributing the fix and noticing the issue @kevincdeng !

**Pull request merged**
