### PR TITLE
Update cluster.md

### PR DESCRIPTION
**Pull request by minjibir**
Fixed a simple typo

References #xxxx

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @minjibir,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Review by darionyaphet — APPROVED** [review]

**Review by octonato — APPROVED** [review]

**Comment by octonato** [comment]
Thanks @minjibir. Well spotted.

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
ouch, this had wrong target branch. I'll submit a new PR with this commit.

**Pull request merged**
