### PR TITLE
Make it clearer that StreamRefs should be used with Akka Cluster #26173

### PR DESCRIPTION
**Pull request by chunjef**
- Added a warning that StreamRefs should be used with Akka Cluster.
- Made minor grammatical improvements.

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Comment by johanandren** [comment]
OK TO TEST

**Review by chbatey — APPROVED** [review]
LGTM

**Comment by raboof** [comment]
(manually checked: CLA was signed :+1: )

**Review by raboof — APPROVED** [review]
Very nice improvements, thanks!

**Pull request merged**
