### PR TITLE
Upgrade sbt-jmh to 0.2.16

### PR DESCRIPTION
**Pull request by monkey-mas**
Let's upgrade sbt-jmh to the latest version (with the latest JMH version 1.14.1) if there's no problems :)

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by 2m** [comment]
PLS BUILD

**Comment by ktoso** [comment]
Confirmed locally, should pass

**Comment by ktoso** [comment]
PLS BUILD

**Comment by ktoso** [comment]
Thanks @monkey-mas !

**Comment by monkey-mas** [comment]
Thanks! :)

**Pull request merged**
