### PR TITLE
add examples for scan operator #25468

### PR DESCRIPTION
**Pull request by airtz**
Examples for [Source-or-Flow/scan](https://doc.akka.io/docs/akka/current/stream/operators/Source-or-Flow/scan.html)

Refs #25468

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @airt,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by raboof** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]
Thanks, neat example!

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
