### PR TITLE
Make discovery and dns APIs stable

### PR DESCRIPTION
**Pull request by patriknw**
* remove ApiMayChange

### CODE REVIEW

**Comment by patriknw** [comment]
```
[info] Loading settings for project akka from build.sbt ...
java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.jgit.internal.storage.file.PackIndexV2.<init>(PackIndexV2.java:128)
	at org.eclipse.jgit.internal.storage.file.PackIndex.read(PackIndex.java:140)
	at org.eclipse.jgit.internal.storage.file.PackIndex.open(PackIndex.java:99)
	at org.eclipse.jgit.internal.storage.file.PackFile.idx(PackFile.java:183)
	at org.eclipse.jgit.internal.storage.file.PackFile.get(PackFile.java:274)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedObject(ObjectDirectory.java:471)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedFromSelfOrAlternate(ObjectDirectory.java:429)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:420)
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:159)
	at org.eclipse.jgit.revwalk.RevWalk.getCachedBytes(RevWalk.java:903)
	at org.eclipse.jgit.revwalk.RevCommit.parseHeaders(RevCommit.java:155)
	at org.eclipse.jgit.revwalk.RevWalk.markStart(RevWalk.java:293)
	at org.eclipse.jgit.api.LogCommand.add(LogCommand.java:339)
	at org.eclipse.jgit.api.LogCommand.add(LogCommand.java:198)
	at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:154)
	at scalafix.internal.sbt.JGitCompletion.<init>(JGitCompletions.scala:26)
	at scalafix.internal.sbt.ScalafixCompletions.gitDiffParser$lzycompute(ScalafixCompletions.scala:94)
	at scalafix.internal.sbt.ScalafixCompletions.gitDiffParser(ScalafixCompletions.scala:93)
	at scalafix.internal.sbt.ScalafixCompletions.parser(ScalafixCompletions.scala:139)
	at scalafix.sbt.ScalafixPlugin$.scalafix$sbt$ScalafixPlugin$$scalafixInputTask(ScalafixPlugin.scala:143)
	at scalafix.sbt.ScalafixPlugin$autoImport$.scalafixConfigSettings(ScalafixPlugin.scala:53)
	at scalafix.sbt.ScalafixPlugin$.$anonfun$projectSettings$1(ScalafixPlugin.scala:77)
	at scalafix.sbt.ScalafixPlugin$$$Lambda$4968/1503319846.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
	at scala.collection.TraversableLike$$Lambda$60/1164107853.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
	at scala.collection.immutable.List.flatMap(List.scala:351)
	at scalafix.sbt.ScalafixPlugin$.projectSettings(ScalafixPlugin.scala:77)
	at sbt.internal.Load$.$anonfun$resolveProject$3(Load.scala:1062)
	at sbt.internal.Load$$$Lambda$1599/726998651.apply(Unknown Source)
```

**Comment by patriknw** [comment]
PLS BUILD

**Review by chbatey — APPROVED** [review]
Does it have the setting in build.sbt as well?

**Comment by patriknw** [comment]
> Does it have the setting in build.sbt as well?

Good catch, fixed now.

**Pull request merged**
