### PR TITLE
ActorSinkWithAckExample Ack message

### PR DESCRIPTION
**Pull request by jorexe**
Using the example does not work in Java, because it seems that `Sink` compares by equality, no by class.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @jorexe,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by johanandren** [comment]
OK TO TEST

**Comment by johanandren** [comment]
Thanks @jorexe , good catch! To be able to merge this we will need a signed CLA and a re-format/commit/push of the sources (`sbt akka-stream-typed/test:javafmtAll`)

**Comment by octonato** [comment]
@jorexe, the CLA signing is not yet sorted out. The reason is that you have commits using two different users (@jorexe and @jorgesg1986 it seems). 

The CLA was signed by @jorgesg1986 as far I can tell. 

The best way to solve it is to squash the commits using @jorexe (seems to be your preferred account) and sign the CLA using @jorexe.

**Review by octonato — APPROVED** [review]
LGTM

**Comment by lightbend-cla-validator** [comment]
Hi @jorexe,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by jorexe** [comment]
Not sure if it worked

**Comment by octonato** [comment]
@jorexe I can see that you signed it, but the CLA wasn't triggered. I will close and reopen this PR.

**Comment by octonato** [comment]
There we go! I will merge it once the build is green. Thanks

**Review by johanandren — APPROVED** [review]

**Comment by jorexe** [comment]
Great! Thank you very much @johanandren

**Pull request merged**
