### PR TITLE
More consistent naming and style, fixed typos and mistakes #22077

### PR DESCRIPTION
**Pull request by Philippus**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @Philippus,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by Philippus** [comment]
I signed the CLA

**Comment by ktoso** [comment]
OK TO TEST

**Review by ktoso — APPROVED** [review]
Changes look good - thanks! LGTM

**Comment by patriknw** [comment]
Thanks a lot, @Philippus

**Review by patriknw — APPROVED** [review]

**Comment by Philippus** [comment]
thank you for the awesome project! Hakky new year!

**Pull request merged**
