### PR TITLE
=rem #17729 Don't use Implicits.global in remoting shutdown

### PR DESCRIPTION
**Pull request by benmccann**
Backport of https://github.com/akka/akka/commit/099adc500bbf0d849c591f8e737f767b3763ece3

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
LGTM, why not :)

**Comment by benmccann** [comment]
@ktoso the tests pass for me locally. I don't see why the build is failing. Should we re-run the tests on Jenkins somehow?

**Comment by patriknw** [comment]
Since the failing test is related to remoting we must investigate why it failed. We don't want to merge anything that introduce a regression.

**Comment by benmccann** [comment]
I agree, but I'm not sure how to investigate. I don't see what the failure is on Jenkins and it passes for me locally.

Maybe there's a flaky test. Can we rerun on Jenkins?

**Comment by benmccann** [comment]
@ktoso @patriknw any ideas what's going on? It doesn't make sense to me that it says "All tests passed." and "Failed 0, Errors 0" and yet is still saying "Tests unsuccessful". I can't see what's failing and it passes for me locally. This seems like a problem with Jenkins and not the tests?

>[info] All tests passed.
[info] Passed: Total 42, Failed 0, Errors 0, Passed 42
[error] (akka-remote-tests/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 4195 s, completed Aug 4, 2015 12:36:05 PM

**Comment by richdougherty** [comment]
@benmccann, this test might be failing because of timing variations between your local machine and the CI machine. Maybe the `system.dispatcher` is being shut down at the same time that remoting is shutting down and sometimes the dispatcher shuts down first?

If that's the case, instead of using `system.dispatcher` you could try using a custom `ExecutionContext` that starts threads on demand. It won't be efficient, but it doesn't depend on the actor system and it shouldn't leak.

```scala
class OnDemandExecutionContext extends ExecutionContext
  def execute(runnable: Runnable): Unit = {
    val thread = new Thread(runnable)
    thread.start()
  }
}
```

**Comment by benmccann** [comment]
Hmm, well this is just backporting a change to 2.3 that's already in master. If it's flaky, then I'd assume master would also be flaky. I wonder if the Akka guys are seeing their builds randomly fail on the master branch with this same error? I don't really want to make a change on this branch that isn't on master already

**Comment by richdougherty** [comment]
I agree this change should be the same on both master and 2.3. If the bug is due to a race condition then it might be quite rare, which would explain why it's not seen on master.

Another reason why it's failing in 2.3 would be if 2.3 has different semantics for shutting down. Is [this comment](https://github.com/akka/akka/pull/17876#discussion_r33670039) valid for 2.3 as well as master?

**Comment by benmccann** [comment]
PLS BUILD

**Comment by benmccann** [comment]
Can you retest it?

**Comment by richdougherty** [comment]
@ktoso, @patriknw, would you mind retesting this on 2.3 to see if the error is repeatable?

**Comment by benmccann** [comment]
The tests passed this time around

I've run them numerous times on my own machine and haven't been able to cause the error (it's much easier to run on my machine because I can run only the akka-remote tests so that they finish much faster than running the tests for all sub-projects. Also, it's hard for me to kick off the Jenkins tests)

It's not entirely clear to me that the tests even failed on Jenkins in the first place. As I said, it reported that all tests passed and I couldn't find why it ended with an error.

I tend to think that if there is any flakiness here (and again it's not obvious that the tests ever failed in the first place) that it's also present on master. @ktoso @patriknw @drewhk what do you guys think?

As a closing note, if there is a problem, I have to think that it's not nearly as bad as the perm gen leak that's currently present, so we'd probably still want to merge this while investigating anyway.

**Comment by richdougherty** [comment]
@benmccann, I can see test failures in the [log of the original CI tests](https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/3318/consoleFull):

```
[JVM-1] RemoteReDeploymentFastMultiJvmNode1:
[JVM-1] A remote deployment target system
[JVM-1] - must terminate the child when its parent system is replaced by a new one *** FAILED *** (3 seconds, 35 milliseconds)
[JVM-1]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for PreStart
[JVM-1]   at scala.Predef$.assert(Predef.scala:179)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:338)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:315)
[JVM-1]   at akka.testkit.TestKit.expectMsg(TestKit.scala:718)
[JVM-1]   at akka.remote.RemoteReDeploymentMultiJvmSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$3.apply$mcV$sp(RemoteReDeploymentSpec.scala:107)

[JVM-2] RemoteReDeploymentFastMultiJvmNode2:
[JVM-2] A remote deployment target system
[JVM-2] - must terminate the child when its parent system is replaced by a new one *** FAILED *** (3 seconds, 408 milliseconds)
[JVM-2]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for HelloParent
[JVM-2]   at scala.Predef$.assert(Predef.scala:179)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:338)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:315)
[JVM-2]   at akka.testkit.TestKit.expectMsg(TestKit.scala:718)
[JVM-2]   at akka.remote.RemoteReDeploymentMultiJvmSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(RemoteReDeploymentSpec.scala:103)

[error] Failed: akka.remote.RemoteReDeploymentFastMultiJvmNode1
[error] Failed: akka.remote.RemoteReDeploymentFastMultiJvmNode2

[error] Failed: Total 107, Failed 2, Errors 0, Passed 105
[error] Failed tests:
[error]   akka.remote.RemoteReDeploymentFast
```

I have no idea why this test failed or if it has anything to do with using the `system.dispatcher`. Perhaps this is a test that randomly fails and it was just bad luck that we saw it on this PR?

**Comment by patriknw** [comment]
The reason that test failed is that the test is missing a barrier. This has been fixed on master, but not in release-2.3 branch. Compare `RemoteReDeploymentSpec.scala` with master and you see what I mean.

@benmccann It would be great if you could adjust the test, but it is not related to the PR, so we could also do that separately (or ignore it)

**Comment by benmccann** [comment]
Thanks @patriknw !  I just sent you a new PR for that https://github.com/akka/akka/pull/18173

**Comment by benmccann** [comment]
Can we merge this now that https://github.com/akka/akka/pull/18173 is merged and all tests are passing?

**Comment by patriknw** [comment]
yes, thanks

**Comment by patriknw** [comment]
Refs #17729

**Comment by benmccann** [comment]
thanks!!

Do you know will there be a 2.3.13 release soon with this change in it?

**Pull request merged**
