### PR TITLE
Fix memory leak in AddressTerminatedTopic (for validation)

### PR DESCRIPTION
**Pull request by patriknw**
refs #19672

(cherry picked from commit 437474875d51e6c7e7973f29fe3adbb875cb79cf)

### CODE REVIEW

**Comment by patriknw** [comment]
That was https://github.com/akka/akka/issues/18741

**Comment by patriknw** [comment]
PLS REBUILD

**Comment by drewhk** [comment]
thanks for the backport

**Comment by johanandren** [comment]
PLS BUILD

**Comment by patriknw** [comment]
PLS BUILD

**Comment by drewhk** [comment]
PLS BUILD

**Pull request merged**
