### PR TITLE
+str #15588 Additional way of using IO sink/source

### PR DESCRIPTION
**Pull request by ktoso**
I personally very much like this style of importing more capabilities, but may be subject to fierce debate so made it a separate PR (depends on https://github.com/akka/akka/pull/17211) :wink: 

See only this commit in this PR: https://github.com/akka/akka/commit/1cfe2250a0a5c3569d0987cd0a1652e3e2e530a5

Note: we already have this style (but for ops) in `akka.stream.extra` (which currently just is the `timed` thingy) ( https://github.com/akka/akka/blob/release-2.3-dev/akka-stream/src/main/scala/akka/stream/extra/Implicits.scala )

### CODE REVIEW

**Comment by patriknw** [comment]
LGTM, some nitpicks

**Comment by patriknw** [comment]
is this obsolete, or need rebase?

**Comment by ktoso** [comment]
Needs rebase (was making dinner ;-), I'm planing to attend it this evening.
My plan now: 1) figure out if my rebase broke `ConnectionPoolSpec` -> fix 2) rebase and merge this one 3) finish the logging one (have much of preStart working - a few tests fail).

**Comment by patriknw** [comment]
sounds great, thanks

**Comment by ktoso** [comment]
resolves #15588 and resolves #17284

**Pull request merged**
