### PR TITLE
Java formatting

### PR DESCRIPTION
**Pull request by He-Pin**

### CODE REVIEW

**Comment by hepin1989** [comment]
Closed previous one by accident https://github.com/akka/akka/pull/26198

**Comment by raboof** [comment]
Failure seems #26223

**Comment by raboof** [comment]
PLS BUILD

**Comment by raboof** [comment]
Now #26214 :(

**Comment by raboof** [comment]
PLS BUILD

**Review by patriknw — COMMENTED** [review]
I looked closer at this and it's not looking as bad as I feared. I'm willing to accept this format.

When we merge this I think it's important that we make it into two commits, one for the build changes and one for the auto-format changes. Then then build changes can be picked into PRs in progress to facilitate smooth merging.

**Comment by hepin1989** [comment]
@patriknw I can do that once I finish my daily work today:)

**Comment by hepin1989** [comment]
akka.cluster.sharding.CoordinatedShutdownShardingSpec.Sharding and CoordinatedShutdown must run coordinated shutdown when leaving
akka.cluster.sharding.CoordinatedShutdownShardingSpec.Sharding and CoordinatedShutdown must run coordinated shutdown when downing

**Comment by patriknw** [comment]
Test PASSed so merging before something else happens. It will case trouble for open PRs but there is  never a good time for merging formatting changes. Thanks @hepin1989

**Comment by hepin1989** [comment]
Very fine, because we got this merged in before 2.6:) Hope more and more team at Alibaba join this party.

**Pull request merged**
