### PR TITLE
=rem #16505: Do not publish AddressTerminated (missing fwd port)

### PR DESCRIPTION
**Pull request by drewhk**
- also not throw IllegalAssocEx from transport
- added a test for stashing behavior
  (cherry picked from commit b7295a8)

### CODE REVIEW

**Comment by drewhk** [comment]
This commit was not forward ported. I think this was a plain oversight but someone can comment if there was some real reason.

**Comment by drewhk** [comment]
Hmm, a series of Sharding related failures. It seems unlikely that my changes are the issue, so let's retry.

**Comment by drewhk** [comment]
PLS BUILD

**Comment by drewhk** [comment]
now a connection timeout to GH... sigh

**Comment by drewhk** [comment]
PLS BUILD

**Comment by drewhk** [comment]
Ok, so sharding really fails with these patches. Interesting.

**Comment by patriknw** [comment]
Same thing locally, cluster sharding has changed rather much in master.
I will take a look at it.

**Comment by patriknw** [comment]
@drewhk it's a timing issue. Terminated is now triggered later when trying to talk to a shutdown node. In this case node `first` is crashed in an earlier step, but that has not been triggered when coming to the step that now fails.

The fix is to simply move "support proxy only mode" up, and place it after "support passivation and activation of entries". Then it must also `runOn(second)` instead of `sixth`.

Can you fix it here, or do you want me to submit a separate PR?

**Comment by drewhk** [comment]
I can fix it here but probably not today.

**Pull request merged**
