### PR TITLE
Fix Mima in release-2.5

### PR DESCRIPTION
**Pull request by jrudolph**
Refs #28748 

(First commit will just try to retrigger the problem, change will be removed afterwards)

### CODE REVIEW

**Comment by patriknw** [comment]
looks like I never updated latest patch in release-2.5 branch so maybe you can do that here

**Comment by patriknw** [comment]
is it related to the problems in https://github.com/akka/akka/pull/28736 ?

**Comment by jrudolph** [comment]
> is it related to the problems in #28736 ?

It looks similar, but it fails for Scala 2.12. Here are the errors:

```
* static method SortedExtensionMethods(scala.collection.generic.Sorted)akka.util.ccompat.package#SortedExtensionMethods in class akka.util.ccompat.package does not have a correspondent in current version
  filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.util.ccompat.package.SortedExtensionMethods")
* static method ImmutableTreeMapExtensions(scala.collection.immutable.TreeMap#)scala.collection.immutable.TreeMap# in class akka.util.ccompat.package does not have a correspondent in current version
  filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.util.ccompat.package.ImmutableTreeMapExtensions")
* static method ImmutableSortedMapExtensions(scala.collection.immutable.SortedMap#)scala.collection.immutable.SortedMap# in class akka.util.ccompat.package does not have a correspondent in current version
  filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.util.ccompat.package.ImmutableSortedMapExtensions")
* static method sortedSetCompanionToCBF(scala.collection.generic.SortedSetFactory,scala.math.Ordering)scala.collection.generic.CanBuildFrom in class akka.util.ccompat.package does not have a correspondent in current version
  filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.util.ccompat.package.sortedSetCompanionToCBF")
* static method genericCompanionToCBF(scala.collection.generic.GenericCompanion)scala.collection.generic.CanBuildFrom in class akka.util.ccompat.package does not have a correspondent in current version
  filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.util.ccompat.package.genericCompanionToCBF")
* static method FactoryOps(scala.collection.generic.CanBuildFrom)akka.util.ccompat.package#FactoryOps in class akka.util.ccompat.package does not have a correspondent in current version
  filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.util.ccompat.package.FactoryOps")
```

**Review by ennru — APPROVED** [review]
LGTM.

**Comment by ennru** [comment]
No Mima problems reported...

**Comment by ennru** [comment]
Even locally MiMa doesn't report any problems for me.

**Comment by jrudolph** [comment]
I could never reproduce it locally. The first "Test FAILed" was a neutral commit that triggered the problem another time.

**Comment by jrudolph** [comment]
> looks like I never updated latest patch in release-2.5 branch so maybe you can do that here

Added commit for that now.

**Comment by jrudolph** [comment]
Seems the Jenkins PR validator should not be running mima at all but is for unknown reasons.

**Comment by patriknw** [comment]
PLS BUILD

**Review by raboof — APPROVED** [review]
:+1: sorry about the weird jenkins thing :(

**Pull request merged**
