### PR TITLE
Fix #23385, Update ExtendedActorMaterializer doc

### LINKED ISSUE #23385: Obsolete documentation for ExtendedActorMaterializer
The description of `ExtendedActorMaterializer` is no longer true

```scala
/**
 * ExtendedActorMaterializer used by subtypes which materializer using GraphInterpreterShell
 */
@DoNotInherit private[akka] abstract class ExtendedActorMaterializer extends ActorMaterializer {
  ...
}

### PR DESCRIPTION
**Pull request by manuzhang**

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
LGTM, thanks.

**Comment by johanandren** [comment]
OK TO TEST

**Comment by johanandren** [comment]
Fixes #23385

**Comment by manuzhang** [comment]
@johanandren Any more comments ?

**Comment by johanandren** [comment]
Nop. Was waiting for another OK from the core team, which is our usual process. But given that it is just a doc change, I'll merge it.

**Pull request merged**
