### PR TITLE
=htc Relocate HttpResponseParser.stage to tests

### PR DESCRIPTION
**Pull request by leachbj**
This stage is no longer required since 9dc474a1 converted HttpResponseParser
to a GraphStage.

### CODE REVIEW

**Comment by jrudolph** [comment]
OK TO TEST

**Comment by jrudolph** [comment]
Nice catch. LGTM. Let's see what the build says (akka-ci seems to be deaf to my voice...).

**Comment by jrudolph** [comment]
OK TO TEST

**Comment by jrudolph** [comment]
OK TO TEST

**Comment by leachbj** [comment]
Migrated to akka-http in https://github.com/akka/akka-http/pull/312

**Pull request closed without merging**
