### PR TITLE
-doc,str,tes remove statsd and graphite reporting code, its not used

### PR DESCRIPTION
**Pull request by ktoso**
Just trimming some fat that I've committed some time ago.
None of this code is currently used.

/me needs some negative line count ;-)

### CODE REVIEW

**Comment by patriknw** [comment]
I hope you don't mind that I didn't use this for the Artery trend plots. I wanted something dead simple without need for additional infra, and especially I didn't want to put more workload on you.

**Comment by ktoso** [comment]
Nah, completely don't mind.
This requires quite some infrastructure to go with it, and the new thing is
much simpler - which I like! 👍

**Comment by johanandren** [comment]
PLS BUILD

**Comment by ktoso** [comment]
I'll merge, this is just removing not used things.

**Pull request merged**
