### PR TITLE
akka-cluster: logging selfRoles during node unreachable and quarantined

### PR DESCRIPTION
**Pull request by f1yegor**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @f1yegor,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by patriknw** [comment]
OK TO TEST

**Comment by patriknw** [comment]
LGTM

**Comment by ktoso** [comment]
LGTM I guess

**Comment by ktoso** [comment]
Resolves https://github.com/akka/akka/issues/20613

**Comment by ktoso** [comment]
Thanks for contributing @f1yegor :-)
Seems like a nice addition 👍

**Comment by f1yegor** [comment]
yeah, we use roles, and it's had to understand situation when the cluster is falling apart without roles information.

**Pull request merged**
