### PR TITLE
Fix compilation issue

### PR DESCRIPTION
**Pull request by 2m**
After #24016

### CODE REVIEW

**Comment by patriknw** [comment]
How could this have passed PR validation? We shouldn't merge without successful validation.

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by SethTisue** [comment]
the compilation failure turned up in the Scala community build at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2266/consoleFull

**Comment by 2m** [comment]
PLS BUILD

**Comment by nachinius** [comment]
> How could this have passed PR validation? We shouldn't merge without successful validation.

It seems there were a forgotten `ok to test` in the original PR

**Comment by nachinius** [comment]
> Test Result (1 failure / +1)
> akka.stream.DslFactoriesConsistencySpec.Java DSL must provide Sink which allows creating the same Sinks as Scala DSL

It sounds like the original merged PR should be reverted, until this is addressed.
I created a revert PR #24060 for your convenience. I suggest merging #24060, closing this, and reopening #23917 (and add in #23917 the 'ok to test').

**Comment by patriknw** [comment]
yes, let's revert and fix it properly

**Pull request closed without merging**
