### PR TITLE
introduce Scaladoc groups for Directives

### PR DESCRIPTION
**Pull request by larsrh**
First part of #20103.

Review by @ktoso.

### CODE REVIEW

**Comment by larsrh** [comment]
screenshot_20160402_232252

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Thanks a lot for picking this up!

**Comment by 2beaucoup** [comment]
:+1:  Awesome!

**Comment by drewhk** [comment]
Great, we need something like this for Streams, too.

**Comment by ktoso** [comment]
Looks great, thanks a lot Lars for this!

**Pull request merged**
