### PR TITLE
Improve map stage diagrams

### PR DESCRIPTION
**Pull request by johanandren**
Supersedes #20360

### CODE REVIEW

**Comment by drewhk** [comment]
How does this clear up things? I don't agree with the change here.

**Comment by johanandren** [comment]
I don't really have an opinion but thought there was consensus on the original PR?

**Comment by johanandren** [comment]
Or you mean the LGTM from you was invalidated by me changing the orange `f(elem)` into `f` ?

**Comment by drewhk** [comment]
Ah yes, I only saw that change in this PR. Yeah, I find the single `f` a bit confusing there. Maybe make it imperative then and say "apply `f`"? My main issue is that a single letter is too terse and harder to parse when skimming the image.

**Comment by johanandren** [comment]
I kind of wanted to do a `b = f(grab(in))` in orange and then `push(out, b)` but didn't figure out a terse enough way to do that.

**Comment by drewhk** [comment]
This looks reasonable, thanks!

**Pull request merged**
