### PR TITLE
+htp,spray allow Marshal(T).to[ByteString] given JSON marshallers

### PR DESCRIPTION
**Pull request by ktoso**
Added missing marshalling side, unmarshalling was part of JSON Streaming PR

### CODE REVIEW

**Comment by ktoso** [comment]
Please give it a skim @akka/akka-team, found this while preparing https://github.com/ktoso/akka-streaming-example/blob/master/src/main/scala/akka/http/example/TwitterSampleStream.scala

**Comment by johanandren** [comment]
LGTM

**Comment by 2beaucoup** [comment]
No test/sample. :cry:

What's the `flatMap` needed for?

**Comment by ktoso** [comment]
>  No test/sample. 😢


Very true, I shall add

**Comment by ktoso** [comment]
Closing for now

**Pull request closed without merging**
