### PR TITLE
=str #16935 revive dsl consistency spec

### PR DESCRIPTION
**Pull request by 2m**
`DslConsistencySpec` is up and kicking.

Next up: `DslFactoriesConsistencySpec`

### CODE REVIEW

**Comment by drewhk** [comment]
LGTM. The hard part will be the factories, I guess.

**Comment by 2m** [comment]
That is right. Low hanging fruit this one is.

**Comment by ktoso** [comment]
Very cool, LGTM.
Should we merge this already and the other Spec in a different PR or together?

**Comment by 2m** [comment]
I think we can merge this one.

**Comment by ktoso** [comment]
Happy to do so :-)

**Comment by ktoso** [comment]
Refs #16935

**Pull request merged**
