### PR TITLE
feat: Predefined marker interfaces for JSON and CBOR

### PR DESCRIPTION
**Pull request by johanandren**
Or is there a good reason we don't ship such @patriknw ?

### CODE REVIEW

**Review by patriknw — COMMENTED** [review]
Yeah, I'm not sure why we don't have those. I think it's good, and removes that boilerplate step of adding your own. We must have considered it in the original implementation because we had it in Lagom, but I can't find any memories or comments about it. Closest might be https://github.com/akka/akka/pull/26870#issuecomment-490464915

Anyway, go ahead, can't hurt. There is also docs that should be updated.

**Review by patriknw — COMMENTED** [review]
I think we already have some JsonSerializable in tests and another in SerializationDocSpec.scala that should be replaced. Search for JsonSerializable in `main`.

**Comment by johanandren** [comment]
Had indeed missed two markers in tests, but those already had the same package as the new ones, so just dropping those should be enough.

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
