### PR TITLE
=doc =per fixed a few typos from 'Unknow' to 'Unknown'

### PR DESCRIPTION
**Pull request by ch33hau**
Fixed a few simple typos in exception's message, from "Unknow" to "Unknown".

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Excellent, thanks!

**Comment by ktoso** [comment]
Thanks @ch33hau !

**Comment by ch33hau** [comment]
Thanks @ktoso too =)

**Pull request merged**
