### PR TITLE
Add recipe to take the last n elements

### PR DESCRIPTION
**Pull request by naferx**
Refs https://github.com/akka/akka/issues/25322

### CODE REVIEW

**Review by ktoso — COMMENTED** [review]
That's one of those basic operators that I'd rather implement on Sink rather than have people reimplement them... How about doing that?

**Comment by naferx** [comment]
That was exactly my initial proposal. Take a look at the issue

**Comment by ktoso** [comment]
Yeah heh... I guess I'm disagreeing with the point made there. There's a set of very basic general operators, `last` / `takeLast` being one of them, that IMHO we really should provide; yes, taking last elements in a streaming setting "sucks" a bit, but may be exacly what is sometimes needed...

I'll discuss with team a bit more and see what conclusion we can come up with

**Comment by naferx** [comment]
Ok, That sounds reasonable ;)

**Comment by ktoso** [comment]
Discussed internally and for the sake of symmetry we'd like to add the `takeLast` operator after all. 
Would you want to PR it @naferx ? Please rememeber JavaDSL as well, let us know if you'd need help there.

**Comment by ktoso** [comment]
I'll close this PR for now, awaiting the takeLast impl! :-)
Thanks in advance!

**Pull request closed without merging**
