### PR TITLE
Update to paradox 0.31

### PR DESCRIPTION
**Pull request by jrudolph**
That would unblock the Akka HTTP 10.1 nightlies which currently fail because of the plugin incompatibility.

https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.1/AKKA_VERSION=release-2.5,Node=akka-http-nightly-node,SCALA_VERSION=2.12.10,jdk=AdoptOpenJDK%208/832/console

Is there a reason this hasn't been done or mostly because not touching things that are not broken?

### CODE REVIEW

**Review by raboof — APPROVED** [review]
Seems OK to me but it appears it wants the 'project-info' backported as well

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by ennru** [comment]
There are bad links that make Paradox fail. I'll fix things up.

**Comment by ennru** [comment]
PR validation: `akka-actor: Binary compatibility check failed!`

**Comment by jrudolph** [comment]
Mima errors are:

```
[03-16 16:02:42.830] [error]  * static method SortedExtensionMethods(scala.collection.generic.Sorted)akka.util.ccompat.package#SortedExtensionMethods in class akka.util.ccompat.package does not have a correspondent in current version
[03-16 16:02:42.830] [error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.util.ccompat.package.SortedExtensionMethods")
[03-16 16:02:42.830] [error]  * static method ImmutableTreeMapExtensions(scala.collection.immutable.TreeMap#)scala.collection.immutable.TreeMap# in class akka.util.ccompat.package does not have a correspondent in current version
[03-16 16:02:42.830] [error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.util.ccompat.package.ImmutableTreeMapExtensions")
[03-16 16:02:42.831] [error]  * static method ImmutableSortedMapExtensions(scala.collection.immutable.SortedMap#)scala.collection.immutable.SortedMap# in class akka.util.ccompat.package does not have a correspondent in current version
[03-16 16:02:42.831] [error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.util.ccompat.package.ImmutableSortedMapExtensions")
[03-16 16:02:42.831] [error]  * static method sortedSetCompanionToCBF(scala.collection.generic.SortedSetFactory,scala.math.Ordering)scala.collection.generic.CanBuildFrom in class akka.util.ccompat.package does not have a correspondent in current version
[03-16 16:02:42.831] [error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.util.ccompat.package.sortedSetCompanionToCBF")
[03-16 16:02:42.831] [error]  * static method genericCompanionToCBF(scala.collection.generic.GenericCompanion)scala.collection.generic.CanBuildFrom in class akka.util.ccompat.package does not have a correspondent in current version
[03-16 16:02:42.831] [error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.util.ccompat.package.genericCompanionToCBF")
[03-16 16:02:42.831] [error]  * static method FactoryOps(scala.collection.generic.CanBuildFrom)akka.util.ccompat.package#FactoryOps in class akka.util.ccompat.package does not have a correspondent in current version
[03-16 16:02:42.831] [error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.util.ccompat.package.FactoryOps")
```

however, I cannot reproduce them locally. I now reverted the changes to see if it's related at all to this change.

**Comment by ennru** [comment]
https://github.com/akka/akka/pull/28749 fixes the Mima problem.

**Comment by patriknw** [comment]
PLS BUILD

**Comment by ennru** [comment]
With Akka HTTP using pre-build Akka snapshots, should we leave this alone?

**Comment by ennru** [comment]
Let's give this up.

**Pull request closed without merging**
