### PR TITLE
Rebased "New" JavaDSL (almost there...)

### PR DESCRIPTION
**Pull request by ktoso**
Rebased what previously was https://github.com/akka/akka/pull/20088

Resolves #19632 #19519

### CODE REVIEW

**Comment by ktoso** [comment]
(FYI – @johanandren this is simply brought to a mergeable state what we had during the day today, spending some time on it still, will inform on progress).

**Comment by johanandren** [comment]
Should we squash this before merging when we get there? There is quite a bit of useless commit messages in there (because we were micro-committing to be able to integrate with each others changes).

**Comment by patriknw** [comment]
I think some squashing (cleanup of commit messages) is needed. It's possible to set multiple authors on commits, right?

**Comment by johanandren** [comment]
Yeah, or maybe we can do an interactive rebase and squash more selectively

**Comment by ktoso** [comment]
Yes, well want to squash here in some nice way, maybe into a few commits. There are a few phases in it that we can make (ending up with like 3 commits or so)

**Comment by ktoso** [comment]
Checked the failure, it's ry compatibility it seems. Yay. I'll address that today I hope

**Comment by ktoso** [comment]
Now as: https://github.com/akka/akka/pull/20505

**Pull request closed without merging**
