### PR TITLE
Fixup for OAuth2 token for WWW-Authenticate Part1

### PR DESCRIPTION
**Pull request by pchordia15**
#20102 fixes part 1.

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Comment by ktoso** [comment]
This does not look to be correct, also, a test would be needed to verify behaviour.
Please see my comment in https://github.com/akka/akka/issues/20102#issuecomment-199443697 that explains the potential fix, and then add a test proving it's good :)

**Comment by pchordia15** [comment]
I tried it the way(my first commit) you described in your comment but the test failed.

**Comment by monkey-mas** [comment]
Hi @pchordia15 ,

Can you please let me know if you're still working on this? :)

**Comment by ktoso** [comment]
If you'd like to take over this ticket please do @monkey-mas, thanks in advance :)

**Comment by monkey-mas** [comment]
Could we close this PR? The fix of this PR has been merged in https://github.com/akka/akka/pull/20756 I suppose :)

**Comment by ktoso** [comment]
Right, thanks for noticing!

**Pull request closed without merging**
