### PR TITLE
Remove application.conf from typed test projects

### LINKED ISSUE #25014: Failed: MultiJVM nightlies
Assembly is broken so can't send the artifacts across: 

https://jenkins.akka.io:8498/job/akka-multi-node/2738/consoleFull

### PR DESCRIPTION
**Pull request by chbatey**
It breaks assembly for multi-jvm jobs as there are duplicates. Only needs to be in
the tests project. 

Fixes #25014

### CODE REVIEW

**Review by raboof — APPROVED** [review]
So the tests in the these projects will still pick up the application.conf from `akka-actor-typed-tests` because of the `actorTypedTests % "test->test"` dependency? Pretty subtle... but OK :+1:

**Review by johanandren — APPROVED** [review]

**Comment by patriknw** [comment]
What tests depend on this? If they have to be .conf files it might be
better to name it something more unique that is more specific for the
test(s) that need it.

I prefer String based config in tests.
mån 30 apr. 2018 kl. 10:58 skrev Johan Andrén <notifications@github.com>:

**Comment by chbatey** [comment]
Actually doesn't look like any of them do now, i'll remove the final app.conf

**Comment by johanandren** [comment]
Can't see that any of the dispatchers where actually referenced in any test.

**Comment by chbatey** [comment]
I lie, dispatchers are not used but the extensions are. I will move that to a string config in the test

**Pull request merged**
