### PR TITLE
Missing functionality akka-fsm (during onTransition): nextStateName

### PR DESCRIPTION
**Pull request by IanGrima**
To be used during onTransition similar to nextStateData.

### CODE REVIEW

**Comment by IanGrima** [comment]
Note: This method would be useful when using a wildcard to match the "to" state during a transition.

**Comment by ktoso** [comment]
Does this have a ticket open? If not, please create one and link to it from here.
Please provide tests as well as documentation (reference docs, and scala docs) for any new feature.
Technically this would be binary compatible I guess.

**Comment by patriknw** [comment]
@IanGrima I'm not sure I like such variable that can only be accessed from onTransition. Could a better solution be to improve the `FSMTransitionHandlerBuilder` to support wildcard and passing in the `nextState` in those functions?

**Comment by IanGrima** [comment]
@patriknw Thanks for your reply, I looked into it it seems the FSMTransitionHandlerBuilder already supports something like you mentioned, i had not noticed this, it seems that the nextStateName is not required. Thanks again.

**Comment by patriknw** [comment]
ah, awesome :)

**Pull request closed without merging**
