### PR TITLE
=str: Don't use "remaining", check proper localized TCP messages

### PR DESCRIPTION
**Pull request by drewhk**

### CODE REVIEW

**Comment by ktoso** [comment]
LGTM

**Comment by rkuhn** [comment]
LGTM

**Comment by rkuhn** [comment]
(I assume that the FIXME will be fixed before merging)

**Comment by drewhk** [comment]
It needs a fix in Akka 2.3.x, becuase it is duplicated there. Anyway, I didn't intend to merge this for RC3 anyway, I just fixed stuff while I was at it.

**Comment by patriknw** [comment]
LGTM

**Comment by drewhk** [comment]
Added ticket to remove test code duplication: https://github.com/akka/akka/issues/17612

**Comment by drewhk** [comment]
Now streams should compile with 2.4 (until we break it again ;) )

**Pull request merged**
