### PR TITLE
Update event-bus.md

### PR DESCRIPTION
**Pull request by dgomezg**
Removed a duplicate sentence (comming from an automatic merge) at line 24 :"An event bus must define the following three type parameters:"

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @dgomezg,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by dgomezg** [comment]
I've signed the CLA

**Comment by johanandren** [comment]
OK TO TEST

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Review by ktoso — APPROVED** [review]
Thanks!

**Pull request merged**
