### PR TITLE
Remove some of `Unused import` warning

### PR DESCRIPTION
**Pull request by jiminhsieh**
Fix part of #16334.

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Review by chbatey — APPROVED** [review]
LGTM, needs a squash

**Comment by ktoso** [comment]
I propose merging today, yet after we try to aggresively merge other things, in order to not cause too many conflicts in imports on other PRs

**Review by ktoso — APPROVED** [review]

**Review by patriknw — APPROVED** [review]
LGTM, I'll see if some other PRs can be merged first

**Comment by ktoso** [comment]
Rebased, will squash merge as otherwise this will continue needing rebases.

**Pull request merged**
