### PR TITLE
Remove obsolete RestartTestStage, #20288.

### PR DESCRIPTION
**Pull request by danxmoran**
Following the same reasoning as in #20629, I don't think defining and testing the `RestartTestStage` is telling us anything useful now that there's no longer any centralized supervision logic for stages.

This deletion wasn't pre-sanctioned like the other was, though, so let me know if my reasoning is off :)

### CODE REVIEW

**Comment by danxmoran** [comment]
Refs #20288.

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
I think you're right, same reasoning applies - thanks!
LGTM

**Comment by danxmoran** [comment]
Failure is #20676, which looks like it's been fixed by #20693 (merged after I set up this PR). I'll see if a rebase fixes things.

**Comment by ktoso** [comment]
Yup, thanks for rebasing

**Comment by ktoso** [comment]
LGTM from my side.
cc @drewhk

**Comment by drewhk** [comment]
LGTM, agreed.

**Comment by ktoso** [comment]
Thanks again @danxmoran !

**Pull request merged**
