### PR TITLE
=doc set up mailbox for BalancingPool documented #13961

### PR DESCRIPTION
**Pull request by ivan-lorenz**
Tests for the new documentation has been introduced previously in [PR #2127](https://github.com/akka/akka/pull/2127).

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by johanandren** [comment]
LGTM

**Comment by ktoso** [comment]
Refs https://github.com/akka/akka/issues/13961

**Comment by johanandren** [comment]
LGTM, Thanks!

**Comment by ivan-lorenz** [comment]
Thanks to you all to keep alive this great toolkit.

**Pull request merged**
