### PR TITLE
Update sbt version in akka-samples subprojects

### PR DESCRIPTION
**Pull request by naferx**

### CODE REVIEW

**Comment by ktoso** [comment]
Hmm, I'm not sure if Activator will survive this.
The samples are a bit weird.

@2m would know once he's back

**Comment by ktoso** [comment]
OK TO TEST

**Comment by naferx** [comment]
Mmm. Interesting. I didn't know that.

**Comment by patriknw** [comment]
Let's fix this together with https://github.com/akka/akka/issues/21639

**Pull request closed without merging**
