### PR TITLE
Clean duplicate member access

### PR DESCRIPTION
**Pull request by naferx**

### CODE REVIEW

**Comment by johanandren** [comment]
Not sure how these changes do what the PR title says?

**Comment by johanandren** [comment]
@naferx do you have any feedback on this or can we close this pull request?

**Comment by naferx** [comment]
I made a mistake with the PR title but I think the change is fine.

**Comment by drewhk** [comment]
I don't see anything fixed here. I reopen once the purpose of this PR has been clarified.

**Pull request closed without merging**
