### PR TITLE
Upgrade to akka-paradox 0.24 with search box transparency fix

### LINKED ISSUE #27592: Update to latest Akka Paradox theme
The search box index fix https://github.com/akka/akka-paradox/issues/78 should be used before cutting the next 2.6 milestone.
It requires an Akka Paradox release.

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #27592

### CODE REVIEW

**Review by helena — APPROVED** [review]

**Comment by johanandren** [comment]
Strange, travis cannot resolve even though I could build locally and have sbt resolve the new version from bintray. Clearing the cache did not help.

**Comment by helena** [comment]
@johanandren I think I know why, re-running after deleting this job run cache.

**Comment by helena** [comment]
That was the issue a few weeks ago with a few upgrades, but it did not fix this travis run.

**Comment by raboof** [comment]
added jcenter to resolve the theme - not sure how this could've worked before...

**Comment by johanandren** [comment]
Now it fails with a MiMa error !?!

**Review by raboof — APPROVED** [review]

**Pull request merged**
