### PR TITLE
Update to Akka 2.3.15

### PR DESCRIPTION
**Pull request by 2m**

### CODE REVIEW

**Comment by 2m** [comment]
So the 2.3.15 is [here](http://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.10/2.3.15/) but not [here](http://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.10/). Probably some replication is still in progress...

**Comment by ktoso** [comment]
LGTM whenever maven central is ready :)

**Comment by patriknw** [comment]
LGTM

**Comment by patriknw** [comment]
PLS BUILD

**Comment by 2m** [comment]
PLS BUILD

**Comment by 2m** [comment]
PLS BUILD

**Pull request merged**
