### PR TITLE
#17074 fix typo: form -> from

### PR DESCRIPTION
**Pull request by ijsong**
Fix typo in akka stream document (#17074)

### CODE REVIEW

**Comment by drewhk** [comment]
Thanks for your contribution. Please sign our CLA here: https://www.typesafe.com/contribute/cla

**Comment by ijsong** [comment]
I just signed the CLA via that url.

**Comment by ktoso** [comment]
Thanks for the fix @ijsong! LGTM

**Comment by 2m** [comment]
This was merged to a wrong branch.

**Comment by ktoso** [comment]
Sorry about that. I'll cherrypick to `release-2.3-dev`

**Comment by 2m** [comment]
No prob. Thanks. :)

**Pull request merged**
