### PR TITLE
=pro #19581 Ignore MiMa changes in validatePullRequest.

### PR DESCRIPTION
**Pull request by danxmoran**
Ref #19581

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @danxmoran,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by drewhk** [comment]
You will need to sign the CLA, otherwise we won't be able to merge your PR. It is very easy to do, you can do it with your Github account easily.

**Comment by danxmoran** [comment]
I did right after the initial automated message.  Sorry, didn't realize I should indicate here that I filled it out!

**Comment by drewhk** [comment]
Thanks!

**Comment by drewhk** [comment]
OK TO TEST

**Comment by patriknw** [comment]
LGTM

**Comment by ktoso** [comment]
Great, thanks a lot!
:GTM

**Pull request merged**
