### PR TITLE
Fix typo of DispatcherSelector's Scaladoc

### PR DESCRIPTION
**Pull request by tisonkun**
straight forward

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @TisonKun,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by TisonKun** [comment]
> If you have already sent a pull request please add a comment to the pull request saying you did sign the CLA.

Ack.

**Review by raboof — APPROVED** [review]

**Comment by raboof** [comment]
OK TO TEST

**Review by helena — APPROVED** [review]
LGTM

**Comment by raboof** [comment]
Thanks!

**Pull request merged**
