### PR TITLE
Compiler warnings for actor-testkit #26708

### PR DESCRIPTION
**Pull request by helena**
## Purpose
Resolve compiler warnings for module.

## References 
https://github.com/akka/akka/issues/26708

### CODE REVIEW

**Review by johanandren — APPROVED** [review]

**Review by patriknw — APPROVED** [review]
LGTM

**Review by raboof — APPROVED** [review]
Would be good to also enable fatal warnings for this module - though we're close to just enabling it for all modules, though, and I manually confirmed it's complete now, so :+1:

**Comment by helena** [comment]
Ah that's the part I forgot @raboof ! Though indeed I think we are close to all being done.

**Comment by raboof** [comment]
(swapped from opt-in to opt-out in #26726)

**Pull request merged**
