### PR TITLE
mima: check against 2.6.4

### PR DESCRIPTION
**Pull request by raboof**
Checking against 2.5.30 is problematic, see #28736

### CODE REVIEW

**Comment by raboof** [comment]
failure is #28770

**Comment by patriknw** [comment]
PLS BUILD

**Comment by raboof** [comment]
(travis is failing because master gained some conflicts against 2.6.4, those need to be reviewed and either rolled back or excluded)

**Comment by patriknw** [comment]
fixed missing mima in https://github.com/akka/akka/pull/28827

**Pull request closed without merging**
