### PR TITLE
Fixed a spelling error in a cluster sharding error message when coordinator is not contactable.

### PR DESCRIPTION
**Pull request by bwmcadams**
Message should now be spelled correctly.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @bwmcadams,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by patriknw** [comment]
OK TO TEST

**Comment by patriknw** [comment]
LGTM, thanks

**Comment by ktoso** [comment]
Thanks LGTM

**Pull request merged**
