### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by cloudcalvin**
## Purpose

Fix a simple grammar mistake in the docs.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @cloudcalvin,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by johanandren** [comment]
Hi @cloudcalvin thanks for the PR, it seems to be against a weird branch that only exists to release artifacts for Scala 2.13 and needs to be against master instead. Curious: did you do create it through the docs or the GitHub UI somewhere?

**Comment by cloudcalvin** [comment]
Hey Johan,

Yeah sorry, first time contrib to Akka.

I noticed the error while reading and saw a link at the bottom of the docs to submit fixes, but the link (https://github.com/akka/akka/tree/v2.5.22/akka-docs/src/main/paradox/common/may-change.md) is on a tag and not on a branch so I just guessed a branch to work on.

Will use master branch next time!

Kind regards
Calvin
________________________________

**Review by jrudolph — APPROVED** [review]
LGTM

**Comment by jrudolph** [comment]
>  I noticed the error while reading and saw a link at the bottom of the docs to submit fixes, but the link ([/akka-docs/src/main/paradox/common/may-change.md@`v2.5.22`](https://github.com/akka/akka/tree/v2.5.22/akka-docs/src/main/paradox/common/may-change.md) [](/akka/akka/tree/HEAD@{2019-05-15T09:48:59Z}/akka-docs/src/main/paradox/common/may-change.md)

Can you rebase on top of master and change the base branch by using "Edit" above in the PR?

**Review by raboof — APPROVED** [review]
Change looks good, thanks! Changing the target branch to 'master' with the 'edit' button next to the PR title above might be sufficient.

**Comment by patriknw** [comment]
Might be easiest to start over from master, and then add the changes again. Can still be force pushed to same branch/PR.

**Pull request merged**
