### PR TITLE
WIP: Optimized first recovery, #25072

### PR DESCRIPTION
**Pull request by patriknw**
* Introduce a new Recovery.first that can be used if it's known that it's
  the very first time the persistent actor is started.

Refs #25072

Marked as WIP because we still don't know if this will be needed or if the other more safe optimizations in https://github.com/akka/akka/pull/25132 are enough.

### CODE REVIEW

**Review by ktoso — APPROVED** [review]
Fairly specialized but I see the use case.

**Review by johanandren — APPROVED** [review]
Looks dangerous but OK to me (LDBOTM).

**Comment by ktoso** [comment]
On the other hand, I've just noticed the subtitle of the PR...

> Marked as WIP because we still don't know if this will be needed or if the other more safe optimizations in #25132 are enough.

Not sure if should merge then hm...

**Comment by patriknw** [comment]
Don’t merge until we know more from customer

**Review by ktoso — CHANGES_REQUESTED** [review]
WIP do not merge for now

**Comment by patriknw** [comment]
Since I haven't heard anything I'm closing it.

**Pull request closed without merging**
