### PR TITLE
=per #19283 Fix OSGi manifest for optional LevelDB dependency

### PR DESCRIPTION
**Pull request by briantopping**

### CODE REVIEW

**Comment by briantopping** [comment]
I'm going to re-run this on the 2.3-dev branch. I forgot that one existed.

**Comment by ktoso** [comment]
Thanks @briantopping!
Actually master is the right branch for any persistence work.

**Comment by ktoso** [comment]
Branches are explained here: https://github.com/akka/akka/blob/master/CONTRIBUTING.md#branches-summary

**Comment by ktoso** [comment]
OK TO TEST

**Comment by briantopping** [comment]
Okay, thanks for the info! Please feel free to CC me on OSGi stuff as well.

**Comment by ktoso** [comment]
Thanks a lot! We're not very deep in OSGi things so help is very welcome on that front!
// Refs #19283

**Comment by ktoso** [comment]
OK TO TEST

**Comment by patriknw** [comment]
LGTM

**Comment by briantopping** [comment]
Could we get some eyes on #19286 as well? I would have put them in the same patch, but they are on different branches. Thank you! :)

**Comment by ktoso** [comment]
This one LGTM, will look at the other soon, thanks @briantopping !

**Comment by ktoso** [comment]
Refs #19283

**Comment by briantopping** [comment]
Thank @ktoso!!

**Pull request merged**
