### PR TITLE
Fix 'Location Transparency' link in remoting

### PR DESCRIPTION
**Pull request by raboof**
Also merge Java and Scala variations of this .md

### CODE REVIEW

**Review by ktoso — APPROVED** [review]
LGTM, and good additions/merge along the way!

**Comment by raboof** [comment]
Yeah merging reveals the java and scala variations diverged a bit over time, feels good to make that consistent again :). The IDEA diff/merge window is quite nice for this btw.

**Comment by ktoso** [comment]
Yeah, one of the reasons merging should give us better docs consistency/quality :-)

**Review by johanandren — APPROVED** [review]
LGTM!

**Review by patriknw — COMMENTED** [review]
very nice to see this consolidation

**Pull request merged**
