### PR TITLE
Remove superfluous final modifier (closes #19493)

### LINKED ISSUE #19493: [Akka Typed] Superfluous final modifier for objects
Example: `final case object PreStart extends Signal`

### PR DESCRIPTION
**Pull request by hseeberger**

### CODE REVIEW

**Review by chbatey — APPROVED** [review]
LGTM

**Comment by johanandren** [comment]
Refs #19493

**Review by johanandren — APPROVED** [review]
LGTM, thanks @hseeberger !

**Comment by patriknw** [comment]
thanks

**Pull request merged**
