### PR TITLE
=act #18364 fix AbstractFSM#onTransition infinite recursion

### LINKED ISSUE #18364: AbstractFSM#onTransition is recursive by accident
As noticed by @bjoernhaeuser (Thanks!)
https://github.com/akka/akka/blob/v2.3.12/akka-actor/src/main/scala/akka/actor/FSM.scala#L863

### PR DESCRIPTION
**Pull request by AnkushKhanna**
Closes #18364

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by AnkushKhanna** [comment]
We fixed the compile issue. Can you let the bot test again?

**Comment by patriknw** [comment]
it will

**Comment by ktoso** [comment]
Excellent, thanks for the PR @AnkushKhanna! Would you please change the commit message to match out contributing guidelines ( https://github.com/akka/akka/blob/master/CONTRIBUTING.md )? In this case it would be `=act #18364 fix AbstractFSM#onTransition infinite recursion"

**Comment by ktoso** [comment]
Thanks for noticing the problem and the fix @AnkushKhanna! 
 We'll ship it in the next 2.3.x as well as 2.4-RC2.

**Pull request merged**
