### PR TITLE
optimized temp buffer for IndexedSeq

### PR DESCRIPTION
**Pull request by colinrgodsey**
Avoid resizing and potentially copying the temp buffer for IndexedSeqs larger than the temp buffer.

This change-set relates to ideas discussed in issue #17028 (and stems from proposed optimizations in PR #17029).

### CODE REVIEW

**Comment by patriknw** [comment]
OK TO TEST

**Comment by drewhk** [comment]
LGTM

**Comment by bantonsson** [comment]
LGTM

**Comment by patriknw** [comment]
LGTM

**Comment by ktoso** [comment]
LGTM

**Pull request merged**
