### PR TITLE
Separate dot attributes by comma's

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by ktoso** [comment]
Was it broken with ; or why?

**Comment by raboof** [comment]
Yeah, or at least http://webgraphviz.com/ did not accept it ;)

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
webgraphviz, nice!

**Comment by ktoso** [comment]
Thanks for the info - LGTM!
Nice, did not know that website :)

**Pull request merged**
