### PR TITLE
Update to a working version of Scalariform

### PR DESCRIPTION
**Pull request by bantonsson**
Now without the binary incompatibility ™ of #19746. The fix for #19772 is not automagic, and to use the new `→` extractor in `FSM` and `PersistentFSM`, you need to import it from the `FSM`/`PersistentFSM` object, or wildcard import it, but that will not affect any existing code using the old one.

Also, the somewhat ugly imports in the style of `import FSM.`→`` is needed so that Scalariform doesn't throw an error (I've just rewritten all your arrows, but you don't expect me to read them back again. Right? 😉)

### CODE REVIEW

**Comment by patriknw** [comment]
Great, I will take a look. We just said in today's meeting that it should be possible.

Docs should not use unicode arrows, but you know that, right?

**Comment by bantonsson** [comment]
I know that, and AFAICS I haven't added any with my changes, but there are still UC arrows in there from earlier if you grep for them.

**Comment by bantonsson** [comment]
Do you want me to clean them up as well?

**Comment by bantonsson** [comment]
Cleaned up the old left over unicode arrows in docs and samples as well. (Got to keep the fans spinning in Switzerland)

**Comment by bantonsson** [comment]
That test failure is the first run that started before the extra arrow fixes.

**Comment by patriknw** [comment]
@bantonsson that solution for the `FSM` looks good to me.
The test stabilizing PRs are merged to master, so a rebase here and then we can hopefully get this in.
Thanks for your patience.

**Comment by bantonsson** [comment]
No problem. Glad that you found the issues and cleaned up the tests. Hopefully our nightlies will be a lot more stable now as well.

_"Patience, to god-damned hell with patience! We have no patience. In fact, we don't need patience. I don't have to show you any stinking patience..."_ 😉

**Comment by bantonsson** [comment]
PLS TEST

**Comment by ktoso** [comment]
Wohoo, awesome :)

**Comment by patriknw** [comment]
Thanks, @bantonsson

**Comment by patriknw** [comment]
Refs https://github.com/akka/akka/issues/17570

**Comment by patriknw** [comment]
Refs https://github.com/akka/akka/issues/19772 (FSM)

**Comment by drewhk** [comment]
Yaaay!

**Pull request merged**
