### PR TITLE
Docs: Fix a small typo in sharded daemon process docs

### PR DESCRIPTION
**Pull request by rbraley**
References #xxxx

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @rbraley,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by patriknw — COMMENTED** [review]
thanks

**Review by octonato — APPROVED** [review]

**Review by ennru — APPROVED** [review]
LGTM.

**Comment by ennru** [comment]
CLA checked out of systems.

**Pull request merged**
