### PR TITLE
=rem #17583 Increase default value of system-message-buffer-size

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by drewhk** [comment]
LGTM

**Comment by ktoso** [comment]
LGTM

**Comment by patriknw** [comment]
failure was in some persistent channel test, that we don't care about

**Comment by drewhk** [comment]
Please forward port

**Comment by patriknw** [comment]
Forward port in progress: https://github.com/akka/akka/pull/17703

**Comment by patriknw** [comment]
Refs #17583

**Pull request merged**
