### PR TITLE
docs: Fix Java code to check cookiesReply for ask

### PR DESCRIPTION
**Pull request by bufferings**
Change to check cookiesReply not null instead of cookies for #standalone-ask-fail-future Java code

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
LGTM, that was probably the intended null check.

**Comment by johanandren** [comment]
OK TO TEST

**Comment by bufferings** [comment]
I'll try this

> [error] Unformatted code found. Please run 'scalafmtAll' and 'test:compile' and commit the reformatted code.

**Comment by lightbend-cla-validator** [comment]
Hi @bufferings,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by bufferings** [comment]
I signed to the CLA.

**Comment by johanandren** [comment]
I have manually checked that the CLA is signed 👍

**Comment by johanandren** [comment]
Thanks @bufferings !

**Comment by bufferings** [comment]
Thank you @johanandren !

**Pull request merged**
