### PR TITLE
Merge content of stream graphs.md

### PR DESCRIPTION
**Pull request by naferx**
Ref #23052

### CODE REVIEW

**Comment by raboof** [comment]
@naferx did you mean to close this one?

**Comment by naferx** [comment]
yeah, closed it because I made a mistake, I don't know why `.../scala/stream/stream-graphs.md` is not commited here but in my local branch this file is commited. Then tried to submit a new branch. Hope to get back to it tomorrow

**Comment by raboof** [comment]
Ah that might actually be the GitHub UI playing tricks at us: we've noticed before it sometimes gets confused (we think by the symlinks) and the aggregate 'Files changed' tab doesn't show all changes (though viewing each commit separately tends to work)

**Comment by naferx** [comment]
Hehe, Thanks for the hint :)

**Pull request closed without merging**
