### PR TITLE
Use generic type inference and method references in FlowDocTest.java

### PR DESCRIPTION
**Pull request by Captain1653**
Maybe it will be little better.

Kind regards

### CODE REVIEW

**Comment by Captain1653** [comment]
```
[info] Tests: succeeded 949, failed 1, canceled 0, ignored 0, pending 13
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	akka.actor.typed.scaladsl.MessageAdapterSpec
[error] (akka-actor-typed-tests / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 271 s (04:31), completed Aug 4, 2021, 8:01:34 PM
```
I didn't change the code. Infrustructure?

**Comment by raboof** [comment]
> Hmmmm.... I didn't change the code. Infrastructure?

Yes, don't worry about the GitHub Actions tests for now - we're in the process of migrating but some tests are still somewhat unreliable.

**Comment by raboof** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]
I don't have a strong preference between lambda's and method references

**Review by johanandren — APPROVED** [review]

**Pull request merged**
