### PR TITLE
harden NodeChurnSpec, #21053

### PR DESCRIPTION
**Pull request by patriknw**
I have looked at the logs of the failing test. The cluster extension is not shutdown as expected for one node when leaving the cluster. That node is removed as expected from the cluster so I don't know why the test fails.

I have added an extra barrier before the failing check.

I can start a repeat job for this branch.

### CODE REVIEW

**Comment by drewhk** [comment]
LGTM so far.

**Comment by johanandren** [comment]
LGTM

**Comment by patriknw** [comment]
no failures from the the repeat job, we'll see if it happens again

**Comment by patriknw** [comment]
Refs #21053

**Pull request merged**
