### PR TITLE
[#24294] Fix DistributedPubSubMediator not unsubscribing actors from …

### LINKED ISSUE #24294: Actors are not unsubscribed from DistributedPubSub on termination
Hi all. I hit a problem today where it appears the DistributedPubSub system is not automatically unsubscribing actors from topics when they terminate (which is contrary to the [PubSub documentation](https://doc.akka.io/docs/akka/current/distributed-pub-sub.html#publish)). I have a snippet demonstrating this behavior [here](https://gist.github.com/naiello/f97a77398e5bce8fe9937dad5171a999). Since references to the ActorRef instances are retained by the DistributedPubSubMediator, the JVM can't garbage collect them and they accumulate on the heap.

After investigating the issue, I found [this](https://github.com/akka/akka/blob/master/akka-cluster-tools/src/main/scala/akka/cluster/pubsub/DistributedPubSubMediator.scala#L350) (L350). It appears the Terminated message handler in TopicLike removes the dead subscriber from the set, but the Terminated handler is overridden via .orElse in the Topic class, and the behavior is not replicated in Topic.

I'd be happy to submit a pull request against this tomorrow.

### PR DESCRIPTION
**Pull request by naiello**
Resolves #24294 - Actors are not unsubscrubed from DistributedPubSubMediator topics when they terminate.

The actual fix for this issue was only one line (DistributedPubSubMediator.scala L396 in the diff), to remove the ActorRef from the subscriber list when it terminates. I have written some infrastructure to observe changes to topic subscribers in test, but as I don't have prior experience writing Multi-JVM tests, I would definitely appreciate feedback on that front.

Additionally, I ran the same Gist that I posted to reproduce the original issue (https://gist.github.com/naiello/f97a77398e5bce8fe9937dad5171a999) against the patch, and observed that no dead-letter for the terminated actor was logged. Finally, I ran a test in VisualVM which continually created, subscribed and terminated actors, observing that in the patched version, invoking the GC manually causes the stale ActorRefs on the heap to be reclaimed.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @naiello,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
OK TO TEST

**Comment by lightbend-cla-validator** [comment]
Hi @naiello,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by johanandren** [comment]
Hi @naiello, is there a problem for you signing the CLA?

**Comment by naiello** [comment]
My apologies for the delay, I wrote this patch for my employer and I needed to get the CCLA reviewed. I have obtained verbal approval and I'm just waiting for the official signed copy. Should be today or tomorrow.

**Comment by johanandren** [comment]
How's it going with the approval?

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by naiello** [comment]
Hi again guys. Sorry for the continued delay, this is the first time I've submitted an external PR through my employer and I evidently severely underestimated the turnaround time required. I reached out to our legal department again today and they assured me that the document has been reviewed and is just awaiting a signature.

**Comment by johanandren** [comment]
Thanks for letting us know :)

**Review by johanandren — APPROVED** [review]

**Comment by naiello** [comment]
CLA signed and approved. Thanks for your patience!

**Comment by ktoso** [comment]
CLA confirmed, thanks!

**Review by ktoso — APPROVED** [review]

**Comment by ktoso** [comment]
Looks good, thanks!

**Comment by patriknw** [comment]
Thanks @naiello , sorry for the inconvenient delay with the CLA. Will be smooth next time.

**Pull request merged**
