### PR TITLE
Update to the latest akka-paradox

### PR DESCRIPTION
**Pull request by 2m**
Update to the latest of https://github.com/akka/akka-paradox/pull/1

### CODE REVIEW

**Comment by 2m** [comment]
There has been some NZ activity on the PR since. We can merge this, but I'll create one more PR when the dust settles.

**Comment by pvlugter** [comment]
@2m ready to go now.

**Comment by 2m** [comment]
Thnanks. Updated.

**Comment by raboof** [comment]
Some more updates in f87c015c ;). Perhaps we should merge https://github.com/akka/akka-paradox/pull/1, too?

**Comment by 2m** [comment]
Released with that commit as well.

**Pull request merged**
