### PR TITLE
=per #17598 Add writerUuid to PersistentRepr

### PR DESCRIPTION
**Pull request by patriknw**
**Skip the first commit, it is from PR #17818, which will be merged first.**
- to support detection of multiple writers, facility to do that automatically is not part of this commit (I will create a separate ticket for that part)

### CODE REVIEW

**Comment by patriknw** [comment]
@ktoso ok to merge?

**Comment by ktoso** [comment]
I know I'm slow today ;) Finishing up docs on mine and will review all remaining your PRs.

**Comment by patriknw** [comment]
Sorry for being pushy, I'm so eager to get M2 out tomorrow. Things are looking good, and we can complete the last pieces tomorrow morning. Have a nice evening!

I have created a ticket for the second part of this: #17837

**Comment by ktoso** [comment]
No worries, no offence taken :-) I'm not completely back to usual speed :-)
Things look good for shipping tomorrow!

**Comment by ktoso** [comment]
Oh, that was a small patch - sorry to have it waiting so long then. 
Looks good, LGTM!

Can't wait to make use of that field, should help a lot in cluster siuations

**Comment by patriknw** [comment]
Refs #17598

**Pull request merged**
