### PR TITLE
* Compression table created in transport, but owned by Decoder (For Validation)

### PR DESCRIPTION
**Pull request by ktoso**
for validation backport of https://github.com/akka/akka/issues/21475

### CODE REVIEW

**Comment by patriknw** [comment]
@ktoso looks like a missing import
```
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphMatValueSpec.scala:238: not found: type Promise
[error]       val m3: Promise[Option[Int]] = Source.maybe[Int].viaMat(Flow[Int])(Keep.left).to(Sink.ignore).run()
[error]               ^
[error] one error found
```

**Comment by ktoso** [comment]
Attampted a fix via web ui, while waiting here... If that wasn't all will
fix once back home.

**Comment by patriknw** [comment]
Wow, how is that possible. https://github.com/akka/akka/issues/22161
Not related to this PR as far as I can see.

**Comment by patriknw** [comment]
PLS BUILD

**Comment by ktoso** [comment]
Removed the accidentally added test, waiting on validation will then squash merge

**Comment by ktoso** [comment]
Tests passed, merging ./

**Pull request merged**
