### PR TITLE
Correct link to Java Akka Docs

### PR DESCRIPTION
**Pull request by Philippus**

### CODE REVIEW

**Comment by ktoso** [comment]
Refs https://github.com/akka/akka/issues/22879 
(please link to issues in the comment, not just title :))

LGTM :)

Not sure how we want to go about merging docs changes with the docs work now, so waiting with that

**Comment by johanandren** [comment]
Thanks! We are in the progress of migrating our docs to a different tool (paradox) so I think we might want you to hold off a bit and then possibly, if you are up to it, do a new PR with this fix in the new docs. We expect to be done with migration to the new tool in a few weeks, we're sorry that it's so distruptive but it's the most efficient way we can migrate all content at once.

**Comment by Philippus** [comment]
Sure, I'm fine with that. Though if there is a new release before the new docs are completed there will still be a broken link right on the 'What is Akka?' introduction page.

**Comment by johanandren** [comment]
Good point, I'll just merge this and keep the ticket open.

**Pull request merged**
