### PR TITLE
fixed typos

### PR DESCRIPTION
**Pull request by owolabiezekiel**
Found some not so correct sentences when reading through the akka documentation, specifically the guide on "How the Actor Model Meets the Needs of Modern, Distributed Systems". I saw this as an opportunity to make my first open source contribution

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @owolabiezekiel,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Review by raboof — APPROVED** [review]
Great, thanks!

**Review by patriknw — APPROVED** [review]
LGTM, thanks

**Comment by owolabiezekiel** [comment]
> LGTM, thanks

How soon till this minor fix gets deployed? Just asking. I can't wait to show the world my little contribution to OSS.

**Pull request merged**
