### PR TITLE
Add API parameter comments to expectTerminated

### LINKED ISSUE #23091: Improve doc for TestKitBase.expectTerminated
`TestKitBase.expectTerminated` requires the actor to be watched. This is not made explicit in the API doc.

### PR DESCRIPTION
**Pull request by richardimaoka**
Fixes #23091 

Scaladoc has parameter description populated:

image

### CODE REVIEW

**Comment by raboof** [comment]
Nice improvement. For this to work you must have `watch`ed the actor first, perhaps it's a good idea to make that more explicit?

**Comment by richard-imaoka** [comment]
OK, added mentions to `watch`. Does it look better now?

**Review by raboof — APPROVED** [review]
Yes I think that is a useful addition!

**Review by ktoso — APPROVED** [review]
LGTM, better docs is always good  :)

**Pull request merged**
