### PR TITLE
Fix typos in contributing and testing docs #22883

### PR DESCRIPTION
**Pull request by iffyio**
I noticed a couple minor typos going through the guide on Testing Actor
Systems and the contributing guide and fixed them.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @iffyio,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
Issue https://github.com/akka/akka/issues/22883

**Comment by johanandren** [comment]
Thanks! We are in the progress of migrating our docs to a different tool (paradox) so I think we might want you to hold off a bit and then possibly, if you are up to it, do a new PR with this fix in the new docs. We expect to be done with migration to the new tool in a few weeks, we're sorry that it's so distruptive but it's the most efficient way we can migrate all content at once.

**Comment by iffyio** [comment]
all good, I'll do a new PR when the new docs are ready

**Pull request closed without merging**
