### PR TITLE
Move typed persistence tests away from LevelDB

### PR DESCRIPTION
**Pull request by johanandren**
To make test suite more stable (esp on CI) and faster. 

Moving the tests to akka-persistence-typed-tests as that is where we have the dependency on the testkit.

Includes a few improvements of the testkit:

* Bug with wrong emitted offset in testkit read journal fixed
* Convenient default params on testkit read journal
* Correct storage of adapter manifest in testkit journal

### CODE REVIEW

**Comment by johanandren** [comment]
PLS BUILD

**Review by patriknw — APPROVED** [review]
LGTM

**Review by octonato — APPROVED** [review]
LGTM

**Comment by octonato** [comment]
build failing with 

```scala
[error] /home/travis/build/akka/akka/akka-persistence-typed-tests/src/test/scala/akka/persistence/typed/scaladsl/EventSourcedBehaviorSpec.scala:50:25: Unused import
[error] import scala.annotation.nowarn
[error]                         ^
[error] one error found
```

**Pull request merged**
