### PR TITLE
Remove 'the' duplicates

### PR DESCRIPTION
**Pull request by naferx**

### CODE REVIEW

**Comment by ktoso** [comment]
Thanks! These are always a mystery to me how they keep happening...

**Comment by naferx** [comment]
Perhaps, they are resilient ;)

**Comment by patriknw** [comment]
yeah, I also did a sweep of those some week ago. Thanks!

**Comment by patriknw** [comment]
OK TO TEST

**Comment by patriknw** [comment]
LGTM

**Pull request merged**
