### PR TITLE
=act #16330 deprecating akka.util.Crypt

### PR DESCRIPTION
**Pull request by skrauchenia**
- Fix for #16330 
- Additionally clean several files up: final modifiers on objects and final class members, unused imports, iterators.nonEmpty instead of !iterators.isEmpty

### CODE REVIEW

**Comment by guidomedina** [comment]
Hi, I know this is an old issue but it is still unclear to me on how to emulate Akka remote association, say you have several clusters, how do you stop a node connecting to the wrong cluster? At the moment I'm using the cluster name and secured cookie for such purpose, if you name your cluster differently, will that stop a node connecting to another, say can `DevCluster@hostname_1` to `ProdCluster@hostname_2`, is there a way to stop that from happening?

**Comment by patriknw** [comment]
Yes, it will not be able to join if the actor system names are not the same. 

It is still possible to send messages with actor selection to the "wrong" system, if you write the name in such an address.

**Comment by guidomedina** [comment]
No problem, thanks for the quick response, since we build our jars using Maven profiles each profile has a cluster name and each cluster name is set via config to each module so there no hard code cluster name, good to know it doesn't connect if cluster name doesn't match, now hoping Akka 2.4 gets release soon since I'm noticing most of my cost is gone at Akka remote even using Kryo serialization and really really small Java classes for message exchanging but that's another subject not related to this issue.

**Comment by vijikarthi** [comment]
Trying to understand what's the story with respect to securing Akka endpoint given that secure-cookie is deprecated. I am not able to find details anywhere and appreciate any reference that I can lookup

**Comment by ktoso** [comment]
Use remoting with TLS.
Or tunel remoting over a secure connection (established via ssh).

**Comment by ktoso** [comment]
Please ask questions of such nature on the mailing list or gitter.im/akka/akka, the repo is for actual issues.

**Comment by vijikarthi** [comment]
Thanks @ktoso

**Pull request merged**
