### PR TITLE
+htc #17982 introduce ModeledCompanion.parseFromValueString, MediaType.parse, and ContentType.parse

### LINKED ISSUE #17982: Provide the ability to create a ContentType from a String
The `ContentType` companion object should provide a `parse` object, in a similar fashion to `MediaType`, to make it simple to create content types from Strings.

Consider a situation where you're integrating with a third party library, let's say some sort of file repository, and for each file, it includes a content type property as a String, and you want to serve these files using Akka HTTP.  Akka HTTP, as far as I can see, provides no means to create a `ContentType` from a String, you can create a `ContentType` from a `MediaType` and a `HttpCharset`, and both of these can be parsed from strings, but using that would first require parsing the value to extract both the media type and the charset out, if it exists.  The only way I can see to do this is via a round about method of mocking a header map, parsing it, then trying to get the content type header from that parsed map.

### PR DESCRIPTION
**Pull request by jrudolph**
Fixes #17982.

/cc @sirthias, @jroper

### CODE REVIEW

**Comment by jrudolph** [comment]
It would be nice if this could be released as well, this failed for Jenkins reasons I think.

**Comment by ktoso** [comment]
PLS BUILD

**Comment by 2m** [comment]
LGTM

**Comment by ktoso** [comment]
Very nice, LGTM

**Pull request merged**
