### PR TITLE
=rem remove unused code

### PR DESCRIPTION
**Pull request by KadekM**
Stumbled upon this and found it's unused, so probably safe to remove?

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Seems unused indeed, thanks for the look-out :-) 
LGTM

**Comment by KadekM** [comment]
I was porting spec to akka.net and saw it so even though it's another tiny thing, why not :-)
Build failed - I would assume it's unrelated to me?

**Comment by ktoso** [comment]
Failure was unrelated, we'll merge after one more LGTM :)

// Was https://github.com/akka/akka/issues/18235

**Comment by patriknw** [comment]
LGTM, thanks

**Comment by drewhk** [comment]
LGTM

**Pull request merged**
