### PR TITLE
=str #22703 GroupedWithin possible empty sequence upon completion fix

### PR DESCRIPTION
**Pull request by hochgi**

### CODE REVIEW

**Review by ktoso — COMMENTED** [review]
Could you please include a test that shows what didn't work and now does?

**Comment by ktoso** [comment]
Refs #22703

**Comment by ktoso** [comment]
OK TO TEST

**Comment by hochgi** [comment]
Seems like it has already been fixed in:
https://github.com/akka/akka/commit/ba213b7f

**Comment by ktoso** [comment]
Even better :) Thanks a lot for reporting and spending the time to PR in any case though!

**Pull request closed without merging**
