### PR TITLE
WIP #19049 DontLeakActorsOnFailingConnectionSpecs

### PR DESCRIPTION
**Pull request by johanandren**
Re-enabling to see if it still races.

### CODE REVIEW

**Comment by drewhk** [comment]
LGTM

**Comment by patriknw** [comment]
if you want to run it on repeat you can modify and enable https://jenkins.akka.io:8498/job/akka-multi-node-repeat/

**Comment by johanandren** [comment]
Ok will set on repeat, thanks @patriknw

**Comment by johanandren** [comment]
Has now run every three minutes since yesterday afternoon without failing. So I don't think it is unstable. It is however pretty slow, will take 15 seconds in the good case, do we really need to test for that long/with that many requests?

**Comment by patriknw** [comment]
ship it!

**Comment by johanandren** [comment]
:shipit:

**Comment by johanandren** [comment]
Refs #19049

**Pull request merged**
