### PR TITLE
Add Graal recommendation to contributing guide

### PR DESCRIPTION
**Pull request by chbatey**
FYI @helena if you haven't got this already

### CODE REVIEW

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by chbatey** [comment]
Good question. Is that a problem? It is the Scala compile that will be JITed with Graal. The bytecode will be the same.

**Comment by patriknw** [comment]
> The bytecode will be the same.

are we sure ™️ ?

**Comment by hepin1989** [comment]
@chbatey If Akka run its building and test with Graal will be better:)

**Comment by chbatey** [comment]
PLS BUILD

**Review by jrudolph — APPROVED** [review]
LGTM

**Pull request merged**
