### PR TITLE
 #19427 do not require Flow in UpgradeToWebsocket

### LINKED ISSUE #19427: do not require Flow in UpgradeToWebsocket API
should be sufficient to have a `Graph[FlowShape[_, _], _]`

### PR DESCRIPTION
**Pull request by rkuhn**
fixes #19427

### CODE REVIEW

**Comment by drewhk** [comment]
LGTM

**Comment by ktoso** [comment]
LGTM, thanks!

**Comment by rkuhn** [comment]
This probably shouldn’t have been merged: what about the PR validation failure? (pulling closed port)

**Comment by ktoso** [comment]
Does not seem related though, and opened ticket to track the failure here: https://github.com/akka/akka/issues/19503

**Pull request merged**
