### PR TITLE
=str #19481 Fix akka-bench

### PR DESCRIPTION
**Pull request by agolubev**
PR contains code changes to make jmh work. Also added return type according to comment: https://github.com/akka/akka/pull/19701/files#r53234159

PR #19701 also has this fix but as soon as it's performance related and quite complex - I'm not expecting it will be merged any day soon

### CODE REVIEW

**Comment by ktoso** [comment]
> PR #19701 also has this fix but as soon as it's performance related and quite complex - I'm not expecting it will be merged any day soon

Yeah, I agreed with that statement, lets merge the fix independently. Thanks a lot!

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Thanks, LGTM; let's get it in quickly :)

**Comment by agolubev** [comment]
Thanks.

**Pull request merged**
