### PR TITLE
!per #18360 Move Tagged to akka.persistence.journal

### PR DESCRIPTION
**Pull request by patriknw**
breaking api since 2.4.0-RC1, but only related to new things in 2.4 anyway

### CODE REVIEW

**Comment by patriknw** [comment]
Refs #18360

**Comment by patriknw** [comment]
Please review @ktoso 
cc @scullxbones

**Comment by ktoso** [comment]
Yup, excellent. LGTM

**Comment by scullxbones** [comment]
Great - thanks @patriknw !

**Pull request merged**
