### PR TITLE
PersistentFSMBase - matchEvent API bug fix

### PR DESCRIPTION
**Pull request by IanGrima**
Parameter "predicate" not being propagated to created builder.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @IanGrima,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by johanandren — APPROVED** [review]
Good catch. Thanks!

**Comment by johanandren** [comment]
OK TO TEST

**Comment by IanGrima** [comment]
I believe the test failures are unrelated to my trivial change? or am I wrong?

**Comment by IanGrima** [comment]
OK TO TEST

**Comment by IanGrima** [comment]
PLS BUILD

**Review by patriknw — APPROVED** [review]
LGTM

**Review by drewhk — APPROVED** [review]

**Comment by drewhk** [comment]
PLS BUILD

**Comment by patriknw** [comment]
Refs https://github.com/akka/akka/issues/22285

**Comment by patriknw** [comment]
Thanks @IanGrima

**Pull request merged**
