### PR TITLE
Minor grammar change that was incorrect on both the Scala and Java docs.

### PR DESCRIPTION
**Pull request by bdavisx**
I didn't create an issue for this since it wasn't a code change and was a pretty small change to the docs. I can create one if it's needed.

### CODE REVIEW

**Comment by ktoso** [comment]
No issue is fine for small typos, thanks a lot!

**Comment by johanandren** [comment]
OK TO TEST

**Review by johanandren — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
strange that cla validation is not active?

**Comment by patriknw** [comment]
Hi @bdavisx,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

http://www.lightbend.com/contribute/cla

**Comment by bdavisx** [comment]
I have signed the agreement.

**Comment by johanandren** [comment]
Thanks. There's something weird with the PR validator, but this is just a minor text change so it doesn't really matter. I'll merge this.

**Pull request merged**
