### PR TITLE
Fix broken url to "Better Bloom Filter" paper

### PR DESCRIPTION
**Pull request by andrelaszlo**
I noticed that this link was broken so I replaced it with a link to a copy provided by the other author

### CODE REVIEW

**Comment by patriknw** [comment]
OK TO TEST

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
Hi @andrelaszlo,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

http://www.lightbend.com/contribute/cla

**Comment by patriknw** [comment]
(don't know why cla validator didn't run automatically)

**Comment by andrelaszlo** [comment]
Tack @patriknw! I have signed the agreement.

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
