### PR TITLE
make RunnableGraph.addAttributes return a RunnableGraph #20630

### LINKED ISSUE #20630: RunnableGraph.addAttributes should return same type as RunnableGraph.withAttributes
The issue can be seen by looking at the API docs:

http://doc.akka.io/api/akka/2.4.6/?_ga=1.198496171.504920134.1442952792#akka.stream.scaladsl.RunnableGraph

### PR DESCRIPTION
**Pull request by timcharper**
closes #20630

### CODE REVIEW

**Comment by drewhk** [comment]
OK TO TEST

**Comment by drewhk** [comment]
Can this be an issue for other DSL types, like Source, Sink, or those all work?

**Comment by drewhk** [comment]
Also, the Java counterpart is OK?

**Comment by timcharper** [comment]
@drewhk neither the `withAttributes`, `addAttributes` or `named` override the return type in javadsl (so, they already differed).

**Comment by timcharper** [comment]
@drewhk the javadsl RunnableGraph api already differed from Scala in that none of the methods attempted to change the return type. I'll add another commit quickly to fix that also.

**Comment by timcharper** [comment]
Getting the javadsl RunnableGraph in shape is much more effort, primarily because an abstract class can't override the return type of a concrete method without providing an implementation.

https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala#L1928

Gitter discussion: [May 26, 2016 10:17 AM](https://gitter.im/akka/dev?at=5747219710f0fed86f487429)

**Comment by timcharper** [comment]
Sinks / Flows / Sources appear to have these methods implemented properly.

**Comment by johanandren** [comment]
PLS BUILD

**Comment by johanandren** [comment]
Failure is binary comp:

```
[info] akka-stream: found 2 potential binary incompatibilities while checking against com.typesafe.akka:akka-stream_2.11:2.4.2  (filtered 247)
[error]  * method named(java.lang.String)akka.stream.javadsl.RunnableGraph#RunnableGraphAdapter in class akka.stream.javadsl.RunnableGraph#RunnableGraphAdapter has a different result type in current version, where it is akka.stream.Graph rather than akka.stream.javadsl.RunnableGraph#RunnableGraphAdapter
[error]    filter with: ProblemFilters.exclude[IncompatibleResultTypeProblem]("akka.stream.javadsl.RunnableGraph#RunnableGraphAdapter.named")
[error]  * abstract method withAttributes(akka.stream.Attributes)akka.stream.javadsl.RunnableGraph in class akka.stream.javadsl.RunnableGraph is present only in current version
[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.stream.javadsl.RunnableGraph.withAttributes")
```

**Comment by ktoso** [comment]
Sorry this was delayed a bit, vacation mode has stuck us a bit.
Will add the MiMa filters, thanks for the contrib!

**Comment by johanandren** [comment]
Closing as I'm pushing it the last bit.

**Pull request closed without merging**
