### PR TITLE
=pro update Aeron to 1.0.4

### PR DESCRIPTION
**Pull request by ktoso**
No exact changelist was provided for this release though.
See tags: https://github.com/real-logic/Aeron/tags

### CODE REVIEW

**Comment by ktoso** [comment]
Release notes for that release coming soon, said Todd.
I skimmed the commits - mostly small fixes around a number of things, commits easy to skim here: https://github.com/real-logic/Aeron/commits/master

**Review by patriknw — APPROVED** [review]
LGTM

**Review by johanandren — APPROVED** [review]
LGTM but should we perhaps run the aeron cluster tests against it before merging, as an extra precaution?

**Comment by patriknw** [comment]
Let's merge and then kick off that cluster test job from master. That job seems failing pretty much all the time. What is going on there?

**Pull request merged**
