### PR TITLE
Use Future.successful/failed instead of Promise.s/f.future

### PR DESCRIPTION
**Pull request by evis**

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Review by ktoso — APPROVED** [review]
Looking good, LGTM.

**Comment by 2m** [comment]
Ooh. This touched some old tests. :) Most of the tests in `FutureSpec.scala` are now a part of scala tests that can be found in https://github.com/scala/scala/blob/2.13.x/test/files/jvm/future-spec/FutureTests.scala and https://github.com/scala/scala/blob/2.13.x/test/files/jvm/future-spec/PromiseTests.scala

It would be a good idea to remove these duplicated tests from Akka all together.

**Review by johanandren — APPROVED** [review]

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
@2m feel free to create another PR removing the old future tests

**Comment by ktoso** [comment]
I did a ticket for it just now https://github.com/akka/akka/issues/24095

**Pull request merged**
