### PR TITLE
Expose capacity property on StashBuffer

### PR DESCRIPTION
**Pull request by ioreskovic**
## Summary of changes
Just as `size` is available as a property on `StashBuffer`, I have ran into cases where I needed a capacity as well (mainly for logging/monitoring). Instead of passing stash construction parameter to places where it should not be passed, I believe a `capacity` property would be a better solution.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by ioreskovic** [comment]
> At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

Just did it, sorry.

**Comment by ioreskovic** [comment]
I'm assuming the failure is due to lack of binary compatibility with 2.6.x version; this is an API extension, and there is no such method on any of the 2.6.x versions.

Could someone confirm?

**Comment by raboof** [comment]
> I'm assuming the failure is due to lack of binary compatibility with 2.6.x version; this is an API extension, and there is no such method on any of the 2.6.x versions.
> Could someone confirm?

Yes indeed: MiMa is triggering because you're adding a method to a trait, because that would break any external codebases that implement that trait.

That is not a problem in this case because the trait is not meant to be extended by external users, and is marked as such with a `@DoNotInherit` - so you can add a mima filter as documented in CONTRIBUTING.md

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by ioreskovic** [comment]
> At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

Added an email

**Comment by ioreskovic** [comment]
I pushed the commits with the correct user.email this time :)

**Review by octonato — APPROVED** [review]
LGTM

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
