### PR TITLE
Use MessageBuffer in RecoveryPermitter, #28417

### PR DESCRIPTION
**Pull request by patriknw**
Backport of https://github.com/akka/akka/pull/28418

* to propagate trace context

(cherry picked from commit 44cac83d0fa9aabf722334adc396992dbbfd5750)

### CODE REVIEW

**Comment by patriknw** [comment]
Refs #28417

**Comment by patriknw** [comment]
PLS BUILD

**Comment by jrudolph** [comment]
PLS BUILD

**Comment by jrudolph** [comment]
(broken jenkins config at the time)

**Pull request merged**
