### PR TITLE
Execute tasks from Actors constructor on creation of BehaviorTestKit

### LINKED ISSUE #24703: [Akka Typed] Future does not get executed with BehaviorTestKit
Future does not get executed with BehaviorTestKit.

For Example:
```
import akka.actor.typed.Behavior
import akka.actor.typed.scaladsl.{ActorContext, Behaviors}
import akka.testkit.typed.scaladsl.BehaviorTestKit
import org.scalatest.FunSuite
import scala.concurrent.{ExecutionContext, Future}

class MutableRoundRobin[T](ctx: ActorContext[T]) extends Behaviors.MutableBehavior[T] {

  implicit val ec: ExecutionContext = ctx.system.executionContext

  Future {
    println("Inside Future in BehaviorTestKit")
  }
  println("Outside Future in BehaviorTestKit")

  override def onMessage(msg: T): Behavior[T] = {
    this
  }
}

class TestMe extends FunSuite {
  test("should display Inside and Outside Future printlns.") {
    val behTestKit = BehaviorTestKit(Behaviors.mutable[String](ctx ⇒ new MutableRoundRobin[String](ctx)))
    Thread.sleep(1000)
  }
}

```
This test does not print "Inside Future in BehaviorTestKit".

### PR DESCRIPTION
**Pull request by kpritam**
Fixes #24703

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
_for the record; I'm skeptical to trying to use the synchronous BehaviorTestKit for things that are asynchronous, you will hit the wall at some point_

**Comment by kpritam** [comment]
Yes @patriknw, we are using ActorTestkit for testing Asynchronous behavior.

We have some typed Actors which do some initialization actions in constructor and once initialization completes, they send self message saying I am Initialized. 
So when we used BehaviorTestkit, we were expecting Initialized message in the selfInbox.

**Review by johanandren — APPROVED** [review]
LGTM (with the same reservation as Patrik about whether it is a good idea ;) )

**Pull request merged**
