### PR TITLE
Remove obsolete OneToManyTestStage, #20288

### PR DESCRIPTION
**Pull request by danxmoran**
As per the comment [here](https://github.com/akka/akka/issues/20288#issuecomment-221469196), I'm deleting the `OneToManyTestStage` instead of porting it because in the new `GraphStage` way of doing things there's no unified supervision logic, so testing the supervision of the `OneToManyTestStage` wouldn't tell us anything useful about any "real" stages.

Refs #20288.

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
LGTM, as [discussed](https://github.com/akka/akka/issues/20288#issuecomment-221469196) class can be removed.

Thanks for the cleanup @danxmoran !

**Comment by danxmoran** [comment]
@ktoso closed instead of merged?

**Comment by ktoso** [comment]
Whoa thanks for noticing... Not my best self today due to painful dentist visit :(

**Comment by ktoso** [comment]
Definitely want this one merged!

**Pull request merged**
