### PR TITLE
Remove duplicated section in doc

### PR DESCRIPTION
**Pull request by vhiairrassary**
This section is duplicated later in the same file. For consistency with other files, I choose to keep the first reference.

### CODE REVIEW

**Comment by chbatey** [comment]
OK TO TEST

**Review by johanandren — APPROVED** [review]
LGTM. Thanks!

**Comment by johanandren** [comment]
Test failure is Jenkins instability, not related to this PR

**Review by patriknw — APPROVED** [review]
LGTM, thanks

**Pull request merged**
