### PR TITLE
=htp #19099 make sure headers are always written on `finish` in `GzipCompressor`

### LINKED ISSUE #19099: Http: `encodeResponse` directive produces corrupted gzip data on empty chunked response stream
Usage of `encodeResponse` directive with empty chunked response stream leads to corrupted gzip data, due to gzip header never being sent.

Corresponding PR in Spray: https://github.com/spray/spray/pull/1090

```scala
implicit val system = ActorSystem("http-streaming")
implicit val flowBuilder = ActorMaterializer()

val result = HttpEntity.Chunked.fromData(MediaTypes.`text/html`, Source.empty)
val route = encodeResponse & path("stream") & complete(result)

Http().bindAndHandle(route, "localhost", 8080)
```

```
$ http :8080/stream
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Type: text/html
Date: Sat, 05 Dec 2015 22:15:02 GMT
Server: akka-http/2.3.12
Transfer-Encoding: chunked


http: error: ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))
```

### PR DESCRIPTION
**Pull request by ataraxer**
Closes #19099

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by jrudolph** [comment]
Thanks for the PR, @ataraxer. Fix and test LGTM. We should also add a test to `CoderSpec` which has the additional benefit that all the encoders will be tested against similar kind of bugs.

**Comment by jrudolph** [comment]
I've seen you've added tests to spray in the equivalent of CoderSpec so maybe you could just copy them over.

**Comment by ataraxer** [comment]
@jrudolph unfortunately it turns out those particular tests aren't reliable in this particular case due to `ourGzip` explicitly calling `compress`. I'll modify them to call `finish` directly and carry over to this PR.

**Comment by ataraxer** [comment]
Aaaand done.

While working on tests I've also discovered that empty string encoding is broken because `compressAndFinish` calls `newTempBuffer` with size of an input as an argument, leading to empty buffer being created and deflator not being able to produce any output via it (imperative programming sucks :c ).

I've also noticed that there is no limit on buffer size whatsoever, which may lead to excessive memory footprint on compression of big entities, which would effectively double the amount of used memory used during compression.

**Comment by ataraxer** [comment]
Spray seems to be OK on those issues, since it uses fixed-size buffer.

**Comment by jrudolph** [comment]
> While working on tests I've also discovered that empty string encoding is broken because compressAndFinish calls newTempBuffer with size of an input as an argument, leading to empty buffer being created and deflator not being able to produce any output via it (imperative programming sucks :c ).

Ah, nice. I yesterday tried those test myself quickly and saw that something was wrong.

> I've also noticed that there is no limit on buffer size whatsoever, which may lead to excessive memory footprint on compression of big entities, effectively doubling the amount of memory used during compression.

Can you explain how this would happen? The Gzip and Deflate compressors both used the default value which isn't different from what you've specified here. The decompressors use a configurable maximum number of bytes which I think is a more flexible solution.

**Comment by ataraxer** [comment]
> Can you explain how this would happen? The Gzip and Deflate compressors both used the default value which isn't different from what you've specified here. The decompressors use a configurable maximum number of bytes which I think is a more flexible solution.

Indeed, my concern might have been a bit superficial: it only appears to be the case when `Encoder.encode` is invoked directly on `ByteString` (`encode => compressAndFinish => newTempBuffer(input.size)` leading to buffer size of up to `Int.MaxValue`) which only happens in tests as far as I can see. However it is still a public API so it might be a good idea to keep buffer size in check anyway.

**Comment by jrudolph** [comment]
> However it is still a public API so it might be a good idea to keep buffer size in check anyway.

Yes, but if we want to do it we should do it consistently in the same way as it is done for the decoding side. I'd say let's keep it the way it is and only introduce the lower bound for now to fix the bug.

Then we can create another ticket to figure out if and how we want to fix the upper bound issue on the encoding side. I agree it can be somewhat surprising but we could even document ourselves out of it by specifying that an encoding call may temporarily allocate additional memory in the size of the incoming buffer which is still a predictable solution (in contrast to the former solution on the decoding side which lead to the introduction of the buffer bound).

**Comment by ataraxer** [comment]
> Yes, but if we want to do it we should do it consistently in the same way as it is done for the decoding side. I'd say let's keep it the way it is and only introduce the lower bound for now to fix the bug. Then we can create another ticket to figure out if and how we want to fix the upper bound issue on the encoding side.

Sounds good to me.

**Comment by ataraxer** [comment]
Removed the upper bound and created a separate issue: #19119.

**Comment by ataraxer** [comment]
ping

**Comment by ktoso** [comment]
Thanks for the fix and the other ticket, @ataraxer.
LGTM so I'll merge right away then (last days was team meeting, so we we're not really online, thanks for your patience!)

**Comment by jrudolph** [comment]
Great, thanks @ataraxer.

**Comment by jrudolph** [comment]
Oops, this also targeted the wrong branch.

**Comment by ktoso** [comment]
Ouch nooo. I didn't notice..
Ill more it to the right one tomorrow, then.

**Comment by ktoso** [comment]
I'm doing the porting now.

**Comment by ataraxer** [comment]
> Oops, this also targeted the wrong branch.

Sorry, it is a bit unclear which branch should be used for akka-http/akka-streams PR's since they are not present in the master for some reason and ...well, there are a lot of branches out there :\

**Comment by ataraxer** [comment]
Also I would like to remind that original Spray issue is still open: https://github.com/spray/spray/pull/1090

**Comment by ktoso** [comment]
> Sorry, it is a bit unclear which branch should be used for akka-http/akka-streams PR's since they are not present in the master for some reason and ...well, there are a lot of branches out there :\

Hey, thanks for your contribs and sorry we didn't notice right away. 
The branches you care about are (at the moment I'm writing this):

- `release-2.3-dev` = akka streams and http
- `master` = akka 2.4 (currently)
- `release-2.3` = akka 2.3 maintanance

We'll soon merge streams into master, we'll let the community know about it

**Comment by ataraxer** [comment]
Thanks for the clarifications! (:

**Pull request merged**
