### PR TITLE
Remove duplicated 'to be's. issue #23646

### PR DESCRIPTION
**Pull request by kun-song**

### CODE REVIEW

**Review by raboof — APPROVED** [review]

**Comment by raboof** [comment]
OK TO TEST

**Comment by raboof** [comment]
Thanks for noticing!

**Review by ktoso — COMMENTED** [review]
LGTM, thanks :)

**Comment by ktoso** [comment]
Please refer to the issue being solved in comments like this:
Resolves #23646 
:)

**Comment by satansk** [comment]
Thanks @ktoso, Get it :)

**Pull request merged**
