### PR TITLE
Fix README scladex badge

### PR DESCRIPTION
**Pull request by sideeffffect**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @sideeffffect,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
Thanks a lot, seems good -- we do need to ask you to sign the CLA before we can merge though, thanks in advance :)

**Review by ktoso — APPROVED** [review]

**Comment by raboof** [comment]
OK TO TEST

**Comment by sideeffffect** [comment]
signed cla

**Review by raboof — APPROVED** [review]
Seemed to work without this change as well, but still nice simplification!

**Comment by raboof** [comment]
Thanks!

**Pull request merged**
