### PR TITLE
doc: fix Broadcast Stream operator async usage

### PR DESCRIPTION
**Pull request by phiSgr**
References #28091 #28583

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @phiSgr,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by patriknw — COMMENTED** [review]
Thanks for fixing. Before we close the issue I would like that the Akka team investigates why the original doesn't work as expected (at least my expectations) and if we can do something about it.

**Comment by phiSgr** [comment]
Any idea if this will get merged and if the fix is still valid (I guess it is)?

**Comment by johanandren** [comment]
Hi @phiSgr, sorry, this one seems to have slipped between the cracks, I'll take a look

**Review by johanandren — APPROVED** [review]
LGTM, somewhat annoying that it isn't possible to say `broadcast.out(0) ~> countS.async`, which would have felt more clear, but `countS` is not a graph in the builder but a shape.

As mentioned elsewhere `Flow[Int].async` means an async boundary around the stream graph built up to that point, which is only `Flow.identity`, not very useful to have in its own stream interpreter/actor and I think it may even be optimized away completely during materialization.

**Comment by phiSgr** [comment]
pinging again for another approval😅

**Review by raboof — APPROVED** [review]

**Pull request merged**
