### PR TITLE
=htc #19418 avoid LUB problem in javadsl.model.ContentType, see SI-9621

### PR DESCRIPTION
**Pull request by ktoso**
Resolves https://github.com/akka/akka/issues/19418

### CODE REVIEW

**Comment by rkuhn** [comment]
do we have tests on the Java side that cover this?

**Comment by rkuhn** [comment]
LGTM

**Comment by johanandren** [comment]
LGTM

**Comment by ktoso** [comment]
Now also with test that we can touch them from java

**Pull request merged**
