### PR TITLE
Correct typo in 'Source.from()' function documentation

### PR DESCRIPTION
**Pull request by dorin-cbz**
Change-Id: I85f4c6fe5004f24d7b47c7bed15e6c39861b5250

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Comment by johanandren** [comment]
LGTM

**Comment by johanandren** [comment]
LGTM, but please change commit message according to description in the contributions docs, thanks. (https://github.com/akka/akka/blob/master/CONTRIBUTING.md#creating-commits-and-writing-commit-messages)

**Comment by dorin-cbz** [comment]
@johanandren Done

**Pull request merged**
