### PR TITLE
=doc updating doc references to deferAsync

### PR DESCRIPTION
**Pull request by chbatey**

### CODE REVIEW

**Comment by ktoso** [comment]
Good catch - thanks a lot, Chris! Very cool to see you dig around persistence. :-)

Two small things and we'll merge:
- We have this part of the docs duplicated to `akka-docs/rst/java/persistence.rst` and `akka-docs/rst/java/lambda-persistence.rst`, would you mind applying the same fixup there and squash all these changes into one commit?
- please make the commit message start with `=doc update references to deferAsync` (see [contributing.md](https://github.com/akka/akka/blob/master/CONTRIBUTING.md))

**Comment by chbatey** [comment]
Found my way here from the cassandra plugin. Kudos for docs in version control! 

Updated.

**Comment by ktoso** [comment]
Thanks for the update and kudos :-)
One more file: `akka-docs/rst/java/lambda-persistence.rst`, then we merge :-)

**Comment by ktoso** [comment]
Btw I saw your discussion in the cassandra plugin repo (that there is one), will catch up on it today I hope.

**Comment by patriknw** [comment]
LGTM, after lambda-persistence.rst

**Comment by chbatey** [comment]
Oops, added lamda-persistence.rst

**Comment by ktoso** [comment]
Awesome, thanks :-)

**Pull request merged**
