### PR TITLE
Fix #16791: calculate scala.* import range with numerical addition instead of string concatenation

### LINKED ISSUE #16791: Scala.* package imports in OSGi have an improper version range
Since release 2.3.7 the OSGi manifest imports too large a version range for `scala.*` packages.

**scala.* imports for akka-actor_2.10-2.3.6**
```
Import-Package: scala.collection.convert;version="[2.10,2.11)"
Import-Package: scala.collection.generic;version="[2.10,2.11)"
Import-Package: scala.collection.immutable;version="[2.10,2.11)"
Import-Package: scala.collection.mutable;version="[2.10,2.11)"
Import-Package: scala.collection.parallel.immutable;version="[2.10,2.11)"
Import-Package: scala.collection.parallel;version="[2.10,2.11)"
Import-Package: scala.collection;version="[2.10,2.11)"
Import-Package: scala.concurrent.duration;version="[2.10,2.11)"
Import-Package: scala.concurrent.forkjoin;version="[2.10,2.11)"
Import-Package: scala.concurrent.util;version="[2.10,2.11)"
Import-Package: scala.concurrent;version="[2.10,2.11)"
Import-Package: scala.math;version="[2.10,2.11)"
Import-Package: scala.reflect;version="[2.10,2.11)"
Import-Package: scala.runtime;version="[2.10,2.11)"
Import-Package: scala.sys;version="[2.10,2.11)"
Import-Package: scala.util.control;version="[2.10,2.11)"
Import-Package: scala.util.hashing;version="[2.10,2.11)"
Import-Package: scala.util.matching;version="[2.10,2.11)"
Import-Package: scala.util;version="[2.10,2.11)"
Import-Package: scala;version="[2.10,2.11)"
```

**scala.* imports for akka-actor_2.10-2.3.7**
```
Import-Package: scala.collection.convert;version="[2.10,2.101)"
Import-Package: scala.collection.generic;version="[2.10,2.101)"
Import-Package: scala.collection.immutable;version="[2.10,2.101)"
Import-Package: scala.collection.mutable;version="[2.10,2.101)"
Import-Package: scala.collection.parallel.immutable;version="[2.10,2.101)"
Import-Package: scala.collection.parallel;version="[2.10,2.101)"
Import-Package: scala.collection;version="[2.10,2.101)"
Import-Package: scala.concurrent.duration;version="[2.10,2.101)"
Import-Package: scala.concurrent.forkjoin;version="[2.10,2.101)"
Import-Package: scala.concurrent.util;version="[2.10,2.101)"
Import-Package: scala.concurrent;version="[2.10,2.101)"
Import-Package: scala.math;version="[2.10,2.101)"
Import-Package: scala.reflect;version="[2.10,2.101)"
Import-Package: scala.runtime;version="[2.10,2.101)"
Import-Package: scala.sys;version="[2.10,2.101)"
Import-Package: scala.util.control;version="[2.10,2.101)"
Import-Package: scala.util.hashing;version="[2.10,2.101)"
Import-Package: scala.util.matching;version="[2.10,2.101)"
Import-Package: scala.util;version="[2.10,2.101)"
Import-Package: scala;version="[2.10,2.101)"
```

This causes Akka 2.10 to resolve Scala 2.11 classes when both Scala 2.10 and 2.11 are in use.

There is a similar problem for akka-actor_2.11-2.3.7+ where the version range is `[2.11,2.111)`, which would experience the same issue if run in an environment with Scala 2.12+ (whenever that exists).

Since Akka 2.10 imports to 2.101 and 2.11 imports to 2.111, I suspected a string concatenation instead of numerical addition. So far I have traced the cause to [here](https://github.com/akka/akka/blob/master/project/OSGi.scala#L62), which does indeed do concatenation instead of addition.

```
val ScalaVersion = """(\d+)\.(\d+)\..*""".r
val ScalaVersion(epoch, major) = version
versionedImport(packageName, s"$epoch.$major", s"$epoch.${major+1}")`
```

This code was introduced on 2014-11-30 in [this pull request](https://github.com/akka/akka/pull/16371/files#diff-f862909d2853386601985172466fd7f6L9). Prior to that, the epoch and major version were converted to integers with `toInt`.

I expect the trivial change below will set the import range correctly, through I've not yet tried to build the artifacts with the change to verify.

```
versionedImport(packageName, s"$epoch.$major", s"$epoch.${major.toInt+1}")
```

### PR DESCRIPTION
**Pull request by jgulotta**
Fixes #16791

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @jgulotta,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by bantonsson** [comment]
OK TO TEST

**Comment by bantonsson** [comment]
@jgulotta could you please apply the same commit comment change as described in #16863

**Comment by jgulotta** [comment]
@bantonsson Done!

**Comment by bantonsson** [comment]
LGTM

**Comment by ktoso** [comment]
LGTM, thanks!

**Comment by patriknw** [comment]
LGTM, thanks for fixing

**Pull request merged**
