### PR TITLE
FINAL: Svozniuk wip stream ref timeout #24934

### PR DESCRIPTION
**Pull request by ktoso**
Follows up on https://github.com/akka/akka/pull/24948 by fixing attribution and some review followups and cleanup.

Thanks a lot @svozniuk! And sorry we ended up going so roundabout with merging these :-)

### CODE REVIEW

**Comment by ktoso** [comment]
This was reviewed before, merge once passes validation

**Comment by ktoso** [comment]
Resolves #24934

**Comment by ktoso** [comment]
Sorry, seems I missed one commit during rebase, squashed them.

**Comment by svozniuk** [comment]
> Thanks a lot @svozniuk! And sorry we ended up going so roundabout with merging these :-)
Happy to help @ktoso . It was an interesting issue to debug and it was interesting to take a look at the internals. And no worries about the procedure. Unfortunately I only can dedicate some time to this in the morning and in the evening, so I wasn't reactive enough

**Comment by ktoso** [comment]
Failure was unrelated https://github.com/akka/akka/issues/24979

**Comment by ktoso** [comment]
Okey, will merge only once passes then

**Pull request merged**
