### PR TITLE
Full word.

### PR DESCRIPTION
**Pull request by jiminhsieh**
* origin 
	* up- and downstreams
* current 
	* upstreams and downstreams

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]
I'm not sure I'd say the word is missing per se (AFAIK this is a valid way to make text shorter), but spelling it out completely indeed seems like an improvement.

**Comment by jiminhsieh** [comment]
@raboof I got it. I would try to change git log.

**Comment by raboof** [comment]
Perhaps nitpicking, but since we're now spelling those out, 'upstream and downstream' (singular) might be even more clear? Or (full bikeshed mode) "which connects its upstream to its downstream by processing the data elements flowing through it".

**Comment by ktoso** [comment]
That's fine rewording now, thanks.

**Pull request merged**
