### PR TITLE
Issue 24594: Integration with sbt-headers and initial header population.

### PR DESCRIPTION
**Pull request by kelebra**
This is continuation of [previous PR](https://github.com/akka/akka/pull/24594). I actually reset my branch and PR got closed, sorry for mess. Nevertheless I addressed comments (or explained showstoppers) and this PR is for reference in case you would like to proceed with merging.

Happy weekend :beers:

### CODE REVIEW

**Comment by jrudolph** [comment]
OK TO TEST

**Review by jrudolph — APPROVED** [review]
LGTM

I verified all changes with

```
git diff --word-diff=color --ignore-blank-lines -w 1574faf18076c6b5e5383e8692b03338a2ef7bb1..refs/pull/24652
```

locally because Github has problems showing such big PRs.

**Comment by ktoso** [comment]
Hehe yeah, GH dies on those...
So the dual license things are also fine?

If yes, please merge :)

**Comment by jrudolph** [comment]
Currently it fails the header check: https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11972/console

Should we enable the header check by default?

**Comment by kelebra** [comment]
Ok, now build fails because of absence of headers explicitly:

```scala
[error] java.lang.RuntimeException: There are files without headers!
[error]   /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-stream/src/main/scala/akka/stream/impl/FanoutProcessor.scala
```

**Comment by kelebra** [comment]
Looks like all tests and checks passed but build failed for another reason :worried:

**Comment by kelebra** [comment]
After merging with master newly introduced test `akka.stream.tck.EmptyProcessorTest` does not pass both on CI and locally ([commit](https://github.com/akka/akka/commit/d55990fa64589dc7f74bccd293fb5ee2c4034f8c)). 

Could anyone please have a look at it?

**Comment by kelebra** [comment]
Guys, it is getting quite repetitive to keep this PR up-to-date with master. Please let me know if you are going to merge this or I should leave it as is till better times.

**Comment by ktoso** [comment]
I suppose there is no real "good time" to merge this, there's always things in flight -- I'll rebase and merge. Thanks for your help!

**Comment by ktoso** [comment]
Refs #24594

**Pull request closed without merging**
