### PR TITLE
akka-stream: Add a PartitionEither implementation

### PR DESCRIPTION
**Pull request by longshorej**
This adds a `PartitionEither` implementation, splitting the inlet's `Either[A, B]` into two outlets, `A` and `B`.

`out0` receives all `Left` inner values.
`out1` receives all `Right` inner values.

If y'all accept, does this need doc somewhere?

### CODE REVIEW

**Comment by hepin1989** [comment]
I think this can be done with a GraphDSL

**Comment by hepin1989** [comment]
@longshorej Can you share some of your use case thanks~~

**Comment by hepin1989** [comment]
Cool ,and open an issue to track it ？

**Comment by longshorej** [comment]
> Cool ,and open an issue to track it ？

Done - https://github.com/akka/akka/issues/31375

**Comment by longshorej** [comment]
I've added tests  (based off `Partition`) and the JavaDSL.

**Review by johanandren — COMMENTED** [review]
I'm on the fence whether this is useful enough to be added to the library set of operators. On one hand it seems useful and Either is a part of the stdlib but on the other hand I haven't heard any requests of it before (so maybe having your own impl or composed version if you need it is good enough)

If we do decide to add it though, I think we should have something in the flow DSL for it, somewhat like the `alsoTo` where you can pass a sink for the uncommon case (I don't remember for the moment if either leans towards right or left), and return a Source of the unwrapped common case.

**Comment by longshorej** [comment]
Thanks for the feedback @johanandren. I did find a small amount of implicit interest by googling around for solutions to consuming `Either`s that people came up with, which indicates at least some small amount of interest:

https://gist.github.com/klpx/6b9b9e3a88ecbd1452da095223306505
https://gist.github.com/ecyshor/322ec57515d1367df25b6ca7deee9574

...but I also understand that it may not hold its weight w.r.t. maintenance etc. Whatever y'all decide is fine with me.

> If we do decide to add it though, I think we should have something in the flow DSL for it, somewhat like the alsoTo where you can pass a sink for the uncommon case (I don't remember for the moment if either leans towards right or left), and return a Source of the unwrapped common case.

It's right-biased -- and I'd be happy to explore this, although I'm not sure how it would work. `FlowOps` has an out type of `Out`, and this proposed method should only be available when `Out` is `Either[A, B]`.

I could see adding some enrichment-style implicit class to achieve this, but don't see any precedence in codebase for that and am not sure the ergonomics would be good. Seems like we need some evidence parameter to prove that `Out` is a subtype of `Either[A, B]`? Or is there some simpler way I'm not thinking of? Any suggestions or advice? Thank you.

My initial, likely hare-brained, idea is something like this in scaladsl package:

```scala
  implicit class EitherFlowOps[+A, +B, +Out <: Either[A, B], +Mat, F <: FlowOps[Out, Mat]](val f: F) extends AnyVal {
    /** Extract primary (Right) values from this Either, sending the others (left) to the provided sink  */
    def values(others: Sink[A, _]): F#Repr[B] = ???  // @TODO wire up call to PartitionEither
  }
```

**Comment by johanandren** [comment]
Let's get some consensus on the operator to start with, before we dig into a nice operator factory shortcut. 

I'm somewhat thawing to the idea with a built in `Either` partition, given that `Either` _is_ in the Scala stdlib, wdyt @raboof @patriknw ?

**Comment by leviramsey** [comment]
I know at a `$PREVIOUS_EMPLOYER` we implemented similar functionality, so there's definitely some demand.  At minimum maybe this goes into `akka-stream-contrib`?

I do wonder if there needs to be a `javadsl` for this, given that it seems unlikely that a Java dev would encounter a `scala.util.Either`?  We don't tend to expose `Option` or `Try` or `scala.concurrent.Future` in the Java APIs (though there there's at least a generally-accepted Java equivalent for each).

**Comment by patriknw** [comment]
Would it be possible to make `partition` more powerful/convenient to use for this case? Maybe some `partitionTwo`? I'm thinking that `Either` is just one class of many possible things that can be used for routing elements to one or the other. For example, one may have an application specific AST with sealed trait and two implementations or a class with some discriminator (enum) field. Yeah, one  could map to Either first, but Either is not useful for javadsl.

**Comment by longshorej** [comment]
`partitionTwo` makes sense, let me explore that a bit.

**Comment by patriknw** [comment]
@longshorej do you have the possibility to complete this?

**Comment by longshorej** [comment]
I'd still like to explore but it'll be a while (6w newborn 👶 ) - should we close, or can we let it sit?

**Comment by johanandren** [comment]
Congrats @longshorej !

Let's close it for now and re-open/revisit in the future.

**Pull request closed without merging**
