### PR TITLE
Move DnsSpec to multi-jvm test, #22330 (for validation)

### PR DESCRIPTION
**Pull request by patriknw**
* run in spepaate jvm to avoid issues with parallel test execution
  when modifying global System.properties

Refs #22330

### CODE REVIEW

**Comment by patriknw** [comment]
Follow up to https://github.com/akka/akka/pull/22336

**Review by johanandren — APPROVED** [review]
LGTM

**Review by drewhk — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
PLS BUILD

**Pull request merged**
