### PR TITLE
fix #23416 instantiate exceptions at right time

### LINKED ISSUE #23416: Invalid stack trace because reused exception code is defined as val
Both `OutputStreamSourceStage` (and `InputStreamSinkStage`) build an IOException and store it as val. This causes the stack trace to be populated at val instantiation time instead of the place where it is thrown. This in turn yields strange stack traces originating at the wrong location.

My guess is that this is not on purpose and should have been defined as a `def` instead of a `val`
(you might want to search the code for more of these)

https://github.com/akka/akka/blob/87b28d0dc53d236168b00dab0f443886f0f11853/akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala#L164

```scala
 val publisherClosedException = new IOException("Reactive stream is terminated, no writes are possible")

  @scala.throws(classOf[IOException])
  private[this] def send(sendAction: () ⇒ Unit): Unit = {
    if (isActive) {
      if (isPublisherAlive) sendAction()
      else throw publisherClosedException
    } else throw new IOException("OutputStream is closed")
  }
```

the same is done here: https://github.com/akka/akka/blob/87b28d0dc53d236168b00dab0f443886f0f11853/akka-stream/src/main/scala/akka/stream/impl/io/InputStreamSinkStage.scala#L117

### PR DESCRIPTION
**Pull request by francisdb**
fix #23416 instantiate exceptions at right time

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by francisdb** [comment]
I'm having this being thrown and am trying to debug what is going on, since the cause might be in the implementation of the reading/writing done by a different lib the stack trace would be more than welcome. Currently the trace points to the location where .run() is called which is very confusing.

```
java.io.IOException: Reactive stream is terminated, no writes are possible
	at akka.stream.impl.io.OutputStreamAdapter.<init>(OutputStreamSourceStage.scala:164)
	at akka.stream.impl.io.OutputStreamSourceStage.createLogicAndMaterializedValue(OutputStreamSourceStage.scala:151)
	at akka.stream.impl.GraphStageIsland.materializeAtomic(PhasedFusingActorMaterializer.scala:627)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:458)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:420)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:415)
	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:439)
	at my.project.ImportExport$.readZip(ImportExport.scala:66)
...
```

where the line in my code is this

```scala
val is = source.toMat(StreamConverters.asInputStream(5.seconds))(Keep.right).run()
...
```

The error is probably caused by the library I am using thar writes to the stream and closes/flushes multiple times.

**Review by johanandren — APPROVED** [review]
I don't think the stack trace will be useful, but I also think caching the exception was a premature optimisation, so LGTM

**Comment by francisdb** [comment]
added some more proof of the usefulness of this patch in the ticket:
https://github.com/akka/akka/issues/23416#issuecomment-318079977

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
