### PR TITLE
Separate sharding regions and proxies, #23472

### PR DESCRIPTION
**Pull request by patriknw**
Pushing https://github.com/akka/akka/pull/23552 over the finish line. Reverted some of the too verbose formatting changes that were introduced there. Already reviewed, so can be merged after validation.

Refs #23472

### CODE REVIEW

**Comment by sergiy0** [comment]
@patriknw did you run the multi-node-tests for this change? 
The documentation for `ClusterSharding.shardRegion` ("The entity type must be registered with the [[#start]] or [[#startProxy]] method before it can be used here.") and  `ClusterSharding.shardRegionProxy` ("A proxy within the same data center can be accessed with [[#shardRegion]] instead of this method.") now is wrong and some of multi-node tests are failing because `ClusterSharding.shardRegion` doesn't return local proxies for the sharding type.

**Comment by patriknw** [comment]
Thanks for reporting. Is that perhaps what is fixed in https://github.com/akka/akka/pull/23995 ?

**Comment by sergiy0** [comment]
Yes, it looks so, but the scaladoc  for `ClusterSharding.shardRegion` and `ClusterSharding.shardRegionProxy` also should be updated.

**Comment by patriknw** [comment]
please update docs in your PR

**Comment by sergiy0** [comment]
As #23995 returns the previous semantic of these 2 methods, the docs are ok. Sorry for partially misleading comment.

**Comment by patriknw** [comment]
ok, that was my thinking but I thought I missed something :)

**Pull request merged**
