### PR TITLE
#19441 convert from Option to Optional in javadsl

### LINKED ISSUE #19441: convert from Scala Option to Optional in javadsl packages
using scala-java8-compat library

### PR DESCRIPTION
**Pull request by 2m**
Was looking for `Option` in:

```
akka-http-core/src/main/scala/akka/http/javadsl
akka-http-core/src/main/java/akka/http/javadsl
akka-http/src/main/scala/akka/http/javadsl
akka-stream/src/main/scala/akka/stream/javadsl
```

Fixes #19441

### CODE REVIEW

**Comment by drewhk** [comment]
So these were missed because these werent using japi.Option in the first place...

**Comment by drewhk** [comment]
Can you please remove the `scala.Option` imports where possible? Not a biggie but better not mix too much language dependent stuff. Otherwise LGTM.

**Comment by 2m** [comment]
Ok. I found one instance of `scala.Option` import in one of the java tests and removed it.

**Comment by johanandren** [comment]
Closing as I rebased and took this over in #19604

**Pull request closed without merging**
