### PR TITLE
!htc #16972 harmonize naming - bindAndHandle...

### PR DESCRIPTION
**Pull request by ktoso**
Harmonizes naming of `bindAnd...` with StreamTcp, discussed here: https://github.com/akka/akka/issues/16972

### CODE REVIEW

**Comment by rkuhn** [comment]
LGTM

**Comment by bantonsson** [comment]
LGTM

**Comment by patriknw** [comment]
LGTM

**Comment by drewhk** [comment]
LGTM

**Comment by ktoso** [comment]
Shall I merge or revalidate? Don't think anyone touched those classes in the recent days right?

**Comment by drewhk** [comment]
I don't think they were touched

**Comment by ktoso** [comment]
Thanks, merged.

**Pull request merged**
