### PR TITLE
Add streams recipe for 'source from function' (#22074)

### LINKED ISSUE #22074: Source.fromFunction / Source.continually - shortcut to eval a function for every emit
Not sure if this has been asked already. I find it very common to construct a Source along the lines of `Source.repeat`, but with the need of evaluating a function and producing a new element every time the source emits.

I usually end up writing `Source.cycle(() => Iterator(Random.nextInt()))` . I'm writing here to check if anyone might deem useful to have a shortcut in `Source.scala` - with a meaningful name (e.g. `Source.fromFunction`, or `Source.continually`).

### PR DESCRIPTION
**Pull request by catalin-ursachi**
Fixes #22074

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Review by johanandren — COMMENTED** [review]
The sample code is not thread safe (as it mutates state). Even if that is not in the code that is pulled in, please make it stateless. And note in the section of the docs that it should not touch mutable state and recommend another tool for that (`Source.unfold` or `Source.unfoldResource`) .

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
Thanks @catalin-ursachi

**Pull request merged**
