### PR TITLE
Replace labels on the image: should be flatMapMerge, but was flatFlattenMerge #28040

### PR DESCRIPTION
**Pull request by Captain1653**
References #28040

I'm not an expert in graphics, but it can be something like that :) .

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @Captain1653,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Lightbend Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by Captain1653** [comment]
I signed CLA. Please, run typesafe-cla-validator again :) 
Screenshot 2023-09-05 at 10 32 56

**Comment by johanandren** [comment]
Manually verified CLA 👍

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
