### PR TITLE
Log sent/receive message log level check

### PR DESCRIPTION
**Pull request by chbatey**
Only evaluates toString of payload if debug logging is enabled

Refs #24774

### CODE REVIEW

**Review by patriknw — APPROVED** [review]
LGTM
No problem with LogSend and no prob in Artery?

**Comment by chbatey** [comment]
Artery does the check but i'll make the test run with both

**Comment by chbatey** [comment]
@patriknw Artery only logs the class name so wouldn't suffer from this. We should make this consistent.

 As you clock the most hours looking at remoting logs I think you should decide if we want big and maybe useful or concise but less useful :)

**Comment by chbatey** [comment]
Updated artery to log the full message and made the test run with both transports

**Review by johanandren — APPROVED** [review]
LGTM

**Pull request merged**
