### PR TITLE
fix reliable delivery doc example #31026

### PR DESCRIPTION
**Pull request by Roiocam**
References #31026

This commit is used to fix the documentation issue found in #31026

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @Roiocam,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Comment by johanandren** [comment]
Closing and reopening to see if I can trigger CI PR validation which didn't happen for some reason.

**Review by raboof — APPROVED** [review]
Good catch, thanks!

**Pull request merged**
