### PR TITLE
Use dilated timeout in enterBarrier

### PR DESCRIPTION
**Pull request by octonato**
The current `enterBarrier` method uses a timeout that is not dilated. That's ok when using inside a `within` block in which case it will use the remaining dilated timeout from `within`. 

The problem becomes more apparent when using a mix of tests methods with and without using `within` method. Since `enterBarrier` is cross node, it can be impacted by tests pending completion on another node.

For instance: 

```scala

// config ->  akka.test.timefactor = 3

"My Tests" must {

    "test1" in within(20.seconds) { // effectively 60.5
		enterBarrier("test 1") // 30s, but actually remaning of 60.5
		// run some long tests
    }

	"test2" in  {
		enterBarrier("test 2") // 30s
    }
}
```

We can have node1 finishing "test1" quickly, moving to test2 and waiting at the barrier. 

Node2 for some reason takes time to complete "test1" and its timeout is dialted to 60 (actually 60.5, assuming `akka.test.timefactor = 3`). 

The `enterBarrier` call in node1 will fail after 30s (default, not dilated). 

That makes it harder to reason about because:

1. dilation time factor is global and defined by config
1. barrier timeout can only be defined via config
2. users can programmaticaly define timeouts, but not always
2. `enterBarrier` is cross test barrier and can be impacted by tests on other nodes

If we make the timeout inside `enterBarrier` to be dilated we will the following instead:

```scala 
"My Tests" must {

    "test1" in within(20.seconds) { // effectively 60.5
		enterBarrier("test 1") // 90.5s, but actually remaning of 60.5
		// run some long tests
    }

	"test2" in  {
		enterBarrier("test 2") // 90.5s
    }
}
```

Additionally, it won't hurt to extend `enterBarrier` and have

```scala

def enterBarrier(max: FiniteDuration, name: String*): Unit = {
  import akka.testkit._
  testConductor.enter(
   Timeout.durationToTimeout(remainingOr(max.dilated)),
    name.to(immutable.Seq))
  )
}
```

Not included (yet) on this PR though.

### CODE REVIEW

**Review by helena — APPROVED** [review]
👍 I don't see a problem with doing this but I may be missing something. It could be that we don't want to do this across the board but keep it controllable.

**Comment by helena** [comment]
@renatocaval needs a `scalafmtCheck`

**Comment by renatocaval** [comment]
> I don't see a problem with doing this but I may be missing something. It could be that we don't want to do this across the board but keep it controllable. 

I've been thinking about it. I'm not comfortable (anymore) with the idea of dilating the timeout on behalf of the users anymore. Maybe we should just go for an overloaded method that accepts a timeout and we document that the timeout will be dilated using the value of `akka.test.timefactor` and we leave the current method as is. 

This is similar to the `within` method. It's documented that `max` will be dilated.

**Comment by helena** [comment]
I agree, I'm not comfortable having it not user controlled.

**Comment by renatocaval** [comment]
@helena, I did a forced push on the branch. 

Remove the previous code and added an overloaded `enterBarrier` with an explicit timeout that is dilated behind the scenes (like in `within`).

**Comment by johanandren** [comment]
I think having the possibility to specify explicit timeout sounds useful, but I think I'd prefer the user just use `enterBarrier("yadi", 20.seconds.dilated)` for that case rather than magically dilating.

**Comment by helena** [comment]
@johanandren I agree, so perhaps instead we need an example for the testing docs on what options are available to accomplish this with `enterBarrier`. I'm not seeing anything for users other than what we have in scaladoc.

**Comment by johanandren** [comment]
Or just mention in the scaladoc that it can/often makes sense to dilate the timeout?

**Comment by patriknw** [comment]
I don't mind adding this. Strangely I have never had the need for it although I have written many many multi-jvm tests over the years. In above example there is one difference to how I always use them. I always end each test method with a separate barrier, so that the tests don't continue to next test method before all nodes have completed previous test method. Also, I never use barriers for checking time related things. For that I always use other assertions, such as expectMessage.

**Comment by renatocaval** [comment]
I agree that is better to not dilate is behind the scenes, but other parts of the API is doing that, so isn't that better to keep it aligned? 

I'm fine to change it, just let me know what the team prefers.

**Comment by patriknw** [comment]
I think it can be automatically dilated. Given that within and most other timeouts are dilated that is probably the best choice.

**Comment by renatocaval** [comment]
@patriknw, in that case, is there anything else we should do here? 

I think this is ready for last review.

**Review by johanandren — APPROVED** [review]
LGTM then

**Comment by patriknw** [comment]
thanks

**Pull request merged**
