### PR TITLE
fix: clear inflight DNS requests on failure to allow retries

### PR DESCRIPTION
**Pull request by leviramsey**
While looking over #32109, I noticed that in a situation where a DNS request times out, the `inflightRequests` dedupe buffer isn't cleared, which would cause retries to be attached to a resolve that never comes.  This would manifest in the behavior reported in the issue (pending confirmatory logs that the DNS request timed out or disconfirmation from @nodefactory-bk that the `resolve-timeout` in use was longer than 5 seconds).

### CODE REVIEW

**Comment by leviramsey** [comment]
Test failure appears to be flaky test https://github.com/akka/akka/pull/32104/files#r1330825019

**Comment by leviramsey** [comment]
Will need to rebase on #32111

**Review by patriknw — APPROVED** [review]
LGTM, this will probably deserve a backport to a patch 2.8.5 release

**Comment by patriknw** [comment]
Refs https://github.com/akka/akka/issues/32109

**Comment by nodefactory-bk** [comment]
I strongly concur that this should be backported to 2.8.5 asap.

**Review by johanandren — APPROVED** [review]
LGTM

**Pull request merged**
