### PR TITLE
Add some logging to track down #20180

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by ktoso** [comment]
LGTM, want it merged so it goes into some nightlies I assume right? :)

**Review by ktoso — APPROVED** [review]

**Comment by ktoso** [comment]
refs 
#20180

**Comment by raboof** [comment]
Yes that'd probably be nicer than putting time into setting up a repeat job and reproducing it there

**Comment by ktoso** [comment]
Cool, wanted to sanity check that was the intent :)

**Pull request merged**
