### PR TITLE
Fix scala.util.parsing.combinator version for OSGi import #21966

### PR DESCRIPTION
**Pull request by domel8dp**

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Refs https://github.com/akka/akka/issues/21966 (please ref back to the issue a PR is addressintg, thanks!)

**Comment by ktoso** [comment]
So what's the correct range here? We want to release on monday, thus this must be complete and merged today.

**Comment by ktoso** [comment]
I see, I made the change then. LGTM if @briantopping claims this is LGTHim ;-)

**Comment by briantopping** [comment]
Yep, I'm good with that change. Thanks! :shipit:

**Comment by ktoso** [comment]
:shipit:-ing it after validation just for sanity's sake.

**Comment by domel8dp** [comment]
@briantopping I was trying to be consistent with those other imports, like:
`def kamonImport(packageName: String = "kamon.sigar.*") = optionalResolution(versionedImport(packageName, "1.6.5", "1.6.6"))`

which uses the asterisk, although I don't think there are any sub-packages and exact package version, although I agree that next minor version should be used. Tbh even the next major version should be used, but let's be realistic ;)

**Comment by briantopping** [comment]
Well, I assume they are using SemVer, which would indicate the first breaking release would be the minor version. Maybe your point is that the stuff won't change for a very long time, in which case the minor version will be more than adequate ;)

**Comment by domel8dp** [comment]
SemVer states that minor version bump should be backward compatible, major version should be changed when breaking changes are introduced:

> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API

> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced

**Comment by briantopping** [comment]
@domel8dp Hah, I stand corrected!

**Comment by ktoso** [comment]
Thanks, both of you 👍

**Pull request merged**
