### PR TITLE
=doc,htc show explicitly how to return an HttpResponse in Java8 DSL

### PR DESCRIPTION
**Pull request by ktoso**
Add explicit HttpResponse sample to Java 8 DSL section of docs (no example showed this here).

See question: https://groups.google.com/forum/#!topic/akka-user/ZmIP7RIDeUs

### CODE REVIEW

**Comment by ktoso** [comment]
failure was unrelated

**Comment by ktoso** [comment]
PLS BUILD

**Comment by ktoso** [comment]
Please review @2m @johanandren

**Comment by johanandren** [comment]
LGTM!

**Pull request merged**
