### PR TITLE
actor: streamline cross source directory usage

### PR DESCRIPTION
**Pull request by jrudolph**
With 2.12 and 2.13 being the last releases of the 2.x series, it's hard
to say if we currently still need the 2.13+/- directories. For now it seems
more explicit to use simple 2.12/2.13 directories.

### CODE REVIEW

**Comment by jrudolph** [comment]
In any case, we don't need 4 of those directories which was the original idea behind this PR.

**Review by raboof — COMMENTED** [review]
Nice, this means we can also drop the custom code for this in `project/AkkaBuild.scala`

**Comment by jrudolph** [comment]
> Nice, this means we can also drop the custom code for this in `project/AkkaBuild.scala`

Yep, indeed. I don't wanted to go as far as that because we might need it at some point in the future? But maybe we can remove it for now.

**Review by johanandren — APPROVED** [review]
Makes sense to me.

**Comment by raboof** [comment]
> But maybe we can remove it for now.

As you said there's not going to be a 2.14 and we won't re-introduce 2.11, so it might be fine. When we add a structure for Scala 3 we can decide then whether we want to split up or duplicate.

**Review by raboof — APPROVED** [review]
LGTM like this as well, though

**Pull request merged**
