### PR TITLE
Exclude docs package from API docs #22296

### PR DESCRIPTION
**Pull request by athieriot**
Attempt to fix issue #22296 by adding the Doc project in the filtered list

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Comment by ktoso** [comment]
LGTM, thanks!

**Review by ktoso — APPROVED** [review]

**Comment by ktoso** [comment]
This looks good to me, sanity check please @2m?

**Review by 2m — APPROVED** [review]
LGTM

**Pull request merged**
