### PR TITLE
=htc #19361 FrameOutHandler and FrameEventRenderer as graph stages

### PR DESCRIPTION
**Pull request by gosubpl**
This is actually a little dust-off of code written by @ktoso and not merged in PR 19362. Contains FrameOutHandler and FrameEventRenderer as graph stages.

### CODE REVIEW

**Comment by gosubpl** [comment]
Refs #19361

**Comment by gosubpl** [comment]
There is one thing I would like to discuss - there is a function `absorbTermination()` which is private in `FrameOutHandler` and is a copy of function from `Context`, which was used in previous incarnation of the same - https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/ws/FrameOutHandler.scala#L57 . Question: maybe it would be better to place this function either in `GraphStage` or `Output` to be reusable (like the original `ctx.absorbTermination()`)?

I would also like to thank @ktoso for kindly agreeing to me issuing this PR (as he takes credit for almost all the code in it :smiley: )

**Comment by ktoso** [comment]
OK TO TEST

**Comment by jrudolph** [comment]
@ktoso are the automated autobahn tests still running? Should I run them manually otherwise?

**Comment by ktoso** [comment]
Sadly they're not :( We had trouble with stability of the infrastructure starting them and turned them off :/ Would be great to get them back working... For reference: https://jenkins.akka.io:8498/job/akka-http-websockets/

**Comment by gosubpl** [comment]
Please note that this is `akka-http` PR, despite original issue not being moved there.

**Comment by gosubpl** [comment]
@ktoso any plans of porting this to `akka-http`, or will this be _the second time_ this code dies unmerged? Probably third time is the charm...

**Comment by ktoso** [comment]
If you want to reopen it on akka-http please do, otherwise we'll have do so manually for you. 
Nothing Akka-HTTP related should be merged on akka/akka currently.

I'm stuck in tons of customer meetings and javone this week, sorry for slow progress on repo.

**Comment by gosubpl** [comment]
Closing this here, will re-open manually on `akka-http`. Many thanks for porting'n'merging others!

**Pull request closed without merging**
