### PR TITLE
Remove "Future is a monad" title

### LINKED ISSUE #25433: Clarify the docs about Future being a monad
Please assign to me :)

### PR DESCRIPTION
**Pull request by kubukoz**
Closes #25433

### CODE REVIEW

**Review by chbatey — CHANGES_REQUESTED** [review]
I think we should just remove the title/reference to monadic methods and explain the methods and they allow Futures to be used in a for comprehension.

**Comment by ktoso** [comment]
I agree with @chbatey, please remove references pointing to that it is a monad -- a thing either is or isn't one so the current change that proposes "kind of" is more confusing than helpful.

**Comment by kubukoz** [comment]
For now I just reverted and removed the "Future is a monad" title, so now the only mention of "monad" is in "future had monadic operations", which is reasonably close to truth - do you think we can leave it as it is, or should I do something about the rest of the text?

**Review by chbatey — APPROVED** [review]
LGTM, thanks

**Review by ktoso — APPROVED** [review]
This looks good :) "has monadic operations" is true enough, thanks a lot!

**Pull request merged**
