### PR TITLE
+htc #19577 binding DSL for javadsl Http

### PR DESCRIPTION
**Pull request by ktoso**
One method overload for now, will intensely look at API to see if more overloads are needed or if we stuff it all to the Connect DSL (there's server settings too etc).

### CODE REVIEW

**Comment by ktoso** [comment]
Resolves #19577

**Comment by drewhk** [comment]
LGTM

**Comment by rkuhn** [comment]
PLS BUILD

**Comment by rkuhn** [comment]
LGTM

**Comment by rkuhn** [comment]
failure cannot have been related

**Comment by ktoso** [comment]
I'm not sure all apis are consistent yet. Will reopen the ticket as a reminder once I'm back

**Pull request merged**
