### PR TITLE
Remove stale other language bindings doc page 

### LINKED ISSUE #21426: Remove the "other language bindings" docs page
As it is not really maintained and very old.

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #21426

### CODE REVIEW

**Comment by ktoso** [comment]
Did you check the projects and they're indeed dead?

LGTM I guess

**Comment by johanandren** [comment]
Mikka hasn't been touched in 3 years, the other two are not projects but samples of how Akka could be used by Groovy++ and Clojure. I was more after the fact that we do not keep our eyes on those three links so a user of JVM language X is probably better off just googling for Akka + X than us having a page we never update.

**Comment by ktoso** [comment]
Yeah, good to delete it. Thanks

**Comment by drewhk** [comment]
LGTM

**Pull request merged**
