### PR TITLE
Fix CapabilityFlag.off

### PR DESCRIPTION
**Pull request by t3hnar**

### CODE REVIEW

**Comment by ktoso** [comment]
Whoa what a silly bug thanks!
We'll include it in the upcoming release

**Comment by ktoso** [comment]
OK TO TEST

**Comment by johanandren** [comment]
LGTM

**Comment by ktoso** [comment]
Thanks again @t3hnar !

**Comment by ktoso** [comment]
Resolves https://github.com/akka/akka/issues/21084

**Pull request merged**
