### PR TITLE
Fix formatting of plural ByteStrings in docs

### PR DESCRIPTION
**Pull request by liff**
Replace occurrences of ` ``ByteStrings`` ` with ` ``ByteString`` s `.

Re: https://github.com/akka/akka/pull/21409#issuecomment-257529475

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
LGTM, thanks

**Comment by drewhk** [comment]
Hm, should we fix this instead after the conversion to MarkDown? I am not yet sure what are the quirks there but maybe we don't need the extra space. We can keep this open as a reminder and port it to the new docs. What do you think?

**Comment by ktoso** [comment]
Not sure if this really matters when to apply hm - I suppose it's Endre's call since he's doing all the docs conversions :)

**Comment by jrudolph** [comment]
We will have other docs changes until then, so that things will have to get reimported to markdown anyway when the switch is finally made. Why not just merge it then now?

**Comment by drewhk** [comment]
Just modify the docs, I know how to migrate them.

**Comment by ktoso** [comment]
Yup, cool 👍

**Comment by ktoso** [comment]
Thanks for the cleanup @liff !

**Pull request merged**
