### PR TITLE
=act #18607 Test failing on timeout not happening

### PR DESCRIPTION
**Pull request by johanandren**
Changed the future to never complete to be sure there is no racing

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Comment by johanandren** [comment]
PLS BUILD

**Comment by drewhk** [comment]
Lol, LGTM

**Comment by ktoso** [comment]
lol indeed :-)
LGTM! Merge on successful validation.

**Comment by johanandren** [comment]
PLS BUILD

**Pull request merged**
