### PR TITLE
Make ReceiveBuilder a real mutable builder #18894

### PR DESCRIPTION
**Pull request by wojtasskorcz**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @wojtasskorcz,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by wojtasskorcz** [comment]
I've just signed the Lightbend CLA

**Comment by johanandren** [comment]
Refs #18894

**Review by johanandren — APPROVED** [review]
LGTM

**Review by drewhk — APPROVED** [review]
LGTM

**Review by patriknw — APPROVED** [review]
LGTM, thanks @wojtasskorcz

**Pull request merged**
