### PR TITLE
=htp: reactivate file-chunking-* settings

### PR DESCRIPTION
**Pull request by aruediger**

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Thanks for the PR @2beaucoup! We've added you to the jenkins whitelist now, all PRs will automatically be validated without one of us having to OK it :-) Thanks again for the continued stream of great PRs :+1:

**Comment by drewhk** [comment]
This is LGTM to me, @jrudolph?

**Comment by jrudolph** [comment]
For me there are two questions:

 * Does chunking still serve any purpose on streams and if yes, which one? :)
 * If yes, why not piggy back on the chunking configuration of the file source directly.

For me, the previous need for chunking in spray was more a hack around missing proper backpressure support. So, AFAIR we got rid of any chunking directives by purpose.

@2beaucoup, what's your stance on this? Are there use cases I am missing?

**Comment by 2beaucoup** [comment]
Thx fpr your comments @jrudolph. That was the input I was looking for when I opened this PR.

I agree, that chunking has no purpose in the context of serving static files.

But what about resources where the content length is either not available (e.g. streaming of live content) or expensive to calculate?

**Comment by jrudolph** [comment]
There are a few things that play together in this topic and which maybe need some consideration:

 1. Do chunks carry any meaning on the HTTP (routing/low-level) API level?
 2. What are the stream-level consequences of chunk sizes?
 3. How often do applications need to tweak chunking? Is it significant enough to warrant a directive?

To give a few answers:

 1. Yes, API chunks are currently visible on the network but only for chunked transfer-encoding. However, we would rather make chunking decisions opaque in the default case to have more flexibility in the implementation as suggested in #17694.
 2. For limiting resources, after-the-fact rechunking cannot have any positive effect. As it stands, adding more stages or cutting smaller chunks will always introduce more work. The only place where you can turn knobs to change resource usage effectively can be at the original source which allocates the original buffers. By configuring these original buffers (like network receive buffers) you choose how much data you let into your system. (Decompressing stages that expand data are "original sources" as well.)
 3. I really don't know if there are "good applications" of chunking for now. Adding a directive now could users give the impression that chunks mattered more than they actually do. So, I'd like to be lazy with introducing something on the HTTP level which may not be so interesting for most users anyway.

**Comment by 2beaucoup** [comment]
@jrudolph agreed. Chunking doesn't serve a purpose on the routing level and especially not for files. I'll just remove the leftover settings from the test.

On the other hand maybe we should think about the value of chunking in the context of serving `WithoutKnownLength` request/response entities.

**Comment by drewhk** [comment]
What is the conclusion here? Should I merge?

**Comment by 2beaucoup** [comment]
@drewhk no. I'll open another PR that removes the remnants of chunking for now.

**Comment by jrudolph** [comment]
Thanks, @2beaucoup, I think it makes sense to have another discussion before coming to a conclusion.

**Comment by 2beaucoup** [comment]
superseded by #18316

**Pull request closed without merging**
