### PR TITLE
Fixed #31098.

### LINKED ISSUE #31098: javadsl.ClusterSharding Typed : withRole also sets datacenter
`Entity.of(...).withRole("backend") `:

1. sets entity's role with "backend" value : OK
2. but ALSO sets datacenter with "backend" : NOT OK !

As a result, my shard region is always running as a proxy.

I think there is a typo in method Entity#copy at line 331 of akka.cluster.sharding.typed.javadsl.ClusterSharding.scala in version 2.6.18. Instead of
`dataCenter: Optional[String] = role): Entity[M, E] = {`

It should be
`dataCenter: Optional[String] = datacenter): Entity[M, E] = {`

akka.cluster.sharding.typed.scaladsl.ClusterSharding.scala looks OK.

### PR DESCRIPTION
**Pull request by vicopol**
References #31098

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @Vicopol,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Review by johanandren — APPROVED** [review]
LGTM, thanks @Vicopol !

**Review by pvlugter — APPROVED** [review]
👍🏼

**Review by raboof — APPROVED** [review]
Thanks!

**Pull request merged**
