### PR TITLE
=str switch to java std lib ThreadLocalRandom.

### PR DESCRIPTION
**Pull request by andreaTP**
Following what we did in the past.
We have a promising initial port of akka-stream :-)

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
I guess this is fine, don't see a reason to prefer the Scala one

**Comment by patriknw** [comment]
yeah, I think we already did this previously. These are new ones.

**Comment by patriknw** [comment]
LGTM, thanks

**Comment by andreaTP** [comment]
the failure seems to be related with cluster that isn't affected by this PR ... spurious maybe?

**Comment by patriknw** [comment]
The failing test is `SupervisorHierarchySpec`, but that should be unrelated.

**Comment by patriknw** [comment]
PLS BUILD

**Comment by ktoso** [comment]
Thanks @andreaTP

**Comment by andreaTP** [comment]
Thank you guys!

**Pull request merged**
