### PR TITLE
customise test for race between GetState message and persistAsync handler

### PR DESCRIPTION
**Pull request by ortibazar**
In this failure, updateState handler in `persistAsync(Evt("rc-3"))(updateState)` processed before GetState message. And there is also chance GetState message handler may execute before this handler. So the result message may contain "rc-3" or not.

Refs  #22052

### CODE REVIEW

**Review by patriknw — APPROVED** [review]
LGTM, good catch

**Comment by patriknw** [comment]
OK TO TEST

**Comment by patriknw** [comment]
PLS BUILD

**Comment by patriknw** [comment]
PLS BUILD

**Comment by johanandren** [comment]
PLS BUILD

**Comment by johanandren** [comment]
What is it with this PR refusing to build on jenkins?

**Comment by patriknw** [comment]
yeah, I had some of those also. I solved it by pushing a new commit (rebasing with master)

**Comment by ortigali** [comment]
I'll create new pull request

**Comment by ktoso** [comment]
This seems like a rebase gone wrong @ortigali ?

Okey, thanks

**Pull request closed without merging**
