### PR TITLE
Change error to waning

### PR DESCRIPTION
**Pull request by muskan3006**
References #30608

### CODE REVIEW

**Comment by johanandren** [comment]
What we would like for #30608 is to first log warning a few times, then log an error (since it seems to be unrecoverable, or at least a bigger problem than if the first few retries failed), see https://github.com/akka/akka/pull/30488 for an example where we did just that for another logged error .

**Comment by muskan3006** [comment]
> Looks good but needs a code reformat compile + commit and push should fix it.

applyCodeStyle should work right?

**Comment by johanandren** [comment]
Sorry about that extra work, not sure how we added the alias without also verifying what it formats and checking those changes in.

**Comment by muskan3006** [comment]
> That is very curious, PR validation should be green if you just skip checking the changed Java sources in though, so please do that and I will investigate what is going on with the Java formatting.

Check passed

**Review by patriknw — COMMENTED** [review]
looking good, a few suggestions...

**Comment by muskan3006** [comment]
@patriknw comments resolved

**Review by patriknw — APPROVED** [review]
LGTM, thanks for contributing

**Review by johanandren — APPROVED** [review]

**Pull request merged**
