### PR TITLE
Update cluster-metrics.md

### PR DESCRIPTION
**Pull request by guobinhit**
## Purpose

Optimize document content and remove redundancy dependencies

## References

NONE.

## Changes

NONE.

## Background Context

Make the content more concise.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @guobinhit,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by raboof — APPROVED** [review]
Having it twice right after each other indeed seems excessive, thanks!

**Comment by raboof** [comment]
OK TO TEST

**Review by chbatey — APPROVED** [review]
LGTM, thanks!

**Comment by chbatey** [comment]
Thanks for signing the CLA @guobinhit we'll merge once the validation has passed

**Comment by guobinhit** [comment]
@raboof @chbatey I'm glad to make a little contribution to that.

**Pull request merged**
