### PR TITLE
bump sbt version to 0.13.11

### PR DESCRIPTION
**Pull request by ktoso**
Seems the upgrade is safe from what I've quickly checked locally

### CODE REVIEW

**Comment by johanandren** [comment]
LGTM!

**Comment by zhangshifeng** [comment]
@ktoso Can you update the akka-samples too?

**Comment by ktoso** [comment]
Sure, good point.

-- 
Cheers,
Konrad 'ktoso’ Malawski
Akka @ Typesafe

On 23 February 2016 at 12:41:32, Shifeng Zhang (notifications@github.com) wrote:

@ktoso Can you update the akka-samples too?

**Comment by ktoso** [comment]
I'll do the updating of the templates in a separate PR, not sure if Activator likes 0.13.11 yet.

**Pull request merged**
