### PR TITLE
Restart replication stream from correct seen seqNr

### PR DESCRIPTION
**Pull request by chbatey**
Needs to go via the actor as it is stored in its state

### CODE REVIEW

**Review by johanandren — APPROVED** [review]

**Comment by chbatey** [comment]
Needs a rebase on the rename

**Comment by chbatey** [comment]
Bah time for another rebase

**Comment by chbatey** [comment]
lol now for a third time, you're banned from doing things @johanandren

**Comment by johanandren** [comment]
Something weird still with this branch, lists a ton of commits...

**Comment by chbatey** [comment]
I merged rather than rebased

**Pull request merged**
