### PR TITLE
Simplify the definition of ActorRef#narrow

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
Maybe narrow should be deprecated and removed.

**Comment by patriknw** [comment]
> Maybe narrow should be deprecated and removed.

We have a bunch of tickets related to `narrow` of `Behavior` and we will look into those, but `narrow` of `ActorRef` is useful (at least needed in Java) and safe (as far as I see it so far).

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by dwijnand** [comment]
Looking for another @akka/akka-team member to approve this 1-line PR.

**Review by johanandren — APPROVED** [review]

**Pull request merged**
