### PR TITLE
Post 2.6.7 updates

### PR DESCRIPTION
**Pull request by johanandren**

### CODE REVIEW

**Review by raboof — APPROVED** [review]

**Review by ennru — APPROVED** [review]
LGTM.

**Comment by johanandren** [comment]
Hmm, I don't understand this, we are getting MiMa complaints about missing classes against 2.6.7 but that was just released and nothing committed since. Any ideas @raboof ?

**Comment by johanandren** [comment]
Those are all JFR related and we only build them for JDK9+ so something about that not working perhaps?

**Comment by raboof** [comment]
Yes, I think mima doesn't 'see' jdk11-only classes. We probably want to add them to '2.6.x.backwards.excludes' like we did for akka-actor-typed/src/main/mima-filters/2.6.x.backwards.excludes/jfr.excludes and akka-remote/src/main/mima-filters/2.6.x.backwards.excludes/jdk11-specific-classes.backwards.excludes

**Comment by johanandren** [comment]
Ok, thanks!

**Comment by johanandren** [comment]
PLS BUILD

**Comment by johanandren** [comment]
Hmm, what is up with travis?

**Comment by johanandren** [comment]
Green in travis (https://travis-ci.org/github/akka/akka/builds/706916330 ), just not reported back

**Pull request merged**
