### PR TITLE
!htp,java #20592 javadsl complete* should take Marshaller[...,Request…

### PR DESCRIPTION
**Pull request by ktoso**
Resolves  https://github.com/akka/akka/issues/20592 with test

### CODE REVIEW

**Comment by ktoso** [comment]
@akka/akka-team @jypma please review

**Comment by drewhk** [comment]
LGTM

**Comment by jypma** [comment]
I actually think we should have two variants, just like with `complete`. You can `complete` with a marshaller to `RequestEntity`, but only if you also specify a `StatusCode` (since `RequestEntity` only has a content-type and body).

So in order for `completeWithFuture` to accept a marshaller just to `RequestEntity`, the caller would have to provide a `StatusCode` somewhere as well. 

You could just add your current code as `completeOKWithFuture`, and leave the existing one in place.

**Comment by jypma** [comment]
And the original reporter should be able to just wrap his marshaller in [`entityToOKResponse`](https://github.com/akka/akka/blob/master/akka-http/src/main/scala/akka/http/javadsl/server/Marshaller.scala#L81) as a workaround to get a `HttpResponse` Marshaller

**Comment by ktoso** [comment]
Thanks for chiming in @jypma, I'll look into addressing your feedback 👍

**Comment by ktoso** [comment]
I'm not completely sold on the forcing passing around the status code... I see it'd be the correct thing but it gets insane pretty quickly with how / where / number of overloads...

How about I rename the one's I'm adding just now to `completeOKWithFuture` and keep previous ones as is.

**Comment by jypma** [comment]
I can share some real usage scenarios that show how having the marshaller contribute a response code makes sense.

We actually have a fairly standard pattern of having a service layer return `Optional<MyWidget>` for a typical "find element by ID" functionality. On the REST layer this could be `GET /widgets/15`. Our marshaller then turns this either into 404 if it was `Optional.none`, or 200 if there was an element.

In other scenarios, one might map `Optional.none` to 204 No Content.

**Comment by ktoso** [comment]
Like I said, I see both the use case and it will be possible - via HttpResponse.
If you'd like to contribute the other overloads please do, I'll want to not stay on this PR for too long :)

**Comment by jypma** [comment]
Oh sorry, I misunderstood your previous message. OK to add your new directive under `completeOKWithFuture`.

**Comment by ktoso** [comment]
My head started spinning when I started to think about having to provide overloads for `() => Future[StatusCode -> Entity]` and similar ones, that'd explode in number of overloads (and method names) again :<

**Comment by jypma** [comment]
That's partly why I originally set on just having "complete as OK with a marshaller for entity" and "complete with a marshaller to response".

I was actually a bit surprised to find that the scala DSL implicitly pulled in "OK" as response code.

Either way, that's the way DSL's in Java unfortunately do look without implicits or default arguments: lots of permutations...

**Comment by ktoso** [comment]
Updated PR, please review @jypma 
Well 200 is what you usually need, and if not you simply `204 -> value` in Scala

**Comment by jypma** [comment]
LGTM :+1: 

Interestingly, I actually prefer to split up the two in my own code, doing `onSuccess(anyFuture, obj -> complete(obj, marshaller))`. Wasn't even aware there was a directive to combine it.

**Comment by ktoso** [comment]
Right, yeah those are somewhat equivalent. I tend to use onComplete when I'll be transforming the result and just complete if the Future is _the_ result.

**Comment by ktoso** [comment]
Thanks for chiming in and reviews!
We'll increasingly need more help from the community to keep the DSL healthy and alive, hope we can count on you there :-)

**Pull request merged**
