### PR TITLE
Configure external links in ScalaDoc

### PR DESCRIPTION
**Pull request by Atry**

### CODE REVIEW

**Comment by Atry** [comment]
I am the maintainer of sbt-api-mappings. I found that Akka's Scaladoc does not link to Scala standard library and other dependencies. This patch fixes the problem.

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Sounds like a nice idea, thanks!

**Comment by johanandren** [comment]
LGTM

**Comment by patriknw** [comment]
LGTM, very nice, @Atry 
I have tried it unidoc locally and it works great.

**Comment by ktoso** [comment]
Awesome, looking forward to it 😄

**Pull request merged**
