### PR TITLE
Fix lookup of coordinator for sharding proxies

### PR DESCRIPTION
**Pull request by chbatey**
Refs https://github.com/akka/akka/issues/23741

### CODE REVIEW

**Comment by chbatey** [comment]
BULD PLS

**Comment by chbatey** [comment]
stupid NPE

**Comment by chbatey** [comment]
BUILD PLS

**Comment by chbatey** [comment]
PLS BUILD

**Review by patriknw — APPROVED** [review]
LGTM

**Review by johanandren — APPROVED** [review]
LGTM

**Pull request merged**
