### PR TITLE
Bump few dependency versions, including Aeron 1.2.0

### PR DESCRIPTION
**Pull request by guidomedina**
Bump few dependencies to latest versions where easy and reasonable.

### CODE REVIEW

**Comment by guidomedina** [comment]
Why when I pull current master doesn't have the changes I'm being shown on the conflicts?

**Review by patriknw — APPROVED** [review]
LGTM, thanks

**Comment by patriknw** [comment]
OK TO TEST

**Comment by patriknw** [comment]
Let's merge this and if nightly tests pass we'll include it in tomorrow's 2.5-M2

**Pull request merged**
