### PR TITLE
=cls #18370 Document supervision for Cluster Sharding

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by patriknw** [comment]
Refs #18370

**Comment by patriknw** [comment]
@ktoso review please

**Comment by ktoso** [comment]
LGTM, though I wonder if it could be more built-in, like `Supervisor(strategy, props)`.

**Comment by patriknw** [comment]
you mean something similar to the `BackoffSupervisor`?

(by the way, it would be useful to configure the `BackoffSupervisor` to stop child in case of exceptions, or install custom strategy in it)

**Comment by ktoso** [comment]
Yes exactly, they could be made API wise pretty similar, and then you pick "hmm... here I need backoff, and here not."

**Comment by patriknw** [comment]
sounds good, please create a separate issue

**Comment by ktoso** [comment]
Done: https://github.com/akka/akka/issues/18487

This PR for now is LGTM :)

**Pull request merged**
