### PR TITLE
=act #17738 RoundRobinRoutingLogic negative index fix after Long.MAX_…

### LINKED ISSUE #17738: RoundRobinRoutingLogic negative index after Long wrap around
Guido Medina proposed improvements here: https://groups.google.com/d/msg/akka-user/bMfdK9ox4-I/gvRSAZtzEqEJ

### PR DESCRIPTION
**Pull request by guidomedina**
RoundRobinRoutingLogic negative index fix after Long.MAX_VALUE due to negative modulo, fixes #17738

### CODE REVIEW

**Comment by guidomedina** [comment]
JHM benchmark and source: https://gist.github.com/guidomedina/5f4c5f116997baa05170

**Comment by ktoso** [comment]
If we stay with `AtomicLong` the reason to add the overflow protection becomes a bit negligible - as @patriknw notices in the previous PR: *Random fact: it would take 29247 years to overflow the long at the speed of 10000000 msg/second.*

@patriknw @rkuhn @drewhk @2m you guys think we should merge or leave as is? 
Since not moving away from AtomicLong I'm not sure we need this...

**Comment by guidomedina** [comment]
I provided the pull request because @patriknw said he would sleep better, think of the current pull request as an insurance, you might never need it and at the same time it won't hurt to have it. Performance wise you can do easily 50m messages per second on an old 8 CPUs server.

**Comment by ktoso** [comment]
I don't mind merging, just got lost what the conclusion in the previous PR was

**Comment by guidomedina** [comment]
@ktoso I tested on a real server and `AtomicLong` performed significantly better than `AtomicInteger` which is why I closed the other pull request, also the other pull request was getting too cluttered and confusing *-mostly my fault-* so I closed it.

**Comment by patriknw** [comment]
LGTM

**Comment by guidomedina** [comment]
Made a very small change to make code more readable.

**Comment by patriknw** [comment]
@guidomedina thanks for contributing. Since it is not a critic fix it will not be included in 2.3.x, but I have cherry-picked it for master to be released in 2.4. Here is the new PR: https://github.com/akka/akka/pull/17907

**Pull request closed without merging**
