### PR TITLE
verify docs for complete directive #20280

### PR DESCRIPTION
**Pull request by svezfaz**
These look OK, I added an example in the docs for each of them

### CODE REVIEW

**Comment by svezfaz** [comment]
Refs #20280

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Thanks, looks Good! Just what we needed here :)
For reference, the docs explain the magnet, but the signature does not really exist, so it makes sense to make sure we test those.

**Comment by johanandren** [comment]
LGTM, thanks!

**Pull request merged**
