### PR TITLE
Add javadsl Query.create(Iterable) overload #21232

### PR DESCRIPTION
**Pull request by pawmot**
- Added the Query.create(Iterable) overload using StreamSupport;
- Added a test for the new overload.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @pawmot,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by pawmot** [comment]
I've signed the CLA

**Comment by johanandren** [comment]
OK TO TEST

**Comment by ktoso** [comment]
LGTM, thanks!

**Comment by ktoso** [comment]
Resolves #21232

**Pull request merged**
