### PR TITLE
=htp #19331 Make FileAndResourceDirectives work in OSGi environments

### PR DESCRIPTION
**Pull request by aruediger**
these have different URI schemes for resources

### CODE REVIEW

**Comment by briantopping** [comment]
Duplicate

**Comment by 2beaucoup** [comment]
@briantopping You offered to test this. How did that go?

**Comment by briantopping** [comment]
I don't have time to test your work, sorry. I already spent a couple of days debugging what you had committed in #17495.

**Comment by 2beaucoup** [comment]
> I don't have time to test your work, sorry.

Then I guess I misinterpreted

> Please let me know if you'd like me to test any PRs you have!

in #19363.

> I already spent a couple of days debugging what you had committed in #17495.

Again: This change was a fix for a security issue that this PR tries to defend against as well.

> I reopened the work you ripped this from as #19415 and that is fully tested.

I didn't rip anything. I [suggested](https://github.com/akka/akka/issues/19331#issuecomment-168608907) exactly that fix: Use the removed code (which I BTW co-authored) for the default case. This PR was just for testing purposes following the discussion in #19363.

Speaking of copying: Copying commit messages / PR titles isn't particularly helpful in reducing the confusion here.

I'll just close this.

**Comment by briantopping** [comment]
> Then I guess I misinterpreted

I did say that I would test your PR. Other priorities came up, like keeping the roof over the head. That's the nature of OSS. I apologized. Nothing else I can do.

SBT doesn't have a framework for unit testing OSGi, that work is all in Maven. Maven doesn't have the facilities for unit testing concurrent code. It's not possible for this build to work in either environment really, so nobody is at fault for not having unit tests here.

> Again: This change was a fix for a security issue that this PR tries to defend against as well.

I asked you previously to provide a reference to the OSGi spec for why you believe your delta was necessary in the first place. Apparently that request was lost or I can't find it. IIRC, OSGi URLs are meant to be opaque and I believe there is no requirement for them to be the same across containers. All I was trying to find is why you believed so strongly that this extra complexity was warranted and I got nothing back. 

> Speaking of copying: Copying commit messages / PR titles isn't particularly helpful in reducing the confusion here.

This has been annoying for both of us. I apologize for my part in that.

**Pull request closed without merging**
