### PR TITLE
Update remoting-artery.md

### PR DESCRIPTION
**Pull request by minjibir**
References #xxxx

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
Thanks!

**Comment by raboof** [comment]
This PR is targeting the `release-2.5` branch, could you update it to target `main` instead?

**Comment by minjibir** [comment]
It is now pointing to main @raboof

**Comment by raboof** [comment]
> It is now pointing to main @raboof

Thanks! I see quite some conflicts - I suspect it needs a rebase as well :)

**Comment by minjibir** [comment]
It is now pointing to main @raboof

**Comment by patriknw** [comment]
This contains 172 commits. Probably easiest to start fresh from `main`.

**Comment by raboof** [comment]
> This contains 172 commits. Probably easiest to start fresh from `main`.

I took the liberty of rebasing (dropping the 171 commits that represented things backported to the 2.5 branch)

**Review by raboof — APPROVED** [review]

**Pull request merged**
