### PR TITLE
=act removed reference to java.reflect.

### PR DESCRIPTION
**Pull request by andreaTP**
In this way I'm able to work with my own implementation of akka.util.Reflect without having to mock java reflect.

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Sneaky, I don't mind I guess. Can we rename the useless part though?
Technically is is "correct" :)

**Comment by andreaTP** [comment]
fixed everywhere!

**Comment by ktoso** [comment]
Thanks! LGTM

**Comment by patriknw** [comment]
LGTM :)

**Comment by andreaTP** [comment]
The cool fact is that this is all I need to cross compile this file :-) Thanks guys!

**Comment by ktoso** [comment]
That's great :) Happy hakking

**Pull request merged**
