### PR TITLE
=act #17781 Optimize the creation of router actor

### PR DESCRIPTION
**Pull request by MQ-EL**
refs: #17905

### CODE REVIEW

**Comment by ktoso** [comment]
Superseeds https://github.com/akka/akka/pull/17905

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
PLS BUILD

**Comment by MQ-EL** [comment]
```shell
[error] Failed: Total 62, Failed 1, Errors 0, Passed 61
[error] Failed tests:
[error] akka.remote.RemoteNodeShutdownAndComesBack

Retest again?

**Comment by ktoso** [comment]
AFAICS this is LGTM, shall we include this week? Needs the commits to be squashed into one commit though (cc @MQ-EL)

**Comment by MQ-EL** [comment]
I am late, so sorry.

**Comment by ktoso** [comment]
No problem at all! We're shipping RC1 this friday, so it did not slip very much :smile: 
Can you amend the commit message to be `=act #17781 Optimize the creation of router actor`? (then we'll merge, thanks!)

**Comment by MQ-EL** [comment]
ok

**Comment by ktoso** [comment]
PLS BUILD

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
LGTM

**Comment by ktoso** [comment]
Thanks for contributing @MQ-EL!

**Comment by ktoso** [comment]
refs: #17781

**Comment by MQ-EL** [comment]
You are welcome!

**Pull request merged**
