### PR TITLE
!str - replaces flattenConcat with flatMapConcat

### PR DESCRIPTION
**Pull request by viktorklang**
For review: proposed change

### CODE REVIEW

**Comment by viktorklang** [comment]
@drewhk Shall I rebase this on release-2.3-dev now?

**Comment by drewhk** [comment]
Yes, I merged the docs.

**Comment by viktorklang** [comment]
@drewhk @ktoso @rkuhn 

Ok, rebased and added examples for migrations.
Please review the feature.

**Comment by drewhk** [comment]
reviewing now

**Comment by drewhk** [comment]
LGTM

**Pull request merged**
