### PR TITLE
spelling corrections

### PR DESCRIPTION
**Pull request by enelson**

### CODE REVIEW

**Comment by ktoso** [comment]
Thanks! Likely the same issues exist in `javadsl/Flow.scala`

// I somehow miss our =str markers hm

**Comment by drewhk** [comment]
LGTM

**Comment by enelson** [comment]
Sure, I'll look at javadsl/Flow.scala too.

**Comment by ktoso** [comment]
Thanks Eric!

**Comment by viktorklang** [comment]
Any reason to hold off merging this? :)

**Comment by ktoso** [comment]
Not after the 2nd commit came in, which we had no time to notice yet ;)

**Comment by ktoso** [comment]
Thanks a lot @enelson !

**Comment by viktorklang** [comment]
Bah, what is this! :)

**Comment by ktoso** [comment]
:wink: 

this is akka

**Comment by enelson** [comment]
Thanks for your quick response @ktoso! This is always a great group of people to work with.

**Comment by ktoso** [comment]
Very glad you feel this way :-) Looking forward to more contributions in the future then perhaps? :-)

**Pull request merged**
