### PR TITLE
[fixes#23329] PersistentFSM: andThen callbacks are not executed when stay()

### LINKED ISSUE #23329: [PersistentFSM] stay andThen not executing
Hey all,

Please regard the following example in a PersistentFSM actor:

```scala
when(Starting) {
  case Event(myEvent(), _) =>
    stay andThen { _ =>
      doSomething() // Never gets called
    }
}
```

The `doSomething()` never gets called. However, the following works:

```scala
when(Starting) {
  case Event(evt @ myEvent(), _) =>
    stay applying evt andThen { _ =>
      doSomething() // Gets called just fine
    }
}
```

Looking at the code of `PersistentFSM.scala`:

```scala
/**
 * Register a handler to be triggered after the state has been persisted successfully
 */
def andThen(handler: D ⇒ Unit): State[S, D, E] = {
  copy(afterTransitionDo = handler)
}
```

I _kinda_ understand why an `andThen` wouldn't fire since there is not a transition. However, this does not explain why `andThen` _does_ run after running `applying()`, since there still isn't any transition happening from one state to the other.

I'm using Akka 2.5.3 and scala 2.11. Any thoughts on this?

CC @jordymoos

### PR DESCRIPTION
**Pull request by sovaalexandr**
fixes #23329
Because [issue](https://github.com/akka/akka/issues/23329) that I have fall into got no reaction awhile I have decided to propose a fix. This is a "simple code fix" that is described at [comment](https://github.com/akka/akka/issues/23329#issuecomment-342319597) to original issue.
This fix covers the PersistentFSM behavior that is not specified by documentation and makes code meet general Transition consequences.

@johanandren @leonidb please, review.

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Review by ktoso — APPROVED** [review]
LGTM

**Comment by ktoso** [comment]
Thanks!

**Comment by ktoso** [comment]
Whooooop! Actually no.
This is as designed. I just remembered the design discussion about FSM, see here: 

```
   *
   * This method always triggers transition events, even for `A -> A` transitions.
   * If you want to stay in the same state without triggering an state transition event use [[#stay]] instead.
*/
def goto
```

and 

```
   * No transition event will be triggered by [[#stay]].
   * If you want to trigger an event like `S -&gt; S` for `onTransition` to handle use `goto` instead.
   *
   * @return descriptor for staying in current state
   */
  final def stay():
```

**Comment by ktoso** [comment]
These are from raw FSM, https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/FSM.scala so PersistendFSM was doing the right thing, replicating FSMs behavious

**Comment by ktoso** [comment]
Sorry but I have to revert the merge; I think we need to make sure the semantics are exactly those of the FSM, so in other words it seems that the `stay applying` is actually doing the wrong thing perhaps 

cc @sovaalexandr

**Comment by sovaalexandr** [comment]
@ktoso But this is not about _stay applying_ but rather about **stay andThen** which behaves in strange way: gets called only when it's _stay applying_. This behavior was never documented and considered as a bug. This PR not changes _stay applying_ but only makes andThen callback being called independent of events.

Also at issue [I have proposed](https://github.com/akka/akka/issues/23329#issuecomment-342319597) a "documentation bug" fix. But it requires decomposition of State to two classes to make andThen callbacks impossible when no event happens. Maybe this way of bug fix would be ok?

BTW about FSM: It doesn't have applying. It have uses, isn't it?

**Comment by sovaalexandr** [comment]
This is useful for instance to command to make a snapshot from outside. When you send a command from somewhere else, and you don't want your fsm to change state, you just want a snapshot to be scheduled. Sure, all logic could be put just before stay() gets called and I'm using this workaround now (not for snapshots but for commands that either not change state nor emit events) but it was really confusing to me why the command consequences ain't happen. And I suppose there could be also some people who'd place a "command consequence" code to andThen. And to save them couple hours - either andThen should be called or "stay andThen" should never be co**d**ed.

**Comment by sovaalexandr** [comment]
It's like you declaring that first of all you stay and only then you apply some consequences

**Comment by ktoso** [comment]
Stay has to have the same semantics as FSM, that’s definitively what has to stay as is. What is wrong is that stay applying actually does execute the and then things I think. As it is documented in FSM, if you want to exec the things, goto(thesamestate) this is because some people have logic which should only be executed in the event of changing a state, and stay explicitly is not about changing the state

**Comment by sovaalexandr** [comment]
@ktoso I think I understand what you talking about. If you want andThen -> goto(currentState)
But what about my [suggestion](https://github.com/akka/akka/issues/23329#issuecomment-342324152) to fix as "documentation bug" with decomposition of State class to not allow andThen be called on, for instance, stay() descriptor?
I do think some people may also have this gotcha to do like
`stay andThen { _ => someOtherActor ! SomeCommand }`
because I think it's quite logical that FSM is first about state and only then about other. So it's quite logical to handle state at first place and all other - afterwards.

**Comment by sovaalexandr** [comment]
The general idea of this suggestion is: as a code author of particular PersistentFSM implementation you decide what have you end up with on particular message. And you have two options:

- stay() at current state and don't have ability to apply any events/call any callbacks/etc.
- goto(someState) with abilities described above
- stop() which is essentially stay()

To achieve this we have to: make `State[S, D, E]` to be sealed abstract class with all 6 first methods that it has now. Than we should add
- `StateWithoutActions extends State[S, D, E]` with empty class body. Instance of this class would be returned form stay() and stop() factory methods
- `StateWithActions extends State[S, D, E]` with body that contains applying and andThen methods

That way we'll achieve expected behavior and wouldn't let users do actions that are not supposed to be done. And, of course describe this behavior at docs.

@ktoso what do you think about his kind of fix?

**Comment by lunaryorn** [comment]
@ktoso I came across this issue when trying to figure out why my `andThen` block was ignored.

Comments here suggest I should be able to replace `stay() andThen { _ => foo() }` with `goto(stateName) andThen { _ => foo() }` to have `foo` invoked.  

Is that really the case?  After all, if the state stays the same there’s nothing to persist, so I’d assume `andThen` is skipped as well.  At least, when I tried briefly today `goto(stateName)` didn’t work; `foo()` wasn’t invoked either.

**Pull request merged**
