### PR TITLE
Fix for dist missing libraries #20661

### LINKED ISSUE #20661: Dist zip doesn't contain libraries
The distribution zip at akka.io is missing all libraries, probably an unexpected consequence of #20495

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #20661

### CODE REVIEW

**Comment by johanandren** [comment]
Unrelated fail

**Comment by johanandren** [comment]
PLS BUILD

**Comment by johanandren** [comment]
Unrelated failure

**Comment by johanandren** [comment]
PLS BUILD

**Comment by johanandren** [comment]
Argh. Unrelated failure.

**Comment by 2m** [comment]
LGTM

**Comment by drewhk** [comment]
LGTM

**Comment by ktoso** [comment]
LGTM, thanks for tracking this down :)

**Pull request merged**
