### PR TITLE
=tes Use ConversionCheckedTripleEquals

### PR DESCRIPTION
**Pull request by patriknw**
@rkuhn suggested that we use `should ===` instead of `should be` for compilation time type check.
I have tried it on akka-actor-test in this PR.

I wanted to make sure that it doesn't blow up compilation time, and it looks alright. 2 sec increase of clean test:compile for akka-actor-tests. 840 replacements.

### CODE REVIEW

**Comment by patriknw** [comment]
The failure is interesting:

    [error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-remote/src/test/scala/akka/remote/serialization/DaemonMsgCreateSerializerSpec.scala:102: types Class[_$5] and Class[_$5] do not adhere to the type constraint selected for the === and !== operators; the missing implicit parameter is of type org.scalautils.Constraint[Class[_$5],Class[_$5]]
    [error]       assert(got.props.clazz === expected.props.clazz)

**Comment by drewhk** [comment]
LGTM, if we really need this.

**Comment by ktoso** [comment]
LGTM, not a big fan of the symbol but more typesafety is always a win ;)

**Comment by rkuhn** [comment]
@patriknw We know how to compare Class objects, so we can teach ScalaTest as well; the following goes into AkkaSpec and it should work:
~~~scala
implicit def c[A, B]: Constraint[Class[A], Class[B]] = new Constraint[Class[A], Class[B]] {
  def areEqual(a: Class[A], b: Class[B]) = a == b
}
~~~

**Comment by bantonsson** [comment]
This needs to be rebased (or re-replaced) :frowning:

**Comment by rkuhn** [comment]
I’ve been sneaking this in in different other places ;-) so I think we should actually do this.

**Comment by patriknw** [comment]
ok, I will

**Comment by patriknw** [comment]
I have rebased, added the class constraint and replaced more projects. Let's merge this quickly.

**Comment by patriknw** [comment]
rebased again

**Comment by patriknw** [comment]
@rkuhn tests successful, merge?

**Comment by rkuhn** [comment]
absolutely!

**Pull request merged**
