### PR TITLE
jdk9-build: Update paradox to 0.3.0

### PR DESCRIPTION
**Pull request by ktoso**
Is that right...?

### CODE REVIEW

**Comment by raboof** [comment]
This is sbt-paradox-akka, which needs https://github.com/akka/akka-paradox/pull/14 and a release first

**Comment by ktoso** [comment]
Ah I see, looking great - LGTMed there... You rock man, just on time with that one... :)
Do you think you'd be able to release that one soon?

(We can close this PR until then or keep it around, whichever you prefer)

**Review by ktoso — COMMENTED** [review]
Nice, LGTM :)

**Comment by ktoso** [comment]
Feel free to make this PR your own, my commit message is a bit weird there anyway ;)

**Comment by raboof** [comment]
Seems to work now!

(build fails because of formatting inconsistencies, but we chose to ignore those for this branch IIRC, right?)

**Comment by ktoso** [comment]
Yeah, ignore the formatting things - it would lead us down rebase/merge hell once we tried to sync the branches then.

Awesome, thanks :)

**Pull request merged**
