### PR TITLE
fix Trigger references in the stream cookbook example for digest #24317

### PR DESCRIPTION
**Pull request by shkoder**
* replace Trigger with Unit
 * use a known test vector for SHA-256 in the test
 * cosmetic changes in docs.stream.cookbook tests

### CODE REVIEW

**Comment by shkoder** [comment]
ref #24317

**Review by ktoso — APPROVED** [review]
OK TO TEST

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Comment by jrudolph** [comment]
OK TO TEST
PLS BUILD

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
