### PR TITLE
Adding links to wireTap and alsoTo docs #25808

### PR DESCRIPTION
**Pull request by nvollmar**
Added short documentation and links between wireTap and alsoTo.

### CODE REVIEW

**Review by raboof — APPROVED** [review]
:+1: very useful!

**Comment by nvollmar** [comment]
and learned something new 👍

**Comment by nvollmar** [comment]
Alternatively since both method do basically the same except how they deal with the sink why not have one method with something similar to the overflow strategy used elsewhere (drop or backpressure)?

**Comment by nvollmar** [comment]
just another review left :)

**Review by patriknw — APPROVED** [review]
LGTM, thanks

**Comment by patriknw** [comment]
Refs #25808

**Pull request merged**
