### PR TITLE
#19440 Added scala-java8-compat as a dependency to streams

### PR DESCRIPTION
**Pull request by drewhk**
Now with ticket numbers and everything. Still no imperative present ;)

### CODE REVIEW

**Comment by ktoso** [comment]
Much LGTM

**Comment by drewhk** [comment]
Hm, this does not make it visible for akka-stream-tests. Why is that?

**Comment by drewhk** [comment]
sorry, I was forgetting updating the sbt project.

**Comment by ktoso** [comment]
Uff, had me worried for a second there

**Comment by rkuhn** [comment]
LGTM

**Comment by drewhk** [comment]
Unrelated failure.

**Pull request merged**
