### PR TITLE
= #17342 Make 2.4 binary compatible with 2.3

### PR DESCRIPTION
**Pull request by patriknw**
Not ready (will fail), but a good starting pointing for splitting up the remaining work.

### CODE REVIEW

**Comment by patriknw** [comment]
The commits marked with `!` are:

    69387bb 2014-10-28 | !act #16125 Timeout Calls through CircuitBreaker. (origin/pr/16161) [Martin Eigenbrodt]
    3f12ef2 2014-09-05 | !clu #15042 useRole restriction on local node is now respected This is an API breaking change if someone implemented their own Routers. The change is required because the router must know if the local routees should be started or not so it has to check the roles of the cluster member (the local one). We could delay this decision of starting local routees, but that would allow messages to be dead-letter-ed (bad). (origin/pr/15822) [Konrad 'ktoso' Malawski]
    325e05e 2014-08-19 | !act #15626 expose DatagramChannel creation in DatagramChannelCreator (origin/pr/15627) [Martynas Mickevicius]
    a6d3704 2013-09-08 | !act #13490 Changed the callback to SocketOption to accept a channel instead of a Socket, this allows for using the nio features. (origin/pr/15568) [Michael R. Maletich]
    c046cdf 2014-02-22 | !act,doc #3893 Removed isTerminated checks from ActorClassification (origin/pr/15024) [Konrad Malawski]
    826cc74 2014-03-11 | !tes #2971 Make TestKit.remaining throw AssertionError outside of within (origin/pr/2005) [dario.rexin]

**Comment by patriknw** [comment]
remaining mimaReportBinaryIssues:

    [info] akka-actor: found 54 potential binary incompatibilities (filtered 240)
    [error]  * the type hierarchy of class akka.actor.RootActorPath has changed in new version. Missing types {akka.actor.ActorPath}
    [error]    filter with: ProblemFilters.exclude[MissingTypesProblem]("akka.actor.RootActorPath")
    [error]  * method apply(java.lang.Object,java.lang.Object,scala.Option,scala.Option,scala.collection.immutable.List)akka.actor.FSM#State in object akka.actor.FSM#State does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.actor.FSM#State.apply")
    [error]  * method ElementRegex()scala.util.matching.Regex in object akka.actor.ActorPath does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.actor.ActorPath.ElementRegex")
    [error]  * abstract method logFilter()akka.event.LoggingFilter in class akka.actor.ExtendedActorSystem does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.actor.ExtendedActorSystem.logFilter")
    [error]  * method boss()akka.actor.RepointableActorRef in class akka.actor.ActorDSL#Extension does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.actor.ActorDSL#Extension.boss")
    [error]  * declaration of trait akka.actor.ActorPath has changed to class akka.actor.ActorPath in new version; changing trait to class breaks client code
    [error]    filter with: ProblemFilters.exclude[IncompatibleTemplateDefProblem]("akka.actor.ActorPath")
    [error]  * abstract method terminate()scala.concurrent.Future in class akka.actor.ActorSystem does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.actor.ActorSystem.terminate")
    [error]  * abstract method whenTerminated()scala.concurrent.Future in class akka.actor.ActorSystem does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.actor.ActorSystem.whenTerminated")
    [error]  * the type hierarchy of class akka.actor.ChildActorPath has changed in new version. Missing types {akka.actor.ActorPath}
    [error]    filter with: ProblemFilters.exclude[MissingTypesProblem]("akka.actor.ChildActorPath")
    [error]  * method this(java.lang.Object,java.lang.Object,scala.Option,scala.Option,scala.collection.immutable.List)Unit in class akka.actor.FSM#State does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.actor.FSM#State.this")
    [error]  * method afterConnect(java.net.Socket)Unit in trait akka.io.Inet#SocketOption does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.io.Inet#SocketOption.afterConnect")
    [error]  * method beforeServerSocketBind(java.net.ServerSocket)Unit in trait akka.io.Inet#SocketOption does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.io.Inet#SocketOption.beforeServerSocketBind")
    [error]  * method beforeConnect(java.net.Socket)Unit in trait akka.io.Inet#SocketOption does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.io.Inet#SocketOption.beforeConnect")
    [error]  * method beforeDatagramBind(java.net.DatagramSocket)Unit in trait akka.io.Inet#SocketOption does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.io.Inet#SocketOption.beforeDatagramBind")
    [error]  * method afterConnect(java.nio.channels.SocketChannel)Unit in trait akka.io.Inet#SocketOption does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.io.Inet#SocketOption.afterConnect")
    [error]  * method afterConnect(java.nio.channels.ServerSocketChannel)Unit in trait akka.io.Inet#SocketOption does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.io.Inet#SocketOption.afterConnect")
    [error]  * method afterConnect(java.nio.channels.DatagramChannel)Unit in trait akka.io.Inet#SocketOption does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.io.Inet#SocketOption.afterConnect")
    [error]  * method beforeBind(java.nio.channels.SocketChannel)Unit in trait akka.io.Inet#SocketOption does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.io.Inet#SocketOption.beforeBind")
    [error]  * method beforeBind(java.nio.channels.ServerSocketChannel)Unit in trait akka.io.Inet#SocketOption does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.io.Inet#SocketOption.beforeBind")
    [error]  * method beforeBind(java.nio.channels.DatagramChannel)Unit in trait akka.io.Inet#SocketOption does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.io.Inet#SocketOption.beforeBind")
    [error]  * method dissociate(akka.actor.ActorRef)scala.collection.immutable.Iterable in trait akka.event.ActorClassification does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.event.ActorClassification.dissociate")
    [error]  * synthetic method akka$event$ActorClassification$$mappings()java.util.concurrent.ConcurrentHashMap in trait akka.event.ActorClassification has now a different result type; was: java.util.concurrent.ConcurrentHashMap, is now: java.util.concurrent.atomic.AtomicReference
    [error]    filter with: ProblemFilters.exclude[IncompatibleResultTypeProblem]("akka.event.ActorClassification.akka$event$ActorClassification$$mappings")
    [error]  * synthetic method akka$event$ActorClassification$_setter_$akka$event$ActorClassification$$mappings_=(java.util.concurrent.ConcurrentHashMap)Unit in trait akka.event.ActorClassification's type has changed; was (java.util.concurrent.ConcurrentHashMap)Unit, is now: (java.util.concurrent.atomic.AtomicReference)Unit
    [error]    filter with: ProblemFilters.exclude[IncompatibleMethTypeProblem]("akka.event.ActorClassification.akka$event$ActorClassification$_setter_$akka$event$ActorClassification$$mappings_=")
    [error]  * method unsubscriber()akka.actor.ActorRef in trait akka.event.ActorClassification does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.event.ActorClassification.unsubscriber")
    [error]  * method dissociate(akka.actor.ActorRef)Unit in trait akka.event.ActorClassification does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.event.ActorClassification.dissociate")
    [error]  * method unregisterFromUnsubscriber(akka.actor.ActorRef,Int)Boolean in trait akka.event.ActorClassification does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.event.ActorClassification.unregisterFromUnsubscriber")
    [error]  * method registerWithUnsubscriber(akka.actor.ActorRef,Int)Boolean in trait akka.event.ActorClassification does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.event.ActorClassification.registerWithUnsubscriber")
    [error]  * synthetic method akka$event$ActorClassification$$mappings()java.util.concurrent.atomic.AtomicReference in trait akka.event.ActorClassification does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.event.ActorClassification.akka$event$ActorClassification$$mappings")
    [error]  * synthetic method akka$event$ActorClassification$_setter_$akka$event$ActorClassification$$mappings_=(java.util.concurrent.atomic.AtomicReference)Unit in trait akka.event.ActorClassification does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.event.ActorClassification.akka$event$ActorClassification$_setter_$akka$event$ActorClassification$$mappings_=")
    [error]  * method system()akka.actor.ActorSystem in trait akka.event.ActorClassification does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.event.ActorClassification.system")
    [error]  * method this(Boolean)Unit in class akka.event.EventStream does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.event.EventStream.this")
    [error]  * method fromActorSystem(akka.actor.ActorSystem)akka.event.EventStream in object akka.event.EventStream does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.event.EventStream.fromActorSystem")
    [error]  * synthetic method <init>$default$1()Boolean in object akka.event.EventStream does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.event.EventStream.<init>$default$1")
    [error]  * method hasSubscriptions(java.lang.Object)Boolean in trait akka.event.SubchannelClassification does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.event.SubchannelClassification.hasSubscriptions")
    [error]  * method this()Unit in class akka.event.japi.ActorEventBus does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.event.japi.ActorEventBus.this")
    [error]  * method ask(akka.actor.ActorSelection,java.lang.Object,akka.actor.ActorRef,akka.util.Timeout)scala.concurrent.Future in trait akka.pattern.AskSupport does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.pattern.AskSupport.ask")
    [error]  * method ask(akka.actor.ActorRef,java.lang.Object,akka.actor.ActorRef,akka.util.Timeout)scala.concurrent.Future in trait akka.pattern.AskSupport does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.pattern.AskSupport.ask")
    [error]  * synthetic method ask$extension(akka.actor.ActorRef,java.lang.Object,akka.util.Timeout)scala.concurrent.Future in object akka.pattern.AskableActorRef does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.pattern.AskableActorRef.ask$extension")
    [error]  * synthetic method ?$extension(akka.actor.ActorRef,java.lang.Object,akka.util.Timeout)scala.concurrent.Future in object akka.pattern.AskableActorRef does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.pattern.AskableActorRef.?$extension")
    [error]  * method ask(java.lang.Object,akka.util.Timeout)scala.concurrent.Future in class akka.pattern.AskableActorSelection does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.pattern.AskableActorSelection.ask")
    [error]  * method ?(java.lang.Object,akka.util.Timeout)scala.concurrent.Future in class akka.pattern.AskableActorSelection does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.pattern.AskableActorSelection.?")
    [error]  * synthetic method ask$extension(akka.actor.ActorSelection,java.lang.Object,akka.util.Timeout)scala.concurrent.Future in object akka.pattern.AskableActorSelection does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.pattern.AskableActorSelection.ask$extension")
    [error]  * synthetic method ?$extension(akka.actor.ActorSelection,java.lang.Object,akka.util.Timeout)scala.concurrent.Future in object akka.pattern.AskableActorSelection does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.pattern.AskableActorSelection.?$extension")
    [error]  * method ask(java.lang.Object,akka.util.Timeout)scala.concurrent.Future in class akka.pattern.AskableActorRef does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.pattern.AskableActorRef.ask")
    [error]  * method ?(java.lang.Object,akka.util.Timeout)scala.concurrent.Future in class akka.pattern.AskableActorRef does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.pattern.AskableActorRef.?")
    [error]  * method identifier()Int in class akka.serialization.ByteArraySerializer is declared final in new version
    [error]    filter with: ProblemFilters.exclude[FinalMethodProblem]("akka.serialization.ByteArraySerializer.identifier")
    [error]  * method this()Unit in class akka.serialization.ByteArraySerializer does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.serialization.ByteArraySerializer.this")
    [error]  * method identifier()Int in class akka.serialization.JavaSerializer is declared final in new version
    [error]    filter with: ProblemFilters.exclude[FinalMethodProblem]("akka.serialization.JavaSerializer.identifier")
    [error]  * deprecated method apply(Long)akka.util.Timeout in object akka.util.Timeout's type has changed; was (Long)akka.util.Timeout, is now: (scala.concurrent.duration.FiniteDuration)akka.util.Timeout
    [error]    filter with: ProblemFilters.exclude[IncompatibleMethTypeProblem]("akka.util.Timeout.apply")
    [error]  * deprecated method this(Long)Unit in class akka.util.Timeout's type has changed; was (Long)Unit, is now: (scala.concurrent.duration.FiniteDuration)Unit
    [error]    filter with: ProblemFilters.exclude[IncompatibleMethTypeProblem]("akka.util.Timeout.this")
    [error]  * abstract method byteStringCompanion()akka.util.ByteString#Companion in class akka.util.ByteString does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.util.ByteString.byteStringCompanion")
    [error]  * abstract method writeToOutputStream(java.io.ObjectOutputStream)Unit in class akka.util.ByteString does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.util.ByteString.writeToOutputStream")
    [error]  * the type hierarchy of object akka.routing.BalancingPool has changed in new version. Missing types {scala.runtime.AbstractFunction3}
    [error]    filter with: ProblemFilters.exclude[MissingTypesProblem]("akka.routing.BalancingPool$")
    [error]  * method apply(java.lang.Object,java.lang.Object,java.lang.Object)java.lang.Object in object akka.routing.BalancingPool's type has changed; was (java.lang.Object,java.lang.Object,java.lang.Object)java.lang.Object, is now: (Int,akka.actor.SupervisorStrategy,java.lang.String)akka.routing.BalancingPool
    [error]    filter with: ProblemFilters.exclude[IncompatibleMethTypeProblem]("akka.routing.BalancingPool.apply")


    [info] akka-testkit: found 5 potential binary incompatibilities (filtered 14)
    [error]  * method shutdownActorSystem(akka.actor.ActorSystem,java.lang.Boolean)Unit in class akka.testkit.JavaTestKit does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.testkit.JavaTestKit.shutdownActorSystem")
    [error]  * method shutdownActorSystem(akka.actor.ActorSystem,scala.concurrent.duration.Duration)Unit in class akka.testkit.JavaTestKit does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.testkit.JavaTestKit.shutdownActorSystem")
    [error]  * method testActorName()java.lang.String in trait akka.testkit.TestKitBase does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.testkit.TestKitBase.testActorName")
    [error]  * method remainingOrDefault()scala.concurrent.duration.FiniteDuration in trait akka.testkit.TestKitBase does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.testkit.TestKitBase.remainingOrDefault")
    [error]  * deprecated method dilated(scala.concurrent.duration.Duration,akka.actor.ActorSystem)scala.concurrent.duration.Duration in object akka.testkit.TestKit does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.testkit.TestKit.dilated")


    [info] akka-remote: found 8 potential binary incompatibilities (filtered 214)
    [error]  * method ARRAY_OF_BYTE_ARRAY()Array[java.lang.Class] in class akka.remote.serialization.ProtobufSerializer does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.remote.serialization.ProtobufSerializer.ARRAY_OF_BYTE_ARRAY")
    [error]  * method identifier()Int in class akka.remote.serialization.ProtobufSerializer is declared final in new version
    [error]    filter with: ProblemFilters.exclude[FinalMethodProblem]("akka.remote.serialization.ProtobufSerializer.identifier")
    [error]  * method this()Unit in class akka.remote.serialization.ProtobufSerializer does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.remote.serialization.ProtobufSerializer.this")
    [error]  * method identifier()Int in class akka.remote.serialization.MessageContainerSerializer is declared final in new version
    [error]    filter with: ProblemFilters.exclude[FinalMethodProblem]("akka.remote.serialization.MessageContainerSerializer.identifier")
    [error]  * method identifier()Int in class akka.remote.serialization.DaemonMsgCreateSerializer is declared final in new version
    [error]    filter with: ProblemFilters.exclude[FinalMethodProblem]("akka.remote.serialization.DaemonMsgCreateSerializer.identifier")
    [error]  * method boundAddress()akka.actor.Address in trait akka.remote.transport.Transport does not have a correspondent in old version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.remote.transport.Transport.boundAddress")
    [error]  * method addressFromSocketAddress(java.net.SocketAddress,java.lang.String,java.lang.String,scala.Option)scala.Option in object akka.remote.transport.netty.NettyTransport does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.remote.transport.netty.NettyTransport.addressFromSocketAddress")
    [error]  * method nrOfInstances()Int in class akka.remote.routing.RemoteRouterConfig does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.remote.routing.RemoteRouterConfig.nrOfInstances")


    [info] akka-multi-node-testkit: found 1 potential binary incompatibilities (filtered 31)
    [error]  * synthetic method akka$remote$testkit$MultiNodeSpec$Replacement$$$outer()akka.remote.testkit.MultiNodeSpec in class akka.remote.testkit.MultiNodeSpec#Replacement does not have a correspondent in new version
    [error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.remote.testkit.MultiNodeSpec#Replacement.akka$remote$testkit$MultiNodeSpec$Replacement$$$outer")

    
    [info] akka-cluster: found 1 potential binary incompatibilities (filtered 83)
    [error]  * method identifier()Int in class akka.cluster.protobuf.ClusterMessageSerializer is declared final in new version
    [error]    filter with: ProblemFilters.exclude[FinalMethodProblem]("akka.cluster.protobuf.ClusterMessageSerializer.identifier")

**Comment by patriknw** [comment]
Questions:
* ActorSystem and ExtendedActorSystems are not really intended to be subclassed outside of akka. Ok to ignore problems caused by adding new abstract methods?
* "identifier()Int in class XSerializer is declared final in new version" is only a problem if the serializer is intended to be subclassed. Shall we revert the `final` or ignore it?
* do we care about the problems in akka-testkit?
* do we care about the problems in akka-multi-node-testkit?

**Comment by patriknw** [comment]
I'll take a deeper look at the problems in `akka.io` package.

**Comment by patriknw** [comment]
I'll remove the `final` in the serializers

**Comment by ktoso** [comment]
Failure was SSL

**Comment by ktoso** [comment]
Aaargh... merged the wrong PR, sorry. // @patriknw

**Pull request merged**
