### PR TITLE
Fixes broken test for Scala 2.12 #24617

### PR DESCRIPTION
**Pull request by jlprat**
Refs: #24617
Fixes tests for Scala 2.12.x
There are still some differences between 2.11 and 2.12

### CODE REVIEW

**Comment by jlprat** [comment]
```
akka > ++2.12.4
[info] Setting Scala version to 2.12.4 on 36 projects.
[info] Reapplying settings...
[info] Set current project to akka (in build file:/home/jlprat/playground/akka/)
akka > project akka-actor-tests
[info] Set current project to akka-actor-tests (in build file:/home/jlprat/playground/akka/)
sbt:akka-actor-tests> testOnly *LineNumber*
[info] LineNumberSpec:
Coroner Thread Count starts at 12 in akka.util.LineNumberSpec
[info] LineNumbers
[info]   when writing Scala
[info]   - must work for small functions (36 milliseconds)
[info]   - must work for larger functions (3 milliseconds)
[info]   - must work for partial functions (3 milliseconds)
[info]   - must work for `def` (2 milliseconds)
[info]   when writing Java
[info]   - must work for small functions (2 milliseconds)
[info]   - must work for larger functions (2 milliseconds)
[info]   - must work for anonymous classes (2 milliseconds)
Coroner Thread Count started at 12, ended at 11, peaked at 12 in akka.util.LineNumberSpec
[info] ScalaTest
[info] Run completed in 1 second, 424 milliseconds.
[info] Total number of tests run: 7
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 7, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 7, Failed 0, Errors 0, Passed 7
```

And

```
sbt:akka-actor-tests> ++2.11.12
[info] Setting Scala version to 2.11.12 on 36 projects.
[info] Reapplying settings...
[info] Set current project to akka-actor-tests (in build file:/home/jlprat/playground/akka/)
sbt:akka-actor-tests> testOnly *LineNumber*
[info] LineNumberSpec:
Coroner Thread Count starts at 12 in akka.util.LineNumberSpec
[info] LineNumbers
[info]   when writing Scala
[info]   - must work for small functions (20 milliseconds)
[info]   - must work for larger functions (2 milliseconds)
[info]   - must work for partial functions (2 milliseconds)
[info]   - must work for `def` (3 milliseconds)
[info]   when writing Java
[info]   - must work for small functions (3 milliseconds)
[info]   - must work for larger functions (2 milliseconds)
[info]   - must work for anonymous classes (2 milliseconds)
Coroner Thread Count started at 12, ended at 12, peaked at 13 in akka.util.LineNumberSpec
[info] ScalaTest
[info] Run completed in 1 second, 28 milliseconds.
[info] Total number of tests run: 7
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 7, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 7, Failed 0, Errors 0, Passed 7
```

**Comment by ktoso** [comment]
For reference, on which JDK version was this?

**Review by ktoso — APPROVED** [review]

**Comment by jlprat** [comment]
It was on JDK8
I don't think the issue was related to the JDK version after all.
I'll setup JDK9 on my machine and run the tests again in an hour or so.

**Review by johanandren — APPROVED** [review]

**Comment by jlprat** [comment]
Run also with JDK9, same green results :)

**Comment by ktoso** [comment]
That sounds good, thanks

**Pull request merged**
