### PR TITLE
NOT FOR MERGE! #16653 Reproducer for form upload hang

### PR DESCRIPTION
**Pull request by bantonsson**
Refs #16653

### CODE REVIEW

**Comment by patriknw** [comment]
I have no clue. Perhaps this can give some hint to someone that knows this better:

    [DEBUG] [01/23/2015 11:20:24.598] [FormUploadHangSpec-akka.actor.default-dispatcher-14] [akka://FormUploadHangSpec/system/IO-TCP/selectors/$a/3] Invalid argument 23 2355k    0     0   23  542k      0  59839  0:00:40  0:00:09  0:00:31  2905
    [DEBUG] [01/23/2015 11:20:34.603] [FormUploadHangSpec-akka.actor.default-dispatcher-11] [akka://FormUploadHangSpec/system/IO-TCP/selectors/$a/2] Unbinding endpoint /127.0.0.1:62325

**Comment by patriknw** [comment]
the line that cause the problem (throws the Invalid argument exception) is:

    // Turn off Nagle's algorithm by default
    channel.socket.setTcpNoDelay(true)

L184 in TcpConnection.scala

Do you think it's alright to catch and continue such exception here? @rkuhn @drewhk

**Comment by rkuhn** [comment]
That is rather strange, but switching off Nagle is not critical so we should just swallow and continue.

**Comment by patriknw** [comment]
I'll fix that.

**Comment by drewhk** [comment]
swallow and continue is good as a first step, but cannot be that the problem is that this scan option closes the connection immediately and NIO just chokes on it? Is there any reason for we set this option after connect and not before? Was it another quirk that forced us to do that?

**Comment by drewhk** [comment]
At least we should try putting the setting code to pre-connect.

**Comment by patriknw** [comment]
Thanks, this was very useful for tracking down the issue.
Will not merge since I think we should avoid dependencies to external tools.

**Comment by bantonsson** [comment]
@patriknw I completely agree with the external tools thing in this case.

**Pull request closed without merging**
