### PR TITLE
#19333: Remove ImplicitMaterializer

### PR DESCRIPTION
**Pull request by drewhk**

### CODE REVIEW

**Comment by drewhk** [comment]
Fixes #19333

**Comment by ktoso** [comment]
Remove its mention from `akka-docs/rst/scala/http/client-side/request-level.rst` too.

LGTM

**Comment by drewhk** [comment]
ok, thanks

**Comment by johanandren** [comment]
LGTM!

**Comment by patriknw** [comment]
you don't write migration guide as you go?

**Comment by drewhk** [comment]
I actually forgot in this case, so no.

**Comment by drewhk** [comment]
(in general, yes, but in this case just somehow assumed this class to be not used at all :) )

**Comment by drewhk** [comment]
added the missing section: https://github.com/akka/akka/pull/19574

**Pull request merged**
