### PR TITLE
changing logging error as previous wasn't proper english

### PR DESCRIPTION
**Pull request by franciscolopezsancho**
## References

References #xxxx

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @franciscolopezsancho,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by raboof** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]
Nice thanks!

**Review by johanandren — APPROVED** [review]
LGTM

**Pull request merged**
