### PR TITLE
Update latest versions for mima

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Review by octonato — APPROVED** [review]

**Comment by renatocaval** [comment]
MiMa is failing for 2.5, but only for Scala 2.13. Lot's of missing stuff. 

```scala

[error] akka-actor: Failed binary compatibility check against com.typesafe.akka:akka-actor_2.13:2.5.30! Found 12 potential problems (filtered 114)

[error]  * object akka.util.TraversableOnceExtensionMethods does not have a correspondent in current version

[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("akka.util.TraversableOnceExtensionMethods$")

[error]  * class akka.util.TraversableOnceExtensionMethods does not have a correspondent in current version

[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("akka.util.TraversableOnceExtensionMethods")

[error]  * object akka.util.ccompat.CompatImpl does not have a correspondent in current version

[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("akka.util.ccompat.CompatImpl$")

[error]  * class akka.util.ccompat.package#ImmutableSortedMapExtensions does not have a correspondent in current version

[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("akka.util.ccompat.package$ImmutableSortedMapExtensions")

[error]  * class akka.util.ccompat.package#SortedExtensionMethods does not have a correspondent in current version

[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("akka.util.ccompat.package$SortedExtensionMethods")

[error]  * class akka.util.ccompat.package#ImmutableSortedSetOps does not have a correspondent in current version

[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("akka.util.ccompat.package$ImmutableSortedSetOps")

[error]  * class akka.util.ccompat.CompatImpl does not have a correspondent in current version

[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("akka.util.ccompat.CompatImpl")

[error]  * class akka.util.ccompat.package#FactoryOps does not have a correspondent in current version

[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("akka.util.ccompat.package$FactoryOps")

[error]  * object akka.util.ccompat.package#ImmutableTreeMapExtensions does not have a correspondent in current version

[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("akka.util.ccompat.package$ImmutableTreeMapExtensions$")

[error]  * object akka.util.ccompat.package#ImmutableSortedMapExtensions does not have a correspondent in current version

[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("akka.util.ccompat.package$ImmutableSortedMapExtensions$")

[error]  * class akka.util.ccompat.package#ImmutableTreeMapExtensions does not have a correspondent in current version

[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("akka.util.ccompat.package$ImmutableTreeMapExtensions")

[error]  * object akka.util.ccompat.package#ImmutableSortedSetOps does not have a correspondent in current version

```

**Comment by jrudolph** [comment]
The reason is that the published 2.5 artifacts for Scala 2.13 contain files they shouldn't contain.

**Comment by jrudolph** [comment]
> The reason is that the published 2.5 artifacts for Scala 2.13 contain files they shouldn't contain.

And the reason for that is probably that the build uses `crossPaths := false` which leads to all kinds of spurious issues.

**Comment by patriknw** [comment]
Superseded by https://github.com/akka/akka/pull/28771

**Pull request closed without merging**
