### PR TITLE
Add sender information to message received logging

### PR DESCRIPTION
**Pull request by jpeel**
Add a 'from <sender>' portion to the receive messages in LoggingReceive.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @jpeel,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by rkuhn** [comment]
OK TO TEST

**Comment by rkuhn** [comment]
Thanks for your contribution @jpeel ! This change looks good to me, please create a ticket and include its issue number in the commit message; once you signed the SLA we can then merge it.

**Comment by ktoso** [comment]
LGTM, thanks!

**Comment by drewhk** [comment]
LGTM but needs CLA signature (can be done online with your github account)

**Comment by patriknw** [comment]
LGTM

**Comment by ktoso** [comment]
Hi @jpeel - this PR looks good and we'd like to merge it but we'll need you to confirm the CLA here: http://www.typesafe.com/contribute/cla before we can do that. Would you mind signing it online please?

Thanks!

**Comment by ktoso** [comment]
Hi @jpeel. I'm sorry but we can't merge this without the CLA being signed off.
Will have to close due inactivity otherwise. Would like to merge this, it's a nice improvement.

http://www.typesafe.com/contribute/cla

Thanks!

**Comment by rkuhn** [comment]
Sadly need to be closed—there is only one way to do this, though, and future attempts will look exactly the same.

**Pull request closed without merging**
