### PR TITLE
Update logging.md

### PR DESCRIPTION
**Pull request by riteshpuj2013**
Anchor text changed from SL4FJ to SLF4J

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @riteshpuj2013,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by raboof — APPROVED** [review]
Oops! Thanks :)

**Comment by raboof** [comment]
OK TO TEST

**Comment by raboof** [comment]
Thanks for the update @riteshpuj2013!

**Pull request merged**
