### PR TITLE
Extend copyright into 2017

### PR DESCRIPTION
**Pull request by Philippus**
a few leftovers from https://github.com/akka/akka/issues/22102 (from later merged PR's I think)

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Comment by raboof** [comment]
hmm our nexus acting up again? :(

**Comment by raboof** [comment]
PLS BUILD

**Review by raboof — APPROVED** [review]
LGTM

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
