### PR TITLE
+all #16632 Make serialization identifiers configurable in reference.con...

### PR DESCRIPTION
**Pull request by Andrei-Pozolotin**
...f

### CODE REVIEW

**Comment by Andrei-Pozolotin** [comment]
@patriknw please review

**Comment by patriknw** [comment]
OK TO TEST

**Comment by patriknw** [comment]
LGTM, thanks

**Comment by bantonsson** [comment]
LGTM

**Comment by patriknw** [comment]
Refs #16632

**Comment by Andrei-Pozolotin** [comment]
thank you

**Pull request merged**
