### PR TITLE
fix: Harden DownSelfQuarantinedByRemote, #31095

### PR DESCRIPTION
**Pull request by patriknw**
* only trust or care about ThisActorSystemQuarantinedEvent from Up members

References #31095

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
Looks reasonable.

**Comment by patriknw** [comment]
@johanandren since we are uncertain, do you think I should add a feature flag so that it's possible to turn off the DownSelfQuarantinedByRemote?

**Comment by johanandren** [comment]
Hmmm. Yeah, maybe best to have that escape hatch.

**Comment by patriknw** [comment]
I think the whole purpose of introducing DownSelfQuarantinedByRemote was to use it as a STONITH signal, i.e. kill the receiver as quickly as possible. Like reducing the harm that could come from continuing running the quarantined node. There were some discussion in the original PR and issue https://github.com/akka/akka/pull/29737

It could be that there are cases that should be treated as harmless quarantine that we today trigger this from. That's why I asked for root cause (root logging reasons) in the ticket. One suspect is undelivered system messages combined with race conditions during shutdown, but I couldn't pin an exact problem there.

**Comment by patriknw** [comment]
Superseded by https://github.com/akka/akka/pull/32050

**Pull request closed without merging**
