### PR TITLE
Remove weird log cast

### PR DESCRIPTION
**Pull request by chbatey**

### CODE REVIEW

**Comment by raboof** [comment]
hmm
```
[error] /home/travis/build/akka/akka/akka-cluster-sharding/src/main/scala/akka/cluster/sharding/ShardCoordinator.scala:953:13: ambiguous reference to overloaded definition,
[error] both method isInfoEnabled in class MarkerLoggingAdapter of type (marker: akka.event.LogMarker)Boolean
[error] and  method isInfoEnabled in class BusLogging of type => Boolean
[error] match expected type ?
[error]     if (log.isInfoEnabled && (shards.nonEmpty || rebalanceInProgress.nonEmpty)) {
[error]             ^
[error] one error found
```

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
ah, compiler says no

**Comment by chbatey** [comment]
Well that explains that then

**Pull request closed without merging**
