### PR TITLE
headerValueByType should extract just value #20472

### PR DESCRIPTION
**Pull request by anilgursel**

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
LGTM, afair we noticed this while fixing javadsl didn't we @johanandren btw?

**Comment by johanandren** [comment]
LGTM (yes, we did notice exactly this, so we will need to fix it in the Java DSL as well)

**Comment by johanandren** [comment]
Refs #20472

**Pull request merged**
