### PR TITLE
=act #19216 Fix AbstractNodeQueue nepotism

### LINKED ISSUE #19216: AbstractNodeQueue suffers from nepotism
The next references in abstract node queue are never cleared, which leads to promoted dead nodes pulling new dead nodes into the old space of the garbage collector.

### PR DESCRIPTION
**Pull request by bantonsson**
Fixes #19216

### CODE REVIEW

**Comment by ktoso** [comment]
Great!
So with https://github.com/akka/akka/pull/19217/files#diff-1aa2e912a1b540c9cf0ffdb046e38bfdR87 being the actual nepotism fix, do we actually want the diff above (in `poll`)? Amount of code wise `pollNode` is quite bigger - isn't there a chance that it might hurt inlining?

**Comment by bantonsson** [comment]
@ktoso The change in `poll` needs to be there, or else the `tail.next` will not be cleared, we can't clear that field in `peekNode`. There might be another option, but we need to duplicate code or add a parameter to say if we want to clear the next field et.c.

**Comment by rkuhn** [comment]
The PR looks good to me, I think it is cleaner to reuse pollNode, and the additional write is also only an ordered one, so the performance impact should not be terrible—but of course such things can be deceptive.

**Comment by ktoso** [comment]
Thanks for explaining @bantonsson :)

**Comment by bantonsson** [comment]
Ran this benchmark https://github.com/plokhotnyuk/actors without and with the fix on my machine (2 core 2,6GHz Core i5 16GB). You win some and you loose some. The benchmark isn't that repeatable for me. No major differences.

AkkaSCOUnboundedActorSpec
Executor service type: akka-forkjoin-pool

| Without Fix               | With Fix                  |
|---------------------------|---------------------------|
| Enqueueing:               | Enqueueing:               | 
| 10,000,000 ops            | 10,000,000 ops            |
| 327,056,707 ns            | 322,664,131 ns            |
| 30,575,737 ops/s          | 30,991,979 ops/s          |
| 29.6 % of CPU usage       | 52.7 % of CPU usage       |
| 48 bytes per instance     | 48 bytes per instance     |
|                           |                           |
| Dequeueing:               | Dequeueing:               |
| 10,000,000 ops            | 10,000,000 ops            |
| 928,067,394 ns            | 704,244,532 ns            |
| 10,775,079 ops/s          | 14,199,613 ops/s          |
| 44.6 % of CPU usage       | 33.0 % of CPU usage       |
|                           |                           |
| Initiation:               | Initiation:               |
| 100,000 ops               | 100,000 ops               |
| 880,871,092 ns            | 992,992,377 ns            |
| 8,808 ns/op               | 9,929 ns/op               |
| 82.8 % of CPU usage       | 76.7 % of CPU usage       |
| 424 bytes per instance    | 424 bytes per instance    |
|                           |                           |
| Single-producer sending:  | Single-producer sending:  |
| 6,000,000 ops             | 6,000,000 ops             |
| 834,072,027 ns            | 762,917,355 ns            |
| 7,193,623 ops/s           | 7,864,547 ops/s           |
| 57.2 % of CPU usage       | 50.7 % of CPU usage       |
|                           |                           |
| Multi-producer sending:   | Multi-producer sending:   |
| 6,000,000 ops             | 6,000,000 ops             |
| 675,307,347 ns            | 697,114,512 ns            |
| 8,884,843 ops/s           | 8,606,907 ops/s           |
| 57.4 % of CPU usage       | 62.8 % of CPU usage       |
|                           |                           |
| Max throughput:           | Max throughput:           |
| 12,000,000 ops            | 12,000,000 ops            |
| 511,113,445 ns            | 517,883,579 ns            |
| 23,478,153 ops/s          | 23,171,230 ops/s          |
| 92.8 % of CPU usage       | 92.7 % of CPU usage       |
|                           |                           |
| Ping latency:             | Ping latency:             |
| 1,500,000 ops             | 1,500,000 ops             |
| 634,336,612 ns            | 660,414,998 ns            |
| 175 ns/op at 0.0%'ile     | 176 ns/op at 0.0%'ile     |
| 399 ns/op at 50.0%'ile    | 389 ns/op at 50.0%'ile    |
| 435 ns/op at 90.0%'ile    | 441 ns/op at 90.0%'ile    |
| 735 ns/op at 99.0%'ile    | 703 ns/op at 99.0%'ile    |
| 3,167 ns/op at 99.9%'ile  | 3,967 ns/op at 99.9%'ile  |
| 88.2 % of CPU usage       | 82.3 % of CPU usage       |
|                           |                           |
| Ping throughput 10K:      | Ping throughput 10K:      |
| 2,000,000 ops             | 2,000,000 ops             |
| 768,489,067 ns            | 866,642,989 ns            |
| 2,602,509 ops/s           | 2,307,755 ops/s           |
| 95.2 % of CPU usage       | 93.1 % of CPU usage       |

**Comment by rkuhn** [comment]
Thanks a lot, Björn!

**Comment by rkuhn** [comment]
(I’ll port to master)

**Comment by viktorklang** [comment]
Massive thanks, Björn!

**Pull request merged**
