### PR TITLE
=per #17630 FAILED: PersistenceFSMActorSpec

### PR DESCRIPTION
**Pull request by leonidb**
- Changed the timeouts to make tests less sensitive to environment issues

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Thanks for following up on this!
Refs #17630

**Comment by leonidb** [comment]
@ktoso 
Sure, hope this fixes the issue.

**Comment by leonidb** [comment]
@ktoso @patriknw 
On a slightly unrelated note, what's the convenient way to discuss possible improvements of ```PersistentFSM``` - like removing code duplication between the original ```FSM``` class and the clone, timers improvements, users feedback (hopefully :)) etc.?

**Comment by ktoso** [comment]
> On a slightly unrelated note, what's the convenient way to discuss possible improvements of PersistentFSM - like removing code duplication between the original FSM class and the clone, timers improvements, users feedback (hopefully :)) etc.?

There's two channels that work best for such discussions:
- akka-dev - the mailing list dedicated to developing akka - https://groups.google.com/forum/#!forum/akka-dev
- opening issues, if it's something actionable that might end with a PR

There's also the gitter channel if you have something short but we're not constantly monitoring it (like we do with akka-user and akka-dev).

**Comment by ktoso** [comment]
LGTM after marking the timing sensitive tests (those with `within` I'd say) as TimingTest.

Refs https://github.com/akka/akka/issues/17630

**Comment by ktoso** [comment]
Thanks for the update. I guess tagging doesn't work with junit? No idea, will try to check this before we merge. LGTM otherwise.

**Comment by leonidb** [comment]
@ktoso 
I haven't found any usages of the tag in JUnit based tests. I don't think it's possible.
A possible workaround would be to extend the timeout validation limit in the JUnit test.

**Comment by ktoso** [comment]
I'm happy to merge this in its current state, it's an improvement to stability in any case :-)

**Pull request merged**
