### PR TITLE
doc Replace the word stage by operator in stream doc

### PR DESCRIPTION
**Pull request by richardimaoka**
Refs #24995

Replace the word "stage" in stream doc.
Split the PR into multiple commits for easier review.

### CODE REVIEW

**Review by ktoso — APPROVED** [review]
LGTM thanks!

**Review by raboof — CHANGES_REQUESTED** [review]
Thanks for doing this! This PR renames a lot of documentation pages - that is good, but could you also update `./akka-docs/src/main/paradox/.htaccess` to make sure users are properly redirected when they visit the old URL's?

**Comment by richardimaoka** [comment]
Hi @raboof, I think I probably don't need to update .htaccess but please let me know if I'm wrong. 

I only renamed files in this commit https://github.com/akka/akka/pull/25138/commits/e28ded32512aa6414eeae215ed67d0ca8835477d, and everything was under akka-docs/src/main/categories.
image

Looking at [CONTRIBUTING.md](https://github.com/akka/akka/blob/1919f222fa849ea155e2246e814351517eac07e2/CONTRIBUTING.md#contributing-new-akka-streams-stagesoperators), 

> a link to the stages' "category" (these are listed in akka-docs/src/main/paradox/categories)

> Using this structure, the surrounding infrastructure will generate the index pages, so you do not need to maintain the index or category pages manually.

The files under the "category" directory seem to just generate the index page, so renaming the files in the directories does not require redirect?

https://doc.akka.io/docs/akka/snapshot/stream/operators/index.html#fan-in-stages

**Review by raboof — APPROVED** [review]
Ahh I think you're right, sorry!

**Comment by raboof** [comment]
Thanks!

**Pull request merged**
