### PR TITLE
Update CI/CD badge

### PR DESCRIPTION
**Pull request by lambdakilo**
Updating the CI/CD badge to 'publish'. Feel free to request changes in this PR for f.ex. a different build than 'publish'.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @akirataguchi115,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by akirataguchi115** [comment]
signed the cla

**Comment by johanandren** [comment]
Thanks, that has been broken a while, I wonder which action is best though, publish only compiles and publishes, but we don't run the pr validation one on main after merge, the nightlies perhaps, but those has the multi node cluster tests which are a bit unstable so it would show non-passing more often than not. Hmmm.

**Comment by akirataguchi115** [comment]
we can also think about what we want to achieve with the build badge on top of the README

**Comment by johanandren** [comment]
Yeah, good point, maybe we should just drop it.

**Comment by akirataguchi115** [comment]
sure if it makes the most sense! just lmk if i should remove the badge in this pr

**Comment by johanandren** [comment]
Let's drop it, feel free to do it in this PR or we can do it ourselves and close this PR.

**Review by johanandren — APPROVED** [review]

**Pull request merged**
