### PR TITLE
!per #17249 Avoid init problems of persistence tck

### PR DESCRIPTION
**Pull request by patriknw**
- in the end TestKitBase eagerly initialize the ActorSystem and
  to avoid the need for using lazy val tricks I changed the trait
  to abstract class with config constructor parameter

### CODE REVIEW

**Comment by patriknw** [comment]
Refs #17249

**Comment by patriknw** [comment]
failure was unrelated (know issue)

**Comment by ktoso** [comment]
Nice, LGTM

**Comment by drewhk** [comment]
LGTM

**Pull request merged**
