### PR TITLE
=htp #16808 fix unnecessary reverse DNS lookups for >Java1.7

### PR DESCRIPTION
**Pull request by agolubev**
this is fixing 1.6 behavior and relates to #17657

### CODE REVIEW

**Comment by drewhk** [comment]
OK TO TEST

**Comment by ktoso** [comment]
LGTM

**Comment by agolubev** [comment]
Unfortunately this is duplicate of what was fixed here #17658

**Comment by jrudolph** [comment]
Again, I'm sorry to fix it "behind your back". Thanks for following up in any case! Closing...

**Comment by agolubev** [comment]
No problem, =)

**Pull request closed without merging**
