### PR TITLE
=str #18074 UnzipWith#sad case scenario timing issue

### PR DESCRIPTION
**Pull request by agolubev**
Ref #18074

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Thanks, digging in to understand what the issue was...

**Comment by ktoso** [comment]
Ah I see, the error overtook the element previously, because of `demand=2`. LGTM, thanks!

**Comment by ktoso** [comment]
OK TO TEST

**Comment by agolubev** [comment]
Year - errors are not sequential.

**Comment by ktoso** [comment]
Merged, thanks!

**Pull request merged**
