### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### akka/akka now has a Chat Room on Gitter

@rkuhn has just created a chat room. You can visit it here: [https://gitter.im/akka/akka](https://gitter.im/akka/akka?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/akka/akka?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @gitter-badger,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by hepin1989** [comment]
wow nice

**Comment by drewhk** [comment]
umm, do we want this, or this was accidental, @rkuhn?

**Comment by 2m** [comment]
Well, @gitter-badger has not signed the CLA. :)

**Comment by ktoso** [comment]
@rkuhn intentional? Merge or close?

**Comment by rkuhn** [comment]
I’ll deal with it later, please leave open, I’ll close it.

**Comment by rkuhn** [comment]
We won’t put such a badge on the landing page just now.

**Pull request closed without merging**
