### PR TITLE
Fix links sytnax

### PR DESCRIPTION
**Pull request by ioleo**
We've overlooked in #22418 that links were broken. The PR included Markdown syntax links, while Akka docs use reStructuredText syntax.

### CODE REVIEW

**Comment by loostro** [comment]
@ktoso @2m

**Comment by johanandren** [comment]
Thanks! We are in the progress of migrating our docs to a different tool (paradox) so I think we might want you to hold off a bit and then possibly, if you are up to it, do a new PR with this fix in the new docs. We expect to be done with migration to the new tool in a few weeks, we're sorry that it's so distruptive but it's the most efficient way we can migrate all content at once.

**Comment by patriknw** [comment]
We have updated to a new documentation tool called [Paradox](http://developer.lightbend.com/docs/paradox/latest/). Can please rebase this and apply those changes in the new markdown files. Here's instructions of how to build the docs: https://github.com/akka/akka/blob/master/CONTRIBUTING.md#documentation

**Comment by ktoso** [comment]
Hi @loostro, do you want to submit this change to our new docs (see Patrik's comment)?
Thanks in advance, would be nice :)

**Comment by loostro** [comment]
I've just looked into it and it seems the current master has this already fixed (the new documentation uses markdown, and what previously was "wrong syntax" remained untouched, and now is in "correct syntax").

BTW :+1: switch to Paradox (with Markdown syntax)

**Pull request closed without merging**
