### PR TITLE
Compile some more subprojects with scala3 on travis

### PR DESCRIPTION
**Pull request by raboof**
Refs #30243

### CODE REVIEW

**Review by johanandren — APPROVED** [review]

**Comment by johanandren** [comment]
Starting to get to a point where we should maybe list the scala-3 compiled projects in the build instead of the Ci-job?

**Review by octonato — APPROVED** [review]
LGTM

**Comment by octonato** [comment]
> Starting to get to a point where we should maybe list the scala-3 compiled projects in the build instead of the Ci-job?

Would that require extra settings to not publish artifacts? If so, may better to just keep adding the projects in CI. That will hold us from add extra complexity in the build.

**Comment by raboof** [comment]
> > Starting to get to a point where we should maybe list the scala-3 compiled projects in the build instead of the Ci-job?
> 
> Would that require extra settings to not publish artifacts?

Perhaps it would actually be good to start publishing those at some point - though we might want to add a page to the docs explaining their experimental status and the fact that we don't promise binary compatibility for them yet.

> If so, may better to just keep adding the projects in CI. That will hold us from add extra complexity in the build.

Perhaps I'll try moving some of the configuration from `akka.build.scalaVersion` to using the 'regular' sbt cross-building at some point, that might be a neat cleanup already.

**Comment by raboof** [comment]
> Perhaps I'll try moving some of the configuration from akka.build.scalaVersion to using the 'regular' sbt cross-building

Made a start in #30392, but this revealed further problems...

**Pull request merged**
