### PR TITLE
upgrade to latest MiMa (0.1.12)

### PR DESCRIPTION
**Pull request by SethTisue**
the newest version supports Scala 2.12 properly and is capable of
detecting a variety of compatibility issues older versions missed

### CODE REVIEW

**Comment by drewhk** [comment]
OK TO TEST

**Comment by drewhk** [comment]
PLS WHITELIST

**Comment by ktoso** [comment]
It found some incompat things, I'll handle them.

**Comment by ktoso** [comment]
A lot of it seems to be protobuf... I think those we can ignore, but will check.

I'll close this PR and submit one with filters added, thanks @SethTisue !

**Pull request closed without merging**
