### PR TITLE
=str Optimize UnfoldAsync and UnfoldResourceAsync when future is already complete

### PR DESCRIPTION
**Pull request by He-Pin**
Try not to invoke the asynccallback when future is already done

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Comment by johanandren** [comment]
Needs some formatting though.

**Review by johanandren — APPROVED** [review]

**Comment by hepin1989** [comment]
@raboof ~ping

**Review by jrudolph — APPROVED** [review]
LGTM

**Comment by jrudolph** [comment]
Thanks, @hepin1989!

**Pull request merged**
