### PR TITLE
Allow specifying a log level when logging exceptions being seen the SupervisorStrategy

### PR DESCRIPTION
**Pull request by JakubKahovec**
## Purpose
Currently when logging gets enabled on the SupervisorStrategy in Akka Typed, all exceptions are being logged with the error level. It might not always be though the level a user wants thus it would be useful if there is a way how to specify the level the exceptions should be logged with .
## References

References #27133

## Changes

Adding `withLogLevel(level: LogLevel)` method to the SupervisorStrategy which allows to set the desired log level

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Comment by JakubKahovec** [comment]
Did sign the CLA

**Review by johanandren — COMMENTED** [review]
Looks good, missing a test that verifies that it works though. Can be done with the untyped EventFilter (we don't have a typed testkit for logging yet), look for that in other tests to see how to set it up.

**Review by johanandren — APPROVED** [review]
LGTM

There is a slight chance we'll have to change the log level type from the untyped one when/if we do #26537

**Review by patriknw — APPROVED** [review]
LGTM, thanks

**Pull request merged**
