### PR TITLE
remove one needless synchronized in akka-actor

### PR DESCRIPTION
**Pull request by rkuhn**
/cc @viktorklang :-)

### CODE REVIEW

**Comment by viktorklang** [comment]
Indirection sadness :~(

-- 
Cheers,
√

**Comment by rkuhn** [comment]
ARFU?

**Comment by viktorklang** [comment]
Nooooo....

-- 
Cheers,
√

**Comment by patriknw** [comment]
LGTM

**Comment by rkuhn** [comment]
I will still rewrite this to ARFU, please don’t merge just yet.

**Comment by viktorklang** [comment]
I'd prefer s.m.U

-- 
Cheers,
√

**Comment by rkuhn** [comment]
I don’t think the mental overhead is warranted: this is used only during dispatcher self-deactivation.

**Comment by viktorklang** [comment]
You're planning on derefing the field for normal access ISO going thru arfu
then?

-- 
Cheers,
√

**Comment by rkuhn** [comment]
Yes, of course, what else?

**Comment by viktorklang** [comment]
ARFU.get? Just like we do with s.m.U.getVolatile?

In any case, I *personally* prefer s.m.U until J9 VarHandles are out :)

On Tue, Mar 8, 2016 at 3:13 PM, Roland Kuhn <notifications@github.com>
wrote:

> Yes, of course, what else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akka/akka/pull/19938#issuecomment-193798565>.
>



-- 
Cheers,
√

**Comment by rkuhn** [comment]
But why would anyone ever call ARFU.get()? That only makes sense for the array variant.

**Comment by viktorklang** [comment]
Let's generalize the question: why does it exist on A*FU at all? :)

On Tue, Mar 8, 2016 at 3:51 PM, Roland Kuhn <notifications@github.com>
wrote:

> But why would anyone ever call ARFU.get()? That only makes sense for the
> array variant.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akka/akka/pull/19938#issuecomment-193811728>.
>



-- 
Cheers,
√

**Comment by hepin1989** [comment]
@rkuhn then you need use java .

**Comment by patriknw** [comment]
what's left here?

**Pull request merged**
