### PR TITLE
=rem #16224: Not terminate connections if quarantine id do not match (backport)

### PR DESCRIPTION
**Pull request by drewhk**
(cherry picked from commit a6e10f1)

### CODE REVIEW

**Comment by patriknw** [comment]
(akka-cluster/multi-jvm:compile) Compilation failed

**Comment by drewhk** [comment]
I know, I commented on FlowDock

**Comment by drewhk** [comment]
What is the "remainingOrDefault" identifier in RestartNode2Spec? It seems like it is not available in 2.3

**Comment by patriknw** [comment]
@drewhk It comes from testkit, I think you can use `remaining`.

**Comment by drewhk** [comment]
GH issue

**Comment by drewhk** [comment]
PLS BUILD

**Comment by drewhk** [comment]
Y U DDOS ME REPO?? :cry:

**Comment by drewhk** [comment]
PLS BUILD

**Comment by drewhk** [comment]
PLS BUILD

**Comment by drewhk** [comment]
PLS BUILD

**Comment by drewhk** [comment]
hooray, jenkins pulled the code!

**Comment by ktoso** [comment]
refs #16224

**Pull request merged**
