### PR TITLE
Add necessary telemetry interceptors for Akka 2.5 AskPattern

### PR DESCRIPTION
**Pull request by ygree**
Backport for #28580

### CODE REVIEW

**Review by johanandren — APPROVED** [review]

**Review by helena — APPROVED** [review]
LGTM and nice cleanup.

**Comment by ygree** [comment]
Build has failed because coursier couldn't load a dependency from bintray. @akka-ci please try again.

**Comment by ygree** [comment]
@akka/akka-admin-team It would be nice to have it merged as we are getting closer to release telemetry.

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
