### PR TITLE
Optimize Document Content

### PR DESCRIPTION
**Pull request by guobinhit**
Purpose
Optimize document content and remove redundancy descriptions.
1. delete a redundant descriptions of event-bus
2. delete a redundant parentheses of futures

References
NONE.

Changes
NONE.

Background Context
Make the content more concise.

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Review by johanandren — APPROVED** [review]
LGTM, thanks

**Comment by guobinhit** [comment]
> LGTM, thanks

I'm glad it's OK.

**Review by raboof — APPROVED** [review]
Thanks!

**Pull request merged**
