### PR TITLE
Wip new docs drewhk

### PR DESCRIPTION
**Pull request by drewhk**
**WORK IN PROGRESS**

Converting docs into Paradox

### CODE REVIEW

**Comment by ktoso** [comment]
Scrolled through a bit, seems good :)

**Comment by patriknw** [comment]
Not much to review I guess. Let's merge soon.
@drewhk Can you add a note here which commit of the rst docs that were converted, so that we can double check that nothing was updated after that.

**Comment by drewhk** [comment]
Ok, so the commit this based on is ad3ef5982c81b522ddbc2a1bc2d09a01eb54ab5c

**Comment by patriknw** [comment]
ok, that means that my streams actor integration improvements are not included https://github.com/akka/akka/commit/aa8c253d141a96b65ac19f781106fa82d457c2c2

**Comment by drewhk** [comment]
Ok, I will rebase and regenerate the files

**Comment by patriknw** [comment]
thanks

**Comment by jonas** [comment]
In case you regenerate with Paradox 0.2.6 and get notes and warning callouts converted, I noticed that pegdown handles formatting inside a little different. Might be just a matter of adding surrounding new lines.

Also I noticed a space before `]` in most links.

**Comment by drewhk** [comment]
Not going to merge this right now, we need to figure out a few other things as well. Most importantly, the available themes for paradox currently don't cut it for our needs (we have _huge_ docs).

**Comment by drewhk** [comment]
Closing this temporarily. Will revisit once we have our theme.

**Pull request closed without merging**
