### PR TITLE
str #19783 backport buffer configuration from and validation in the r…

### PR DESCRIPTION
**Pull request by patriknw**
…ight place

### CODE REVIEW

**Comment by patriknw** [comment]
the failure was in QueueSinkSpec, I think it's unreleated

**Comment by patriknw** [comment]
PLS BUILD

**Comment by patriknw** [comment]
This is a real failure in `QueueSinkSpec`, something is wrong with this backport, or we did something more in master.
It's supposed to be manual backport of #19783 and b4f507c

```
[info] - must work with one element buffer *** FAILED *** (6 seconds, 37 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for Some(2)
[info]   at scala.Predef$.assert(Predef.scala:179)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:338)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:315)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:718)
[info]   at akka.stream.scaladsl.QueueSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$9$$anonfun$apply$mcV$sp$10.apply$mcV$sp(QueueSinkSpec.scala:113)
```

**Comment by patriknw** [comment]
@drewhk do you have any recollection of the above test failure ^

**Comment by drewhk** [comment]
This is likely something trivial. Do you want me to take over?

**Comment by patriknw** [comment]
@drewhk that would be great, but if it turns out to be non-trivial we'll release without it

**Comment by drewhk** [comment]
The QueueSink has been rewritten, I backported that and now it seems to work. I am running thests locally now to double check.

**Comment by drewhk** [comment]
Ok, ActorRefBackpressureSinkStage also fails and it has been rewritten, too. Backporting that too.

**Comment by patriknw** [comment]
awesome, thanks

**Comment by patriknw** [comment]
that failure was WebsocketServerSpec, probably unrelated?

**Comment by patriknw** [comment]
PLS BUILD

**Comment by drewhk** [comment]
Websockets are completely unrelated.

**Comment by drewhk** [comment]
can I merge?

**Pull request merged**
