### PR TITLE
Fix page layout issue on chromium/linux

### PR DESCRIPTION
**Pull request by Falmarri**
https://github.com/akka/akka/issues/20044

Edit: Underlying bug reported here https://bugs.chromium.org/p/chromium/issues/detail?id=595166#c5

### CODE REVIEW

**Comment by ktoso** [comment]
Thanks a lot for looking into it and the fix too!

I looked into it and my OCD kicked in slightly :cry: 
If we do that there's going to be 1px of lines not touching at the top bar:
cursor_and_scala_documentation_ _akka_documentation

I also got my linux notebook to check it over there, on Chromium 47 (I guess that's old though) it looks good still, hm. Now I'm not sure if we should apply this... maybe I'm overthinking it over that 1 px though, let's see what the team thinks.

Thanks so much for jumping in with the PR in any case!

**Comment by Falmarri** [comment]
@ktoso yeah this might be a chromium issue. I hadn't seen this issue before and I use the akka docs almost daily. I did recently upgrade my system and I just noticed it today. I'm on arch linux with chromium Version 49.0.2623.87 (64-bit). I agree that 1px is annoying. I can probably fix it cleaner but the change will be slightly bigger. basically change the navbar and the main content to not use opposing margins to try to line up pixels

**Comment by Falmarri** [comment]
@ktoso removing the overflow:auto seems to work in both firefox and chromium. If someone could test on windows/osx it might be as simple as that.

**Comment by ktoso** [comment]
Removing overflow auto breaks the bottom bar (on firefox, on chrome it was ok):

scala_documentation_ _akka_documentation

**Comment by Falmarri** [comment]
Argh.

**Comment by ktoso** [comment]
I'm starting to lean towards left untouched hm... :(

**Comment by Falmarri** [comment]
What firefox version/os? Without the overflow: auto it works fine on Firefox 45.0

**Comment by Falmarri** [comment]
@ktoso what if you change overflow: auto to overflow: visible. That fixes it for me as well.

**Comment by ktoso** [comment]
AFAICS that would work!
I checked that on firefox/osx and chrome/osx and chromium/linux, seems to work (`overflow: visible`)

**Comment by patriknw** [comment]
LGTM

**Comment by patriknw** [comment]
please squash to one commit

**Comment by Falmarri** [comment]
@patriknw done

**Comment by ktoso** [comment]
Technically commit should include ref to `#20044`, but it's a minor thing I'll merge once back home in some minutes.

**Comment by Falmarri** [comment]
I'll amend my commit

**Comment by ktoso** [comment]
Thanks!

**Pull request merged**
