### PR TITLE
=htc #17494 fix interpreter leak due to unsubscribed websocket handler hole

### LINKED ISSUE #17494: Each incoming connection leaks one ActorInterpreter
As of RC1, an ActorInterpreter leak appears to have been introduced to Akka HTTP - precisely one actor is leaked per each incoming connection.

The following test sets up a simple Akka server; counts the initial number of ActorInterpreters; sends 100 requests and waits for the responses; allows for a 1-second delay; and counts the number of ActorInterpreters again. Under M4, the initial and final counts were both equal to 2; the test passes. Under RC1, the final count is precisely 100 greater than the initial count. The test doesn't pass.

Allowing for a 20-second delay doesn't help.

```scala
package akka.http

import akka.actor._
import akka.http.scaladsl.Http
import akka.http.scaladsl.client.RequestBuilding
import akka.http.scaladsl.model._
import akka.stream.ActorFlowMaterializer
import akka.stream.impl.fusing.ActorInterpreter
import akka.stream.scaladsl.{Flow, Sink, Source}
import org.specs2.matcher.MatchResult
import org.specs2.mutable.Specification
import org.specs2.time.NoTimeConversions
import scala.collection.mutable
import scala.concurrent.duration._
import scala.concurrent.{Await, Future}

class IncomingConnectionActorInterpreterLeakSpec
  extends Specification
  with RequestBuilding
  with NoTimeConversions {

  val defaultTimeout = 20.seconds

  /**
   * A simple server which replies to all requests with 200 OK and mirrors the request's entity (to confirm that it's
   * been streamed properly both ways). We are interested in the server's [[ActorSystem]]
   */
  class TestServer() {

    implicit val actorSystem = ActorSystem("ServerActorSystem")
    implicit val materializer = ActorFlowMaterializer(namePrefix = Some("ServerMaterializer"))

    val testServerFuture = Http().bind("127.0.0.1", 0).to {
      Sink.foreach { incomingConnection =>
        incomingConnection.handleWith(Flow[HttpRequest].map { request =>
          HttpResponse(entity = request.entity)
        })
      }
    }.run()

    val server = Await.result(testServerFuture, defaultTimeout)

    val host: String = server.localAddress.getHostName
    val port: Int = server.localAddress.getPort
  }

  /**
   * A simple test client which sends requets to a particular host and port.
   * We are not interested in its [[ActorSystem]]; there do not appear to be any actor leaks from outgoing connections.
   */
  class TestClient(host: String, port: Int) {

    private implicit val actorSystem = ActorSystem("ClientActorSystem")
    implicit val materializer = ActorFlowMaterializer(namePrefix = Some("clientMaterializer"))

    def sendRequest(request: HttpRequest): Future[HttpResponse] = {

      val connection =
        Http().outgoingConnection(host, port)

      Source.single(request) via connection runWith Sink.head
    }
  }

  "A simple Akka server" should {

    "not leak ActorInterpreters after incoming connections are closed" in {
      // Given
      implicit val testSystem = ActorSystem("TestSystem")
      implicit val materializer = ActorFlowMaterializer()
      
      val server = new TestServer()
      val client = new TestClient(server.host, server.port)

      val entityString = "Test HTTP entity"
      val request = Post(s"http://${server.host}:${server.port}", content = entityString)

      /**
       * We make a request, stream in the response and check that the entity matches what we expect.
       */
      def makeRequestAndCheckResponse(): MatchResult[Future[String]] = {
        client.sendRequest(request)
          .flatMap(_.entity.toStrict(defaultTimeout))
          .map(_.data.utf8String) must
          beEqualTo(entityString).await()
      }

      // When
      /**
       * We make an initial request to ensure all flows are initialized
       */
      makeRequestAndCheckResponse()

      val initialInterpreterCount: Int = countActorsInSystem(server.actorSystem)(classOf[ActorInterpreter])

      /**
       * We make a series of requests. Each of these will leak one [[ActorInterpreter]] in the server's actor system.
       */
      val numberOfRequests = 100
      (1 to numberOfRequests).foreach(_ => makeRequestAndCheckResponse())

      // Then
      /**
       * We wait to allow all streams enough time to complete. In M4, 1 second is enough
       * for the [[ActorInterpreter]] count to fall back to its initial value.
       */
      val cooldownAllowance = 1.seconds
      Thread.sleep(cooldownAllowance.toMillis)

      val finalInterpreterCount = countActorsInSystem(server.actorSystem)(classOf[ActorInterpreter])

      /**
       * In RC1, this will fail: the difference between the final and initial counts
       * will be precisely equal to the [[numberOfRequests]].
       */
      finalInterpreterCount must not beGreaterThan initialInterpreterCount
    }
  }

  /**
   * A method that counts the actors of each type inside a given actor system.
   */
  def countActorsInSystem(system: ActorSystem) = {

    val actorCountsByClass = new mutable.Map.WithDefault[Class[_ <: Actor], Int](mutable.Map.empty, _ => 0)

    def walk(ref: ActorRef): Unit = {
      ref match {
        case c: ActorRefWithCell =>
          c.underlying match {
            case ac: ActorCell =>
              if (ac.actor != null) {
                val actorClass: Class[_ <: Actor] = ac.actor.getClass
                actorCountsByClass.put(actorClass, actorCountsByClass(actorClass) + 1)
              }
              c.children.foreach(walk)

            case unrecognizedCell: Cell =>
              unrecognizedCell.childrenRefs.children.foreach(walk)
          }
        case _ =>
      }
    }

    walk(system.asInstanceOf[ActorSystemImpl].lookupRoot)

    actorCountsByClass
  }
}
```

### PR DESCRIPTION
**Pull request by jrudolph**
The solution is to install a dummy handler when the connection is closed while still being in http mode.

Fixes #17494 and also introduces a few `assertAllStagesStopped` as suggested in #17524.

/cc @sirthias

### CODE REVIEW

**Comment by drewhk** [comment]
LGTM

**Comment by patriknw** [comment]
LGTM, I guess

**Comment by drewhk** [comment]
Is there a test that fails without the fix?

**Comment by jrudolph** [comment]
Yes, the tests in ClientServerSpec.scala fail since I added `assertAllStagesStopped`.

**Comment by drewhk** [comment]
OK

**Pull request merged**
