### PR TITLE
Update stream-composition.rst

### PR DESCRIPTION
**Pull request by netcomm**
"nestedFlow will inherit from nestedSource",should be "from nestedSink"?

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @netcomm,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by ktoso** [comment]
The same typo needs fixing in the scala file: akka-docs-dev/rst/scala/stream-composition.rst 
Would you mind fixing it as well (and sign the cla so we can merge) thanks!

**Comment by netcomm** [comment]
done!

**Comment by ktoso** [comment]
Thanks!

**Pull request merged**
