### PR TITLE
Implement issue #27745 add mdc support in logging filter

### PR DESCRIPTION
**Pull request by gbrd**
Implement issue #27745 : add mdc support in logging filter

### CODE REVIEW

**Comment by patriknw** [comment]
@gbrd In master (Akka 2.6.0-M8) we have switched to using SLF4J directly so I'm not sure it's worth changing this in the 2.5 branch. Is it critical for you to have it in your production system? Can you update to 2.6.0-M8 instead?

**Comment by gbrd** [comment]
Not critical, but it would be convenient ;). 
Did all akka switched to slf4j API ? or only akka-typed ?

**Comment by patriknw** [comment]
> Did all akka switched to slf4j API ? or only akka-typed ?

Only Typed.

**Comment by gbrd** [comment]
Ok, thus, maybe I can remove modifications for typed and rebase the PR on master (2.6) ?

**Review by patriknw — COMMENTED** [review]
ah, I thought it was only adding something to Typed, but I'm not fully convinced that we should support this. Accessing the MDC ThreadLocal has performance overhead and that might not be something we want in the isEnabled methods

**Comment by gbrd** [comment]
So, it prevent using MDC in turbo filters with akka... 
(MDC in turbo filter example : http://logback.qos.ch/xref/ch/qos/logback/classic/turbo/MDCFilter.html)

But I can understand that in case of akka, MDC is not already in thread context, and it has performance cost (but nothing blocking, just CPU, am I right ?). 

What about checking if MDC is empty before calling withMDC() ?  Or maybe a configuration parameter to enable the feature ?

**Comment by patriknw** [comment]
I don't think this is worth adding and the performance trade-off is difficult to motivate, sorry.

**Pull request closed without merging**
