### PR TITLE
=str #17924: Make IntelliJ IDEA sbt import work again

### PR DESCRIPTION
**Pull request by drewhk**
This does not solve https://github.com/akka/akka/issues/17924 completely, since I don't know what the commented out line did. 

@jrudolph if that was a feature that you don't want to see gone, then please fix it as I have no clue what it does and why. SBT integration with IDEA is rather important and I don't want to use gen-idea again.

### CODE REVIEW

**Comment by ktoso** [comment]
LGTM from my side.
I guess this is to speed up the build slightly.

**Comment by drewhk** [comment]
This resurfaced while updating to IDEA 15 and the new project simply refused to create scala files for me. I didn't want to use gen-idea again though.

**Comment by 2beaucoup** [comment]
the original problem of the ticket was https://github.com/drewhk/akka/blob/wip-17924-make-intellij-import-work-drewhk/project/AkkaBuild.scala#L1127

**Comment by drewhk** [comment]
Hm, you linked to line 1110 in the ticket, and that is what I commented out. I can try L1127.

**Comment by 2beaucoup** [comment]
This line seems to have moved in release-2.3-dev. Should have linked to a a version hash instead.

**Comment by drewhk** [comment]
Ah I see. But commenting out made the import pass interestingly :)

**Comment by drewhk** [comment]
will investigate this later then

**Comment by 2beaucoup** [comment]
Do you have `AKKA_BUILD_JAVA8_HOME` set or does one of the paths match on your machine?

**Comment by drewhk** [comment]
no

**Comment by drewhk** [comment]
Now it removes the *real* offending line.

**Comment by drewhk** [comment]
And I fixed the Zip issue already here: https://github.com/akka/akka/pull/18904

**Pull request merged**
