### PR TITLE
Improve Getting Started Guide Part 3 for writing a first Actor test

### PR DESCRIPTION
**Pull request by olimination**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @olimination,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by raboof** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]
The package name change is good, and it indeed seems useful to cross-link to the more complete example in the quickstart.

**Comment by johanandren** [comment]
Fixes #25193

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
