### PR TITLE
Deprecate LevelDB

### PR DESCRIPTION
**Pull request by johanandren**
In preparation of moving into the testing infra (or deleting it completely) at some distant future point in time.

Refs #28938
Refs #25883
Refs #25441
Somewhat refs #24394 and refs #16525

By removing the tests it also:
Refs #30087

### CODE REVIEW

**Review by patriknw — COMMENTED** [review]
yes, why not?
If someone really uses it they could revive it as a separate community project.

What we could do rather immediately is to remove all the duplicate testing that we have for inmem and leveldb. Should save us some CI time.

**Comment by patriknw** [comment]
What I meant was duplicate tests like this: https://github.com/akka/akka/blob/master/akka-persistence/src/test/scala/akka/persistence/PersistentActorStashingSpec.scala#L312-L315

Most of the unit/tck tests leveldb itself should probably remain, so we don't break anything (while it's deprecated but not removed yet).

**Comment by johanandren** [comment]
Too fast, to furious!

**Review by patriknw — APPROVED** [review]
LGTM

**Review by raboof — APPROVED** [review]
Makes sense to (eventually) move this out - with the wide availability of containers it has become much easier to use a 'real' persistence plugin for tests that cannot use 'inmem'.

**Pull request merged**
