### PR TITLE
Update image links for remoting

### PR DESCRIPTION
**Pull request by jonaslan**
Noticed the image links were broken.

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Comment by raboof** [comment]
Hi @jonaslan, good catch, thanks! I've added a redirect rule on the webserver to 'fix' these links for now, but it would indeed be good to fix them properly in the sources. I'm afraid all image links have the same problem - would you be up for it to update the other ones as well?

**Comment by jonaslan** [comment]
sure, i'll give it a look

**Comment by jonaslan** [comment]
That should be all, I think

**Review by raboof — APPROVED** [review]
Excellent! Thanks a lot, very useful contribution.

**Comment by raboof** [comment]
(my workaround lead to 'mixed content' warnings, I fixed that but it might take [a couple of hours](https://support.cloudflare.com/hc/en-us/articles/200168326-Are-301-and-302-redirects-cached-by-Cloudflare-) for the cloudflare caches to pick that up)

**Review by johanandren — APPROVED** [review]
LGTM, thanks a bunch!

**Pull request merged**
