### PR TITLE
+htp #20705 allows javadsl creating custom rejections

### PR DESCRIPTION
**Pull request by ktoso**

### CODE REVIEW

**Comment by ktoso** [comment]
FYI @Hawstein, IMO that's enough and passes tests.

**Comment by ktoso** [comment]
Resolves #20705

**Comment by Hawstein** [comment]
I think that is OK, too!

**Comment by johanandren** [comment]
LGTM

**Comment by johanandren** [comment]
yay

**Comment by ktoso** [comment]
release the kraken

**Pull request merged**
