### PR TITLE
=str #16982 Fix supervision bug when more than one resume/restart

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by bantonsson** [comment]
LGTM

**Comment by drewhk** [comment]
LGTM

**Comment by patriknw** [comment]
@drewhk @rkuhn I have removed the wrong lines in the `InterpreterSupervisionSpec`, see 8b54c7c

**Comment by rkuhn** [comment]
“Why, oh why did you remove the _wrong_ lines?”

Nah, all good :-)

**Comment by patriknw** [comment]
Refs #16982

**Pull request merged**
