### PR TITLE
Fix regression in Cluster Singleton

### PR DESCRIPTION
**Pull request by patriknw**
- When the test fails the node is removed from the membership
  twice, which triggers two OldestChanged cycles, but in
  the 2.4.9 change https://github.com/akka/akka/pull/21152/files#diff-f0ae95c926a050aecf45dba3e08d1c77L669
  the singleton manager always goes to End (stop) when it has been Oldest
- This fix restores the previous behavior for this scenario

### CODE REVIEW

**Comment by patriknw** [comment]
I will also investigate if the double removal is "normal" or if we should prevent that somehow.

**Comment by patriknw** [comment]
I investigated the reason for the double removal.

* The test has two Joining nodes, node-4 and node-5 and two old Up node-1 and node-3.
* the oldest node-1 is killed
* node-1 is auto-downed and removed as expected
* node-4 receives a Gossip that is in conflict its local
  * the local contains node-1 Up, the remote doesn't contain node-1, since it was removed
  * the merge for that means that node-1 Up wins and that adds node-1 back to the membership
  * note that if node-1 had status Down or Exiting it would not come back

The reason node-1 is removed without node-4 and node-5 seeing it as Down is that Joining nodes are excluded in the `convergence` rule (for other good reasons).

I don't see an easy way to improve that part without introducing some kind of removed tombstones. I don't think it's a big deal that the removal was reverted. It's will only happen under rare circumstances and we are supposed to handle it by removing it again. Therefore I don't think it's worth improving it.

**Comment by patriknw** [comment]
Refs #21236

**Comment by johanandren** [comment]
LGTM. Thanks for the detailed explanation!

**Comment by patriknw** [comment]
merged so that we get master stable again

**Pull request merged**
