### PR TITLE
Fix type of tweets Source

### PR DESCRIPTION
**Pull request by prascuna**
# authors-filter-map won't compile otherwise

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @prascuna,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
Thanks a lot, great catch!

(note: this is due to the fact that actual impl is `val tweets = Source ...`, and the one for sample here is just a mock).

We should fix this differently – remove Example0, and write:

```scala
//#tweets-source
  val tweets: Source[Tweet, NotUsed] 
  //#tweets-source
  = Source(
    Tweet(Author("rolandkuhn"), System.currentTimeMillis, "#akka rocks!") ::
 
```

on line 34.

Would you be able to change (or submit a new one) PR doing that @prascuna?

**Comment by prascuna** [comment]
Done. Thanks for the hint!

**Comment by ktoso** [comment]
Looks great, thanks!
Let's let the validator do it's job and merge.

**Comment by ktoso** [comment]
OK TO TEST

**Pull request merged**
