### PR TITLE
Fixes minor documentation issue

### PR DESCRIPTION
**Pull request by timcharper**
FlowOps.splitAfter seeAlso FlowOps.splitAfter seeAlso FlowOps.splitAfter etc.

### CODE REVIEW

**Comment by ktoso** [comment]
Thanks @timcharper!
It's also missing on `javadsl.Flow` on line 803, can you add a reference there as well?

I checked the other places and it's OK there.

**Comment by ktoso** [comment]
It would also be great if you could name the commit using our commit message style, i.e. something like `=str fixes missing cross reference in scaladoc`

**Comment by timcharper** [comment]
@ktoso done

**Comment by ktoso** [comment]
Thanks!

**Pull request merged**
