### PR TITLE
[rebased] =cls #18762 fix graceful shutdown of empty region

### PR DESCRIPTION
**Pull request by ktoso**
Rebased #18805 so we can merge right away; thinking about release schedule so we can push this out now.

### CODE REVIEW

**Comment by ktoso** [comment]
Will merge after validation passes.

**Comment by ktoso** [comment]
PLS BUILD

**Comment by patriknw** [comment]
LGTM

**Comment by ktoso** [comment]
Thanks for checking @patriknw !

**Comment by ktoso** [comment]
Resolves #18762

**Pull request merged**
