### PR TITLE
update to Scala 2.11.11 and 2.12.2

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by johanandren** [comment]
```com.typesafe.genjavadoc#genjavadoc-plugin_2.11.11;0.10: not found``

**Comment by ktoso** [comment]
And the same will be needed for for 2.12.2 I guess, related ticket: https://github.com/typesafehub/genjavadoc/issues/100 
AFAIR needs release for specific scala versions; can do that

Did it for 2.12.2: https://github.com/typesafehub/genjavadoc/pull/101
Can follow up for the 2.11 in my morning.

**Comment by patriknw** [comment]
PLS BUILD

**Comment by patriknw** [comment]
fixed missing mima filter for 2.5.0
and compilation error in sharding (yeah, there is a reason why I dislike wildcard imports)

**Comment by patriknw** [comment]
PLS BUILD

**Pull request merged**
