### PR TITLE
Upgrade camel-core dependency to 2.17.7 (backport)

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Review by ktoso — COMMENTED** [review]
LGTM

**Review by ktoso — APPROVED** [review]

**Comment by ktoso** [comment]
Huh `.20` already, wow ;)

**Review by johanandren — APPROVED** [review]

**Comment by patriknw** [comment]
paradox was included in a build step, should be in `validatePullRequest` instead, removed for now

**Comment by patriknw** [comment]
PLS BUILD

**Pull request merged**
