### PR TITLE
=clu fix cosmetic in ClusterMessageSerializer

### PR DESCRIPTION
**Pull request by He-Pin**

### CODE REVIEW

**Comment by patriknw** [comment]
OK TO TEST

**Comment by patriknw** [comment]
LGTM, not really needed, but thanks

**Comment by hepin1989** [comment]
@patriknw yes but you mentioned it  on another PR,so keep it consistent

**Comment by rkuhn** [comment]
LGTM :-)

**Comment by patriknw** [comment]
failure was unrelated, looking into that

**Pull request merged**
