### PR TITLE
Replace Lambda with Method reference

### PR DESCRIPTION
**Pull request by nik-kashi**

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Yeah I guess it could be seen as more idiomatic; though it's less visible what params are acessible then, so I'm not 100% convienced.

**Comment by mohsenkashi** [comment]
@ktoso 
Your reason is convincing enough!

**Comment by ktoso** [comment]
Thanks a lot for the contrib though :-) If you find anything worth improving in the docs please PR :)

**Pull request closed without merging**
