### PR TITLE
Typed docs: include the import in the code snippet where it is used

### PR DESCRIPTION
**Pull request by ennru**
It shows quite a bit further down since before.

https://doc.akka.io/docs/akka/current/typed/coexisting.html

### CODE REVIEW

**Review by helena — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
unrelated test failure https://github.com/akka/akka/issues/26614

**Comment by patriknw** [comment]
PLS BUILD

**Comment by patriknw** [comment]
that has been fixed in master now so rebuilding

**Comment by patriknw** [comment]
PLS BUILD

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
