### PR TITLE
doc: Diagrams for intro and interaction examples

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Review by chbatey — APPROVED** [review]
They look nice

**Review by johanandren — APPROVED** [review]
Great 👍

**Comment by raboof** [comment]
Good to have!

**Comment by paltaie** [comment]
Just wondering what tool(s) you guys used to produce the diagrams?

**Comment by patriknw** [comment]
It's just Keynote

**Comment by paltaie** [comment]
Great; thanks @patriknw!

**Pull request merged**
