### PR TITLE
+per #18299 allow registering user-created instances of EventAdapters

### PR DESCRIPTION
**Pull request by ktoso**
Refs https://github.com/akka/akka/issues/18299

### CODE REVIEW

**Comment by patriknw** [comment]
Why do we need this?
How do we prevent race conditions when starting up (e.g. how do we make sure that user code for registering adapters is run before persistent actors managed by cluster sharding are started)?

**Comment by Fristi** [comment]
@patriknw I see the problems of registering the adapters at runtime. Isn't it possible to have a fluent builder API upon creating an actor system to register them via code, or is it not the right place to do for some reason? I can imagine this is not trivial to do, but configuring serializers and adapters by configuration requires a lot of boilerplate (can't abstract over it) and it is not compiled (no static checks).

**Comment by patriknw** [comment]
I think we have to start out simple here. Configuration of event adapters is in line with how other such things are defined in Akka.

**Comment by patriknw** [comment]
@ktoso do you agree?

**Comment by ktoso** [comment]
I'm OK with dropping this PR. Event adapters should usually be something one thinks about long-term-ish anyway. At run-time created adaptation code can reside inside a given adapter anyway, so it's possible to create adapters inside a "MyDynamicAdapter" already, without exposing so much complexity in API.

**Comment by patriknw** [comment]
good point about that the dynamic/advanced parts can reside inside a more general adapter

**Pull request closed without merging**
