### PR TITLE
=doc clarify akka.actor.Status.Success usage with Source.actorRef

### PR DESCRIPTION
**Pull request by timcharper**
Related to https://github.com/akka/akka/issues/20421, and continuing the effort from 34d51dcd001a3917bda3272751195e9f0e863b02

### CODE REVIEW

**Comment by ktoso** [comment]
Needs to be copied over to `/rst/java/stream/stages-overview.rst`, after that it's LGTM, thanks!

**Comment by timcharper** [comment]
@ktoso I'll remember one of these times! Thanks for the reminder. Fixed.

**Comment by ktoso** [comment]
With great libraries comes great responsibility, or did I mix that up... :)
Thanks, LGTM from my side.

**Comment by patriknw** [comment]
Why not accepting the companion also?

**Comment by timcharper** [comment]
@patriknw I was thinking that the route Akka would go would be to fix it in `2.5.x` because changing the inheritance of `Status$.Success$` could be a backwards incompatible change, and I think it could be confusing, also.

I'm concerned that accepting both `Status$.Success$` and `Status$.Success(...)` will introduce additional confusion for users (what if they try to match it? What if other libraries send it around? Which version will they send?) I'd advocate for a solution that reduces surprise as much as possible. Be narrow in what you accept and what you emit.

I'm almost inclined to say, for now, let's clarify the documentation and keep things as is. It's sufficient to control the surprise, and helps reduce the number of things that Actor accepts. Maybe put a TODO to revisit the possibility of converting `Status$.Success$` to extend `Status$.Success`.

**Comment by patriknw** [comment]
ok

**Comment by timcharper** [comment]
TIL if you define a companion object for a case class, and make it extend the Function type that matches the case class parameters, then the `.tupled` method (and others) will be preserved.

**Comment by timcharper** [comment]
If you still feel like the best thing to do is add another receive case, and haven't been persuaded by my comments, I'll happily push another pull request with the other solution.

**Comment by ktoso** [comment]
I vote for supporting the companion, yes 👍 (Seems @patriknw in the ticket https://github.com/akka/akka/issues/20421#issuecomment-216108169 as well)

**Comment by patriknw** [comment]
I don't have a strong opinion, but I can't see that it would hurt to do the right thing for the companion also.

**Comment by drewhk** [comment]
+1 for handling the companion, too.

**Comment by timcharper** [comment]
I'll close and open a new one

**Pull request closed without merging**
