### PR TITLE
#22030 Lazy sink wait for init agolubev

### PR DESCRIPTION
**Pull request by agolubev**
ref #22030 
It's problematic to write good test for this case - so I left one from #22018

### CODE REVIEW

**Comment by agolubev** [comment]
Remote test failed

**Review by drewhk — APPROVED** [review]
LGTM

**Review by johanandren — APPROVED** [review]
LGTM!

**Comment by johanandren** [comment]
PLS BUILD

**Comment by ktoso** [comment]
Awesome, thanks!

**Comment by agolubev** [comment]
That's great. Thank you.

**Pull request merged**
