### PR TITLE
=act #17415 fix concurrency bug in CircuitBreaker

### PR DESCRIPTION
**Pull request by patriknw**
- transition did not account for concurrent transistions

### CODE REVIEW

**Comment by drewhk** [comment]
Do you want to include it in 2.3.11? Since I aborted the release, this can get in still.

**Comment by drewhk** [comment]
ok

**Comment by rkuhn** [comment]
LGTM

**Comment by patriknw** [comment]
I guess there will be no more reviews.

**Comment by patriknw** [comment]
Refs #17415

**Pull request merged**
