### PR TITLE
Fix memory leak in AddressTerminatedTopic, refs #19672

### PR DESCRIPTION
**Pull request by keredin**
Hi, this is commit to fix issue from ticket "Possible memory leak via AddressTerminatedTopic when watching actor #19672"

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @keredin,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by drewhk** [comment]
OK TO TEST

**Comment by drewhk** [comment]
Please sign the CLA. It is a very easy thing to do, you can use your Github account to do it online.

**Comment by patriknw** [comment]
LGTM

**Comment by sarxos** [comment]
Hi @patriknw, is ```akka.stream.scaladsl.GraphMergeSortedSpec``` test fail caused by this change or is this rather some random stuff? I did quick look into the ```GraphMergeSortedSpec``` and see no connection with this PR.

**Comment by patriknw** [comment]
yeah, that should not be related

**Comment by patriknw** [comment]
PLS REBUILD

**Comment by johanandren** [comment]
PLS BUILD

**Comment by johanandren** [comment]
LGTM!

**Comment by drewhk** [comment]
LGTM

**Comment by patriknw** [comment]
Cherry-pick backport to 2.3: https://github.com/akka/akka/pull/19720

**Pull request merged**
