### PR TITLE
harden OutputStreamSourceSpec, #20676

### PR DESCRIPTION
**Pull request by patriknw**
On my local it fails in same way as jenkins with timeout 2 seconds, so I think it just needs some more time.

### CODE REVIEW

**Comment by patriknw** [comment]
Refs #20676

**Comment by patriknw** [comment]
hm, 5 seconds was not enough, or there is actually something wrong

**Comment by patriknw** [comment]
I think I know what it is, new fix coming soon

**Comment by patriknw** [comment]
Now with a proper fix. The reason it started failing was that we started using the `IODispatcher`, which is a thread pool executor that does:

```
[info]   	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@7ec62b61
[info]   	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
[info]   	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
[info]   	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
[info]   	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
```

That is not the locks/blocking we are interested in, so I changed the test to look for more specific locks originating from the stage.

**Comment by ktoso** [comment]
LGTM

**Comment by drewhk** [comment]
LGTM

**Pull request merged**
