### PR TITLE
Fix typo in ShardingCompileOnlyTest.java

### PR DESCRIPTION
**Pull request by jostly**
## Purpose

Fix small typo in docs for akka typed cluster sharding

## Changes

Correct entity id in ShardingCompileOnlyTest.java

### CODE REVIEW

**Review by raboof — APPROVED** [review]
Good observation ;)

**Comment by raboof** [comment]
OK TO TEST

**Review by chbatey — APPROVED** [review]
LGTM

**Comment by jostly** [comment]
I've signed the CLA

**Review by johanandren — APPROVED** [review]

**Comment by johanandren** [comment]
Manually verified @jostly is in the CLA db, thanks!

**Pull request merged**
