### PR TITLE
update grammar and code highlighting

### PR DESCRIPTION
**Pull request by thefourtheye**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @thefourtheye,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by raboof** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]
Thanks!

**Review by ktoso — APPROVED** [review]
Thanks

**Pull request merged**
