### PR TITLE
Discover Linux java versions with full versions

### PR DESCRIPTION
**Pull request by raboof**
Refs #25298

### CODE REVIEW

**Review by chbatey — APPROVED** [review]
Works for me, thanks @raboof

**Comment by chbatey** [comment]
We should port this to SBT. Let me know if you plan to do it @raboof otherwise i'm happy to

**Comment by raboof** [comment]
I added it to https://github.com/sbt/sbt/pull/4245

**Review by patriknw — APPROVED** [review]
LGTM, but I haven't tested anything

**Review by ktoso — APPROVED** [review]
No idea... maybe good?

**Comment by GrafDiffusore** [comment]
Hi,

It might be this change broke compilation of Akka for me -- my JDK is manually downloaded and put into `/home/user/bin` directory and added to `PATH` (and same goes for `scala` and `sbt` as well). Here's output of `ls -1 /home/user/bin`:
```
jdk1.8.0_162
jdk8 # symlink to above, used in PATH and JAVA_HOME
sbt   # symlink to below, used in PATH and SBT_HOME
sbt-1.1.6
scala   # symlink to below, used in PATH and SCALA_HOME
scala-2.12.6
```
Is it possible to run, e.g.,  `java -v` or `scala -version` process to discover version?

**Comment by chbatey** [comment]
Hi @GrafDiffusore can you raise a bug for that?

**Comment by GrafDiffusore** [comment]
Hi,
Filed #25423. This is my first issue filed, thank you for suggestion!

**Comment by ktoso** [comment]
Thanks for reporting!

**Pull request merged**
