### PR TITLE
+doc #17972 added spray migration guide

### PR DESCRIPTION
**Pull request by meln1k**
Migration guide based on https://tech.zalando.de/blog/migrating-spray-akka-http/ article.

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Comment by johanandren** [comment]
Looks great! Thanks @meln1k !

**Comment by ktoso** [comment]
Great, thanks a lot for the great blogpost and contributing back!
We'll merge very soon :) Should be in the next release.

**Comment by ktoso** [comment]
We should then make the "current" code snippets be actual code and use includecode on it.

**Comment by johanandren** [comment]
@ktoso is that something that should be done in this PR or can we merge?

**Comment by ktoso** [comment]
Let's merge, we can move the snippets to actual code rather than snippets after merging.

**Comment by ktoso** [comment]
Thanks @meln1k! It'll make it into today's release

**Pull request merged**
