### PR TITLE
Adding protobuf serialization for SendToOneSubscriber (akka cluster p…

### PR DESCRIPTION
**Pull request by n1ko-w1ll**
…ubsub) #21625

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
LGTM, AFAICS - thanks

**Review by patriknw — COMMENTED** [review]
very good, just one minor nitpick

**Comment by n1ko-w1ll** [comment]
Damn. Originally I used the field number 1 but was confused because other payload fields have always the number 3 even if there is no 2. Thanks for pointing out, I changed it.

**Comment by n1ko-w1ll** [comment]
btw after executing the protobuf build step, the unrelated file akka-persistence/src/main/java/akka/persistence/serialization/MessageFormats.java is changed as well. There is the following added:
```
       /**
        * <code>optional string timeout = 2;</code>
+       *
+       * <pre>
+       *not used in new records from 2.4.5
+       * </pre>
        */
```
I removed this file from my commit, as it seems totally unrelated to my change.

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
