### PR TITLE
Adjust the score for the serialization vulnerability

### PR DESCRIPTION
**Pull request by patriknw**
* and some additional clarifications

### CODE REVIEW

**Review by drewhk — APPROVED** [review]
LGTM

**Comment by ktoso** [comment]
LGTM

**Comment by ktoso** [comment]
Please forward port :)

**Comment by patriknw** [comment]
updated, after one more iteration the conclusion is that we should use `AC:M`

**Comment by ktoso** [comment]
Yeah this is good too 👍

**Pull request merged**
