### PR TITLE
#22889 Use port 0 for address which is supposed to never be bound

### LINKED ISSUE #22889: FAILED: akka.stream.javadsl.TcpTest mustReportClientConnectFailure
https://jenkins.akka.io:8498/job/akka-nightly/4386/testReport/junit/akka.stream.javadsl/TcpTest/mustReportClientConnectFailure/

```
Error Message

java.lang.AssertionError: Expected StreamTcpException, but nothing was reported
Stacktrace

      java.lang.AssertionError: Expected StreamTcpException, but nothing was reported
      at org.junit.Assert.fail(Assert.java:88)
      at org.junit.Assert.assertTrue(Assert.java:41)
      at akka.stream.javadsl.TcpTest.mustReportClientConnectFailure(TcpTest.java:121)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:497)
      at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
      at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
```

### PR DESCRIPTION
**Pull request by 2m**
Fixes #22889 by using 0 for a port that is supposed to be not bound.

Note that 0 for binding means any free port. But 0 for connecting always results in `ECONNREFUSED`.

https://unix.stackexchange.com/questions/180492/is-it-possible-to-connect-to-tcp-port-0

### CODE REVIEW

**Comment by 2m** [comment]
I should probably migrate from `TestUtils` to `SocketUtils` as well while I am at it.

**Review by johanandren — APPROVED** [review]
LGTM

**Review by ktoso — APPROVED** [review]
LGTM once moved to SocketUtils

**Comment by 2m** [comment]
Migrated to `SocketUtil`.

**Pull request merged**
