### PR TITLE
=htt #17353 Reduce verbosity of logging on pool shutdown

### PR DESCRIPTION
**Pull request by hakuch**
Please see the corresponding discussion at https://github.com/akka/akka/issues/17353 .

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @hakuch,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
LGTM, thanks!

**Comment by hakuch** [comment]
@ktoso Do you need anything else from me to get this merged?

**Comment by ktoso** [comment]
All good, just wanted another LGTM before we merge (we usually merge after at least 2 people have a look at something).

**Comment by johanandren** [comment]
LGTM

**Comment by ktoso** [comment]
Let's go ahead with merging ;)
The reason I was hesitant is that I see calling shutdown as something that very rarely happens.

**Comment by ktoso** [comment]
Thanks for contributing @hakuch!

**Pull request merged**
