### PR TITLE
Use Java serialization for typed ActorRef

### LINKED ISSUE #24135: Support Java serialization for Akka Typed
Currently typed `ActorRef`s cannot be serialized with Java serialization. While Java serialization certainly is discouraged for real-world production cases, it is very convenient for demos and teaching. Therefore I suggest it should be enabled.

### PR DESCRIPTION
**Pull request by richardimaoka**
Closes #24135 

Checked the behavior with this code snippet, 
https://gist.github.com/richardimaoka/b413e0ca3095b04c434c59da577ac4e3

and confirmed with IntelliJ's debugger that `writeReplace` was indeed used:

image

### CODE REVIEW

**Review by johanandren — COMMENTED** [review]
Looks good, but missing test coverage.

**Comment by richardimaoka** [comment]
I added anther test case to the existing MiscMessageSerializerSpec.scala and renamed the file, but the diff isn't showing this nicely. So let me paste the link to a commit https://github.com/akka/akka/pull/24306/commits/5a9f0097d0eb4172a3310320388ab784eddb6f7c to see what I added.

Please let me know if I should rather add another test spec file.

**Review by johanandren — APPROVED** [review]
LGTM

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
