### PR TITLE
=str #22463 fix GraphStageLogicSpec

### PR DESCRIPTION
**Pull request by jrudolph**

### CODE REVIEW

**Comment by ktoso** [comment]
Refs #22463

**Review by ktoso — APPROVED** [review]
Hmmm hard to see from the patch why this solves things; but LGTM I guess.

Is it because we kind of construct things by hand here?

**Review by patriknw — APPROVED** [review]
ok

**Review by johanandren — APPROVED** [review]
LGTM

**Comment by jrudolph** [comment]
Already fixed by https://github.com/akka/akka/commit/2ae8c53cfc5b63a6f5b65c7634750a9191e2ed7d.

**Pull request closed without merging**
