### PR TITLE
!clt #13523 Don't expose sender in cluster client replies

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by patriknw** [comment]
Refs #13523

**Comment by hepin1989** [comment]
seems I need update my code:) once I upgrade to RC1

**Comment by ktoso** [comment]
I'm not completely up to date with the reasoning for this change... Why is it bad to expose the ActorRef?

**Comment by patriknw** [comment]
The user should opt-in to talking directly from client to an actor in the cluster. Previosly it was too easy to just use the sender without thinking about the consequences.

**Comment by ktoso** [comment]
Hmm, I see... makes sense I guess. LGTM

**Pull request merged**
