### PR TITLE
Adding AbstractFSMWithStash Java API

### PR DESCRIPTION
**Pull request by nraychaudhuri**

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
LGTM from my side

**Comment by rkuhn** [comment]
LGTM, but shouldn’t we have docs for all these as well?

**Comment by rkuhn** [comment]
We’ll need to figure out the Java documentation story for Akka 2.4 (in the light of Java 8), will add docs then.

**Pull request merged**
