### PR TITLE
additional hardening of RemoteReDeploymentSpec, #23838

### PR DESCRIPTION
**Pull request by patriknw**
Refs #23838

### CODE REVIEW

**Review by chbatey — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
javac NPE, pretty annoying to be honest

**Comment by patriknw** [comment]
and it's probably wrong to blame javac, I'm pretty sure it's sbt that is using it wrong

**Comment by patriknw** [comment]
PLS BUILD

**Review by johanandren — APPROVED** [review]
LGTM

**Pull request merged**
