### PR TITLE
=doc fix akka-http timeouts documentation #21214

### PR DESCRIPTION
**Pull request by lukasz-kusek**
change akka.http.http-connection-pool -> akka.http.host-connection-pool

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @lukasz-kusek,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
Thanks a lot, weird silly typo.

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
and LGTM :)

**Comment by johanandren** [comment]
Refs #21214

**Comment by johanandren** [comment]
LGTM, thanks!

**Comment by 2m** [comment]
LGTM

**Pull request merged**
