### PR TITLE
Fix dead link in cluster.md

### PR DESCRIPTION
**Pull request by FredrikMeyer**
Came over this while reading the documentation. A Google search found a working link.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @FredrikMeyer,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by FredrikMeyer** [comment]
I have now signed the CLA.

**Comment by raboof** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]
Thanks for spotting and finding a working URL!

**Review by 2m — APPROVED** [review]

**Pull request merged**
