### PR TITLE
Stop TCP connection when client disconnects #26453

### PR DESCRIPTION
**Pull request by JeansHH**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @JeansHH,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by raboof** [comment]
refs #26453

**Comment by raboof** [comment]
OK TO TEST

**Comment by JeansHH** [comment]
PR can be closed

**Pull request closed without merging**
