### PR TITLE
fix little typo

### PR DESCRIPTION
**Pull request by marcpiechura**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @Silv3rcircl3,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by patriknw** [comment]
OK TO TEST

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
thanks, @Silv3rcircl3

**Pull request merged**
