### PR TITLE
Distributed data typo documentation

### PR DESCRIPTION
**Pull request by Camsteack**
Fix typo in distributed data documentation related to write behind configuration.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @Camsteack,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by chbatey** [comment]
OK TO TEST

**Review by chbatey — COMMENTED** [review]
LGTM

**Review by raboof — APPROVED** [review]
Good catch!

**Review by patriknw — APPROVED** [review]
LGTM, thanks for fixing

**Pull request merged**
