### PR TITLE
cleanup logging in persistence tests, #24687

### PR DESCRIPTION
**Pull request by patriknw**
Refs #24687

### CODE REVIEW

**Comment by patriknw** [comment]
Draft PR since I want to merge all my other persistence test PRs first (will probably need rebase).

**Review by johanandren — APPROVED** [review]
Good!

**Comment by patriknw** [comment]
TODO: add more references to that EventFilter ticket, such as in comments "needed for the untyped event filter"

**Review by chbatey — APPROVED** [review]

**Comment by patriknw** [comment]
PLS BUILD

**Pull request merged**
