### PR TITLE
=act #19496 add sender information in LoggingReceive

### PR DESCRIPTION
**Pull request by ktoso**
Revives https://github.com/akka/akka/issues/19496
There's basically one way to do it and I thought it made sense to add (had the tab open for some reason with the old PR)

### CODE REVIEW

**Comment by patriknw** [comment]
LGTM

**Comment by ktoso** [comment]
Failure was unrelated: https://github.com/akka/akka/issues/19464

**Comment by johanandren** [comment]
PLS BUILD

**Comment by johanandren** [comment]
LGTM

**Pull request merged**
