### PR TITLE
[doc] remove unsed TypKey form examples

### PR DESCRIPTION
**Pull request by robstoll**

### CODE REVIEW

**Review by raboof — COMMENTED** [review]
It is not used in this file, but (as the travis output make clear) it is used when actually using the sharding. Seems useful to keep it, and keep showing it in the docs so it remains a 'complete' example?

**Comment by raboof** [comment]
OK TO TEST

**Comment by robstoll** [comment]
I see, it is used in a Spec. That's something which is hard to grasp via mobile phone.
Nevertheless, as far as I see (searching via GitHub) the AccountExampleSpec is not referenced in any documentation. Maybe a mistake on its own?
I would still remove it, the persistence examples are not about sharding in particular. I would not add this aspect to the example to keep things minimal for new users (like me).
Btw. another sample showing EntityTypeKey is used in https://doc.akka.io/docs/akka/current/typed/cluster-sharding.html -> or in other words, this aspect seems to be covered there.

What do you think:
- move the TypeKey to AccountExampleSpec?
- remove the AccountExampleSpec?
- drop this PR?
- other ideas?

**Comment by raboof** [comment]
These examples are referenced used on the Persistence style recommendation page. Since Persistence is very commonly used with Sharding, and that TypeKey is needed for Sharding, I think those examples would be incomplete without the TypeKey: having it there is part of the style recommendation for persistence I'd say.

So I wouldn't want to drop it or move it to the spec. Perhaps we could add a snippet to the style guide to show how to use the entity with sharding, to make it even more clear that those are typically used together, and to make it clearer why that TypeKey is there?

**Comment by robstoll** [comment]
> Perhaps we could add a snippet to the style guide to show how to use the entity with sharding, to make it even more clear that those are typically used together, and to make it clearer why that TypeKey is there?

That makes sense as well I would say.

**Pull request closed without merging**
