### PR TITLE
Clarify usage of FromConfig in doc and API doc #18771

### PR DESCRIPTION
**Pull request by richardimaoka**
Refs #18771

### CODE REVIEW

**Comment by johanandren** [comment]
You're on fire today @richard-imaoka, awesome! LGTM!

**Comment by richard-imaoka** [comment]
Haha, thanks :) It's a holiday today in Japan. I appreciate Akka team's quick reviews on my pull requests.

**Comment by ktoso** [comment]
What a great way to spend 海の日! Thanks a lot Richard :-)

**Comment by ktoso** [comment]
LGTM AFAICS. 
Could you sanity check @drewhk, ticket was opened by you back then.

**Comment by drewhk** [comment]
LGTM

**Comment by ktoso** [comment]
Thanks @richard-imaoka !

**Pull request merged**
