### PR TITLE
=act #17805 Don't change self on restart"

### PR DESCRIPTION
**Pull request by patriknw**
- we hold on to the same ActorRef instance anyway in the new
  Actor instance

### CODE REVIEW

**Comment by patriknw** [comment]
Refs #17805

**Comment by drewhk** [comment]
LGTM

**Comment by patriknw** [comment]
do you think this is important enough to backport to 2.3.12?

please double check that it is ok to change the signature of this internal method and still be binary compatible

**Comment by drewhk** [comment]
I don't think there is a danger of binary compatibility here, but you can just add an overloaded method directly if you want to please MiMa.

**Comment by patriknw** [comment]
my reasoning why it is safe is that the signature change is in ActorCell and the only place we invoke it is from the FaultHandling mixin, and those two should always be compiled together
`trait FaultHandling { this: ActorCell`

**Comment by ktoso** [comment]
Looks valid to me, LGTM

**Comment by ktoso** [comment]
I'd vote for backporting as well, it's low effort and keeps the behaviour between the branches in sync which may make things simpler in support.

**Comment by patriknw** [comment]
ok, I'll fix the backport

**Pull request merged**
