### PR TITLE
Update tutorial.md

### PR DESCRIPTION
**Pull request by SirMullich**
typo "temperaturs", fixed to "temperatures"

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @SirMullich,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by raboof — APPROVED** [review]
Good catch!

**Comment by raboof** [comment]
OK TO TEST

**Review by patriknw — APPROVED** [review]
LGTM, thanks

**Pull request merged**
