### PR TITLE
The size of ActorCell is not 64bytes

### PR DESCRIPTION
**Pull request by MQ-EL**
I measured ActorCell is 84bytes, 88bytes and 92bytes in 32/64-bit system
environment. So I changged the annotation of ActorCell.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @MQ-EL,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by patriknw** [comment]
Refs #16603

**Comment by patriknw** [comment]
OK TO TEST

**Comment by rkuhn** [comment]
Thanks a lot!

**Pull request merged**
