### PR TITLE
small test changes for Scala 2.12

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by patriknw** [comment]
See https://github.com/scala/community-builds/pull/317#issuecomment-256629255

**Comment by drewhk** [comment]
Is this a change because of a bug in the compiler, or because something really changed?

**Comment by patriknw** [comment]
something changed, but for (old) TypedActorSpec I don't care about serialization of messages with  lambdas.

For `LocalDeathWatchSpec` it's also something with serialization of things closed over. That test is written in a very bad style, creating anonymous actors `(Props(new Actor...` all over the place.

**Comment by drewhk** [comment]
ok, seems legit, LGTM

**Comment by ktoso** [comment]
LGTM

**Comment by rkuhn** [comment]
LGTM

**Comment by ktoso** [comment]
Needs a rebase :<

**Review by johanandren — APPROVED** [review]

**Comment by drewhk** [comment]
LGTM

**Comment by ktoso** [comment]
LGTM, thanks

**Pull request merged**
