### PR TITLE
Add mapMaterializedValue to Graph

### PR DESCRIPTION
**Pull request by tg44**
solves #26267

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Comment by johanandren** [comment]
I think that bincomp issue is ok since graph is not meant for user extension, can you add exclusions for it for MiMa?

**Comment by tg44** [comment]
Like this? Or should I move it to a concrete version?

**Comment by tg44** [comment]
Hmmm... Its colliding with the already implemented java functions... I'm a bit sad. Its either rename the new function (which will make inconsistency in the Flow.mapMaterializedValue vs Flow.mapMaterializedOTherFunctionName) or rename the java one which will hardly breake binComp...
Another thing is adding back some DummyImplicit which will keep the java api non-ambigous, and makes the scala api useable, but still really ugly.

**Comment by 2m** [comment]
The collision is only when compiling with Scala 2.11, because then the `akka.japi.function.Function` is not treated as a SAM. So this change becomes source incompatible for Scala 2.11 users.

I think binary compatibility is not broker with this change.

**Comment by tg44** [comment]
Okay, but the fact is; this modification is not working out of the box, bcs of the described 2.11 collision...
Any idea how should this been resolved?

**Comment by patriknw** [comment]
I don't have any good idea of how to solve this signature conflict. Adding another name just for this isn't nice. If it is solved when we don't have to support Scala 2.11 it might have to wait until Akka 2.6.

**Comment by tg44** [comment]
OK! Until then should I leave this PR here?

**Review by raboof — APPROVED** [review]
Thanks for the patience!

Since for 2.6 we are dropping support for Scala 2.11, this PR is become relevant again. I've taken the liberty of rebasing to fix some merge conflicts, thanks for this nice improvement!

**Comment by tg44** [comment]
Ofc! Thanks for the improvement!

**Comment by raboof** [comment]
> The collision is only when compiling with Scala 2.11, because then the akka.japi.function.Function is not treated as a SAM.

Hmm, I wonder if this was too optimistic: I still see the ambiguity error on 2.12 as well.

It seems the thing seems to be `akka.stream.Graph` is implemented both by the javadsl and by the scaladsl, and the `mapMaterializedValue` parameter looks different between those 2, but our japi `Function` class implements both... not sure of a way around that.

**Comment by raboof** [comment]
I'll close this one due to inactivity for now - feel free to reopen when resuming work on this!

**Pull request closed without merging**
