### PR TITLE
remove akka.stream.testkit.AkkaSpec, fixes #19879

### LINKED ISSUE #19879: remove AkkaSpec copy from stream.testkit

### PR DESCRIPTION
**Pull request by rkuhn**

### CODE REVIEW

**Comment by ktoso** [comment]
LGTM, merge at will

**Comment by johanandren** [comment]
LGTM

**Comment by drewhk** [comment]
LGTM

**Comment by ktoso** [comment]
Merge and run!

**Comment by ktoso** [comment]
Resolves #19879

**Pull request merged**
