### PR TITLE
fix compilation in scaladoc code for TestFSMRef #22625

### PR DESCRIPTION
**Pull request by pepegar**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @pepegar,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by ktoso — APPROVED** [review]
LGTM, thanks 👍

**Comment by johanandren** [comment]
Refs #22625

**Comment by ktoso** [comment]
Thanks, we can merge this once you've signed the CLA: http://www.lightbend.com/contribute/cla Just follow the steps online there (confirm with github account)

**Review by patriknw — APPROVED** [review]

**Comment by pepegar** [comment]
sorry for the delay, done!

**Pull request merged**
