### PR TITLE
Http core client side Java API

### PR DESCRIPTION
**Pull request by jrudolph**
Based on @sirthias' #17306.

I moved the settings classes into akka.http because it doesn't really make sense to completely duplicate all of them. If you don't like it we will have to change it again.

The signature of some of the client methods still contains `Try`. Is there any precedent of how to handle that in a Java API?

### CODE REVIEW

**Comment by patriknw** [comment]
makes sense to have common things in akka.http, there is similar in akka.stream

I don't know about `Try`, but it should be somewhat usable from java also so it should be alright.

**Comment by patriknw** [comment]
the last two commit LGTM

**Comment by ktoso** [comment]
Looked over packages, seems good, but it's so big I think we'll trust you guys :)

**Comment by 2m** [comment]
Cancelled validation so it can be restarted with merged in changes.

**Comment by 2m** [comment]
PLS BUILD

**Comment by patriknw** [comment]
@jrudolph @sirthias does this need an additional rebase or is it all good? Asking because it still shows 7 commits.

Is this the last PR?

**Comment by jrudolph** [comment]
Yep it's the last one.

Am 24.04.2015 19:42 schrieb "akka-ci" <notifications@github.com>:

**Comment by patriknw** [comment]
and what about the rebase?

**Comment by jrudolph** [comment]
I rebased just before the merge, so I guess it's just the UI which hasn't yet updated.

**Comment by patriknw** [comment]
yes, it looks good when I fetched it locally, merging. Yay!

**Comment by jrudolph** [comment]
Yay!

**Comment by 2m** [comment]
:+1:

**Pull request merged**
