### PR TITLE
Changes all occurances of Typesafe copyright to extend to 2015

### PR DESCRIPTION
**Pull request by jtescher**

### CODE REVIEW

**Comment by drewhk** [comment]
OK TO TEST

**Comment by drewhk** [comment]
Wow, thanks! LGTM

**Comment by ktoso** [comment]
Thanks!
Related info: @bantonsson was researching that we switch to https://github.com/sbt/sbt-header for copyright but I'm not sure on the status of that. Some edge cases popped up AFAIR.

**Comment by rkuhn** [comment]
Thanks, that’s awesome! Now I really hate to say this, but this PR has bugs: those lines that previously only had `2014` in them should not be changed to `2015` but to `2014–2015`. Your efforts are much appreciated!

**Comment by jtescher** [comment]
Ah! Good point. I'll amend the PR.

**Comment by jtescher** [comment]
@rkuhn fixed those bugs. Everything else looking good?

**Comment by rkuhn** [comment]
Looking good, thanks again!

**Pull request merged**
