### PR TITLE
Fix doc - use new markdown directive for dependency

### PR DESCRIPTION
**Pull request by anilkumarmyla**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @anilkumarmyla,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by johanandren** [comment]
There's actually a new markdown directive to use, like so:

```
@@dependency[sbt,Maven,Gradle] {
  group="com.typesafe.akka"
  artifact="akka-cluster-metrics_$scala.binary_version$"
  version="$akka.version$"
}
```

I think that should take care of the explicit Scala version. Can you try?

**Comment by anilkumarmyla** [comment]
Just signed the CLA. I'll take a look at the new markdown

**Comment by anilkumarmyla** [comment]
Sorry, this went off my radar. Got back to it and used the new markdown!

**Review by raboof — APPROVED** [review]
Neat, thanks!

**Review by chbatey — APPROVED** [review]
LGTM

**Pull request merged**
