### PR TITLE
Adds scaladoc to each CoordinatedShutdown phase #23131

### PR DESCRIPTION
**Pull request by tkroman**
As discussed in #23131. Docs are copied from http://doc.akka.io/docs/akka/2.5.2/scala/actors.html#coordinated-shutdown.

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]

**Comment by raboof** [comment]
@tkroman thanks for the contribution!

As you might have seen the build failed. This is because we use a tool called 'scalariform' to check for coding formatting consistency.

Could you use 'sbt scalariformFormat' to format this PR?

**Comment by raboof** [comment]
Oh you format faster than I comment :)

**Comment by raboof** [comment]
PLS BUILD

**Comment by tkroman** [comment]
Hm. Scalariform runs silently/ok on the local code. I re-pushed again, but whaaat...

**Review by ktoso — APPROVED** [review]
LGTM, very good to have the docs on the values - easier to discover by users from code there. A bit of maintanance pain, but I think it's worth it.

**Comment by raboof** [comment]
Thanks!

**Pull request merged**
