### PR TITLE
=sam #16684 Change to scala 2.11.5 in samples

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by patriknw** [comment]
I think the osgi sample is broken, and I have no clue what to do.

    - 2.3.1 | Error installing boot features
    java.lang.Exception: Could not start bundle mvn:org.scalatest/scalatest_2.11/2.1.3 in feature(s) exam-2.6.0: The bundle "org.scalatest_2.1.3 [72]" could not be resolved. Reason: Missing Constraint: Import-Package: scala.reflect.macros.contexts; version="[2.11.0,2.12.0)"
        at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeatures(FeaturesServiceImpl.java:482)[40:org.apache.karaf.features.core:2.3.1]
        at org.apache.karaf.features.internal.FeaturesServiceImpl$2.run(FeaturesServiceImpl.java:1150)[40:org.apache.karaf.features.core:2.3.1]
    Caused by: org.osgi.framework.BundleException: The bundle "org.scalatest_2.1.3 [72]" could not be resolved. Reason: Missing Constraint: Import-Package: scala.reflect.macros.contexts; version="[2.11.0,2.12.0)"
        at org.eclipse.osgi.framework.internal.core.AbstractBundle.getResolverError(AbstractBundle.java:1332)[osgi-3.8.0.v20120529-1548.jar:]
        at org.eclipse.osgi.framework.internal.core.AbstractBundle.getResolutionFailureException(AbstractBundle.java:1316)[osgi-3.8.0.v20120529-1548.jar:]
        at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:323)[osgi-3.8.0.v20120529-1548.jar:]
        at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:300)[osgi-3.8.0.v20120529-1548.jar:]
        at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:292)[osgi-3.8.0.v20120529-1548.jar:]
        at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeatures(FeaturesServiceImpl.java:479)[40:org.apache.karaf.features.core:2.3.1]

**Comment by 2m** [comment]
We should try to update this OSGi sample to the latest scalatest which is `2.2.3`.

**Comment by 2m** [comment]
I also tried moving samples to `2.11.5` a day before, but could not get 
```
{file:/home/martynas/projects/akka/akka-samples/akka-sample-multi-node-scala/}akka-sample-multi-node-scala/test
```
to work, which fails with
```
[info] * sample.multinode.MultiNodeSampleSpec
[JVM-2] *** RUN ABORTED ***
[JVM-2]   java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
[JVM-2]   at akka.remote.testkit.MultiNodeSpec$.<init>(MultiNodeSpec.scala:201)
[JVM-2]   at akka.remote.testkit.MultiNodeSpec$.<clinit>(MultiNodeSpec.scala)
[JVM-2]   at akka.remote.testkit.MultiNodeConfig.myself$lzycompute(MultiNodeSpec.scala:96)
[JVM-2]   at akka.remote.testkit.MultiNodeConfig.myself(MultiNodeSpec.scala:95)
[JVM-2]   at akka.remote.testkit.MultiNodeSpec.<init>(MultiNodeSpec.scala:252)
[JVM-2]   at sample.multinode.MultiNodeSample.<init>(MultiNodeSample.scala:30)
[JVM-2]   at sample.multinode.MultiNodeSampleSpecMultiJvmNode2.<init>(MultiNodeSample.scala:20)
[JVM-2]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[JVM-2]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[JVM-1] *** RUN ABORTED ***
[JVM-1]   java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
[JVM-1]   at akka.remote.testkit.MultiNodeSpec$.<init>(MultiNodeSpec.scala:201)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec$.<clinit>(MultiNodeSpec.scala)
[JVM-1]   at akka.remote.testkit.MultiNodeConfig.myself$lzycompute(MultiNodeSpec.scala:96)
[JVM-1]   at akka.remote.testkit.MultiNodeConfig.myself(MultiNodeSpec.scala:95)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.<init>(MultiNodeSpec.scala:252)
[JVM-1]   at sample.multinode.MultiNodeSample.<init>(MultiNodeSample.scala:30)
[JVM-1]   at sample.multinode.MultiNodeSampleSpecMultiJvmNode1.<init>(MultiNodeSample.scala:19)
[JVM-1]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[JVM-1]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[JVM-1]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[JVM-1]   ...
[JVM-2]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[JVM-2]   ...
```

It seems that different scala versions are used somewhere. But I could find where...

**Comment by 2m** [comment]
So `2.2.3` has `scala.reflect.macros.contexts;version="[2.11,3)"` in the MANIFEST.MF. So changing to this version should fix the problem you were seeing, @patriknw

**Comment by patriknw** [comment]
With 2.2.3 there is a similar but other error:

    2.3.1 | Error installing boot features
    java.lang.Exception: Could not start bundle mvn:org.scalatest/scalatest_2.11/2.2.3 in feature(s) exam-2.6.0: The bundle "org.scalatest_2.2.3 [72]" could not be resolved. Reason: Missing Constraint: Import-Package: org.apache.tools.ant; version="0.0.0"
        at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeatures(FeaturesServiceImpl.java:482)[40:org.apache.karaf.features.core:2.3.1]
        at org.apache.karaf.features.internal.FeaturesServiceImpl$2.run(FeaturesServiceImpl.java:1150)[40:org.apache.karaf.features.core:2.3.1]
    Caused by: org.osgi.framework.BundleException: The bundle "org.scalatest_2.2.3 [72]" could not be resolved. Reason: Missing Constraint: Import-Package: org.apache.tools.ant; version="0.0.0"

**Comment by patriknw** [comment]
I have created an issue in scalatest: https://github.com/scalatest/scalatest/issues/484

**Comment by patriknw** [comment]
@2m akka-sample-multi-node-scala works for me, after publishLocal of akka*_2.11/2.4-SNAPSHOT

**Comment by patriknw** [comment]
I have temporarily removed osgiDiningHakkersSampleMavenTest removed from samples aggregate due to #16703.

@2m will fix #16704 (pr validation of samples) in another PR

**Pull request merged**
