### PR TITLE
log join retries, #22053

### PR DESCRIPTION
**Pull request by patriknw**
Refs #22053

### CODE REVIEW

**Comment by patriknw** [comment]
GC trouble again, and I thought I found the reason yesterday:
```
1498.924: [GC remark 1498.924: [Finalize Marking, 0.0131311 secs] 1498.937: [GC ref-proc, 0.0019491 secs] 1498.939: [Unloading, 2.9628173 secs], 2.9923438 secs]
 [Times: user=2.04 sys=95.44, real=2.99 secs]
```

**Comment by patriknw** [comment]
PLS BUILD

**Comment by ktoso** [comment]
LGTM

**Review by ktoso — APPROVED** [review]

**Comment by ktoso** [comment]
Non controversial I guess, feel free to merge imo

**Pull request merged**
