### PR TITLE
Docs: Fix typos in Distributed Data section

### PR DESCRIPTION
**Pull request by StephenKing**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @StephenKing,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by raboof — APPROVED** [review]
Thanks for spotting and fixing these!

**Comment by raboof** [comment]
OK TO TEST

**Comment by chbatey** [comment]
@StephenKing would you mind signing the CLA? Then I can merge

**Review by chbatey — APPROVED** [review]

**Pull request merged**
