### PR TITLE
+ str Add java.time.Duration to akka-stream's javadsl.*

### PR DESCRIPTION
**Pull request by He-Pin**
following https://github.com/akka/akka/issues/24646

### CODE REVIEW

**Review by raboof — APPROVED** [review]
Should we also deprecate the `FiniteDuration`-based ones?

**Comment by hepin1989** [comment]
@raboof So, the deprecated method will be removed in Akka 2.6?

**Comment by patriknw** [comment]
We normally keep deprecated for one full minor cycle, i.e. will remain in 2.6 and removed in 2.7 (might be shortened if been deprecated ”long enough”)

Sounds good to add the deprecation annotations.

**Comment by hepin1989** [comment]
OK，Will add them:)

**Review by ktoso — APPROVED** [review]
LGTM though we also should make sure we're using the new methods in the java docs, otherwise we're showing people deprecated methods in the documentation. Could  you do this in this PR or as a separate one @hepin1989 ?

**Comment by hepin1989** [comment]
@ktoso I want to change the document in a separate one:).

**Comment by ktoso** [comment]
Okey, sounds good to me

**Pull request merged**
