### PR TITLE
remove redundant yet

### PR DESCRIPTION
**Pull request by robertgol**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @robertgol,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by chbatey — APPROVED** [review]
LGTM

**Comment by chbatey** [comment]
OK TO TEST

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
