### PR TITLE
Scala 2.13.0 -> Scala 2.13.1

### PR DESCRIPTION
**Pull request by sullis**
## References

References #xxxx

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Comment by patriknw** [comment]
```
[error] java.lang.NoSuchMethodError: scala.tools.nsc.Global.reporter()Lscala/tools/nsc/reporters/Reporter;
275[error] com.github.ghik.silencer.SilencerPlugin.reporter$lzycompute(SilencerPlugin.scala:27)
276[error] com.github.ghik.silencer.SilencerPlugin.com$github$ghik$silencer$SilencerPlugin$$reporter(SilencerPlugin.scala:26)
277[error] com.github.ghik.silencer.SilencerPlugin.processOptions(SilencerPlugin.scala:50)
```

**Comment by raboof** [comment]
depends on  #28190

**Comment by raboof** [comment]
(rebased)

**Review by raboof — APPROVED** [review]

**Comment by patriknw** [comment]
Is genjavadoc released for 2.13.1? I guess we run that in PR validation?

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by raboof** [comment]
Good one, genjavadoc 0.15 supports scala 2.13.1 but we're not on that yet... I'll amend this PR.

**Comment by raboof** [comment]
(I guess we enable genjavadoc only for nightlies as it is slower?)

**Comment by raboof** [comment]
PLS BUILD

**Comment by patriknw** [comment]
PLS BUILD

**Pull request merged**
