### PR TITLE
Updated Books

### PR DESCRIPTION
**Pull request by packtpartner**
New book link added

### CODE REVIEW

**Comment by ktoso** [comment]
Thanks 👍

**Comment by packtpartner** [comment]
Thanks for the merge @akka-ci and @ktoso , would you be able to tell me when will this reflect on http://doc.akka.io/docs/akka/2.4.7/additional/books.html ?

**Comment by patriknw** [comment]
It will show in latest docs when we release next version.
http://doc.akka.io/docs/akka/2.4/additional/books.html

**Comment by packtpartner** [comment]
Thanks @patriknw, I will regularly check in for the next release

**Pull request merged**
