### PR TITLE
Add Sink.takeLast operator

### PR DESCRIPTION
**Pull request by ktoso**
Replaces https://github.com/akka/akka/pull/25412 with some DRYing up things

### CODE REVIEW

**Comment by ktoso** [comment]
Resolves #25322
Mostly authored by @naferx , so wathc out and merge only as rebase, not squash!

**Comment by ktoso** [comment]
Mima...

**Review by chbatey — APPROVED** [review]
LGTM

**Comment by ktoso** [comment]
Resolves  #25322, thanks @naferx

**Pull request merged**
