### PR TITLE
+htc #20086 make ws.*Message.Streamed not private

### LINKED ISSUE #20086: Unable to match on ws.TextMessage.Streamed
It's not possible to write:

```scala
  val bindingFuture = Http().bindAndHandle({
    path("ws") {
      handleWebSocketMessages(Flow.fromSinkAndSource(
        Flow[Message]
          .collect {
            case TextMessage.Streamed(s) ⇒ //  <<<<<<<<<<<<<
              s.runForeach(s ⇒ println("STREAM: " + s))
              Strict("streaming...")

            case s @ TextMessage.Strict(msg) ⇒
              s
          }
          .map { x ⇒ { println("Strict: " + x); x } }
          .alsoTo(Sink.onComplete(ex ⇒ println("done: " + ex)))
          .to(Sink.ignore),
        Source.maybe[Message]))
    } 
  }, interface = "localhost", port = 8080)


```

as `Streamed` marked `private`.

### PR DESCRIPTION
**Pull request by ktoso**
In order to allow matching on it.
Resolves #20086

### CODE REVIEW

**Comment by johanandren** [comment]
LGTM

**Comment by ktoso** [comment]
Put on hold, we want to provide more directives instead. Let me think about it for a bit

**Comment by jrudolph** [comment]
I think I made this change by purpose in f50a3ffc4b62d580d6527cfba201ddb7fd9d6f06. Not sure if I still agree with my original assessment that this makes `Streamed` the more prominent case... Popular evidence would suggest otherwise, it seems ;)

**Comment by ktoso** [comment]
I think I'll drop this PR actually – have a look at https://github.com/akka/akka/issues/20096 @jrudolph :)

**Comment by viktorklang** [comment]
LGTM

**Comment by ktoso** [comment]
Nowadays I'm leaning towards merging this anyway, and then providing the operators to make websocket interactions more nice (as explained in above linked issue #20096 )

**Comment by drewhk** [comment]
LGTM. Needs a backport

**Comment by viktorklang** [comment]
:+1:

**Comment by ktoso** [comment]
Merging then

**Pull request merged**
