### PR TITLE
Fix doc typo backpressure explained section #30067

### PR DESCRIPTION
**Pull request by mariohuizar**
Fix doc typo
References #30067

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @marioJambit,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Review by johanandren — APPROVED** [review]

**Comment by johanandren** [comment]
Thanks. A bit silly but I think we'd need a CLA sign even to accept a spelling fix like this. See cla-validator comment above

**Comment by chbatey** [comment]
@mariohuizar I think it is meant to be safety net, the backpressure protocol is the safety net

**Comment by mariohuizar** [comment]
> @mariohuizar I think it is meant to be safety net, the backpressure protocol is the safety net

Oh I see, thanks for the clarification.

**Comment by chbatey** [comment]
Np, thanks for looking to improve the docs, always very appreciated

**Pull request closed without merging**
