### PR TITLE
+per #18485 Add cluster sharding data removal utility

### PR DESCRIPTION
**Pull request by patriknw**
also found a leveldb journal issue with `deleteMessages(Long.MaxValue)`

### CODE REVIEW

**Comment by patriknw** [comment]
Refs #18485

**Comment by patriknw** [comment]
Refs #18497

**Comment by ktoso** [comment]
LGTM, some minor comments

**Comment by patriknw** [comment]
@ktoso added the `remove` method and reworked the termination, and added the persistencePluginId. See 6b9b518

**Comment by ktoso** [comment]
LGTM, that'll be very useful for some people.

**Pull request merged**
