### PR TITLE
Downgrading SBT until https://github.com/sbt/sbt/issues/2686 is fixed

### PR DESCRIPTION
**Pull request by drewhk**
Issue https://github.com/sbt/sbt/issues/2686 is breaking IntelliJ project import on my machine. Downgrading SBT fixes the issue reliably. I request a downgrade here until this is solved.

### CODE REVIEW

**Comment by ktoso** [comment]
LGTM, too bad we have to.
Let's ping Eugene perhaps?

-- 
Konrad `ktoso` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 2 August 2016 at 14:43:05, drewhk (notifications@github.com) wrote:

Issue sbt/sbt#2686 <https://github.com/sbt/sbt/issues/2686> is breaking
IntelliJ project import on my machine. Downgrading SBT fixes the issue
reliably. I request a downgrade here until this is solved.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/akka/akka/pull/21094
Commit Summary

   - Downgrading SBT until https://github.com/sbt/sbt/issues/2686 is fixed

File Changes

   - *M* project/build.properties
   <https://github.com/akka/akka/pull/21094/files#diff-0> (2)

Patch Links:

   - https://github.com/akka/akka/pull/21094.patch
   - https://github.com/akka/akka/pull/21094.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka/pull/21094>, or mute the thread

**Comment by drewhk** [comment]
There is the above ticket already

**Comment by ktoso** [comment]
Ah, I didn't notice.
Cool then, merge at will

-- 
Konrad `ktoso` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 2 August 2016 at 14:43:05, drewhk (notifications@github.com) wrote:

Issue sbt/sbt#2686 <https://github.com/sbt/sbt/issues/2686> is breaking
IntelliJ project import on my machine. Downgrading SBT fixes the issue
reliably. I request a downgrade here until this is solved.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/akka/akka/pull/21094
Commit Summary

   - Downgrading SBT until https://github.com/sbt/sbt/issues/2686 is fixed

File Changes

   - *M* project/build.properties
   <https://github.com/akka/akka/pull/21094/files#diff-0> (2)

Patch Links:

   - https://github.com/akka/akka/pull/21094.patch
   - https://github.com/akka/akka/pull/21094.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka/pull/21094>, or mute the thread

**Comment by johanandren** [comment]
LGTM

**Comment by drewhk** [comment]
Thanks, I will merge after validation.

**Pull request merged**
