### PR TITLE
Use one naming convention for ShardCoordinator in doc and logging

### PR DESCRIPTION
**Pull request by helena**
For search efficiency and consistency.

### CODE REVIEW

**Comment by helena** [comment]
This is a one-off simple change from working through another thing. Does it need its own issue? I'd guess not.

**Review by jrudolph — APPROVED** [review]
LGTM

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by johanandren** [comment]
Unrelated failure (#26230)

**Comment by johanandren** [comment]
PLS BUILD

**Comment by helena** [comment]
PLS BUILD

**Pull request merged**
