### PR TITLE
Clustering documentation example link fix

### PR DESCRIPTION
**Pull request by bkowalik**
I think that there is wrong link in cluster singleton part of Scala documentation.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @bkowalik,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by johanandren** [comment]
OK TO TEST

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Review by patriknw — APPROVED** [review]
LGTM

**Review by ktoso — APPROVED** [review]
LGTM thanks

**Pull request merged**
