### PR TITLE
=str #18037 FlowOps.log exception handler does not follow strategy

### PR DESCRIPTION
**Pull request by agolubev**

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
LGTM, thanks!

**Comment by drewhk** [comment]
Please rebase

**Comment by agolubev** [comment]
@drewhk, PR rebased, build failed with
```
[info] - must work *** FAILED *** (41 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected OnNext(ByteString(11)), found OnNext(ByteString(3))
[info]   at scala.Predef$.assert(Predef.scala:179)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:339)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:315)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:718)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:262)
[info]   at docs.stream.cookbook.RecipeKeepAlive$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(RecipeKeepAlive.scala:59)
[info]   at docs.stream.cookbook.RecipeKeepAlive$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RecipeKeepAlive.scala:12)
[info]   at docs.stream.cookbook.RecipeKeepAlive$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RecipeKeepAlive.scala:12)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
```
this is not related to this PR per my understanding

**Comment by hepin1989** [comment]
Mine failed too:)just the same error

**Comment by ktoso** [comment]
There's a PR to solve that failure already, here: https://github.com/akka/akka/pull/18833

**Comment by drewhk** [comment]
PLS BUILD

**Comment by drewhk** [comment]
refs #18037

**Pull request merged**
