### PR TITLE
=htp #16808 fix unnecessary reverse DNS lookups for >Java1.7

### PR DESCRIPTION
**Pull request by agolubev**
PR from #17481 but re-targeted to release-2.3-dev branch

### CODE REVIEW

**Comment by ktoso** [comment]
Thanks for re-targeting! As reviewed previously, LGTM

**Comment by ktoso** [comment]
OK TO TEST

**Comment by drewhk** [comment]
LGTM

**Comment by drewhk** [comment]
Fixes #16808

**Comment by jrudolph** [comment]
@agolubev This is broken for me in Java 6 OpenJDK. Did you check that it works? Is Java 6 compatibility somehow checked in PR validation?

**Comment by ktoso** [comment]
Good catch... We now are running validation with JDK8 (because `master`), and I think *all* validation is now on JDK8 so probably a bad idea and this could have slipped through hm..

**Comment by jrudolph** [comment]
Yes, also the problem is that to properly test it, you would have to compile the files in the same way the release is compiled and then just run (compile?) the tests with Java 6.

**Comment by agolubev** [comment]
I see, let me check for configuration you mentioned. Compile as in released and then run under 1.6

**Pull request merged**
