### PR TITLE
=http #20687 Remove dead code and unused import from Unmarshaller

### PR DESCRIPTION
**Pull request by kubukoz**
Refs #20687

### CODE REVIEW

**Comment by ktoso** [comment]
And a ticket about mapWithInput please :)

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
LGTM from my side

**Comment by drewhk** [comment]
LGTM

**Comment by ktoso** [comment]
Thanks for bouscouting @kubukoz  :-)

**Pull request merged**
