### PR TITLE
Fix version for stream and http

### PR DESCRIPTION
**Pull request by aruediger**

### CODE REVIEW

**Comment by drewhk** [comment]
OK TO TEST

**Comment by drewhk** [comment]
Thanks, LGTM

**Comment by ktoso** [comment]
LGTM AFAICS, the "substitute version nr during release" works on obtaining the nr from sbt so this should work, right?

**Comment by ktoso** [comment]
OK TO TEST

**Comment by drewhk** [comment]
yes it should work.

**Pull request merged**
