### PR TITLE
=3974 per Persist (serialize) actor refs  with transport info

### PR DESCRIPTION
**Pull request by patriknw**
- The reason for the problem with NoSuchElementException in ClusterSharding was
  that actor references were not serialized with full address information. In
  certain fail over scenarios the references could not be resolved and therefore
  the ShardRegionTerminated did not match corresponding ShardRegionRegistered.
- Wrap serialization with transport information from defaultAddress

There is a great description of how to reproduce the problem in the [ticket](https://www.assembla.com/spaces/akka/tickets/3974).

When debugging I found the following for a failing actor ref with uid 1022170393:

On 2551 it is first registered as expected:

```
[INFO] [04/06/2014 18:55:25.844] [ClusterSystem-akka.actor.default-dispatcher-14] [akka.tcp://ClusterSystem@127.0.0.1:2551/user/sharding/AuthorListingCoordinator/singleton] # updated: ShardRegionRegistered(Actor[akka.tcp://ClusterSystem@127.0.0.1:2552/user/sharding/AuthorListing#1022170393])

# serializedActorPath Actor[akka.tcp://ClusterSystem@127.0.0.1:2552/user/sharding/AuthorListing#1022170393] Information akka.tcp://ClusterSystem@127.0.0.1:2551
### serializedActorPath Actor[akka.tcp://ClusterSystem@127.0.0.1:2552/user/sharding/AuthorListing#1022170393] => akka.tcp://ClusterSystem@127.0.0.1:2552/user/sharding/AuthorListing#1022170393
```

Recovery on 2552:

```
[INFO] [04/06/2014 18:56:10.115] [ClusterSystem-akka.persistence.dispatchers.default-replay-dispatcher-27] [LocalActorRefProvider(akka://ClusterSystem)] # resolve of path sequence [/user/sharding/AuthorListing#1022170393] failed

# readResolve path: akka.tcp://ClusterSystem@127.0.0.1:2552/user/sharding/AuthorListing#1022170393 => Actor[akka://ClusterSystem/user/sharding/AuthorListing#1022170393]

[INFO] [04/06/2014 18:56:10.122] [ClusterSystem-akka.actor.default-dispatcher-14] [akka.tcp://ClusterSystem@127.0.0.1:2552/user/sharding/AuthorListingCoordinator/singleton] # updated: ShardRegionRegistered(Actor[akka://ClusterSystem/user/sharding/AuthorListing#1022170393])

### serializedActorPath Actor[akka://ClusterSystem/user/sharding/AuthorListing#1022170393] => akka://ClusterSystem/user/sharding/AuthorListing#1022170393

[INFO] [04/06/2014 18:56:10.172] [ClusterSystem-akka.actor.default-dispatcher-14] [akka.tcp://ClusterSystem@127.0.0.1:2552/user/sharding/AuthorListingCoordinator/singleton] # updated: ShardRegionTerminated(Actor[akka://ClusterSystem/user/sharding/AuthorListing#1022170393])
```

Recovery on 2553:

```
# readResolve path: akka.tcp://ClusterSystem@127.0.0.1:2552/user/sharding/AuthorListing#1022170393 => Actor[akka.tcp://ClusterSystem@127.0.0.1:2552/user/sharding/AuthorListing#1022170393]


[INFO] [04/06/2014 18:56:40.155] [ClusterSystem-akka.persistence.dispatchers.default-replay-dispatcher-29] [LocalActorRefProvider(akka://ClusterSystem)] # resolve of path sequence [/user/sharding/AuthorListing#1022170393] failed

# readResolve path: akka://ClusterSystem/user/sharding/AuthorListing#1022170393 => Actor[akka://ClusterSystem/user/sharding/AuthorListing#1022170393]

[INFO] [04/06/2014 18:56:40.158] [ClusterSystem-akka.actor.default-dispatcher-24] [akka.tcp://ClusterSystem@127.0.0.1:2553/user/sharding/AuthorListingCoordinator/singleton] # updated: ShardRegionRegistered(Actor[akka.tcp://ClusterSystem@127.0.0.1:2552/user/sharding/AuthorListing#1022170393])

[INFO] [04/06/2014 18:56:40.162] [ClusterSystem-akka.actor.default-dispatcher-24] [akka.tcp://ClusterSystem@127.0.0.1:2553/user/sharding/AuthorListingCoordinator/singleton] # receiveRecover ShardRegionTerminated Actor[akka://ClusterSystem/user/sharding/AuthorListing#1022170393] => state before: State(Map(17 -> Actor[akka.tcp://ClusterSystem@127.0.0.1:2551/user/sharding/AuthorListing#1443663680]),Map(Actor[akka.tcp://ClusterSystem@127.0.0.1:2551/user/sharding/AuthorListing#1443663680] -> Vector(17), Actor[akka.tcp://ClusterSystem@127.0.0.1:2552/user/sharding/AuthorListing#1022170393] -> Vector(), Actor[akka://ClusterSystem/user/sharding/AuthorListing#-85570854] -> Vector()),Set())
[INFO] [04/06/2014 18:56:40.162] [ClusterSystem-akka.actor.default-dispatcher-24] [akka.tcp://ClusterSystem@127.0.0.1:2553/user/sharding/AuthorListingCoordinator/singleton] # updated: ShardRegionTerminated(Actor[akka://ClusterSystem/user/sharding/AuthorListing#1022170393])
```

And boom for that ShardRegionTerminated.

### CODE REVIEW

**Comment by Akrome** [comment]
Hi, have there been any updates or related issues on this? I am using Akka 2.3.4 and I still receive printed the 

log.debug("ShardRegionTerminated, but region {} was not registered. This inconsistency is due to that " +
+ " some stored ActorRef in Akka v2.3.0 and v2.3.1 did not contain full address information. It will be " +
+ "removed by later watch.", region)

message, and looking at debug logs I see that sometimes actorrefs are printed without remoting info, while sometimes they do.

**Comment by patriknw** [comment]
what version was used when **persisting** the old events?

**Comment by Akrome** [comment]
Always 2.3.4 . We have tried cleaning the journal multiple times and the issue reappears periodically leading to "Shard already allocated" errors on restartup (as the region is not deallocated because of this issue, we believe). We are using a custom dynamodb journal plugin, so it may also be our fault, but it did pass the whole test suite for journal plugins provided and we have been inspecting it pretty closely :/

**Comment by patriknw** [comment]
Thanks, then it "should" not be because of missing address information in the serialized refs.

Running with debug logging should give a clear picture of what is actually replayed. I can take a look of such a log to verify.

**Comment by Akrome** [comment]
Here is an extract from the logs of one of the regions. As you can see, ShardHomeAllocated and ShardRegionRegistered store in the internal map the full (ip included) actorref, while the ShardRegionTerminated messages (line 1304) do not include ip address:

	Line 1301: 05:08:33.348 [dispatch-availability-akka.actor.default-dispatcher-30] DEBUG a.contrib.pattern.ShardCoordinator - receiveRecover ShardRegionRegistered(Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-444843889])
	Line 1302: 05:08:33.348 [dispatch-availability-akka.actor.default-dispatcher-30] DEBUG a.contrib.pattern.ShardCoordinator - receiveRecover ShardHomeAllocated(-49,Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-444843889])
	Line 1303: 05:08:33.348 [dispatch-availability-akka.actor.default-dispatcher-30] DEBUG a.contrib.pattern.ShardCoordinator - receiveRecover ShardRegionRegistered(Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#728140365])
	Line 1304: 05:08:33.348 [dispatch-availability-akka.actor.default-dispatcher-30] DEBUG a.contrib.pattern.ShardCoordinator - receiveRecover ShardRegionTerminated(Actor[akka://dispatch-availability/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-444843889])
	Line 1305: 05:08:33.348 [dispatch-availability-akka.actor.default-dispatcher-30] DEBUG a.contrib.pattern.ShardCoordinator - ShardRegionTerminated, but region Actor[akka://dispatch-availability/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-444843889] was not registered. This inconsistency is due to that  some stored ActorRef in Akka v2.3.0 and v2.3.1 did not contain full address information. It will be removed by later watch.
	Line 1345: 05:08:33.470 [dispatch-availability-akka.actor.default-dispatcher-37] DEBUG a.contrib.pattern.ShardCoordinator - receiveRecover ShardRegionTerminated(Actor[akka.tcp://dispatch-availability@10.192.73.1:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#1051516360])
	Line 1346: 05:08:33.470 [dispatch-availability-akka.actor.default-dispatcher-37] DEBUG a.contrib.pattern.ShardCoordinator - receiveRecover ShardRegionRegistered(Actor[akka.tcp://dispatch-availability@10.192.109.27:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-1938310832])
	Line 1361: 05:08:33.572 [dispatch-availability-akka.actor.default-dispatcher-26] DEBUG a.contrib.pattern.ShardCoordinator - receiveRecover ShardRegionTerminated(Actor[akka.tcp://dispatch-availability@10.192.109.27:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-1938310832])
	Line 1362: 05:08:33.572 [dispatch-availability-akka.actor.default-dispatcher-26] DEBUG a.contrib.pattern.ShardCoordinator - receiveRecover ShardRegionRegistered(Actor[akka.tcp://dispatch-availability@10.192.73.1:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#1146611526])
	Line 1363: 05:08:33.572 [dispatch-availability-akka.actor.default-dispatcher-26] DEBUG a.contrib.pattern.ShardCoordinator - receiveRecover ShardHomeAllocated(-49,Actor[akka.tcp://dispatch-availability@10.192.73.1:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#1146611526])
	Line 1579: 05:08:35.511 [dispatch-availability-akka.actor.default-dispatcher-32] ERROR akka.actor.OneForOneStrategy - requirement failed: Shard [-49] already allocated: State(Map(-49 -> Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-444843889]),Map(Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-444843889] -> Vector(-49), Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#728140365] -> Vector(), Actor[akka.tcp://dispatch-availability@10.192.73.1:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#1146611526] -> Vector()),Set())
	Line 1579: 05:08:35.511 [dispatch-availability-akka.actor.default-dispatcher-32] ERROR akka.actor.OneForOneStrategy - requirement failed: Shard [-49] already allocated: State(Map(-49 -> Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-444843889]),Map(Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-444843889] -> Vector(-49), Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#728140365] -> Vector(), Actor[akka.tcp://dispatch-availability@10.192.73.1:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#1146611526] -> Vector()),Set())
	Line 1579: 05:08:35.511 [dispatch-availability-akka.actor.default-dispatcher-32] ERROR akka.actor.OneForOneStrategy - requirement failed: Shard [-49] already allocated: State(Map(-49 -> Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-444843889]),Map(Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-444843889] -> Vector(-49), Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#728140365] -> Vector(), Actor[akka.tcp://dispatch-availability@10.192.73.1:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#1146611526] -> Vector()),Set())
	Line 1579: 05:08:35.511 [dispatch-availability-akka.actor.default-dispatcher-32] ERROR akka.actor.OneForOneStrategy - requirement failed: Shard [-49] already allocated: State(Map(-49 -> Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-444843889]),Map(Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-444843889] -> Vector(-49), Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#728140365] -> Vector(), Actor[akka.tcp://dispatch-availability@10.192.73.1:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#1146611526] -> Vector()),Set())
	Line 1580: java.lang.IllegalArgumentException: requirement failed: Shard [-49] already allocated: State(Map(-49 -> Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-444843889]),Map(Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-444843889] -> Vector(-49), Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#728140365] -> Vector(), Actor[akka.tcp://dispatch-availability@10.192.73.1:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#1146611526] -> Vector()),Set())
	Line 1580: java.lang.IllegalArgumentException: requirement failed: Shard [-49] already allocated: State(Map(-49 -> Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-444843889]),Map(Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-444843889] -> Vector(-49), Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#728140365] -> Vector(), Actor[akka.tcp://dispatch-availability@10.192.73.1:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#1146611526] -> Vector()),Set())
	Line 1580: java.lang.IllegalArgumentException: requirement failed: Shard [-49] already allocated: State(Map(-49 -> Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-444843889]),Map(Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-444843889] -> Vector(-49), Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#728140365] -> Vector(), Actor[akka.tcp://dispatch-availability@10.192.73.1:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#1146611526] -> Vector()),Set())
	Line 1580: java.lang.IllegalArgumentException: requirement failed: Shard [-49] already allocated: State(Map(-49 -> Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-444843889]),Map(Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#-444843889] -> Vector(-49), Actor[akka.tcp://dispatch-availability@10.192.85.154:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#728140365] -> Vector(), Actor[akka.tcp://dispatch-availability@10.192.73.1:2551/user/sharding/ocd%7CTransferScheduleService%7CTransferScheduleData#1146611526] -> Vector()),Set())

**Comment by patriknw** [comment]
@Akrome that indeed looks strange. Was that log from 10.192.85.154:2551?
I can't understand why the ShardHomeAllocated and ShardRegionTerminated are serialized/de-serialized differently.  As you can see in this pull request the fix should apply to all events.

I guess we have to try to reproduce it again. Do you have any clue of a scenario (starting stopping nodes in a specific order) that would lead up to this problem?

By the way, you should switch to 2.3.9 for other reasons. We have fixed some issues in cluster and remoting since 2.3.4.

**Comment by saparbek** [comment]
Thank you, @patriknw. 

I can't reproduce exact sequence of events, because we see the error on recovery and it is hard to pin-point when exactly things went wrong. However, I can give you some description what is happening in less details. We use EC2 instances on Amazon Cloud. Usually we terminate all instances in the evening. The actual termination of instances does not happen at the same moment and some instances may be still running while others going down. Next day we restart the system, with new instances (they all have different IP address)  and we start seeing "Shard already allocated" errors.
I hope that this explanation can be helpful to deduce what is happening. We will keep you updated as we gather more information.

Regarding updating to Akka version 2.3.9, we can try to upgrade, but we would like to try to understand the issue in isolation, unless there is a bug fix that is directly related to our problem.

**Comment by saparbek** [comment]
Sorry, @patriknw. We just found out that we were not using the MessageSerializer. In our custom DynamoDB journal we were serializing and storing payload separately, which uses Java serializer by default and which was likely to cause the issue. Now we are going to store whole PersistenceRepr instead. We will let you know if it resolves our problem.
Thank you very much for your time and effort!

**Comment by patriknw** [comment]
@saparbek thanks for the update. I hope that explains it. Note that the important piece is that the serialization is done within a `Serialization.currentTransportInformation.withValue` block, as can be seen in this pull request.

**Pull request merged**
