### PR TITLE
Upgrade sbt-paradox-akka 0.18 -> 0.23

### PR DESCRIPTION
**Pull request by helena**
Tested against `akka-docs/paradox`.

### CODE REVIEW

**Comment by ennru** [comment]
We could wait for the latest Paradox and akka-paradox changes to be finished.

**Comment by helena** [comment]
Let's wait, I'll add those when they are.

**Review by raboof — APPROVED** [review]
(looks OK to me, no lightbend banner yet because that comes in 0.21 https://github.com/akka/akka-paradox/compare/v0.20...master)

**Comment by raboof** [comment]
Failure was #27489

**Comment by raboof** [comment]
PLS BUILD

**Review by ennru — APPROVED** [review]
LGTM.

**Pull request merged**
