### PR TITLE
Step two in the cluster message manifest change 

### PR DESCRIPTION
**Pull request by johanandren**
Switch over to emitting the new short string based manifests (and the heartbeat messages including a timestamp)

References #13654

### CODE REVIEW

**Review by patriknw — APPROVED** [review]
LGTM, would be good to try this in the akka-upgrade-testing before next release

**Comment by johanandren** [comment]
How do I do that, is it running automatically each night after this is merged or do I need to explicitly do something? (ping @chbatey )

**Comment by chbatey** [comment]
Yep it picks up the latest akka snapshot so we can merge and fix.

**Comment by chbatey** [comment]
It was broken. I've now fixed the testing. 

The only thing you might want to do is check that tg goes through versions you want to test. By default it has a static 2.5 version, then the latest 2.5 snapshot, a static 2.6 version and then the latest 2.6 snapshot.

**Review by chbatey — APPROVED** [review]

**Pull request merged**
