### PR TITLE
Fixes logging when serialization is not defined on NotSerializableExc…

### PR DESCRIPTION
**Pull request by novacekm**
…eption

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Good catch, thanks!

**Review by ktoso — APPROVED** [review]

**Comment by ktoso** [comment]
Not much to debate here, thanks!

**Comment by ktoso** [comment]
Refs #23749

**Comment by novacekm** [comment]
Thank you

**Comment by novacekm** [comment]
I've just sign the CLA.

**Pull request merged**
