### PR TITLE
Update stream-integrations.md

### PR DESCRIPTION
**Pull request by chbatey**
Fix link

### CODE REVIEW

**Comment by ktoso** [comment]
You both did the same PR @patriknw ;-)
https://github.com/akka/akka/pull/25168

Please pick one to merge

**Comment by ktoso** [comment]
This one shall be merged then

**Review by ktoso — APPROVED** [review]

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by raboof** [comment]
https://github.com/lightbend/paradox/issues/187 strikes again

**Pull request merged**
