### PR TITLE
!agnt #21423 agents to be deprecated

### PR DESCRIPTION
**Pull request by ktoso**
Refs https://github.com/akka/akka/issues/21423

Please look/correct at my wording though.

### CODE REVIEW

**Comment by patriknw** [comment]
Could you also start a migration guide for 2.5? For agents it's not much to migrate to, but we can say that it would be a good project to maintain outside akka.

**Review by patriknw — APPROVED** [review]
LGTM

**Review by drewhk — APPROVED** [review]

**Comment by ktoso** [comment]
That's already the migration guide: https://github.com/akka/akka/pull/21913/files#diff-ea1ddbe74d8e901615a13b1553a8d88eR7

Should I add it somewhere else?

**Comment by drewhk** [comment]
Another bites the dust.

**Comment by patriknw** [comment]
Oh, that's excellent. I skimmed to quickly

**Pull request merged**
