### PR TITLE
BehaviourTestKit: Add receptionist inbox

### PR DESCRIPTION
**Pull request by hsn10**
References #29292

### CODE REVIEW

**Review by johanandren — COMMENTED** [review]
A test case verifying that it works as expected would be good.

**Comment by johanandren** [comment]
The binary compatibility check failure in travis can be filtered, because we don't keep binary compatibility for the testkits. You can read how you do the filtering here: https://github.com/akka/akka/blob/master/CONTRIBUTING.md#binary-compatibility

**Comment by johanandren** [comment]
Just some formatting missing now, do a `akka-actor-testkit-typed/test:compile` and that should trigger the autoformatting

**Review by johanandren — APPROVED** [review]
LGTM!

**Review by ennru — APPROVED** [review]
LGTM.

**Comment by ennru** [comment]
Thank you for suggesting and implementing this!

**Pull request merged**
