### PR TITLE
[Docs] Fix scala snippet for Sink.combine #30431

### PR DESCRIPTION
**Pull request by jlprat**
Refs: #30431
Use correct syntax for including a multi language snippet

### CODE REVIEW

**Review by raboof — APPROVED** [review]
Oops, thanks!

**Comment by jlprat** [comment]
Failure was #30363

**Review by octonato — APPROVED** [review]
LGTM

**Comment by octonato** [comment]
I will merge since the failure is on the Scala 3 build (know to be flaky) and this is documentation related.

**Comment by jlprat** [comment]
Thanks for the reviews!

**Pull request merged**
