### PR TITLE
Fix minor text omissions in actor docs

### PR DESCRIPTION
**Pull request by leusgalvan**
I noticed the Actor page in the docs was lacking so words such as Future in some places. Removing some colons in the .md seems to fix it.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @leusgalvan,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by johanandren** [comment]
OK TO TEST

**Review by raboof — COMMENTED** [review]
That is super weird! I'm sure this worked at some point in the past. Now checking since when this stopped working - though I like that consistency, if the `@foo:[` notation is not working anymore we potentially might have to fix many more places.

**Review by patriknw — APPROVED** [review]
Good to fix this, also for consistency reasons.

We mixed usage of `@ref[` and `@ref:[` (I have never understood if there is any difference).

**Review by raboof — APPROVED** [review]
ah they're equivalent for `@ref` but not for `@java`/`@scala` and this is the only file where they snuck in :+1: https://github.com/lightbend/paradox/pull/213#issuecomment-399606720

Thanks!

**Comment by leusgalvan** [comment]
Glad to help :)

**Pull request merged**
