### PR TITLE
Do not try to resolve localhost with search domains 

### PR DESCRIPTION
**Pull request by johanandren**
References #30700

Seems very strange to me to always try to resolve localhost with all the search domains first.

Should it actually ever be resolved with search domains at all @raboof @jrudolph ?

### CODE REVIEW

**Comment by jrudolph** [comment]
Here are a few former comments on that topic:

https://github.com/akka/akka/pull/25987#issuecomment-442199535
https://github.com/akka/akka/pull/25987#discussion_r237733588

I think it might make sense to special case localhost resolution to avoid doing an actual lookup at least unless we support `/etc/hosts` (#25846).

In any case, we only support a somewhat arbitrary set of what you get by using libc host name resolution (e.g. see https://www.gabriel.urdhr.fr/2020/04/20/linux-host-name-resolution/) which has lots of other features which may or may not be assumed to work by users of Akka...

**Comment by jrudolph** [comment]
> I think it might make sense to special case localhost resolution to avoid doing an actual lookup at least unless we support `/etc/hosts` (#25846).

I.e. special case it more than done here. Going to a name server to resolve localhost can be a security risk so one should avoid it if possible.

**Comment by johanandren** [comment]
Also in https://datatracker.ietf.org/doc/html/rfc6761#section-6.3:
>  Name resolution APIs and libraries SHOULD recognize localhost
       names as special and SHOULD always return the IP loopback address
       for address queries and negative responses for all other query
       types.  Name resolution APIs SHOULD NOT send queries for
       localhost names to their configured caching DNS server(s).

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
