### PR TITLE
Drop the exec bit on non-executable files

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by ktoso** [comment]
Interesting - was this causing trouble for some tool?

LGTM

**Review by ktoso — APPROVED** [review]

**Comment by dwijnand** [comment]
Nope. I just noticed .gitignore and LICENSE where executable because they were bright green:
image

**Comment by ktoso** [comment]
Hah ok :) I guess won't hurt to fix that, thanks :)

**Comment by ktoso** [comment]
OK TO TEST

**Review by patriknw — APPROVED** [review]
LGTM, thanks

**Pull request merged**
