### PR TITLE
update mima url

### PR DESCRIPTION
**Pull request by xuwei-k**
## Purpose

update mima url

## Background Context

https://github.com/lightbend/mima/commit/906a81775d0972200291b9b5eff73a4bd86b8792#diff-04c6e90faac2675aa89e2176d2eec7d8

### CODE REVIEW

**Comment by chbatey** [comment]
OK TO TEST

**Review by chbatey — APPROVED** [review]
Thanks, LGTM

**Review by jrudolph — APPROVED** [review]
LGTM

**Review by raboof — APPROVED** [review]
Thanks!

**Pull request merged**
