### PR TITLE
Fix a few typos in akka-stream docs

### PR DESCRIPTION
**Pull request by sbrunk**
Went through the Akka Streams documentation. Stumbled upon a few typos along the way...

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Comment by johanandren** [comment]
LGTM! Thanks!

**Comment by 2beaucoup** [comment]
Did you check the respective java versions, too?

**Comment by sbrunk** [comment]
Ah didn't think of that. One typo was already fixed in the Java version. The others are updated now as well.

**Comment by ktoso** [comment]
Great, thanks a lot @sbrunk :)

**Pull request merged**
