### PR TITLE
use SimpleLinearGraphStage to reduce the boilerplate code

### PR DESCRIPTION
**Pull request by Hawstein**
Refs #21830

### CODE REVIEW

**Comment by Hawstein** [comment]
Ping. 
Does it make sense to merge this simple PR?

**Review by drewhk — APPROVED** [review]
LGTM

**Comment by drewhk** [comment]
OK TO TEST

**Comment by drewhk** [comment]
I will merge after validation passes.

**Review by ktoso — APPROVED** [review]
LGTM, thanks!

**Comment by Hawstein** [comment]
Jenkins threw the following error message: 

> error: pathspec 'master' did not match any file(s) known to git.

Not quite understand.

**Comment by drewhk** [comment]
Don't mind it, it is our Jenkins that has some issue. We will revalidate once Jenkins is OK again.

**Comment by jrudolph** [comment]
PLS BUILD

**Review by patriknw — APPROVED** [review]

**Pull request merged**
