### PR TITLE
Add getScheduler to ActorSystem #24900 

### PR DESCRIPTION
**Pull request by Seetaramayya**
Fixed [issue 24900](https://github.com/akka/akka/issues/24900)

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Review by ktoso — CHANGES_REQUESTED** [review]
It seemes @johanandren's request to move the methods was not applied here though, this looks like a plain copy of @satansk's PR?

Please see: https://github.com/akka/akka/pull/25012/ 
for the request to move them around.

So I think we're also missing them on `ActorSystem`

**Comment by hepin1989** [comment]
I will ping him.

**Comment by Seetaramayya** [comment]
Initially I miss read the issue, I thought `getScheduler` should be an alias to `context.system.scheduler`

I hope now my understanding is correct. Along with `getContext().getSystem().scheduler()` this new java like api should work `getContext().getSystem().getScheduler()`

**Review by johanandren — APPROVED** [review]
LGTM but the Scala/Javadoc should be amended

**Review by ktoso — APPROVED** [review]
LGTM, thanks :)

**Comment by ktoso** [comment]
OK TO TEST

**Pull request merged**
