### PR TITLE
tiny update to code as SI-6208 is resolved

### PR DESCRIPTION
**Pull request by KadekM**
Hi,

I've noticed this TODO while browsing sources - 
I don't know if for such tiny tiny thing I need to create issue (or even PR at all) but I thought I'll just give it a try

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @KadekM,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by ktoso** [comment]
OK TO TEST

**Comment by drewhk** [comment]
But this also needs a version update? Or the version used in master already has the fix?

**Comment by ktoso** [comment]
Thanks @KadekM - the PR is most welcome!

Looks good (LGTM), the https://issues.scala-lang.org/browse/SI-6208 issue was fixed on `2.10-M6` so we can safely change that line it seems now.

Could I ask you to sign our CLA (contributor agreement, you can do it online via github and the above linked page) and change the commit message to match our [contributing guidelines](https://github.com/akka/akka/blob/master/CONTRIBUTING.md) (i.e. `=act use filterNot directly since SI-6208 fixed`?

**Comment by KadekM** [comment]
I will do all that first thing tommorow, thanks for all the info!

**Comment by patriknw** [comment]
LGTM, thanks for contributing

**Comment by KadekM** [comment]
Signed CLA and changed commit message

**Comment by ktoso** [comment]
LGTM, thanks @KadekM!

**Pull request merged**
