### PR TITLE
=htp: fix test in FileAndResourceDirectivesSpec

### PR DESCRIPTION
**Pull request by aruediger**
fix for #18316

### CODE REVIEW

**Comment by jrudolph** [comment]
Btw. akka's commit message policy doesn't include the colon :)

**Comment by jrudolph** [comment]
PLS BUILD

**Comment by jrudolph** [comment]
OK TO TEST

**Comment by 2beaucoup** [comment]
> Btw. akka's commit message policy doesn't include the colon :)

Oops. Removed. ;)

**Comment by jrudolph** [comment]
jenkins still doesn't seem to obey to me :) @drewhk can you start the machine?

**Comment by ktoso** [comment]
@jrudolph weird, it should have hm...

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Nice, LGTM

**Comment by 2beaucoup** [comment]
My takeaway from this: Be careful when testing with IntelliJ. Right click / "run FileAndResourceDirec..." actually runs just `FileAndResourceDirectivesSpec.[the currently focused test]`. So be careful to focus the right one...

**Comment by jrudolph** [comment]
Thanks, @2beaucoup, good to know. Also, skipping PR validation is seldom a good idea :)

**Pull request merged**
