### PR TITLE
Fix grammar of sentence in Stream Rates doc

### PR DESCRIPTION
**Pull request by jayeve**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @jayeve,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by johanandren — APPROVED** [review]

**Comment by patriknw** [comment]
OK TO TEST

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by raboof** [comment]
Looks good! Just drop us a note when you've completed the CLA (should be a quick online verification), then we can merge!

**Comment by jayeve** [comment]
@raboof I've signed it. Thanks

**Comment by raboof** [comment]
Excellent, thanks!

**Pull request merged**
