### PR TITLE
Rebased: Document HTTP custom method (#20508)

### PR DESCRIPTION
**Pull request by ktoso**

### CODE REVIEW

**Comment by ktoso** [comment]
Resolves #20508

**Comment by ktoso** [comment]
The actual commit: 15c77e339230cc58be157a92a6eb0758b70606c6

**Comment by richard-imaoka** [comment]
Thank you very much @ktoso for taking care of rebase and merge!

**Comment by ktoso** [comment]
Not a problem, thanks for the contrib 👍 😎

**Pull request merged**
