### PR TITLE
Add scheme directive example in javadsl

### PR DESCRIPTION
**Pull request by fagossa**
Hi,
I translated the scheme example from Scala DSL to Java, following the instructions given in [issue 20466](https://github.com/akka/akka/issues/20466)

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @fagossa,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Thanks a lot for your help! Looks good :)
Have you been using the previous javadsl by any chance? I was curious how people like the new one :)

LGTM

**Comment by fagossa** [comment]
@ktoso This is the first time i try the javadsl
Anyways, the current dsl is quite cool

**Comment by ktoso** [comment]
Cool, glad to hear that!

LGTM :)

**Pull request merged**
