### PR TITLE
Fixes typo in docstring.

### PR DESCRIPTION
**Pull request by fgeller**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @fgeller,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by ktoso** [comment]
Hey @fgeller :)
Thanks for the contrib, good fix!
As much as I'd love to merge, I can't do that before you sign the CLA (contributor agreement).
Basically it's just a few clicks on the http://www.typesafe.com/contribute/cla site (you confirm with you github account).

Let us know if signed so we can merge this (and maybe future contribs?) :-)

**Comment by fgeller** [comment]
done!

**Comment by drewhk** [comment]
Thanks.

**Pull request merged**
