### PR TITLE
Fix indentation diffs

### PR DESCRIPTION
**Pull request by bantonsson**
These are changes that are produced by the source code formatter on compile that makes it look like there are diffs in the files.

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
LGTM, thanks @bantonsson !

**Comment by johanandren** [comment]
Not all of them it seems, this is how the formatting failures will look I guess? :)

**Comment by bantonsson** [comment]
Excellent! I'll rebase and retry.

**Comment by patriknw** [comment]
finally

**Pull request merged**
