### PR TITLE
=doc fixed part of scaladoc warnings

### PR DESCRIPTION
**Pull request by wlk**
I have fixed few scaladoc warnings (that appear after running `sbt doc` command locally).

Some of those warnings were appearing only when running `sbt doc` locally, and were not appearing on jenkins (but scaladoc was generated incorrectly)

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by wlk** [comment]
pushed again with fixed formatting

**Comment by ktoso** [comment]
LGTM

**Comment by patriknw** [comment]
LGTM, thanks a lot

**Pull request merged**
