### PR TITLE
Remove the JUnit test runner

### PR DESCRIPTION
**Pull request by johanandren**
All our tests are scalatest JUnitSuites so are picked up by the scalatest runner

This makes it so we only run tests once (and subsequently only are listed once in jenkins)

Bad part: the timing of the JunitSuite tests are not reported for some reason. Not sure if that matters as most tests where we care are in *Specs where timing is reported.

### CODE REVIEW

**Comment by patriknw** [comment]
and you have verified that the actual junit *Test.java are running with this, I know we have had problems with that previously (but we have probably updated scalatest since then)

**Comment by johanandren** [comment]
Yep, made a unit test fail, also, counted the test reports from before the change and after to see it found the same classes.

**Comment by johanandren** [comment]
Didn't manage to figure out why the duplicated test report files manifested first when we enabled forked tests though.

**Review by patriknw — APPROVED** [review]
LGTM

**Review by 2m — APPROVED** [review]

**Comment by johanandren** [comment]
sbt file formatting!?! #?€%

**Pull request merged**
