### PR TITLE
Don't automatically down quarantined node, #25632

### PR DESCRIPTION
**Pull request by patriknw**
Refs #25632

I'll setup a repeat job for this.

### CODE REVIEW

**Comment by patriknw** [comment]
As mentioned in the ticket, it will remain as Unreachable (Terminated, which means that it can't go back to Reachable) and then the ordinary downing provider has to act on that.

**Review by chbatey — APPROVED** [review]
LGTM

**Review by johanandren — COMMENTED** [review]
Should it be mentioned somewhere in the docs? I looked for quarantine and there is no mention of the downing of quarantined as far as I can see.

**Comment by patriknw** [comment]
What would we document? That we are not downing? I think the expectation should be that we never down automatically.

**Review by johanandren — APPROVED** [review]
Fair point. LGTM then

**Pull request merged**
