### PR TITLE
!str #15851 Rename FlowMaterializer and settings

### PR DESCRIPTION
**Pull request by patriknw**
- FlowMaterializer is now the actor independent interface
- ActorFlowMaterializer is the actor based interface
- MaterializerSettings renamed to ActorFlowMaterializerSettings
- impl.ActorBasedFlowMaterializer renamed to impl.ActorFlowMaterializerImpl
- Optimizations included in ActorFlowMaterializerSettings
- Note that http is using FlowMaterializer in api, but I suspect that it
  will currently only run with a ActorFlowMaterializer

### CODE REVIEW

**Comment by patriknw** [comment]
Refs #15851

**Comment by drewhk** [comment]
I think this should be merged soon.

**Comment by ktoso** [comment]
LGTM

**Comment by patriknw** [comment]
alright, seems to still merge

**Comment by ktoso** [comment]
Note for our future selves :wink: :
Such renames should also be applied in `akka-bench-jmh`. Good that compiling it is now in [pr validation ](https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/1851/console) :)

**Comment by patriknw** [comment]
ah, missed that one, as usual

**Pull request merged**
