### PR TITLE
=doc add clarification on ActorSelection vs. ActorRef

### PR DESCRIPTION
**Pull request by rkuhn**

### CODE REVIEW

**Comment by patriknw** [comment]
java8 doc also?
otherwise, LGTM

**Comment by rkuhn** [comment]
aargh, of course, thanks for noticing

**Comment by ktoso** [comment]
Now that all 3 files touched LGTM :)

**Comment by rkuhn** [comment]
cherry-picked onto release-2.3

**Comment by rkuhn** [comment]
commit: a084f85a4a1a1f15c4f3d83b033f5f25f8eea583

**Pull request merged**
