### PR TITLE
=htp #18632 check ports of URI and Host header in effectiveUri

### PR DESCRIPTION
**Pull request by aruediger**

### CODE REVIEW

**Comment by ktoso** [comment]
Refs #18632

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Thanks a lot for the fix @2beaucoup!
Failure was unrelated Tls spec failure,
LGTM!

**Comment by ktoso** [comment]
I must have been tired / blind, the failure is a real one. Opening a ticket for it and will fix.

**Comment by drewhk** [comment]
does seem like a simple toString problem

**Pull request merged**
