### PR TITLE
benchmark: ByteString append and builder

### PR DESCRIPTION
**Pull request by patriknw**
* and optimizing ByteStringBuilder for single element

I just wanted to see the difference between using `++` and the builder since we often concatenate in hot paths.

This is already very  fast  so  probably  doesn't matter, but a few places we could consider using the builder would be:
* writeBuffer in TcpStreamLogic
* Framing
* ByteIterator

The builder is beneficial for >= 3 elements.

```
BEFORE

[info] Benchmark                                                               Mode  Cnt       Score       Error   Units
[info] ByteString_append_Benchmark.appendMany                                 thrpt    5   40388,991 ±  3819,496  ops/ms
[info] ByteString_append_Benchmark.appendMany:·gc.alloc.rate                  thrpt    5    6067,624 ±   574,080  MB/sec
[info] ByteString_append_Benchmark.appendMany:·gc.alloc.rate.norm             thrpt    5     165,480 ±     0,001    B/op
[info] ByteString_append_Benchmark.appendThree                                thrpt    5   39992,390 ±   612,897  ops/ms
[info] ByteString_append_Benchmark.appendThree:·gc.alloc.rate                 thrpt    5    2999,260 ±    46,793  MB/sec
[info] ByteString_append_Benchmark.appendThree:·gc.alloc.rate.norm            thrpt    5      82,584 ±     0,001    B/op
[info] ByteString_append_Benchmark.builderFive                                thrpt    5   82569,853 ±   761,744  ops/ms
[info] ByteString_append_Benchmark.builderFive:·gc.alloc.rate                 thrpt    5    5169,880 ±    46,115  MB/sec
[info] ByteString_append_Benchmark.builderFive:·gc.alloc.rate.norm            thrpt    5      68,960 ±     0,001    B/op
[info] ByteString_append_Benchmark.builderMany                                thrpt    5  124046,938 ± 11314,488  ops/ms
[info] ByteString_append_Benchmark.builderMany:·gc.alloc.rate                 thrpt    5    3275,488 ±   298,279  MB/sec
[info] ByteString_append_Benchmark.builderMany:·gc.alloc.rate.norm            thrpt    5      29,080 ±     0,001    B/op
[info] ByteString_append_Benchmark.builderOne                                 thrpt    5   34363,313 ±   618,450  ops/ms
[info] ByteString_append_Benchmark.builderOne:·gc.alloc.rate                  thrpt    5    6496,140 ±   115,898  MB/sec
[info] ByteString_append_Benchmark.builderOne:·gc.alloc.rate.norm             thrpt    5     208,200 ±     0,001    B/op
[info] ByteString_append_Benchmark.builderThree                               thrpt    5   66551,593 ±  4366,640  ops/ms
[info] ByteString_append_Benchmark.builderThree:·gc.alloc.rate                thrpt    5    5820,572 ±   382,703  MB/sec
[info] ByteString_append_Benchmark.builderThree:·gc.alloc.rate.norm           thrpt    5      96,312 ±     0,001    B/op

AFTER

[info] Benchmark                                                               Mode  Cnt       Score      Error   Units
[info] ByteString_append_Benchmark.appendMany                                 thrpt    5   43570,573 ± 1363,038  ops/ms
[info] ByteString_append_Benchmark.appendMany:·gc.alloc.rate                  thrpt    5    6547,023 ±  201,526  MB/sec
[info] ByteString_append_Benchmark.appendMany:·gc.alloc.rate.norm             thrpt    5     165,480 ±    0,001    B/op
[info] ByteString_append_Benchmark.appendThree                                thrpt    5   39609,408 ± 3228,067  ops/ms
[info] ByteString_append_Benchmark.appendThree:·gc.alloc.rate                 thrpt    5    2970,065 ±  242,944  MB/sec
[info] ByteString_append_Benchmark.appendThree:·gc.alloc.rate.norm            thrpt    5      82,584 ±    0,001    B/op
[info] ByteString_append_Benchmark.builderFive                                thrpt    5   65840,422 ± 3062,267  ops/ms
[info] ByteString_append_Benchmark.builderFive:·gc.alloc.rate                 thrpt    5    4778,907 ±  221,106  MB/sec
[info] ByteString_append_Benchmark.builderFive:·gc.alloc.rate.norm            thrpt    5      79,936 ±    0,001    B/op
[info] ByteString_append_Benchmark.builderMany                                thrpt    5  115905,807 ± 8981,791  ops/ms
[info] ByteString_append_Benchmark.builderMany:·gc.alloc.rate                 thrpt    5    3060,382 ±  233,673  MB/sec
[info] ByteString_append_Benchmark.builderMany:·gc.alloc.rate.norm            thrpt    5      29,088 ±    0,001    B/op
[info] ByteString_append_Benchmark.builderOne                                 thrpt    5   83495,350 ± 1355,211  ops/ms
[info] ByteString_append_Benchmark.builderOne:·gc.alloc.rate                  thrpt    5       3,033 ±    0,050  MB/sec
[info] ByteString_append_Benchmark.builderOne:·gc.alloc.rate.norm             thrpt    5       0,040 ±    0,001    B/op
[info] ByteString_append_Benchmark.builderThree                               thrpt    5   55082,698 ± 2190,908  ops/ms
[info] ByteString_append_Benchmark.builderThree:·gc.alloc.rate                thrpt    5    5730,601 ±  227,773  MB/sec
[info] ByteString_append_Benchmark.builderThree:·gc.alloc.rate.norm           thrpt    5     114,592 ±    0,001    B/op
```

### CODE REVIEW

**Comment by johanandren** [comment]
Those results doesn't look very conclusive to me, within error margins? (Also, curious that the allocation rates differs but the normalized doesn't, was it really run the same number of iterations?)

**Comment by patriknw** [comment]
What I was comparing was appendMany vs builderMany, appendThree vs builderThree. The builder is much better, aside from < 3 elements. That's why I was asking if we should use the builder at more places, since we tend to just use `++`.

Then I optimized for the single element case. BEFORE vs AFTER of builderOne. That is good for one element but maybe too much slowdown for more elements. It's also adding some more complexity to that builder and I'm leaning towards that the optimization is not worth it.

However, my suggestion is that we should use the builder at more places where we know that it's likely that we are appending more than 2 elements.

> Also, curious that the allocation rates differs but the normalized doesn't, was it really run the same number of iterations?

I ran this with
```
jmh:run -prof gc -i 5 -wi 3 -f 1 akka.util.ByteString_append_Benchmark
```

**Comment by johanandren** [comment]
Aha, gotcha, yeah, then I agree it could be worth it at least for the TCP and framing operators

**Comment by jrudolph** [comment]
> However, my suggestion is that we should use the builder at more places where we know that it's likely that we are appending more than 2 elements.

Yes, you should always use the builder in places where mutability is acceptable. In general, concatenating small ByteStrings is really expensive (e.g. akka-grpc concatenates to a constant one-byte ByteString). I didn't measure but a single element Vector has an overhead of 150-200 bytes (with CompressedOops, double that otherwise), most will be zero and therefore cheap to initialize but it still creates considerable memory pressure. 

So, that's also something we can optimize in `ByteString.++`, if the resulting ByteString is smaller than some threshold, it probably makes more sense to copy and create a new `ByteString1C` than a `ByteStrings`. Still better to use builder there if you expect this to happen.

**Comment by patriknw** [comment]
Reverted the optimization attempt since it probably added too much code complexity. Only includes an additional JMH test now.

**Review by johanandren — APPROVED** [review]

**Review by jrudolph — APPROVED** [review]
LGTM

**Pull request merged**
