### PR TITLE
Fixed the bug in Attributes.getFirst(default : T) #21658

### PR DESCRIPTION
**Pull request by BayStallion**
Added a few new test cases covering get and getFirst methods with default parameters and fixed a bug in getFirst implementation.

### CODE REVIEW

**Comment by drewhk** [comment]
OK TO TEST

**Review by drewhk — APPROVED** [review]
LGTM, thanks for fixing this!

**Comment by BayStallion** [comment]
Can I get the build log to see the errors? The Details link does not open for me.

**Comment by drewhk** [comment]
Weird issue, it has nothing to do with your code as it did not get even to compilation. Some Git hiccup.

**Comment by drewhk** [comment]
PLS BUILD

**Comment by ktoso** [comment]
> Can I get the build log to see the errors? The Details link does not open for me.
 
Details link should work (I tried while being logged out of jenkins etc): 
fixed_the_bug_in_attributes_getfirst_default___t___21658_by_baystallion_ _pull_request__21846_ _akka_akka

**Review by ktoso — APPROVED** [review]
LGTM, thanks a lot also for the nice tests 👍

**Comment by BayStallion** [comment]
@ktoso @drewhk No problem at all :)

**Comment by BayStallion** [comment]
@ktoso I've tried this link already, it doesn't open for me unfortunately

**Comment by BayStallion** [comment]
What sort of problem is it? Should I probably update my branch with the latest commits from akka/master? Seems like there've been added a few more since the last time I updated.

**Comment by drewhk** [comment]
> @ktoso I've tried this link already, it doesn't open for me unfortunately

Company firewall blocking HTTP ports not on `80` or `443`?

**Comment by drewhk** [comment]
I don't think your PR has anything to do with the Git issue. We see some Git errors once in a while...

**Comment by BayStallion** [comment]
PLS BUILD

**Comment by BayStallion** [comment]
Can one of the repo owners merge this pull request please?

**Comment by ktoso** [comment]
LGTM, shall we merge for 2.4.14?

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
@ktoso yes, we can include this in 2.4.14

**Review by johanandren — APPROVED** [review]

**Comment by ktoso** [comment]
Good 👍 
Thanks @BayStallion !

**Comment by ktoso** [comment]
Resolves #21658

**Comment by BayStallion** [comment]
@ktoso Pleasure is all mine ;)

**Pull request merged**
