### PR TITLE
More debugging statements for RestartSpec

### PR DESCRIPTION
**Pull request by ktoso**
Was not able to reproduce or figure out the issue, need a reproducer log from jenkins which this will enable. Shall we just merge (it's not super verbose), or just run the branch for a while?

### CODE REVIEW

**Comment by ktoso** [comment]
Refs, but does not solve, https://github.com/akka/akka/issues/23593

**Comment by ktoso** [comment]
PLS BUILD

**Review by johanandren — APPROVED** [review]
LGTM

**Comment by ktoso** [comment]
FYI I have a repeat job with this that failed twice, so don't merge yet, will analyse those failures first.

**Comment by raboof** [comment]
@ktoso do you have a link to those repeat job failures?

**Comment by ktoso** [comment]
Here's another one yeah: https://jenkins.akka.io:8498/job/akka-multi-node-repeat/15130/consoleFull

Did not get to look at it again though...

**Comment by ktoso** [comment]
Closing this, @patriknw is looking at it now

**Pull request closed without merging**
