### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
Correct the grammar.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @dhiru30,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by dhiru30** [comment]
I have signed CLA.

**Review by raboof — APPROVED** [review]
Thanks ;)

**Comment by dhiru30** [comment]
@raboof  Thanks !!!

**Pull request merged**
