### PR TITLE
=sam #17104 use SilenceSystemOut in tests

### LINKED ISSUE #17104: Silence printing to stdout in documentation sample code
[Discussion](https://github.com/akka/akka/pull/17072#discussion-diff-27401712).

### PR DESCRIPTION
**Pull request by 2m**
Resolves #17104

### CODE REVIEW

**Comment by ktoso** [comment]
LGTM (I love this trick <3)

**Comment by drewhk** [comment]
LGTM

**Comment by 2m** [comment]
Test failure unrelated. It looks like `assertAllStagesStopped` failed in akka-http-core-experimental/ClientServerSpec

**Comment by drewhk** [comment]
That test might be flaky, since it relies on the panic mode of the materializer if there is an Exception during materialization itself. This is best-effort, and might fail to clean up all stages properly. Maybe that test needs assertAllStagesStopped to be removed.

**Pull request merged**
