### PR TITLE
Update missing Mima filters in master for recently released 2.4.x versions

### PR DESCRIPTION
**Pull request by jrudolph**
Forward port of changes in #22311 + some extra cleanup and comments.

Refs #22306

### CODE REVIEW

**Comment by jrudolph** [comment]
Seems to be missing already a few 2.5 incompatible changes, which I will add.

**Comment by jrudolph** [comment]
PLS BUILD

**Review by drewhk — APPROVED** [review]

**Comment by jrudolph** [comment]
I removed the extra filters I added while waiting for the serialization changes forward-port in #22283, so now this has to be merged after #22283. (And PR validation should fail before)

**Comment by jrudolph** [comment]
As this doesn't seem to validate, I'll close and recreate this PR.

**Pull request closed without merging**
