### PR TITLE
Refactor First and Join seed node processes to shared logic for dry and logic hardening

### PR DESCRIPTION
**Pull request by helena**
* Removes much duplication in seed logic. 
* The separation out to a new file was suggested here https://github.com/akka/akka/pull/28084#discussion_r340199314
 
Originated in https://github.com/akka/akka/pull/28084, sat around since October 28. Cleaner for reviewing in new PR.

### CODE REVIEW

**Comment by helena** [comment]
@patriknw @raboof

**Comment by helena** [comment]
Running against a multi-node-repeat job over the weekend.

**Review by patriknw — APPROVED** [review]
LGTM, were there any more changes than moving to separate file in this PR compared to the previous https://github.com/akka/akka/pull/28084? I think I did a rather thorough side by side comparison in previous PR and it looked good. Don't want to spend time on that again if nothing changed.

**Comment by helena** [comment]
@patriknw The only change is two lines in `JoinSeedNode` that log with structured logging.

**Comment by patriknw** [comment]
thanks, lgtm

**Review by raboof — APPROVED** [review]
:tada:

**Pull request merged**
