### PR TITLE
Port WithLogCapturing + Silence TLSSpec

### PR DESCRIPTION
**Pull request by jrudolph**

### CODE REVIEW

**Comment by johanandren** [comment]
OMG OMG!

**Comment by jrudolph** [comment]
Now also for the noisy `CoordinatedShutdownShardingSpec`.

**Comment by jrudolph** [comment]
Failed with whitesource error...

PLS BUILD

**Comment by ktoso** [comment]
Yay, LGTM

**Review by patriknw — COMMENTED** [review]
Awesome, thanks. Let's start to gradually use this at more places.

**Pull request merged**
