### PR TITLE
Correct cluster sharding docs sample link

### LINKED ISSUE #23759: Incorrect sample in 2.5.6 Cluster Sharding docs
The first sample under https://doc.akka.io/docs/akka/2.5.6/scala/cluster-sharding.html#an-example displays a sample from the recent doc on clusters across multiple data centers, instead of an example for how an entity may look.

For comparison with 2.5.4: https://doc.akka.io/docs/akka/2.5.4/scala/cluster-sharding.html#an-example

### PR DESCRIPTION
**Pull request by DanielMoss**
Fixes #23759

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @DanielMoss,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by johanandren** [comment]
OK TO TEST

**Review by johanandren — APPROVED** [review]
LGTM, thanks! I wonder how that could have snuck in....

**Review by raboof — APPROVED** [review]
Jup, weird mistake in 87d74f1510e I suppose.

**Pull request merged**
