### PR TITLE
+act #17257 add Actor.ignoringBehavior

### PR DESCRIPTION
**Pull request by He-Pin**
refs https://github.com/akka/akka/issues/17257

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
LGTM, let's merge after https://github.com/akka/akka/pull/17202 though so that we can update this line: https://github.com/akka/akka/pull/17202/files#diff-71694a11312b3a3c3df0b7bf674f7ee7R1344 right away to use this object.

**Comment by ktoso** [comment]
Hi @hepin1989, would you like to update lines in #17202 so that they make use of this new toy? :-)

(Discussion was: https://github.com/akka/akka/pull/17202#discussion-diff-28493470R1344 )

Thanks in advance!

**Comment by hepin1989** [comment]
the code you point is in release-2.3,so I open a new pr here https://github.com/akka/akka/pull/17309
I think we could close this one?

**Comment by patriknw** [comment]
I don't think this qualifies to release-2.3, corresponding code for ClusterSharding exists in master

**Comment by hepin1989** [comment]
yes,I located it:P will update .

**Comment by rkuhn** [comment]
Thanks, @hepin1989 !

**Pull request merged**
