### PR TITLE
Reset `pendingSend` on address resolution failure #22076

### PR DESCRIPTION
**Pull request by tIGO**

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by tIGO** [comment]
Is it an issue with my code or just flaky tests (can't see link to ci results).

**Comment by jrudolph** [comment]
PLS BUILD

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Review by drewhk — APPROVED** [review]
LGTM

**Comment by johanandren** [comment]
Refs #22076

**Pull request merged**
