### PR TITLE
deprecate akka-contrib, #22198

### PR DESCRIPTION
**Pull request by patriknw**
Refs #22198

Deprecate all things in akka-contrib

### CODE REVIEW

**Comment by ktoso** [comment]
Yeah I absolutely agree, those that did not get promoted should be deprecated. Seems none of these have achieved heavy usage in the field - and if they did we'll hear about it this way.

LGTM

**Review by johanandren — APPROVED** [review]
LGTM!

**Comment by patriknw** [comment]
Unrelated failure, created issue https://github.com/akka/akka/issues/22365

**Comment by patriknw** [comment]
PLS BUILD

**Comment by patriknw** [comment]
one more time, perhaps GC?

     [Times: user=98.73 sys=0.09, real=3.08 secs]

**Comment by patriknw** [comment]
PLS BUILD

**Pull request merged**
