### PR TITLE
Use java.util.function.Predicate for Stash Java API

### PR DESCRIPTION
**Pull request by octonato**

### CODE REVIEW

**Review by patriknw — APPROVED** [review]
LGTM, thanks for following up

**Review by johanandren — APPROVED** [review]

**Review by raboof — COMMENTED** [review]
so the difference is `akka.japi.function.Predicate` allows throwing checked exceptions from the predicate body while `java.util.function.Predicate` does not - and I guess we don't expect exceptions to be thrown from predicates here?

**Comment by patriknw** [comment]
> so the difference is akka.japi.function.Predicate allows throwing checked exceptions from the predicate body while java.util.function.Predicate does not - and I guess we don't expect exceptions to be thrown from predicates here?

That is right. We should prefer java.util.function in new API if we don't have a reason for not using it.
The other reason can be variance differences.
For users it normally doesn't matter, since they will use a lambda.
See also https://github.com/akka/akka/issues/25775

**Comment by octonato** [comment]
Closed and re-open because CLA validator didn't recognize me after vacation.

**Pull request merged**
