### PR TITLE
Rebased pull 16537 - Constant value made a val to avoid unnecessary allocation

### PR DESCRIPTION
**Pull request by Arneball**
https://github.com/akka/akka/pull/16537

### CODE REVIEW

**Comment by ktoso** [comment]
Superseeded by https://github.com/akka/akka/pull/16595

**Comment by Arneball** [comment]
This is to the 2.3-branch and the other one is master. Maybe doesn't matter.

**Comment by ktoso** [comment]
Oh, thanks - didn't notice that difference.
So in order for this to be OK to merge into `2.3` it needs to be binary compatible (must not change public API like this commit does), which this line is not: https://github.com/akka/akka/pull/16594/files#diff-cf2c23f405ce790a43c6817e6b9cae93R329

Would you mind updating this commit so that it only moves the exception to the val, without changing the signature of that `apply` method?

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Thanks, LGTM!

**Comment by ktoso** [comment]
Thanks for the contribution @Arneball!

**Pull request merged**
