### PR TITLE
align package structure in http javadsl

### PR DESCRIPTION
**Pull request by Hawstein**
Ref #20945

### CODE REVIEW

**Comment by Hawstein** [comment]
Now the structure under `akka.http.javadsl` package is:

```
./
├── marshalling
│   └── Marshaller.scala
├── server
│   ├── Directives.scala
│   ├── ExceptionHandler.scala
│   ├── PathMatchers.scala
│   ├── RejectionHandler.scala
│   ├── Rejections.scala
│   ├── RequestContext.scala
│   ├── Route.scala
│   ├── RouteResult.scala
│   ├── RoutingJavaMapping.scala
│   └── directives
│       ├── BasicDirectives.scala
│       ├── CacheConditionDirectives.scala
│       ├── CodingDirectives.scala
│       ├── CookieDirectives.scala
│       ├── DebuggingDirectives.scala
│       ├── ExecutionDirectives.scala
│       ├── FileAndResourceDirectives.scala
│       ├── FileUploadDirectives.scala
│       ├── FormFieldDirectives.scala
│       ├── FutureDirectives.scala
│       ├── HeaderDirectives.scala
│       ├── HostDirectives.scala
│       ├── MarshallingDirectives.scala
│       ├── MethodDirectives.scala
│       ├── MiscDirectives.scala
│       ├── ParameterDirectives.scala
│       ├── PathDirectives.scala
│       ├── RangeDirectives.scala
│       ├── RespondWithDirectives.scala
│       ├── RouteAdapter.scala
│       ├── RouteDirectives.scala
│       ├── SchemeDirectives.scala
│       ├── SecurityDirectives.scala
│       ├── TimeoutDirectives.scala
│       └── WebSocketDirectives.scala
└── unmarshalling
    ├── StringUnmarshaller.scala
    └── Unmarshaller.scala
```

**Comment by ktoso** [comment]
OK TO TEST

**Comment by Hawstein** [comment]
@ktoso Jenkins said that the `multiNodeTest` is failed, however I can't reproduce it on my laptop. any suggestions?

**Comment by Hawstein** [comment]
hmm, caused by this PR #20964

**Comment by ktoso** [comment]
Ignore that failure, I'll look at it. Weird because the test works well on
the other build,
Must be a config difference.

-- 
Konrad Malawski

From: Hawstein <notifications@github.com> <notifications@github.com>
Reply: akka/akka
<reply@reply.github.com>
<reply@reply.github.com>
Date: 16 July 2016 at 21:08:44
To: akka/akka <akka@noreply.github.com> <akka@noreply.github.com>
CC: Konrad Malawski <konrad.malawski@lightbend.com>
<konrad.malawski@lightbend.com>, Mention <mention@noreply.github.com>
<mention@noreply.github.com>
Subject:  Re: [akka/akka] align package structure in http javadsl (#20966)

hmm, caused by this PR #20964 <https://github.com/akka/akka/pull/20964>

**Comment by ktoso** [comment]
PLS BUILD

**Comment by ktoso** [comment]
Move looks good. Need to carefully pick when to merge this, will figure it out today

**Comment by ktoso** [comment]
I'm working towards merging this one by merging all other HTTP PRs by the community, then this, and then some of our stuff

**Comment by johanandren** [comment]
Closing as I have taken this over

**Pull request closed without merging**
