### PR TITLE
#24097 Try a few times to get an exception

### LINKED ISSUE #24097: Failed: OutputStreamSourceSpec
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/10866/testReport/junit/akka.stream.io/OutputStreamSourceSpec/OutputStreamSource_must_throw_IOException_when_writing_to_the_stream_after_the_subscriber_has_cancelled_the_reactive_stream/

``` 
sbt.ForkMain$ForkError: org.scalatest.exceptions.TestFailedException: Expected exception java.lang.Exception to be thrown, but no exception was thrown
	at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:138)
	at org.scalatest.MatchersHelper$.checkExpectedException(MatchersHelper.scala:316)
	at org.scalatest.words.ResultOfTheTypeInvocation.thrownBy(ResultOfTheTypeInvocation.scala:39)
	at akka.stream.io.OutputStreamSourceSpec$$anonfun$2$$anonfun$apply$mcV$sp$9$$anonfun$apply$12.apply(OutputStreamSourceSpec.scala:163)
	at akka.stream.io.OutputStreamSourceSpec$$anonfun$2$$anonfun$apply$mcV$sp$9$$anonfun$apply$12.apply(OutputStreamSourceSpec.scala:148)
	at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:25)
	at akka.stream.io.OutputStreamSourceSpec$$anonfun$2$$anonfun$apply$mcV$sp$9.apply(OutputStreamSourceSpec.scala:148)
	at akka.stream.io.OutputStreamSourceSpec$$anonfun$2$$anonfun$apply$mcV$sp$9.apply(OutputStreamSourceSpec.scala:148)
```

### PR DESCRIPTION
**Pull request by 2m**
Fixes #24097

### CODE REVIEW

**Comment by chbatey** [comment]
PLS BUILD

**Review by chbatey — APPROVED** [review]
LGTM

**Comment by chbatey** [comment]
PLS BUILD

**Review by raboof — APPROVED** [review]
Sounds like it makes sense

**Comment by johanandren** [comment]
So was the test based on an incorrect assumption, is there a race or why do we need to try again for a while?

**Comment by johanandren** [comment]
Isn't this a stage that should use `invokeWithFeedback` instead of building its own promise-that-may-be-never-completed-because-stage-stopped logic in `wakeup`?

**Comment by 2m** [comment]
There is a race between cancelling and when the materialized java streams becomes unwritable. I'll take a look if the stage can be redone using `invokeWithFeedback`.

**Comment by 2m** [comment]
I do not think it is going to fly. `invokeWithFeedback` promise is completed as soon as the handler has been successfully called. But the stage in question either completes the promise right away in the handler, or a bit later after onPush.

**Comment by johanandren** [comment]
I think it needs to do both? If the `invokeWithFeedback` promise is failed with stream-detached, then that should fail or complete the promise from this stage as well.

**Comment by 2m** [comment]
I see what you mean. I have played around with it and observed the following:

The promise, that is being created in `wakeUp` does not leak outside of the stage and the adapter. And that promise future is only used by `Await.ready` in the adapter with a timeout. So even if the stage fails while Await.ready is being called, the timeout will kick in.

The stage could do `invokeWithFeedback` and fail the `wakeUp` promise if the feedback future fails. That would allow for things to stop quicker on failure. However only in a very specific scenario, where the stage stops before the async callback even is processed. Therefore I think it is not worth the complexity.

**Comment by johanandren** [comment]
Otoh, if it used invokeWithFeedback onFail it wouldn't need the timeout anymore?

**Comment by johanandren** [comment]
Or maybe I'm wrong. Thanks for looking into it though. I guess the test update is fine then :)

**Comment by 2m** [comment]
The timeout is still needed when the feedback future is completed
successfully.

**Review by johanandren — APPROVED** [review]
LGTM

**Pull request merged**
