### PR TITLE
Add gradle to all dependency doc sections

### PR DESCRIPTION
**Pull request by chbatey**

### CODE REVIEW

**Comment by raboof** [comment]
This might overlap with #25010 here and there?

**Comment by chbatey** [comment]
Ya i'll let that one go through first

**Review by patriknw — APPROVED** [review]
LGTM

**Review by johanandren — APPROVED** [review]
LGTM!

**Comment by johanandren** [comment]
D'oh! The waiting for #25010 I missed out on...

**Comment by johanandren** [comment]
Should we revert this one so that the other one can go in first?

**Comment by patriknw** [comment]
yes, probably best to revert, isn't that one superseding this one?
We could also ask @richardimaoka to revert in his PR, since it needs a rebase anyway?

**Pull request merged**
