### PR TITLE
Docs: Fixing sbt deprecation warning

### PR DESCRIPTION
**Pull request by sjoerdmulder**
warning: `<<=` operator is deprecated. Use `key := { x.value }`
See http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @sjoerdmulder,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by sjoerdmulder** [comment]
Just signed the CLA

**Comment by ktoso** [comment]
OK TO TEST

**Review by ktoso — APPROVED** [review]
LGTM I think, thanks! Let's have the PR be validated though

**Comment by ktoso** [comment]
Thanks!

**Comment by patriknw** [comment]
Please verify that multi-jvm classes are compiled by test:compile (eg intoduce a fake compilation error). That was the reason we kept the old way, but I think it has been fixed in sbt.

**Pull request merged**
