### PR TITLE
Migrate PushStages in LifecycleInterpreterSpec to GraphStages #19834.

### PR DESCRIPTION
**Pull request by danxmoran**
Includes:
- PreStartAndPostStopIdentity
- PreStartFailer
- PostStopFailer
- PushFinishStage

### CODE REVIEW

**Comment by danxmoran** [comment]
Ref #19834

**Comment by ktoso** [comment]
OK TO TEST

**Comment by johanandren** [comment]
LGTM

**Comment by patriknw** [comment]
LGTM, thanks @danxmoran

**Pull request merged**
