### PR TITLE
Fix handling of escape sequences in JsonObjectParser #21961

### PR DESCRIPTION
**Pull request by andrewrapp**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @andrewrapp,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Refs https://github.com/akka/akka/issues/21961

**Review by ktoso — COMMENTED** [review]
Thanks! Would you please add a test for this case in  `JsonFramingSpec`?

**Review by drewhk — DISMISSED** [review]
Needs a unit test for the original failure and cases like "\\\", otherwise looks correct.

**Comment by andrewrapp** [comment]
@ktoso I'm on it

**Comment by ktoso** [comment]
Thanks a lot for adding the test, LGTM

**Comment by ktoso** [comment]
I'll backport

**Pull request merged**
