### PR TITLE
New JavaDSL for Akka HTTP finally there

### PR DESCRIPTION
**Pull request by ktoso**
Rebased what previously was #20088 and #20470

Resolves #19632 #19519

### CODE REVIEW

**Comment by jypma** [comment]
Thank you guys so much for all of the effort of pulling this through.

**Comment by ktoso** [comment]
Error was silly missing import which caused compile failure. Pushed fix.

**Comment by ktoso** [comment]
> Thank you guys so much for all of the effort of pulling this through.

That's what we're here for one could say :-)
Thanks for kicking it off!

**Comment by ktoso** [comment]
PLS BUILD

**Comment by johanandren** [comment]
```[info] - should define Scala directive [stringNameOptionReceptacle2PathMatcher] for JavaDSL too *** FAILED *** (0 milliseconds)
[info]   java.lang.Exception: Unable to locate method [stringNameOptionReceptacle2PathMatcher] on source class interface akka.http.scaladsl.server.Directives
```

and 
```
[error] Could not run test akka.http.javadsl.server.directives.CodingDirectivesTest: java.lang.IllegalArgumentException: ActorRefFactory context must be defined
```

**Comment by ktoso** [comment]
Thanks for pulling out the failures, 1st I recognise, trivial fix, looking at 2nd...

**Comment by johanandren** [comment]
Had no idea about the first one so that's why I didn't fix them

**Comment by ktoso** [comment]
You'll laugh, but fix is to prefix with underscore so consistency spec excludes it from checking for feature parity...

**Comment by ktoso** [comment]
`akka.remote.RemotingSpec` failed, thus... unrelated! Can I merge?

cc @patriknw @drewhk @johanandren

**Comment by johanandren** [comment]
YEA! LOOKS AWESOME TO ME! 🎆 🎉 🎈

**Comment by patriknw** [comment]
PLS BUILD

**Comment by patriknw** [comment]
awesome, I just want to see it green before merging

**Comment by johanandren** [comment]
Don't merge this PR on green, will selectively rebase-squash and create a new PR since commit history is so messy.

**Comment by johanandren** [comment]
Hmm, that is weird. its `akka.http.javadsl.DirectivesConsistencySpec` failing about `concat` missing, but that is passing locally for me.

**Comment by johanandren** [comment]
Fixing that is the last thing Konrad pushed yesterday. So why did it run without that fix?

**Comment by johanandren** [comment]
Closing this as it is superseeded by PR #20518

**Pull request closed without merging**
