### PR TITLE
Modified iff statements from JavaDSL/Flow.scala

### PR DESCRIPTION
**Pull request by Prsna23**
Added fix for #25486

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @Prsna23,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by raboof** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]
Seems clearer to me!

**Review by johanandren — APPROVED** [review]
A little bit clearer to me, thanks.

**Pull request merged**
