### PR TITLE
BehaviorTestKit - hasEffects and expectEffectPF

### PR DESCRIPTION
**Pull request by chbatey**
I didn't add the partial function API to the javadsl, didn't seem very javary. Tho in untyped I see we have it on the testkit but not on the test probe.

Refs #24781

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
LGTM

**Comment by johanandren** [comment]
Refs #24781 ?

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
@chbatey merged, but I didn't update the ticket since I don't know if this was everything or if it covers more?

**Comment by chbatey** [comment]
There's one other thing from that issue. I'll update it

**Pull request merged**
