### PR TITLE
Fix or improve some formatting in the new docs

### PR DESCRIPTION
**Pull request by pvlugter**
I made a pass through the new docs looking for anything weird or broken in the formatting, and also checking that we've covered everything in the theme. Here are some fixes.

I notice that there are quite a few lists inside blockquotes. Not sure if all of them are intended to be formatted like that? It's also like this in the sphinx docs.

There are also a lot of explicit anchors `<a id="anchor">`. Is the plan to remove these and switch to the automatic anchors based on headers?

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Review by patriknw — APPROVED** [review]
Thanks a lot for going through it once more.

> I notice that there are quite a few lists inside blockquotes. Not sure if all of them are intended to be formatted like that? It's also like this in the sphinx docs.

I see no reason why we use that. Ordinary lists should be fine everywhere as far as I can see.

> There are also a lot of explicit anchors <a id="anchor">. Is the plan to remove these and switch to the automatic anchors based on headers?

How does that work, it is based on the header text. I guess that should be fine, but sometimes it's important to use the same anchor for java and scala, e.g. when linking from a general page. Normally the headings are the same in java and scala. I don't think we have to change this (right now).

Another question. What is the difference between using `@ref:` and not using it? (I think it works without it also?) Is there some link/anchor checker?

**Comment by pvlugter** [comment]
>> I notice that there are quite a few lists inside blockquotes. Not sure if all of them are intended to be formatted like that? It's also like this in the sphinx docs.
>
> I see no reason why we use that. Ordinary lists should be fine everywhere as far as I can see.

Okay, removed the blockquotes from lists in this PR too.

**Comment by pvlugter** [comment]
>> There are also a lot of explicit anchors . Is the plan to remove these and switch to the automatic anchors based on headers?
>
> How does that work, it is based on the header text. I guess that should be fine, but sometimes it's important to use the same anchor for java and scala, e.g. when linking from a general page. Normally the headings are the same in java and scala. I don't think we have to change this (right now).

Yes, the anchors are based on the header text. For example: "Creating Actors" has `#creating-actors`. And this is also the link when you hover on a heading.

**Comment by pvlugter** [comment]
> Another question. What is the difference between using @ref: and not using it? (I think it works without it also?) Is there some link/anchor checker?

`@ref` accepts the source file, checks that it exists, and converts to the output file. So you can `@ref:[actors](../actors.md)`, it will check that it's a valid reference, and then create a link to `../actors.html` in the output.

You can also add fragments: `@ref:[actors](../actors.md#creating-actors)`. I don't think it checks the fragment is a valid anchor, but that would be useful to add.

With the `@ref`s using source links, it also means that when browsing on github you can follow the links to other sources (and which is one reason the inline directives use the regular markdown link format). For example, the `@ref`s on this page can be followed:

https://github.com/akka/akka/blob/master/akka-docs/src/main/paradox/scala/general/actors.md

**Comment by patriknw** [comment]
thanks for explaining

**Pull request merged**
