### PR TITLE
Fix scala.util.parsing.combinator version for OSGi import #21966 (#21…

### PR DESCRIPTION
**Pull request by ktoso**
Backport of https://github.com/akka/akka/issues/21966

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @domel8dp,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
We want this one in 2.4.15

**Comment by ktoso** [comment]
Validator is being weird, in previous PR it said he did sign.

**Comment by patriknw** [comment]
I can't see domel8dp in the list of CLA signatures. We can't merge before that is fixed.
Did you sign the CLA online, @domel8dp ?

**Comment by domel8dp** [comment]
I did just now

**Comment by patriknw** [comment]
Thanks! I have confirmed CLA.

**Pull request merged**
