### PR TITLE
Behavior methods change to receiveMessage and receiveSignal #19492

### PR DESCRIPTION
**Pull request by stanislav-chetvertkov**
`Behavior` methods change to `receiveMessage` and `receiveSignal` #19492

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @stanislav-chetvertkov,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by raboof** [comment]
OK TO TEST

**Comment by stanislav-chetvertkov** [comment]
made a mistake in renaming

**Comment by patriknw** [comment]
@stanislav-chetvertkov Thanks for this refactoring. We are developing Akka Typed on the branch `wip-akka-typed-dev`. Could you retarget this PR (unfortunately a lot of conflicts).

**Comment by patriknw** [comment]
Refs https://github.com/akka/akka/issues/19492

**Comment by stanislav-chetvertkov** [comment]
Going to fix it today, might be easier to create a new PR for it

**Comment by raboof** [comment]
Sounds good!

**Comment by raboof** [comment]
Superseded by #22799

**Pull request closed without merging**
