### PR TITLE
Some old netty config paths in tests fixed

### LINKED ISSUE #27157: Failed: AccountExampleSpec
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/48/testReport/docs.akka.cluster.sharding.typed/AccountExampleSpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/

Address already in use

Seems to be consistently failing in akka-classic-cluster-tests

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #27157

### CODE REVIEW

**Review by raboof — APPROVED** [review]
good finds

**Review by helena — APPROVED** [review]
LGTM

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by helena** [comment]
Wow, Travis still building it?

**Comment by raboof** [comment]
I guess the travis callback event to github got lost - it's done

**Pull request merged**
