### PR TITLE
Remove unused sample references from FlowDoc{Test|Spec} (#20450)

### PR DESCRIPTION
**Pull request by Captain1653**
References #20450

Kind regards

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Comment by raboof** [comment]
(don't worry about the GitHub Actions failure, we're still in the process of stabilizing those. Filed #30528 for this failure)

**Review by raboof — APPROVED** [review]
Perhaps we could even remove the entire tests? It doesn't look like it's actually testing anything AFAICS?

**Comment by Captain1653** [comment]
I wasn't sure about removing tests :) . I can remove it. Let's wait for other reviewer?

**Review by patriknw — COMMENTED** [review]
LGTM, thanks

**Pull request merged**
