### PR TITLE
=sbt Bump Scala version to 2.12.17 & 2.13.9.

### PR DESCRIPTION
**Pull request by He-Pin**
Bump Scala version to 2.12.17 & 2.13.9.

https://github.com/scala/scala/releases/tag/v2.13.9

### CODE REVIEW

**Comment by He-Pin** [comment]
There are many variable is never used warnning

**Comment by patriknw** [comment]
I'll check with Scala team about those. Looks like it is reported wrong?

**Comment by He-Pin** [comment]
maybe that's because of:
>Add -Wnonunit-statement to warn about discarded values in statement position 
Will try to fix this after work.

**Comment by He-Pin** [comment]
https://github.com/scala/bug/issues/12643

**Comment by He-Pin** [comment]
close for now, there are issues need to be fixed first

**Pull request closed without merging**
