### PR TITLE
Updated books.md

### PR DESCRIPTION
**Pull request by packtpartner**
Added new book link on Akka

### CODE REVIEW

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
OK TO TEST

**Review by johanandren — APPROVED** [review]

**Comment by packtpartner** [comment]
When would this feature on http://doc.akka.io/docs/akka/2.5.2/scala/additional/books.html ?
@johanandren @patriknw

**Comment by ktoso** [comment]
There? Never, since that's an archived version.
It is here though http://doc.akka.io/docs/akka/current/scala/additional/books.html

**Comment by packtpartner** [comment]
Thanks for confirming. I was looking at the wrong page

**Pull request merged**
