### PR TITLE
+act adds missing java api for byte string

### PR DESCRIPTION
**Pull request by ktoso**
As noticed here: https://github.com/akka/akka/pull/16850#discussion_r24813909

### CODE REVIEW

**Comment by rkuhn** [comment]
LGTM

**Comment by patriknw** [comment]
@ktoso @rkuhn was this ported to master? What is the ticket?

**Comment by ktoso** [comment]
Both missing. Created now.

Issue: https://github.com/akka/akka/issues/16970
Port: https://github.com/akka/akka/pull/16971

**Comment by ktoso** [comment]
Thanks for the reminder Patrik!

**Comment by patriknw** [comment]
you're welcome

**Pull request merged**
