### PR TITLE
update to slf4j 17.16, #19758

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by patriknw** [comment]
Refs #19758

**Comment by drewhk** [comment]
LGTM

**Comment by johanandren** [comment]
LGTM

**Comment by rkuhn** [comment]
Was there a specific reason or is it just getting warmer outside? :-) (not saying it shouldn’t be done, but the ticket doesn’t say why)

**Comment by drewhk** [comment]
failure is unrelated.

**Pull request merged**
