### PR TITLE
fix missing letter typo in stream-flows-and-basics #23876

### PR DESCRIPTION
**Pull request by RaymondKlass**
Adds a missing "a" into the documentation for "stream-flows-and-basics" #23876

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @RaymondKlass,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by raboof** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]
Thanks!

**Review by chbatey — APPROVED** [review]

**Comment by chbatey** [comment]
Thanks @RaymondKlass

**Comment by ktoso** [comment]
Resolved https://github.com/akka/akka/issues/23876

**Pull request merged**
