### PR TITLE
Typos and type signature mismatch

### PR DESCRIPTION
**Pull request by Rafailong**
In Device Group section there are 2 occurrences of contains word and a mismatch type in the section about removing device actor when stopped.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @Rafailong,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by Rafailong** [comment]
I just did sign the CLA.

**Review by ktoso — APPROVED** [review]
Good catch, thanks a lot!

**Comment by raboof** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]
thanks!

**Pull request merged**
