### PR TITLE
=htc #16795 add missing test

### LINKED ISSUE #16795: HTTP client not robust
client deadlocks after a few requests, see https://groups.google.com/d/msg/akka-user/Gp0TezTei94/x5py6rcY1RIJ

### PR DESCRIPTION
**Pull request by sirthias**
Closes #16795.

/cc @jrudolph

### CODE REVIEW

**Comment by sirthias** [comment]
Failed seems unrelated (in `akka.stream.scaladsl.GraphPreferredMergeSpec`).

**Comment by rkuhn** [comment]
LGTM, but does it really need 1000 requests? Takes 7 sec on Jenkins …

**Comment by sirthias** [comment]
Ok, I'll reduce it to 100 requests. Should be almost as effective.

> Takes 7 sec on Jenkins

On my machine (i7-4960HQ CPU @ 2.60GHz) it takes 3.8 sec.
And here is a pointer to a nice "actual iron" 4-core machine with about the same [CPU PassMark](https://www.cpubenchmark.net/high_end_cpus.html) score as mine, 32 GB RAM, 2 x 240 GB SSD and 30 TB of traffic for 59 EUR/month:
https://www.hetzner.de/hosting/produkte_rootserver/ex40ssd

I bet this is a fraction of what you are currently paying to amazon, for at least twice the oomph.

It might make sense to go for even more iron, like a 6-core for 109 EUR/month (https://www.hetzner.de/de/hosting/produkte_rootserver/px90ssd) or an 8-core for 189 EUR/month (https://www.hetzner.de/de/hosting/produkte_rootserver/dx151), and make Jenkins deliver those PR validations a lot more presto.

**Comment by sirthias** [comment]
Reduced to 100 test requests to not be so hard on Jenkins, the old man.

**Comment by rkuhn** [comment]
«Thanks!», said the grumpy old gaffer.

**Comment by jrudolph** [comment]
> I bet this is a fraction of what you are currently paying to amazon, for at least twice the oomph.

It seems the 4770 would be roughly comparable to a c3.2xlarge - c4.2xlarge instance in terms of CPU power which currently is about 200 $/month for a reserved instance.

**Comment by patriknw** [comment]
thanks for suggestions, fyi we are currently running this on our own old servers, so they are pretty cheap (they are not fast, but they have many cores)

**Pull request merged**
