### PR TITLE
Clarify in Scaladoc that failed sinks are removed (#21693)

### LINKED ISSUE #21693: MergeHub doesn't fail the Source when one of the inputs fails a Sink
The `onUpstreamFailure` method of the `MergeHub` stage only throw an exception and doesn't fail the Source as it's written in the ScalaDoc:

> If one of the inputs fails the Sink, the Source is failed in turn

### PR DESCRIPTION
**Pull request by 2m**
Fixes #21693

### CODE REVIEW

**Review by ktoso — APPROVED** [review]
LGTM, is there any mention of this in reference docs that could need updating as well?

**Comment by 2m** [comment]
Checked [here](https://doc.akka.io/docs/akka/current/stream/stream-dynamic.html#dynamic-fan-in-and-fan-out-with-mergehub-broadcasthub-and-partitionhub) and there is none.

**Comment by chbatey** [comment]
PLS BUILD

**Review by chbatey — APPROVED** [review]
LGTM

**Pull request merged**
