### PR TITLE
fix github links for stream-http-2.0 branch

### PR DESCRIPTION
**Pull request by rkuhn**

### CODE REVIEW

**Comment by patriknw** [comment]
I think there is a mention in CONTRIBUTING also

**Comment by ktoso** [comment]
Thanks a lot for noticing and please don't merge yet, will make my life a bit easier with the bigger PR ;)

**Comment by ktoso** [comment]
Ah, that's on 2.0 – LGTM then :)

**Comment by rkuhn** [comment]
The MiMa failure from Jenkins does not make sense at all, the code it complains about is in another PR that is not yet merged, and checking out the current PR’s very commit I cannot reproduce any of it (i.e. the code really is not there)—weird.

**Pull request merged**
