### PR TITLE
=doc passive mode for fiddles

### PR DESCRIPTION
**Pull request by andreaTP**
Enabling passive mode in fiddles as requested here: https://github.com/lightbend/paradox/issues/123

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Review by 2m — APPROVED** [review]
Great!

**Review by johanandren — APPROVED** [review]
LGTM

**Comment by ktoso** [comment]
I have confirmed it does not run the sample when loaded with this option

**Comment by ktoso** [comment]
(That's all we needed I think 👍 )

**Comment by patriknw** [comment]
ah, so there was a solution all the time. thanks!

**Pull request merged**
