### PR TITLE
Revert: Update ssl-config-core 0.6.0 (was 0.4.3)

### PR DESCRIPTION
**Pull request by raboof**
This partially reverts #31046, but not the changes there that were
needed to unblock playframework/playframework#11081

### CODE REVIEW

**Review by johanandren — APPROVED** [review]

**Comment by mkurz** [comment]
Hmm.. What's the reason use the older version now?

**Comment by mkurz** [comment]
OK I just saw your message about `Ciphers.recommendedCiphers`...That was removed in https://github.com/playframework/play-ws/pull/638 already... Not released yet however.

**Comment by mkurz** [comment]
Give me a second...

**Comment by raboof** [comment]
> `Ciphers.recommendedCiphers`...That was removed in [playframework/play-ws#638](https://github.com/playframework/play-ws/pull/638) already... Not released yet however.

Yeah, exactly - and to support that we'd have to re-introduce basically all of `Ciphers.scala` at https://github.com/lightbend/ssl-config/pull/302/files#diff-9db2f1b62c827e6c91c0733dd5a2d2f5603f099e9740b53d59248ba38219852eL1 which doesn't seem too attractive...

The main motivation of https://github.com/akka/akka/pull/31046 was to unblock https://github.com/playframework/playframework/pull/11081. I suspect with those other changes still in place you could exclude the old scala-java8-compat dependency now?

**Review by mkurz — APPROVED** [review]
@raboof so... it seems upgrading ssl-config to 0.6.1 is a risk for akka. Lets merge this PR then.

In play and play-ws I will just exclude ssl-config from the akka 2.6.19+ dependency and use 0.6.1, which play and play-ws already  pull in explicitly anyway. We know that akka works with ssl-config 0.6.1 now - after removing methods and classes (that got removed in ssl-config 0.6.1) in #31046, I think that should work.

**Comment by mkurz** [comment]
BTW: Will akka 2.6.19 happen today?

**Comment by raboof** [comment]
> @raboof so... it seems upgrading ssl-config to 0.6.1 is a risk for akka. Lets merge this PR then.
> 
> In play and play-ws I will just exclude ssl-config from the akka 2.6.19+ dependency and use 0.6.1, which play and play-ws already pull in explicitly anyway. We know that akka works with ssl-config 0.6.1 now - after removing methods and classes (that got removed in ssl-config 0.6.1) in #31046, I think that should work.

Thanks a lot for the second pair of eyes!

**Comment by raboof** [comment]
> BTW: Will akka 2.6.19 happen today?

Probably monday!

**Pull request merged**
