### PR TITLE
Update MiMa to check against Akka 2.4.6 as well

### PR DESCRIPTION
**Pull request by bantonsson**

### CODE REVIEW

**Comment by ktoso** [comment]
LGTM assuming validation passes, thanks a lot for the help @bantonsson 👍

**Comment by patriknw** [comment]
LGTM, thanks

**Comment by bantonsson** [comment]
Seriously. The code works locally and the line numbers in the error don't match up. Feels like Jenkins needs some TLC.

**Comment by bantonsson** [comment]
So there where more broken things added to master.

**Comment by ktoso** [comment]
Hm, I've been merging a lot of stuff today but all were green... perhaps outdated test results since the branch was moving on? 

I'll look into it now.

**Comment by bantonsson** [comment]
On it already, it's in the MiMa file...

**Comment by ktoso** [comment]
It's a missing comma, sorry @bantonsson  :(

**Comment by bantonsson** [comment]
I know, just leave it be. The changes are in the wrong section as well.

**Comment by bantonsson** [comment]
I'm testing locally will force push.

**Comment by ktoso** [comment]
Thanks @bantonsson! Merging

**Pull request merged**
