### PR TITLE
Changed instances of addr with address #21874

### PR DESCRIPTION
**Pull request by bdtrunks**
I apologize for forgetting to squash by commits before pushing.

I updated all files that I could find where addr was used instead of the fully spelled address. There were some files where 'address' was already defined, so I made the parameter/variable more specific, ie 'socketAddress' instead of addr in NettyTransport.scala

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @bdtrunks,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by johanandren** [comment]
OK TO TEST

**Comment by johanandren** [comment]
Note that all places where it was part of a public API (method parameter name is one of those) cannot be changed as it breaks source compatibility.

**Comment by johanandren** [comment]
Refs #21874

**Comment by johanandren** [comment]
Compilation failure, I think that next after fixing that though we will se lots of MiMa errors - MiMa is our binary compatibility checking tool which ensures you can take Akka 2.4.n+1 and just drop in as a replacement jar for Akka 2.4.n

**Comment by bdtrunks** [comment]
Thank you for testing and your comments Johan. I'll go back and look closer at the code and possible effects of the changes.

**Comment by patriknw** [comment]
Regarding binary compatibility we can't do any such changes in public api, but in implementation internals and tests it is fine.

**Comment by patriknw** [comment]
@bdtrunks please ping us when you have updated

**Comment by ktoso** [comment]
Resolved conflicts but still needs to be updated according to review comments. Are you planning on picking this up again @bdtrunks ?

**Comment by patriknw** [comment]
Closing due to inactivity. Please create new PR if you get back to this.

**Comment by patriknw** [comment]
Refs #21874

**Pull request closed without merging**
