### PR TITLE
Documentation fix

### PR DESCRIPTION
**Pull request by mattkohl**
typo corrections (see commits)

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @mattkohl,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by raboof** [comment]
OK TO TEST

**Comment by mattkohl** [comment]
Signed Scala CLA

**Comment by raboof** [comment]
I'm afraid for Akka contributions you'll have to sign the Lightbend CLA - sorry for the 'red tape', should be a quick online validation though ;)

**Comment by mattkohl** [comment]
Lightbend CLA signed as well.

**Review by raboof — APPROVED** [review]
Thanks, good catch :+1:

**Pull request merged**
