### PR TITLE
=doc Add clarity for GraphStage image with map transformation

### PR DESCRIPTION
**Pull request by naferx**
The current illustration of GraphStage that implements the map transformation can generate confusion.

screen2

### CODE REVIEW

**Comment by patriknw** [comment]
OK TO TEST

**Comment by patriknw** [comment]
good catch, LGTM

**Comment by ktoso** [comment]
Good idea, LGTM however we also need to update the `graph_stage_chain.png` along with this PR, not only the svg's (docs include png)

**Comment by drewhk** [comment]
LGTM, but needs to re-render the PNG as @ktoso said

**Comment by johanandren** [comment]
There is an additional separated version of it as well, that probably should have the same update: `graph_stage_map.{svg,png}`

**Comment by johanandren** [comment]
Ah, it was in there, sorry missed it through the github ui somehow.

**Comment by patriknw** [comment]
@naferx we are still missing the png files, right?

**Comment by naferx** [comment]
I was trying to render them now with Inkscape (I don't have a Mac) but the
they were rendered with Omnigraffle. It is not the same quality. Perhaps
somebody can help

**Comment by ktoso** [comment]
The graphs @drewhk created so very sure it was Inkscape too actually. Hm hm

**Comment by johanandren** [comment]
Actually it was me with omnigraffle. I can do it.

**Comment by ktoso** [comment]
Oh, didn't know that - sorry then :) Yes please!

**Comment by johanandren** [comment]
Closing because of #20551

**Pull request closed without merging**
