### PR TITLE
=htc #16823 make `Access-Control-Allow-Origin` with multiple origins harder to access

### LINKED ISSUE #16823: Make `Access-Control-Allow-Origin` with multiple origins harder to access
The problem is that browser currently don't support multiple origins in general.

See spray/spray#814 and https://groups.google.com/forum/#!topic/spray-user/qa-LJjHID4Y

/cc @sirthias

### PR DESCRIPTION
**Pull request by sirthias**
Closes #16823.

/cc @jrudolph

### CODE REVIEW

**Comment by jrudolph** [comment]
LGTM

**Comment by sirthias** [comment]
Validation appears to be unrelated (in akka-stream-tests).

**Comment by sirthias** [comment]
PLS REBUILD

**Comment by sirthias** [comment]
PLS BUILD

**Pull request merged**
