### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by jeremie-seguin**
## Purpose

Typo if select java in the doc

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Review by helena — APPROVED** [review]
👍

**Review by raboof — APPROVED** [review]
Looks good, but it seems the email address in the commit isn't associated with your github account - could you look into that?

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Pull request closed without merging**
