### PR TITLE
docs: Use apidoc directive in stream/stream-testkit.md (#22904)

### PR DESCRIPTION
**Pull request by Captain1653**
References #22904

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Comment by Captain1653** [comment]
Can it be reviewed for 2.6.20? Please :)

**Comment by Captain1653** [comment]
@raboof Can it be reviewed, please? I need one approve

**Review by octonato — APPROVED** [review]
LGTM

**Comment by Captain1653** [comment]
2.6.20 milestone, please :)

**Pull request merged**
