### PR TITLE
update MiMa latestPatch

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Review by raboof — APPROVED** [review]

**Review by johanandren — APPROVED** [review]

**Comment by patriknw** [comment]
Looks like MiMa is note aware of the JDK specific source directories, so complaining about akka.remote.artery.jfr.JFRRemotingFlightRecorder and many other things

**Comment by raboof** [comment]
> MiMa is note aware of the JDK specific source directories

We previously worked around that by just excluding those (a3ca3a3fca014fb77476e27a04d15976ff795e2a) - perhaps we should put those in `2.6.x.backwards.excludes`?

**Comment by raboof** [comment]
This surfaced #28538 , let's do that first?

**Comment by patriknw** [comment]
added the excluded to 2.6.x

**Review by johanandren — APPROVED** [review]

**Comment by patriknw** [comment]
rebased, and also had to add the exclude for the SystemMaterializer.materializer type from https://github.com/akka/akka/pull/28538/files

**Pull request merged**
