### PR TITLE
Fix typo in source-streaming-support #21103

### PR DESCRIPTION
**Pull request by tginsberg**
The word "uding" should be "using". Sorry for such a small PR, I just noticed the typo while reading today.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @tginsberg,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by tginsberg** [comment]
Signed CLA.

**Comment by ktoso** [comment]
>  Sorry for such a small PR, I just noticed the typo while reading today.

No reason to feel sorry about, thanks a lot for the fix!

**Comment by ktoso** [comment]
Resolves #21103

**Pull request merged**
