### PR TITLE
Disambiguate 'position' and 'limit' calls

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by ktoso** [comment]
Heh, I was doing that today https://github.com/akka/akka/pull/23658 ;-)
I know reviewing someone's code is boring ;)

**Comment by ktoso** [comment]
Gotta drop the https://github.com/akka/akka/pull/23659/commits/158ea69642248e5fe5af45ef88f12de556e058e0 commit from this pr :) LGTM otherwise, thanks!

**Comment by raboof** [comment]
woops

**Comment by raboof** [comment]
done

**Comment by ktoso** [comment]
Thanks and sorry for the conflict on fixing the same thing :)

**Pull request merged**
