### PR TITLE
Backports for 2.4.11.2

### PR DESCRIPTION
**Pull request by ktoso**

### CODE REVIEW

**Comment by jrudolph** [comment]
Try cherry-picking 78b9843230b45097f2e81437d67feb5a5ddb41dc from akka-http to fix the build. Seems corners were cut last time we released from the release-2.4-http branch.

**Comment by ktoso** [comment]
Picked it and fixing the akka.annotation issues. Thanks for the SHA

**Comment by ktoso** [comment]
Yeah it does seem we cut corners there :\
I need to take it easier with stuff heh, sorry about that.

**Comment by ktoso** [comment]
Pushed the fixes, validation should like it again now (tested all http tests locally)

**Pull request merged**
