### PR TITLE
Adding new book reference for Akka HTTP

### PR DESCRIPTION
**Pull request by ayushmishra2005**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @ayushmishra2005,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ayushmishra2005** [comment]
I did sign the CLA.

**Comment by patriknw** [comment]
OK TO TEST

**Review by patriknw — APPROVED** [review]
LGTM

**Review by johanandren — APPROVED** [review]
LGTM!

**Pull request merged**
