### PR TITLE
Fix some links in cluster-dc.md documentation

### PR DESCRIPTION
**Pull request by vhiairrassary**
Some links in https://doc.akka.io/docs/akka/current/cluster-dc.html returns a 404 error as they are not correctly registered.

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Review by ktoso — APPROVED** [review]
Looks good, thanks!

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
thanks

**Pull request merged**
