### PR TITLE
simplify InHandler in Merge junction: isAvailable(out) implies !pending

### PR DESCRIPTION
**Pull request by swachter**
I studied the code of the Merge junction and stumbled across the implementation of the InHandlers. First I thought that the logic is erroneous because after the isAvailable(out) check there was a nested !pending check. In case that the nested !pending check is not satisfied the input would be lost. However, after deep thinking I came to the conclusion that isAvailable(out) always implies !pending. (The OutHandler would immediately push something when it signals availability. This in turn makes the output unavailable again.)

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @swachter,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by drewhk** [comment]
Thanks! This will need a rebase though

**Comment by swachter** [comment]
I tried to rebase. Yet, I fear, I mixed the process somehow up. The final result should be fine, however.

**Comment by ktoso** [comment]
OK TO TEST

**Comment by drewhk** [comment]
Well, it did went wrong somewhere, I see some unrelated changes here. The fix is only those 2 lines in Merge. Can you please redo the PR if you cannot figure it out how to make git happy? 

otherwise LGTM, nice!

**Comment by swachter** [comment]
I merged upstream/master into the pull request branch. Now it shows only the expected difference:

```
diff --git a/akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala b/akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala
index f4c9fd5..9513f16 100644
--- a/akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala
+++ b/akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala
@@ -71,10 +71,10 @@ final class Merge[T] private (val inputPorts: Int, val eagerComplete: Boolean) e
       setHandler(i, new InHandler {
         override def onPush(): Unit = {
           if (isAvailable(out)) {
-            if (!pending) {
-              push(out, grab(i))
-              tryPull(i)
-            }
+            // isAvailable(out) implies !pending
+            // -> grab and push immediately
+            push(out, grab(i))
+            tryPull(i)
           } else pendingQueue.enqueue(i)
         }
```
I pushed into the pull request branch after the merge. Hopefully it is now up-to-date. Sorry for the inconvenience!

**Comment by johanandren** [comment]
LGTM

**Comment by johanandren** [comment]
Well, aside from the three-commit weirdness. I can pick the right one of them and merge.

**Comment by johanandren** [comment]
Closing this and merging a cherry pick of the commit in PR #19880

**Pull request closed without merging**
