### PR TITLE
Remove signature directive

### PR DESCRIPTION
**Pull request by ignasi35**
Removes the no-longer necessary `@@signature` directive (https://github.com/akka/akka/pull/29021#issuecomment-624143353).

Built on top of #29021 

Refs #28901

### CODE REVIEW

**Comment by raboof** [comment]
it seems this only has the  #29021 commits?

**Comment by ignasi35** [comment]
> it seems this only has the #29021 commits?

Not only I didn't push the commit, I can't find the commit on my local repo. 

Just redid it and pushed.

**Comment by raboof** [comment]
> Just redid it and pushed.

:+1: maybe also rebase since #29021 is now merged?

**Comment by ignasi35** [comment]
> 👍 maybe also rebase since #29021

Done! Thanks for reviewing.

**Review by raboof — APPROVED** [review]
wow so we don't need any custom directives anymore? that's great!

**Review by johanandren — APPROVED** [review]

**Review by ennru — APPROVED** [review]
LGTM.

**Pull request merged**
