### PR TITLE
fix flow control in FanOutThroughputSpec, #23198

### PR DESCRIPTION
**Pull request by patriknw**
It was only using one of the targets for the flow control and therefore there was a risk of filling up the send queue for other targets.

Please review, but let me run this a few times in the repeat job before merging.

Refs #23198

### CODE REVIEW

**Comment by patriknw** [comment]
sbt npe

**Comment by patriknw** [comment]
PLS BUILD

**Review by johanandren — APPROVED** [review]
LGTM

**Review by jrudolph — APPROVED** [review]
LGTM

**Review by 2m — APPROVED** [review]

**Pull request merged**
