### PR TITLE
Support Scala 2.13.0

### PR DESCRIPTION
**Pull request by raboof**
Depends on:
* [x] https://github.com/lightbend/ssl-config/pull/178
* [x] https://github.com/etorreborre/specs2/issues/745
* [x] https://github.com/scalatest/scalatest/issues/1601

### CODE REVIEW

**Review by ennru — APPROVED** [review]
LGTM.

**Review by helena — APPROVED** [review]
LGTM

**Review by chbatey — APPROVED** [review]
LGTM

**Comment by chbatey** [comment]
Believe this isn't running in travis due to the branch name, i'll push it as a new name

**Comment by chbatey** [comment]
Closing and will merge https://github.com/akka/akka/pull/27129 once validation has completed

**Pull request closed without merging**
