### PR TITLE
clarifying return to read returns

### PR DESCRIPTION
**Pull request by lewissk**
changing return in intransitive verb form to transitive verb form

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @lewissk,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by johanandren — APPROVED** [review]

**Review by raboof — APPROVED** [review]

**Comment by chbatey** [comment]
Hi @lewissk  are you able to sign the CLA? Then we can merge this

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by lewissk** [comment]
> Hi @lewissk are you able to sign the CLA? Then we can merge this

I think I just signed it.  Let me know if it is not done correctly and will try to fix it.

**Comment by patriknw** [comment]
OK TO TEST

**Comment by raboof** [comment]
@lewissk sorry for the long turnaround, the Jenkins test reveals that this should also be fixed in akka-docs/src/main/paradox/stream/operators/index.md for consistency. Would you want to fix that as well? Then we can merge and you'll get the full credits as a contributor in the next release notes ;)

**Comment by lewissk** [comment]
@raboof per your request I fixed the additional place where this occurs in the following commit on my fork

https://github.com/lewissk/akka/commit/ff8fa978ca3d1a765d9d41c494933c14b71a8ec7  

Should I create another merge request with both of those changes in it or just create an additional merge request  and link it?

**Comment by raboof** [comment]
@lewissk if you add that commit on top of your `patch-1` branch it should be added to this PR automatically

**Pull request closed without merging**
