### PR TITLE
+htp #19168 add 'strictlyAs' method that allows IAE to bubble up

### PR DESCRIPTION
**Pull request by aosagie**

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
OK TO TEST

**Comment by 2beaucoup** [comment]
I dunno. The marshalling directives have `entity(as[...])` which behaves (now thanks to @aosagie) consistently with case class extraction.

Instead of adding `strictlyAs` there as well I'd vote for adding docs to show how to change rejection handling via `handleRejections` to e.g. throw instead.

**Comment by ktoso** [comment]
Yeah, perhaps you're right here @2beaucoup. 
Handling rejections is something people ought to be doing anyway, so it would make sense to explain it here instead of special casing.

Would you be able to change this PR to instead show how to use the `handleRejections` such that it throws when such rejection is found?

**Comment by ktoso** [comment]
Refs #19168

**Comment by 2beaucoup** [comment]
@ktoso you mean smth. like this https://github.com/2beaucoup/akka/commit/336dec36bfb1c1b97cfd3995face3a19d7cbd5f3?

**Comment by ktoso** [comment]
Yep, exactly! I'd also like to include that example (validation rejection => error) in here: http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0-M2/scala/http/routing-dsl/rejections.html

**Comment by 2beaucoup** [comment]
see #19247

**Comment by ktoso** [comment]
Thanks @2beaucoup.
Sorry for changing the decision about how we want to expose this after your previous PR @aosagie, thanks a lot for both PRs!

**Comment by ktoso** [comment]
Closing this for now, thanks again @aosagie - looking forward to see some more PRs from you maybe? :smile:

**Comment by aosagie** [comment]
No problem @ktoso - I understand. And thanks for making this the most pleasant experience I've had contributing to a major open source project. I can't wait to help out again.

**Pull request closed without merging**
