### PR TITLE
fix eventbus doc-code

### PR DESCRIPTION
**Pull request by matsu-chara**
remove `new AnyRef {`

before: http://doc.akka.io/docs/akka/2.4/scala/event-bus.html

image

after:

image

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Comment by johanandren** [comment]
LGTM

**Comment by ktoso** [comment]
LGTM, thanks!

**Comment by ktoso** [comment]
Thanks a lot for noticing!

**Pull request merged**
