### PR TITLE
Rename LoggingEventFilter to LoggingTestKit

### PR DESCRIPTION
**Pull request by chbatey**
Refs #27702

### CODE REVIEW

**Comment by patriknw** [comment]
anything else than a plain search-replace here?

**Review by raboof — COMMENTED** [review]
scalafmt likes some changes (probably because the width changed?)

I think I'd prefer `LoggingTestkit` (lowercase 'K', like `BehaviourTestkit`), though we also have some more places where we spell it `TestKit`..

**Comment by patriknw** [comment]
It's `BehaviorTestKit` and `ActorTestKit`.
Personally I'd probably would have used Testkit, but original author (also in Classic) didn't so I think we should stick to what we have for that.

**Comment by raboof** [comment]
> It's BehaviorTestKit

Oops :smile: #27890 

Agreed it's better to consistently spell TestKit in class names with a capital K (though unfortunate :smile: )

**Comment by chbatey** [comment]
| anything else than a plain search-replace here?

Nope

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
@chbatey formatting needed here

**Comment by chbatey** [comment]
Doh, upgrading intellij decided to remove format on save

**Comment by patriknw** [comment]
> upgrading intellij decided to remove format on save

also note that you have to approve download of new scalafmt version (small note in status bar)

**Review by helena — APPROVED** [review]
Mostly renaming, LGTM

**Pull request merged**
