### PR TITLE
=str #17008 Close the TcpConnectionStream on failure.

### PR DESCRIPTION
**Pull request by RichardBradley**
See #17008

### CODE REVIEW

**Comment by rkuhn** [comment]
OK TO TEST

**Comment by rkuhn** [comment]
Thanks for the patch! Would you mind adding a test case that keeps us safe from breaking this again in the future? (That’s how we always do things.)

**Comment by RichardBradley** [comment]
> Would you mind adding a test case that keeps us safe from breaking this again in the future? (That’s how we always do things.)

I'd like to, but I may not be able to do it very soon, and I'd like some advice on how to write such a test.

The issue is a memory leak: after the connection is finished, a `TcpStreamActor` lives on (and it can never be GCed as it's an Actor).

Are there any existing Akka tests which address Actor leaks of this kind, which I can use as a template? 

We have found that tests which address global issues like leaks don't mesh well with the tests being run in parallel by SBT. Are there any patterns in Akka tests which address that issue which I can use?

I don't see any Akka test which directly reference the `TcpStreamActor` class. I presume this class is tested indirectly. Do you know which tests cover this class indirectly?

**Comment by rkuhn** [comment]
Verifying a global property is indeed problematic, but luckily we are after something very local: we only need to verify that one particular Actor shuts down. In this case you should look at StreamTcpManager to see how to create this kind of Actor, the `processorPromise` allows you to extract the Reactive Streams interface to which you can then subscribe SubscriberProbe / PublisherProbe to inject the failure case you want to see, and Actor termination can then be verified by using normal DeathWatch from a TestProbe.

The existing tests work on the stream level, you can find them in `akka-stream-tests/src/test/scala/akka/stream/io/StreamTcpSpec.scala`.

**Comment by drewhk** [comment]
OK TO TEST

**Comment by patriknw** [comment]
shall we merge this so that it is included in M5 and add a separate ticket for adding a test?

**Comment by drewhk** [comment]
There is a ticket here: https://github.com/akka/akka/issues/15191

**Comment by patriknw** [comment]
LGTM

**Comment by patriknw** [comment]
@drewhk good, so then I merge this? is it LGTY?

**Comment by drewhk** [comment]
Yes, this is clearly LGTM

**Pull request merged**
