### PR TITLE
Correct a word 'degredation'

### PR DESCRIPTION
**Pull request by lvq410**
'degredation' maybe wrong , correct it

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @lvq410,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by raboof — APPROVED** [review]
Good one, thanks!

**Comment by raboof** [comment]
OK TO TEST

**Review by chbatey — APPROVED** [review]
LGTM

Can you sign the CLA @lvq410 ?

**Comment by lvq410** [comment]
I've signed the CLA, what's next?

**Pull request merged**
