### PR TITLE
Enable fatal warnings by default (with excludes)

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Review by chbatey — APPROVED** [review]
LGTM, but can i merge my PR first? :)

**Review by johanandren — APPROVED** [review]
LGTM but let's be nice to Chris for once.

**Comment by raboof** [comment]
@chbatey you were referring to #26685 I think, right? Any others you'd like to see go in first?

**Comment by chbatey** [comment]
Go forth and merge!

**Pull request merged**
