### PR TITLE
Operators: Add example for groupBy

### PR DESCRIPTION
**Pull request by mdipirro**
References #25468

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @mdipirro,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Review by johanandren — APPROVED** [review]
Given how complex groupBy actually is, with substreams and backpressure it would be good with some more complex samples as well.

This is a great start and definitely better than no example at all though.

LGTM!

**Review by ennru — APPROVED** [review]
LGTM.

**Comment by ennru** [comment]
Thank you! Keep them coming...

**Pull request merged**
