### PR TITLE
Remove warnOldDocs.js from release procedure

### PR DESCRIPTION
**Pull request by raboof**
Since we don't have that file with Paradox.

We'd probably want to reintroduce this (or something similar) however.

### CODE REVIEW

**Comment by ktoso** [comment]
> We'd probably want to reintroduce this (or something similar) however.
 
Yes, please make a ticket for it.

**Review by ktoso — APPROVED** [review]
LGTM, but let's make sure we ticketify bringing it back

**Comment by raboof** [comment]
Agreed added #23027

**Comment by ktoso** [comment]
Thanks :)

**Pull request merged**
