### PR TITLE
=cls improve the graceful shutdown example

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by drewhk** [comment]
Hm, 3 seconds are enough? How to determine a safe value?

**Comment by drewhk** [comment]
otherwise LGTM

**Comment by ktoso** [comment]
LGTM, I'd also give perhaps 10s in the example?

**Comment by patriknw** [comment]
Nothing bad happens if its shutdown too early, apart from a bit longer take-over for the singletons. I'll increase it anyway, thanks.

**Pull request merged**
