### PR TITLE
= htc #17943 more robust creation of function literals

### LINKED ISSUE #17943: JavaMapping doesn't compile under 2.10.3
From https://github.com/akka/akka/pull/17880#issuecomment-119016168:

```
[error] /home/stanch/projects/akka/akka-http-core/src/main/scala/akka/http/impl/util/JavaMapping.scala:100: method with dependent type (scalaObject: SIn)inMapping.J cannot be converted to function value
[error]         scaladsl.Flow[SIn].map(inMapping.toJava).viaMat(javaObject)(scaladsl.Keep.right).map(outMapping.toScala)
[error]                                          ^
[error] /home/stanch/projects/akka/akka-http-core/src/main/scala/akka/http/impl/util/JavaMapping.scala:103: method with dependent type (javaObject: JIn)inMapping.S cannot be converted to function value
[error]           scaladsl.Flow[JIn].map(inMapping.toScala).viaMat(scalaObject)(scaladsl.Keep.right).map(outMapping.toJava)
[error]                                            ^
[info] No documentation generated with unsucessful compiler run
[error] two errors found
[info] Compiling 123 Scala sources and 114 Java sources to /home/stanch/projects/akka/akka-http-core/target/classes...
[error] /home/stanch/projects/akka/akka-http-core/src/main/scala/akka/http/impl/util/JavaMapping.scala:100: method with dependent type (scalaObject: SIn)inMapping.J cannot be converted to function value
[error]         scaladsl.Flow[SIn].map(inMapping.toJava).viaMat(javaObject)(scaladsl.Keep.right).map(outMapping.toScala)
[error]                                          ^
[error] /home/stanch/projects/akka/akka-http-core/src/main/scala/akka/http/impl/util/JavaMapping.scala:103: method with dependent type (javaObject: JIn)inMapping.S cannot be converted to function value
[error]           scaladsl.Flow[JIn].map(inMapping.toScala).viaMat(scalaObject)(scaladsl.Keep.right).map(outMapping.toJava)
[error]                                            ^
[error] two errors found
```

### PR DESCRIPTION
**Pull request by jrudolph**
Fixes #17943.

### CODE REVIEW

**Comment by ktoso** [comment]
Interesting, LGTM

**Comment by stanch** [comment]
This seems to work (note another addition at the end of the line):

```diff
@@ -97,10 +97,10 @@ object JavaMapping {
   implicit def flowMapping[JIn, SIn, JOut, SOut, M](implicit inMapping: JavaMapping[JIn, SIn], outMapping: JavaMapping[JOut, SOut]): JavaMapping[javadsl.Flow[JIn, JOut, M], scaladsl.Flow[SIn, SOut, M]] =
     new JavaMapping[javadsl.Flow[JIn, JOut, M], scaladsl.Flow[SIn, SOut, M]] {
       def toScala(javaObject: javadsl.Flow[JIn, JOut, M]): S =
-        scaladsl.Flow[SIn].map(inMapping.toJava).viaMat(javaObject)(scaladsl.Keep.right).map(outMapping.toScala)
+        scaladsl.Flow[SIn].map(inMapping.toJava(_)).viaMat(javaObject)(scaladsl.Keep.right).map(outMapping.toScala(_))
       def toJava(scalaObject: scaladsl.Flow[SIn, SOut, M]): J =
         javadsl.Flow.wrap {
-          scaladsl.Flow[JIn].map(inMapping.toScala).viaMat(scalaObject)(scaladsl.Keep.right).map(outMapping.toJava)
+          scaladsl.Flow[JIn].map(inMapping.toScala(_)).viaMat(scalaObject)(scaladsl.Keep.right).map(outMapping.toJava(_))
         }
     }
```

**Comment by jrudolph** [comment]
As we (me and @stanch) just found out it only fails to compile under 2.10.3. Nevertheless the change will increase robustness.

**Comment by ktoso** [comment]
Failure was unrelated, LGTM

**Pull request merged**
