### PR TITLE
Merge Artery into master

### PR DESCRIPTION
**Pull request by patriknw**
```
commits added removed
  130   21919    6504 Patrik Nordwall
   19    2565    1087 Johan Andrén
   15    9934     402 Endre Sándor Varga
    8    4662    1635 Konrad Malawski
    5     825     201 Johan Andrén
    4    1441     361 Martynas Mickevičius
    3    6584      76 Johannes Rudolph
    2     341     276 Łukasz Dubiel
```

### CODE REVIEW

**Comment by patriknw** [comment]
before merging master into artery-dev I did two changes:
* dcd9213
* 5558caa

The only merge conflict was a trivial thing in Mima

**Comment by johanandren** [comment]
LGTM. (Woho!)

**Comment by ktoso** [comment]
Good job!

[](http://img1.wikia.nocookie.net/__cb20111127000051/adventuretimewithfinnandjake/images/3/35/S3e4_Goodjobiceking.gif)

**Comment by ktoso** [comment]
Awesome, good job!

**Comment by ktoso** [comment]
Only non-lightbender @bambuchaAdm, nice ;-)

**Pull request merged**
