### PR TITLE
Switch languages in paradox without page refresh

### PR DESCRIPTION
**Pull request by raboof**
Requires:

* [x] https://github.com/akka/akka-paradox/pull/10 to be reviewed/merged
* [x] changes to the documentation upload script (created a `deployRsync` sbt task but not calling it yet)
* [x] redirects from old to new page locations
* [x] allow specifying the language as a query parameter?
* [x] ~building the docs now produces an `akka-docs/target/paradox/site/main/target/` folder - find out why and avoid it.~ (akka/akka-paradox#13)

Demo: http://doc.akka.io/docs/akka/2.5-SNAPSHOT/java/persistence.html

Refs #23052

### CODE REVIEW

**Comment by patriknw** [comment]
waiting for release

**Comment by patriknw** [comment]
does this mean that there is no java/scala page? we still need direct links from http://akka.io/docs/
query param would be a good solution

**Comment by patriknw** [comment]
I think this is looking good. What is the status? Is the query parameter feature included in that paradox version? How do we handle redirects of old links?

**Comment by raboof** [comment]
The query parameter feature is included in paradox, but for us also needs akka/akka-paradox#10 for our own akka-paradox. 

Redirects are implemented with .htaccess in https://github.com/akka/akka/pull/23544/files#diff-b5f788d092e9bf5e9eb7c8cb3365cf83R1

**Review by 2m — APPROVED** [review]
Great. Does adding `.htaccess` files to src/main/paradox just work?

**Comment by raboof** [comment]
@2m yes, on `doc.akka.io` I configured apache so that it does/should :)

**Comment by 2m** [comment]
But paradox also grabs it from src/main/paradox and puts it in the target directory. That's cool. :)

**Comment by raboof** [comment]
yeah I like having those in version control :)

**Comment by ktoso** [comment]
Wohooo! :)

**Pull request merged**
