### PR TITLE
Upgrade Aeron to 1.15.1

### PR DESCRIPTION
**Pull request by chbatey**

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
LGTM, it's bin/wire comp with 1.12?

**Comment by patriknw** [comment]
Latest is 1.15 now

**Comment by chbatey** [comment]
And now 1.15.1, updated

**Comment by chbatey** [comment]
Yep, as usual it is wire compatible but not compatible between pub/sub and a media driver.

**Review by johanandren — APPROVED** [review]

**Review by jrudolph — COMMENTED** [review]
LGTM

**Review by jrudolph — APPROVED** [review]
LGTM

**Pull request merged**
