### PR TITLE
Remove the duplicated class Coroner.scala

### PR DESCRIPTION
**Pull request by mjwsteenbergen**
`Coroner.scala` is almost a 100% duplicated from [akka-testkit/Coroner](https://github.com/akka/akka/blob/master/akka-testkit/src/test/scala/akka/testkit/Coroner.scala). It has not been changed since 2014, except for copyright updates. Furthermore there no usages of this code in the rest of the codebase.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @mjwsteenbergen,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by raboof** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]
Good observation, thanks!

**Review by patriknw — APPROVED** [review]
excellent, thanks

**Pull request merged**
