### PR TITLE
[WIP] Reimplementation of mapAsync on top of simpler components

### PR DESCRIPTION
**Pull request by jrudolph**
The idea is that one can break up the implementations like this:

mapAsync:
 * map(f)
 * LimitUncompleted Flow[Future[T], Future[T]]
 * simple buffer
 * WaitForCompletion Flow[Future[T], T]

LimitUncompleted just passes the futures through but only let's a maximum number of uncompleted futures through.

WaitForCompletion just waits for a single future to complete.

One important observation was that the `parallelism` setting has two meanings:
 * How many thunks should possibly be running in parallel?
 * How large should the buffer be on the outgoing side when there's either backpressure from downstream or (for mapAsync) head-of-line blocking.

The first question is one of how many resources your stream should use while the second question is mostly a tuning parameter of that stream.

E.g. with mapAsync you want to avoid head-of-line blocking so you want to set a  high parallelism setting (like 1000) to hide latency outliers. But that might put extra strain on you backend systems (REST Apis, DBs, CPU cores, etc).

With the new setup, there could be another operator (or a combination of the ones here) where you keep the parallelism setting at something that makes sense with your resources (e.g. number of cores for CPU-bottlenecked tasks) but increase the buffer size to whatever is necessary to hide tail latency (of course, keeping additional memory usage in mind).

### CODE REVIEW

**Comment by johanandren** [comment]
I'm on the fence: Simpler separate stages but not much easier to reason about in concert. 
Also two `invokeAsync` per element instead of one (but otoh perhaps one less alloc with the `Holder` gone)?

I guess we could (would anyways have to) keep the one param version so maybe an overload with the additional buffer size?

**Comment by jrudolph** [comment]
> 'm on the fence: Simpler separate stages but not much easier to reason about in concert.
> Also two `invokeAsync` per element instead of one (but otoh perhaps one less alloc with the `Holder` gone)?

I also tried a version which just uses an AtomicLong in the `LimitUncompleted` and only uses async callback when known to be needed. However, that introduces some complexity and some reasoning to explain why it is safe.

**Review by patriknw — COMMENTED** [review]
Looks like a nice structure. mapAsync is a core performance critical operator so we must benchmark the changes, and also use tricks like not involving async callbacks when futures are already completed.

**Comment by ennru** [comment]
I like it. Comparing (and possibly optimising) performance would be interesting, indeed.

**Comment by ennru** [comment]
BTW Alpakka SQS contains this `mapAsync` with dynamic parallelism.

https://github.com/akka/alpakka/blob/2cd0c008b630a72390b4ff2eb3cc4fc7db1f9317/sqs/src/main/scala/akka/stream/alpakka/sqs/impl/BalancingMapAsync.scala#L41

**Comment by hepin1989** [comment]
@jrudolph Is there anychange the `LimitUncompleted Flow[Future[T], Future[T]]` and `
WaitForCompletion Flow[Future[T], T]` be first get merged ?

**Comment by hepin1989** [comment]
>Due to the default materialization scheme that places all combinators within a single actor (unless specified otherwise with .async) there is no significant overhead in using two operators, or said the other way around, there is no need to have a single operator for any possible thing you might want to do. Answering your concrete cases:
https://discuss.lightbend.com/t/state-inside-of-flow-operators/5717/14

So is there any change this PR got merged:)

**Comment by patriknw** [comment]
nice idea, but we don't have the bandwidth to move it forward at the moment (and it has already been stale for very long)

**Pull request closed without merging**
