### PR TITLE
Fix warnings when compiling against jdk11

### PR DESCRIPTION
**Pull request by raboof**
Compiling against jdk11 is possible with #27083

### CODE REVIEW

**Comment by raboof** [comment]
(have to check if performance is on par before merging)

**Review by helena — APPROVED** [review]
Looks good

**Review by patriknw — COMMENTED** [review]
pending performance validation of actor creation

**Comment by raboof** [comment]
ActorCreationBenchmark looks good but the variance seems rather big (even with 'performance' governor)...
```ActorCreationBenchmark
before:
[info] ActorCreationBenchmark.synchronousStarting    ss    3  200.523 ± 833.761  us/op
[info] ActorCreationBenchmark.synchronousStarting    ss    3  206.496 ± 584.709  us/op
[info] ActorCreationBenchmark.synchronousStarting    ss    3  185.079 ± 325.940  us/op
[info] ActorCreationBenchmark.synchronousStarting    ss    3  226.821 ± 276.221  us/op
after:
[info] ActorCreationBenchmark.synchronousStarting    ss    3  182.120 ± 408.678  us/op
[info] ActorCreationBenchmark.synchronousStarting    ss    3  221.438 ± 216.214  us/op
[info] ActorCreationBenchmark.synchronousStarting    ss    3  162.510 ± 354.119  us/op
[info] ActorCreationBenchmark.synchronousStarting    ss    3  179.318 ± 684.364  us/op
```
Let's be on the safe side and ignore the deprecation for now

**Comment by patriknw** [comment]
Maybe I was too afraid of performance regression here. Best is to not use the reflection based Props at all, and instead use the lambda/function to create the instance. The only case that doesn't work is for remote deployed actors, and then this small performance concern should matter at all.

Also, Props can be reused and I think we already have some caching in there when reflection is used.

**Comment by raboof** [comment]
Makes sense. Let's prefer #27308 though.

**Pull request closed without merging**
