### PR TITLE
re-enable tests using DisposableSys

### PR DESCRIPTION
**Pull request by octonato**
After we can confirm that https://github.com/akka/akka/pull/30835 is working, we can give a try to this.

### CODE REVIEW

**Review by patriknw — COMMENTED** [review]
LGTM, the only reason this would work now is that we switched to 8 vCPU nodes. We can give it a try, but if it's still flaky we don't have to run these with Aeron.

**Review by patriknw — APPROVED** [review]

**Comment by octonato** [comment]
> LGTM, the only reason this would work now is that we switched to 8 vCPU nodes. We can give it a try, but if it's still flaky we don't have to run these with Aeron.

Ok, let's see and if  not we can use the new tag instead of handed-hacked config juggling

**Comment by patriknw** [comment]
@octonato seems this didn't work. SplitBrainResolverIntegrationSpec failed https://github.com/akka/akka/runs/5482244373?check_suite_focus=true

For now, I think we have to accept that we can't run these with Aeron in CI.

**Comment by octonato** [comment]
ok, I will tag them with the areon exclude tag

**Pull request merged**
