### PR TITLE
fix wrong ActorSystem name when using MultiNodeClusterShardingSpec #28953

### PR DESCRIPTION
**Pull request by patriknw**
* use same testNameFromCallStack everywhere

References #28953

### CODE REVIEW

**Comment by patriknw** [comment]
@johanandren this can be useful when debugging the sharding tests

**Review by raboof — APPROVED** [review]
Nice to deduplicate as well :+1:

**Comment by patriknw** [comment]
Don't merge yet. This didn't work quite right for multi-jvm tests. Name became `ClusterShardingSingleShardPerEntitySpecMultiJvmNode1`

**Comment by patriknw** [comment]
fixed in https://github.com/akka/akka/pull/28954/commits/a4362de0d9a7e7662cf56ece01917fe916019f50

**Review by johanandren — APPROVED** [review]
LGTM!

**Pull request merged**
