### PR TITLE
+doc Improved scalafiddle integration

### PR DESCRIPTION
**Pull request by andreaTP**
This is the end result, to have this landing we need:

https://github.com/lightbend/paradox/pull/231

https://github.com/akka/akka-paradox/pull/33

### CODE REVIEW

**Comment by chbatey** [comment]
OK TO TEST

**Comment by andreaTP** [comment]
@chbatey CI won't succeed until we got the other two PR merged, all is based on non-released snapshot versions.

**Review by patriknw — COMMENTED** [review]
looking good when Paradox has been released

**Comment by andreaTP** [comment]
thanks for releasing @ktoso  I'm on it: https://github.com/akka/akka-paradox/pull/33

**Comment by andreaTP** [comment]
Updated accordingly now ready for review.

**Review by raboof — APPROVED** [review]
Looks pretty neat to me!

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
Thanks @andreaTP 
Just in time for tomorrows 2.5.15 release 😃

**Comment by andreaTP** [comment]
YaY! :+1: looking forward for it!

**Pull request merged**
