### PR TITLE
Add dep from multi-jvm cluster to multi-jvm cluster-typed

### PR DESCRIPTION
**Pull request by chbatey**
This doesn't fail locally for me for some reason but does in jenkins

### CODE REVIEW

**Comment by chbatey** [comment]
Running this here to make sure: https://jenkins.akka.io:8498/job/akka-multi-node-repeat/18808

**Review by patriknw — APPROVED** [review]
LGTM, I guess

**Review by johanandren — APPROVED** [review]

**Review by ktoso — COMMENTED** [review]
LGTM, weird

**Review by ktoso — APPROVED** [review]

**Comment by chbatey** [comment]
I tried with and without this in the multi-node repeat job and this fixes it

**Pull request merged**
