### PR TITLE
log materialization errors in `bindAndHandle`

### LINKED ISSUE #16507: ServerBinding.startHandling* must not throw away errors
E.g. by returning `ForeachSink`'s `Future[Unit]` result to be able to subscribe to errors.

### PR DESCRIPTION
**Pull request by sirthias**
Closes #16507.

/cc @jrudolph

### CODE REVIEW

**Comment by jrudolph** [comment]
LGTM

**Comment by drewhk** [comment]
LGTM

**Comment by ktoso** [comment]
LGTM, had multiple different test failures but does not seem related to this chage (incl. one I just fixed).

**Comment by ktoso** [comment]
PLS BUILS

**Comment by ktoso** [comment]
PLS BUILD

**Comment by patriknw** [comment]
LGTM (I guess I reviewed a duplicate previously)

**Pull request merged**
