### PR TITLE
Allocate rebalanced shards immediately, #29543

### PR DESCRIPTION
**Pull request by patriknw**
* Otherwise it will continue to deallocate when there is no traffic
  that triggers allocations

Problem described in https://github.com/akka/akka/issues/29543#issuecomment-686542787

References #29543

### CODE REVIEW

**Review by johanandren — COMMENTED** [review]
Makes sense, all multi-node tests passing with this change (theyre not part of PR validation, right)?

**Comment by patriknw** [comment]
> all multi-node tests passing with this change

I have (now) run them in the sharding projects. All good.

**Review by johanandren — APPROVED** [review]
LGTM

**Review by chbatey — APPROVED** [review]

**Review by octonato — APPROVED** [review]

**Comment by patriknw** [comment]
let's merge this after the 2.6.9 release so all sharding improvements are together

**Pull request merged**
