### PR TITLE
=pro Use provided dependency from persistence in bench-jmh

### PR DESCRIPTION
**Pull request by patriknw**
- compilation error when running release script

### CODE REVIEW

**Comment by patriknw** [comment]
no need for pr-validation

**Comment by patriknw** [comment]
@ktoso Do you know if it is possible to compile, but not run, `bench-jmh` in ordinary builds?

**Comment by ktoso** [comment]
@patriknw could you refine what you mean by ordinary builds? Validation / during dev time?
It should be compiled, and never run on jenkins as-is already, but I guess you mean something different?

**Comment by patriknw** [comment]
It did not fail in any of our jobs, we have this dependeny change for a long time. Release script triggered compilation error.

Note that it is not included in the aggregate project

**Comment by ktoso** [comment]
I see, thanks for noticing, now is a good time to clean up all these things. Adding it to the aggregate makes sense, compilation is slow for that project but we want to include it anyway.

**Pull request merged**
