### PR TITLE
added examples for Stream # actorRef operator. As part of #25468

### PR DESCRIPTION
**Pull request by Seetaramayya**

### CODE REVIEW

**Comment by raboof** [comment]
Refs #25468

**Comment by raboof** [comment]
OK TO TEST

**Comment by raboof** [comment]
Unfortunately it seems scalariform found some formatting inconsistencies, could you try `sbt scalariformFormat test:scalariformFormat`?

**Review by raboof — APPROVED** [review]
Thanks!

**Review by johanandren — APPROVED** [review]
LGTM, thanks

**Comment by johanandren** [comment]
(manually verified signed CLA)

**Pull request merged**
