### PR TITLE
Documentation fixes

### PR DESCRIPTION
**Pull request by mattkohl**

### CODE REVIEW

**Review by raboof — APPROVED** [review]
Good catch, thanks!

**Comment by raboof** [comment]
OK TO TEST

**Comment by raboof** [comment]
The added newline at the end of `additional-sink-and-source-converters.md` caused the generated-but-checked-in `akka-docs/src/main/paradox/stream/operators/index.md` to be different, which causes the build to fail. Could you run `sbt paradox` and commit the changed generated `akka-docs/src/main/paradox/stream/operators/index.md`, or would you prefer me to take care of this?

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
