### PR TITLE
doc: fix the word spell error in actor-lifecycle

### PR DESCRIPTION
**Pull request by pxsdirac**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Review by raboof — APPROVED** [review]
Thanks!

**Comment by raboof** [comment]
OK TO TEST

**Pull request merged**
