### PR TITLE
=pro #16704 add validatePullRequest task to samples

### LINKED ISSUE #16704: samples not tested by pr-validator

### PR DESCRIPTION
**Pull request by 2m**
Add validatePullRequest task to samples.
- move validatePullRequest to separate autoplugin
- move MiMa settings to separate autoplugin

Fixes #16704.

### CODE REVIEW

**Comment by 2m** [comment]
PLS BUILD

**Comment by patriknw** [comment]
interesting, LGTM

**Comment by ktoso** [comment]
Pretty cool to add this via AutoPlugin... /me beginning to like them.
LGTM

**Comment by drewhk** [comment]
LGTM I guess

**Comment by ktoso** [comment]
Merging since seems good and no-one opposed ;-)

**Pull request merged**
