### PR TITLE
=htc Remove Java 7 features

### PR DESCRIPTION
**Pull request by RichardBradley**
See https://groups.google.com/forum/#!topic/akka-dev/pCeQJEQEmKk

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Thanks a lot @RichardBradley for noticing this!
I'll have an additional look how we can prevent those from slipping in on our jenkins (note to self, don't close until checked)

**Comment by ktoso** [comment]
OK TO TEST

**Comment by 2m** [comment]
LGTM. Should we create a ticket to put these back, once Akka Stream is for Java 8+?

**Comment by ktoso** [comment]
LGTM, thanks @RichardBradley!

**Comment by ktoso** [comment]
@2m ticket sounds good, please add one @2m

**Pull request merged**
