### PR TITLE
=sam #17537 relax timing in multi node spec

### LINKED ISSUE #17537: failed: MultiNodeSample
https://jenkins.akka.io:8498/job/akka-nightly/2267/consoleFull

    [JVM-2] A MultiNodeSample
    [JVM-2] - must wait for all nodes to enter a barrier
    [JVM-1] - must wait for all nodes to enter a barrier
    [JVM-1] - must send to and receive from a remote node *** FAILED ***
    [JVM-1]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for pong
    [JVM-1]   at scala.Predef$.assert(Predef.scala:165)
    [JVM-1]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:353)
    [JVM-1]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:330)
    [JVM-1]   at akka.testkit.TestKit.expectMsg(TestKit.scala:738)
    [JVM-1]   at sample.multinode.MultiNodeSample$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3.apply$mcV$sp(MultiNodeSample.scala:49)
    [JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:338)
    [JVM-1]   at sample.multinode.MultiNodeSample$$anonfun$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(MultiNodeSample.scala:45)
    [JVM-1]   at sample.multinode.MultiNodeSample$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(MultiNodeSample.scala:44)
    [JVM-1]   at sample.multinode.MultiNodeSample$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(MultiNodeSample.scala:44)
    [JVM-1]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)

### PR DESCRIPTION
**Pull request by ktoso**
resolves https://github.com/akka/akka/issues/17537

### CODE REVIEW

**Comment by patriknw** [comment]
Strange that it would take more than 3 seconds to send the message. Perhaps something caused by it being the first message, or some issue with a0?

Anyway LGTM

**Comment by ktoso** [comment]
Yes most failures were on a0, so I think it's due to that.

**Comment by patriknw** [comment]
ok, let's merge this anyway (I hate timeouts)

**Comment by ktoso** [comment]
Yeah, me too ;)

**Pull request merged**
