### PR TITLE
Docs and sampl. receptionist, typed cluster #24274

### PR DESCRIPTION
**Pull request by johanandren**
Continuation of #24274 because I messed up while trying to push commits to Christophers existing PR ...

### CODE REVIEW

**Comment by johanandren** [comment]
Instead of fixing #24279 I worked around it here.

**Comment by patriknw** [comment]
@johanandren can we merge this, or is the workaround not releasable?

**Review by ktoso — APPROVED** [review]
Seems LGTM to me, but not sure if this should be in the release?

**Comment by ktoso** [comment]
Rebase merging to keep credits for @chbatey

**Pull request merged**
