### PR TITLE
Flow.recoverWithRetries with backoff strategy

### PR DESCRIPTION
**Pull request by mavericksid**
## Purpose

Provides backoff strategy in Flow.recoverWithRetries which can be helpful for scenarios wherein, for example, a separate implicit might not have to be defined like this:
https://github.com/akka/alpakka/pull/1712/files#diff-af410f9f2cf2d5bbc64e112ab0a691d9R22

## Changes

Add Flow.recoverWithRetries with additional parameters, initialRetryTimeout and backoffStrategy.

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Comment by raboof** [comment]
(I understand this is still a draft, so I'll hold off reviewing, but I'll already tell Jenkins to test this branch)

**Comment by mavericksid** [comment]
Hi @raboof 

The build completed with failure but I do not understand why. Can you please have a look? I guess I might be missing something but the test says all passed.

`[05-28 07:18:22.929] [info] ScalaTest
[05-28 07:18:22.929] [info] Run completed in 2 minutes, 5 seconds.
[05-28 07:18:22.929] [info] Total number of tests run: 679
[05-28 07:18:22.929] [info] Suites: completed 176, aborted 0
[05-28 07:18:22.929] [info] Tests: succeeded 679, failed 0, canceled 0, ignored 6, pending 1
[05-28 07:18:22.929] [info] All tests passed.
[05-28 07:18:22.930] [info] Passed: Total 679, Failed 0, Errors 0, Passed 679, Ignored 6, Pending 1
[success] Total time: 1262 s, completed May 28, 2019 9:18:30 AM`

https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/16130/console

**Comment by mavericksid** [comment]
> Hi @raboof
> 
> The build completed with failure but I do not understand why. Can you please have a look? I guess I might be missing something but the test says all passed.
> 
> > [05-28 07:18:22.929] [info] ScalaTest
> > [05-28 07:18:22.929] [info] Run completed in 2 minutes, 5 seconds.
> > [05-28 07:18:22.929] [info] Total number of tests run: 679
> > [05-28 07:18:22.929] [info] Suites: completed 176, aborted 0
> > [05-28 07:18:22.929] [info] Tests: succeeded 679, failed 0, canceled 0, ignored 6, pending 1
> > [05-28 07:18:22.929] [info] All tests passed.
> > [05-28 07:18:22.930] [info] Passed: Total 679, Failed 0, Errors 0, Passed 679, Ignored 6, Pending 1
> > [success] Total time: 1262 s, completed May 28, 2019 9:18:30 AM
> 
> https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/16130/console

Figured PR validator fails with Permission Denied error. Is it something wrong with Jenkins pipeline or the changes in this PR causing it? I believe it's the former?

> [PostBuildScript] - Executing post build scripts.
> [pr-validator-per-commit-jenkins] $ /bin/bash -xe /tmp/jenkins3625196160168339971.sh
> + rm -rf /localhome/jenkinsakka/pr-validator-per-commit-jenkins/16150
> + ssh a5.local rm -rf /localhome/jenkinsakka/pr-validator-per-commit-jenkins/16150
> + ssh a6.local rm -rf /localhome/jenkinsakka/pr-validator-per-commit-jenkins/16150
> Permission denied, please try again.
> Permission denied, please try again.
> Permission denied (publickey,password).

**Comment by raboof** [comment]
PLS BUILD

**Comment by raboof** [comment]
> Figured PR validator fails with Permission Denied error. Is it something wrong with Jenkins pipeline or the changes in this PR is causing it? I believe it's the former?

Yes, it was the former - sorry to not get back to this PR before now.

**Comment by raboof** [comment]
(the Jenkins failure is due to the merge conflict with master)

**Comment by hepin1989** [comment]
@mavericksid This need a rebase

**Comment by Captain1653** [comment]
The PR is really old. Is it still needed? The last activity was 1.5 years ago.

**Comment by johanandren** [comment]
Let's close for now and re-open if there is new activity

**Pull request closed without merging**
