### PR TITLE
Fixes for Akka Streams docs

### PR DESCRIPTION
**Pull request by hseeberger**

### CODE REVIEW

**Comment by ktoso** [comment]
Thanks Heiko :-) 
Could you mirror the fixups to `akka-docs-dev/rst/scala/stream-rate.rst`?

**Comment by hseeberger** [comment]
OMG! I changed the Java docs? ;-)

**Comment by ktoso** [comment]
Not sure what you were doing on the `/java/` side of things... (-:

**Comment by hseeberger** [comment]
Now the dark side has been taken care of, too ;-)

**Comment by ktoso** [comment]
Great, thanks!

**Pull request merged**
