### PR TITLE
Implement isTimerActive for BehaviorTestKit #30140

### PR DESCRIPTION
**Pull request by chessman**
References #30140

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @chessman,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by johanandren** [comment]
OK TO TEST

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Review by octonato — APPROVED** [review]
LGTM

Thanks @chessman

**Pull request merged**
