### PR TITLE
Use apidoc directive in stream/stream-quickstart.md (#22904)

### PR DESCRIPTION
**Pull request by Captain1653**
References #22904

My question: Should I add links to this two paragraphs:
Screenshot 2022-03-14 at 22 49 13

I'm not sure about it.

Kind regards

### CODE REVIEW

**Review by raboof — APPROVED** [review]
> Should I add links to this two paragraphs

Would be nice, but even without that paragraph this is already a nice improvement :+1:

**Comment by Captain1653** [comment]
@raboof Thank you for your review. I'll do it in my next PR's

**Comment by Captain1653** [comment]
Can it be reviewed for 2.6.20 ? Please :)

**Review by johanandren — APPROVED** [review]

**Comment by Captain1653** [comment]
The 2.6.20 milestone was forgotten

**Pull request merged**
