### PR TITLE
Bump jackson to 2.10.5

### PR DESCRIPTION
**Pull request by ignasi35**
See the release notes: https://github.com/FasterXML/jackson-databind/blob/2.10/release-notes/VERSION-2.x#L7-L10

### CODE REVIEW

**Comment by raboof** [comment]
(looks like jackson-module-scala isn't there yet, https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2.12/2.10.5/jackson-module-scala_2.12-2.10.5.pom )

**Comment by ignasi35** [comment]
> (looks like jackson-module-scala isn't there yet, [repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2.12/2.10.5/jackson-module-scala_2.12-2.10.5.pom](https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2.12/2.10.5/jackson-module-scala_2.12-2.10.5.pom) )

I wouldn't be surprised if it isn't released in the next day or two either. We may need to start using different variables for each jackson module. Let's put this on hold for a bit.

**Comment by raboof** [comment]
> We may need to start using different variables for each jackson module.

I don't know, it seems kind of nice to keep them in sync.

> Let's put this on hold for a bit

:+1:

**Comment by ignasi35** [comment]
> I don't know, it seems kind of nice to keep them in sync.

Sure! We should do our best, but each jackson library may have a different release cycle (see this lagom [dependency list](https://github.com/lagom/lagom/blame/925bf73ab95b5c2f0761fc6c70112b97e85098c3/project/Dependencies.scala#L39-L42) from some time ago)

**Comment by ignasi35** [comment]
> (looks like jackson-module-scala isn't there yet, [repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2.12/2.10.5/jackson-module-scala_2.12-2.10.5.pom](https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2.12/2.10.5/jackson-module-scala_2.12-2.10.5.pom) )

BTW: the missing artifact is here now :-)

**Comment by ignasi35** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]

**Comment by ennru** [comment]
A few more CVEs got fixed FasterXML/jackson-databind/milestone/112?closed=1

**Review by ennru — APPROVED** [review]
LGTM.

**Pull request merged**
