### PR TITLE
=act split FSM java api implementation in a separate file.

### PR DESCRIPTION
**Pull request by andreaTP**
This will be the first of some, unintrusive PR to keep easier the work of us for Akka.js, 
https://github.com/unicredit/akka.js/tree/annotation-adder

I think this can be accepted and is clean as AbstractActor is.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @andreaTP,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by andreaTP** [comment]
agreed for scala.js  first.

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
From what I see this is an 1:1 moving out the classes into a separate file, no other changes?
If so then, LGTM

**Comment by andreaTP** [comment]
exactly :-)

**Comment by drewhk** [comment]
Does this need any update to the migration guide for 2.4? Or no compatibility was harmed?

**Comment by patriknw** [comment]
LGTM, assuming nothing changed apart from file location.

**Comment by andreaTP** [comment]
no changes at all a part from the file structure

**Comment by andreaTP** [comment]
fixed text of commit messages and PR

**Comment by andreaTP** [comment]
PLS BUILD

**Comment by patriknw** [comment]
Thanks for contributing

**Pull request merged**
