### PR TITLE
Update Scala 2.11.x version to 2.11.12

### PR DESCRIPTION
**Pull request by Philippus**

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Thanks :)

**Comment by patriknw** [comment]
PLS BUILD

**Comment by raboof** [comment]
Looks like it fails because genjavadoc 0.10 was not built for 2.11.12 (https://github.com/lightbend/genjavadoc/pull/122)

**Comment by 2m** [comment]
I have just published genjavadoc 0.10 for 2.11.12. Show be in Maven Central soon.

**Comment by Philippus** [comment]
PLS BUILD

**Comment by 2m** [comment]
PLS BUILD

**Comment by 2m** [comment]
PLS BUILD

**Review by 2m — APPROVED** [review]

**Review by raboof — APPROVED** [review]

**Pull request merged**
