### PR TITLE
bump: Shaded protobuf-java 3.24.0

### PR DESCRIPTION
**Pull request by patriknw**
To align with the grpc bump https://github.com/akka/akka-grpc
Not important to use the same, but since we are anyway bumping.

Previous non-released bump was in #32149 

Merge, not squash, to keep commit attribution to nobody for the regenerate.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one commit author (nobody) is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Review by johanandren — APPROVED** [review]

**Comment by lightbend-cla-validator** [comment]
At least one commit author (nobody) is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by johanandren** [comment]
Argh, did the squash anyway because too quick squash-fingers

**Comment by patriknw** [comment]
commit jackpot my way

**Pull request merged**
