### PR TITLE
=str - removing superfluous try-catch in stream-customize.rst

### PR DESCRIPTION
**Pull request by viktorklang**
@drewhk ping

### CODE REVIEW

**Comment by drewhk** [comment]
LGTM, thanks for noticing!

**Comment by ktoso** [comment]
LGTM, good catch

**Comment by viktorklang** [comment]
The Eye of Klang

**Comment by viktorklang** [comment]
merge?

**Comment by drewhk** [comment]
only after validation

**Comment by viktorklang** [comment]
Is it running all tests to check a doc class? #wtf ?

**Comment by ktoso** [comment]
We have smart validation, will run only docs and projects which depend on it.

**Comment by viktorklang** [comment]
Ow, Y SO SLO? :(

**Comment by viktorklang** [comment]
Ah, so Function declares that it @throws Exception but onPush/onPull and friends on AbstractInHandler/AbstractOutHandler do not declare that they @throws Exception.

**Comment by viktorklang** [comment]
Question is if that should be done or not, @drewhk ?

**Comment by drewhk** [comment]
I think they can be safely decorated with `throws Exception`. It is the framework anyway that needs to deal with any exceptions, but we are the framework, and we happily take the Exception :)

**Pull request merged**
