### PR TITLE
Remove Akka-HTTP sources from akka/akka, moving to akka/akka-http!

### PR DESCRIPTION
**Pull request by ktoso**
Removed all http files, docs, dependencies.
Note also the docs page of http (index only):

```
Akka HTTP Documentation (Java) moved!
=====================================

Akka HTTP has been released as independent stable module (from Akka HTTP 3.x onwards).
The documentation is available under `doc.akka.io/akka-http/current/ <http://doc.akka.io/docs/akka-http/current/java.html>`_.

```

### CODE REVIEW

**Comment by johanandren** [comment]
PLS BUILD

**Comment by patriknw** [comment]
woot

**Comment by johanandren** [comment]
Unrelated fail (`akka.pattern.BackoffSupervisorSpec`)

**Comment by johanandren** [comment]
PLS BUILD

**Comment by patriknw** [comment]
I guess it's not much to review here, but congrats to -19.5k ;-)

**Comment by ktoso** [comment]
Feels good...!

**Pull request merged**
