### PR TITLE
Use java.lang.StringBuilder to format timestamp

### PR DESCRIPTION
**Pull request by REASY**
Addressing https://github.com/akka/akka/issues/26842

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @REASY,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by raboof** [comment]
OK TO TEST

**Comment by raboof** [comment]
looks like the formatting of some imports changed, I suspect our CI will fail on that. Could you format the code? `sbt scalafmtAll` should be able to take care of it.

**Comment by REASY** [comment]
@raboof, fixed formatting. Now CI has passed.

**Review by raboof — APPROVED** [review]
Great, thanks!

**Review by johanandren — APPROVED** [review]

**Review by patriknw — APPROVED** [review]
LGTM, thanks. We'll backport this to 2.5 branch

**Pull request merged**
