### PR TITLE
!htp simplify implicit resolution by getting rid of `RoutingSetup`

### PR DESCRIPTION
**Pull request by jrudolph**
In similar vein to #18064 getting rid of `RoutingSetup` will give better error messages to the user if only one of the implicits is missing. It introduces a bit of denormalization by having to duplicate quite long implicit parameter lists. As long as the Scala compiler doesn't give better error messages it may still be the solution with the best UX for now.

WDYT @sirthias?

### CODE REVIEW

**Comment by jrudolph** [comment]
Error lines in https://jenkins.akka.io/job/pr-validator-per-commit-jenkins/3287/:

```
 10200 Test akka.stream.javadsl.SourceTest.mustBeAbleToRecover failed: java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for 1, took 3.024 sec
 10201     at scala.Predef$.assert(Predef.scala:179)
 10202     at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:338)
 10203     at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:315)
 10204     at akka.testkit.TestKit.expectMsg(TestKit.scala:718)
 10205     at akka.testkit.JavaTestKit.expectMsgEquals(JavaTestKit.java:378)
 10206     at akka.stream.javadsl.SourceTest.mustBeAbleToRecover(SourceTest.java:549)
 10207     ...
 10602 Failed: Total 867, Failed 1, Errors 0, Passed 866, Pending 22
 10603 Failed tests:
 10604 	akka.stream.javadsl.SourceTest
 13958 (akka-stream-tests-experimental/test:test) sbt.TestsFailedException: Tests unsuccessful
 13959 Total time: 821 s, completed Jul 24, 2015 5:50:05 PM
```

**Comment by sirthias** [comment]
Ok, looks good to me!
I agree that having this additional implicit level didn't come with enough benefits to justify the (error message quality) cost.

**Comment by ktoso** [comment]
LGTM and the test that failed should be fixed by now as well.

**Comment by ktoso** [comment]
Refs https://github.com/akka/akka/issues/18096 for tracking what went into which release

**Pull request merged**
