### PR TITLE
=http =doc fix some spray references in scaladoc

### PR DESCRIPTION
**Pull request by matsluni**
just removed some spray references in scaladoc.

### CODE REVIEW

**Comment by drewhk** [comment]
LGTM

**Comment by rkuhn** [comment]
fixes #16113 

LGTM; could you include the ticket number in the commit message? Then we can merge.

**Comment by matsluni** [comment]
Sure.

**Comment by matsluni** [comment]
Changed the commit message to include the ticket number.

**Comment by rkuhn** [comment]
Thanks @matsluni !

**Pull request merged**
