### PR TITLE
Akka.js cherries to master

### PR DESCRIPTION
**Pull request by ktoso**
Paves the way for Akka.js moving forward https://github.com/akka/akka/issues/18234 

I had conflicts in the Scheduler and FSM PRs, the rest applied cleanly. 
Please have a look if the picks are valid.

// cc @andreaTP (what's your colleagues github handle? I seem to not know..)
// cc @rkuhn

### CODE REVIEW

**Comment by andreaTP** [comment]
@andreaferretti @yawnt
will check later!

**Comment by ktoso** [comment]
Excellent, thanks! And thanks for the handles :)

**Comment by andreaTP** [comment]
github says that there are no conflicts...
https://github.com/akka/akka/compare/akka-js-dev...master

If this is true LGTM!

**Comment by rkuhn** [comment]
LGTM

**Comment by yawnt** [comment]
just wanted to chip in and just say thanks :) bright future ahead!

**Comment by ktoso** [comment]
> just wanted to chip in and just say thanks :)
Indeed, very exciting :) The demos looked very interesting, hoping to see a recording of the talk which includes the demos by @andreaTP :)

> *bright future* ahead!

// random: fun movie, weird fun :-) [アカルイミライ](https://en.wikipedia.org/wiki/Bright_Future)

**Comment by 2beaucoup** [comment]
Looks like the first commit is wrong.

**Comment by ktoso** [comment]
// cc @bantonsson @patriknw

**Comment by patriknw** [comment]
apart from the comments it looks good

**Comment by bantonsson** [comment]
LGTM

**Comment by ktoso** [comment]
The https://github.com/akka/akka/pull/18172/commits commit actually was already on master, thus https://github.com/akka/akka/pull/18875#commitcomment-14270381 all's good with that one, will check LARS next...

**Pull request merged**
