### PR TITLE
Adding explanation for Java DSL TestKit#awaitAssert return value

### PR DESCRIPTION
**Pull request by emag**
Refs #24110

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @emag,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Thanks, first PR from the ScalaMatsuri hackathon ;-)

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Review by raboof — APPROVED** [review]
Nice one, thanks!

**Pull request merged**
