### PR TITLE
=str defer calling SSLEngine.closeOutbound until after handshake

### LINKED ISSUE #26104: When using EagerClose on a TLS connection, the handshake may fail if one of the sides completes before the handshake is complete
It appears that when either side completes before the handshake is complete, the SSLEngine goes into ERROR/CLOSED state and is no longer valid for processing data on the other half of the connection.

This problem occurs under JDK8. In later JDK's it appears this code was rewritten and no longer shows the problem.

### PR DESCRIPTION
**Pull request by jrudolph**
In JDK8, SSLEngine may otherwise run into an IllegalStateException when
receiving the next handshake packet.

Fixes #26104.

### CODE REVIEW

**Comment by patriknw** [comment]
ping

**Comment by jrudolph** [comment]
Added a test scenario.

**Review by raboof — APPROVED** [review]
The logic is quite intricate (e.g. it's not quite obvious to my why we want to add this check on line 305 and not 306, apparently we want to call `doWrap` when `inputBunch.isDepleted(UserIn) && userInChoppingBlock.isEmpty` but not `mayCloseOutbound`?), but the test is pretty convincing.

Indeed verified that the test fails without the change and succeeds with it on jdk8.

Unfortunately I don't remember how I originally ran into this issue when I filed #26104, so I can't double-check whether it has the desired effect for that case as well.

**Comment by raboof** [comment]
(rebased for conflicts)

**Comment by egisj** [comment]
> Unfortunately I don't remember how I originally ran into this issue when I filed #26104, so I can't double-check whether it has the desired effect for that case as well.

I _think_ this PR was opened in response to a bug report from me (Case ID: 11989). Here's an original reproducer: https://github.com/egisj/stream-ssl-handshake-bug/

**Comment by jrudolph** [comment]
> The logic is quite intricate (e.g. it's not quite obvious to my why we want to add this check on line 305 and not 306, apparently we want to call `doWrap` when `inputBunch.isDepleted(UserIn) && userInChoppingBlock.isEmpty` but not `mayCloseOutbound`?), but the test is pretty convincing.

I guess the reasoning was that when we would put it on the next line `nextPhase(outboundClosed)` might still be called which is not what we want. If we do it like this, nothing is done in the moment when it's called. What happens instead is that we carry on with the handshake which drives the next states until the handshake is finished and we arrive here again but now `mayCloseOutbound` is `true` then.

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
should it be backported to `release-2.5`?

**Comment by jrudolph** [comment]
> should it be backported to `release-2.5`?

I guess it merges cleanly, so why not.

**Pull request merged**
