### PR TITLE
fix failing SystemMessageDeliverySpec, #21331

### PR DESCRIPTION
**Pull request by patriknw**
I had a good reproducer, failing 1 of 20 runs. The test utility was not `synchronized`

### CODE REVIEW

**Comment by ktoso** [comment]
LGTM

**Comment by drewhk** [comment]
LGTM (took a sec until I realized this is test code :) )

**Comment by johanandren** [comment]
LGTM

**Comment by patriknw** [comment]
yeah, the nice feeling of being able to use the awesome `synchronized` ;-)

**Comment by patriknw** [comment]
Refs #21331

**Pull request merged**
