### PR TITLE
Don't use pattern matching to generate less bytecode.

### PR DESCRIPTION
**Pull request by He-Pin**

### CODE REVIEW

**Comment by hepin1989** [comment]
L8
    LINENUMBER 538 L8
    ALOAD 3
    ASTORE 5
   L9
    LINENUMBER 539 L9
    ALOAD 5
    INSTANCEOF akka/actor/AutoReceivedMessage
    IFEQ L10
    ALOAD 0
    ALOAD 1
    INVOKEVIRTUAL akka/actor/ActorCell.autoReceiveMessage (Lakka/dispatch/Envelope;)V
    GETSTATIC scala/runtime/BoxedUnit.UNIT : Lscala/runtime/BoxedUnit;
    ASTORE 2
    GOTO L11
   L10
   FRAME FULL [akka/actor/ActorCell akka/dispatch/Envelope T java/lang/Object scala/Tuple2 java/lang/Object] []
    GOTO L12
   L12
    LINENUMBER 540 L12
   FRAME SAME
    ALOAD 0
    ALOAD 5
    INVOKEVIRTUAL akka/actor/ActorCell.receiveMessage (Ljava/lang/Object;)V
    GETSTATIC scala/runtime/BoxedUnit.UNIT : Lscala/runtime/BoxedUnit;
    ASTORE 2
    GOTO L11

    
   L11
    LINENUMBER 542 L11
   FRAME FULL [akka/actor/ActorCell akka/dispatch/Envelope scala/runtime/BoxedUnit java/lang/Object scala/Tuple2 java/lang/Object] []
    ALOAD 3
    INSTANCEOF akka/actor/AutoReceivedMessage
    IFEQ L13
   L14
    LINENUMBER 543 L14
    ALOAD 0
    ALOAD 1
    INVOKEVIRTUAL akka/actor/ActorCell.autoReceiveMessage (Lakka/dispatch/Envelope;)V
    GOTO L15
   L13
    LINENUMBER 545 L13
   FRAME SAME
    ALOAD 0
    ALOAD 3
    INVOKEVIRTUAL akka/actor/ActorCell.receiveMessage (Ljava/lang/Object;)V

**Comment by helena** [comment]
Interesting. I have found pattern matching to be more performant/faster than the if/else.

**Review by raboof — APPROVED** [review]
So it saves loading the 'unit' value that is the result of the patternmatch but is ignored anyway.

2 aspects to consider here are performance and readability. I don't see a big difference on either aspect, so I'm OK with this change.

**Review by helena — APPROVED** [review]
Thanks

**Pull request merged**
