### PR TITLE
Fix maximumObjectLength check in JsonFraming, #31569

### PR DESCRIPTION
**Pull request by patriknw**
References #31569

### CODE REVIEW

**Comment by an-tex** [comment]
looks good to me, thanks @patriknw !

**Review by johanandren — APPROVED** [review]
LGTM

**Comment by leviramsey** [comment]
Since this is fixing a regression in 2.6.20, I presume this should be backported?  We should have a label for `backport-to-apache`.

**Review by octonato — APPROVED** [review]
LGMT

**Pull request merged**
