### PR TITLE
ByteString deserialization unbroken for large bytestrings 

### LINKED ISSUE #20901: Problem serializing akka.util.ByteString
I do *not* have a minimized recipe for this one, nor time to try to craft one, so consider it a heads-up and braindump of the facts.  Here's what I know:

The context is [Querki](https://www.querki.net/), specifically photo upload.  The data packets come from the browser, [through Play](https://github.com/jducoeur/Querki/blob/2.0.3.5/querki/scalajvm/app/controllers/PhotoController.scala#L35), into [a rough-and-ready Actor-to-Actor streaming system](https://github.com/jducoeur/Querki/blob/2.0.3.5/querki/scalajvm/app/querki/streaming/StreamSendActor.scala#L45), and thence to [a receiving sharded Entity](https://github.com/jducoeur/Querki/blob/2.0.3.5/querki/scalajvm/app/querki/streaming/UploadActor.scala#L100) that does the processing.  I found that the photos were corrupted by the time I started processing them, and eventually traced it back to the send from the Play node to the sharded one.

I'm *fairly* sure that the problem was serialization -- this code all worked fine on my single-node development system, but showed corruption in the multi-node production one.  The corruption occurred in the ByteString that we get from Play's BodyParser (typically 8k chunks), which is wrapped inside [a case class message](https://github.com/jducoeur/Querki/blob/2.0.3.5/querki/scalajvm/app/querki/streaming/ApiTraits.scala#L10).  I haven't gotten around to customizing the serialization of this class, so I believe it's using Java Serialization -- it wouldn't surprise me if that is involved in the problem.

I did some examination of the ByteString on both the [sending](https://github.com/jducoeur/Querki/blob/2.0.3.5/querki/scalajvm/app/querki/streaming/StreamSendActor.scala#L44) and [receiving](https://github.com/jducoeur/Querki/blob/2.0.3.5/querki/scalajvm/app/querki/streaming/UploadActor.scala#L101) sides.  The received length is correct, and the first few bytes are right, but the final bytes of the chunk are zeroed out on the receiving side.  So it feels as if one or more of the blocks in a ByteStrings is missing, but the length is serializing and deserializing properly.

To confirm that serialization of ByteString is the problem, I [replaced that with a Vector in the message](https://github.com/jducoeur/Querki/blob/2.0.3.6/querki/scalajvm/app/querki/streaming/ApiTraits.scala#L16), simply adding a `.toVector` on the sending side, and the problem immediately cleared up.  (So this isn't a crisis for me, just an FYI.)

The problem packets seem to at least mostly be 8k, so it is *possible* that this is an off-by-1 error on power of 2 boundaries.  (I don't think this is likely, just something to be aware of.)

Everything is built with Akka 2.4.6, in case that is relevant.

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #20901

### CODE REVIEW

**Comment by drewhk** [comment]
Can you a bit explain what is happening here?

**Comment by johanandren** [comment]
The bug was that `ObjectInputStream.read` was used, and it `Attempts to read len bytes into the array b ... returns the number of bytes read`. So with a large enough ByteString it failed to read all bytes (repeatedly got it to read 11 bytes for some reason), returned how many bytes it read and returned that partially read array.

`readFully` reads len bytes or throws an exception, which is what we want here

**Comment by drewhk** [comment]
Ok, thanks, LGTM.

**Comment by ktoso** [comment]
LGTM

**Pull request merged**
