### PR TITLE
= actor extract StringFormatter from Logging.scala for reuse.

### PR DESCRIPTION
**Pull request by He-Pin**
for reusage

like formating the exception's error message in Java.

### CODE REVIEW

**Comment by ktoso** [comment]
Please argument why you're doing PRs.

**Comment by ktoso** [comment]
1) that's not true; in Java you'd simply use `String.format()`
2) why is that akka's responsibility to provide libs for that? we're not a "everything-you-possibly-want including string operations" toolkit, we're a concurrency and distribution toolkit

**Comment by hepin1989** [comment]
I know, it's for improving the experiment of using Akka.
Cause we have made a lot of usage of `LoggingHelper` thing do to the same. I do this from a Java developer's point, not from the Scala one.
And it does keep the BC.

**Comment by hepin1989** [comment]
for `concurrency`, we will have `Future` and `CompletableStage` which do contain `Exception`s,
and `Exception` do have messages. Users would like the write most the same code in both Scala and Java.

**Comment by ktoso** [comment]
This has nothing to do with Java vs. Scala; we simply do not expose all kinds of internal things that we happen to have somewhere because someone might want to use them *maybe*. There are plenty libraries out there that focus on logging or string operations, why would Akka start offering those methods -- which it simply uses internally.

In Java, for formatting strings, use the usual Java style: String.format -- what's wrong with that?

**Comment by hepin1989** [comment]
There is a word in Chinese,`曲高和寡`，Improve the accessibility is helpful for marketing too. 
The problem is ,the `{}` and the `%s` is not the same.

**Comment by ktoso** [comment]
You can, and *should*, use plain slf4j or any other logging lib you like.
Please do not keep mistaking Akka's logging tool as "the one you must use", because it is NOT. It is simply a small logging tool that Akka needs to be able to log things without depending on a specific logging library.

**Comment by hepin1989** [comment]
It's not for logging but the formatting message in the Exception, that's my two coins of concern.

**Comment by raboof** [comment]
I agree using `LoggingAdapater` `{}` string formatting for logging and `String.format` `%s` string formatting for exceptions might look a bit inconsistent, but this might actually be good since they really behave differently: `LoggingAdapter` will only `toString` the arguments when the log level is configured such that this logging will actually appear, while `String.format` will always evaluate them.

When we make these look too so similar I fear we give the impression that `LoggingAdapter.log(level, pattern, arg)` is equivalent to `LoggingAdapter.log(level, StringFormatter.format(pattern, arg))`, which is not the case.

**Comment by patriknw** [comment]
Thanks for the suggestion @hepin1989 , but this one is not accepted for the reasons given by others already. We take usability of Akka from Java very seriously and appreciate improvement suggestions but we can't include everything in Akka and this is not an essential part of Akka.

**Pull request closed without merging**
