### PR TITLE
Fixed scaladoc-typo in FSM.scala

### PR DESCRIPTION
**Pull request by vadimsemenov**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @vadimsemenov,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
Thanks for the catch! LGTM

**Comment by patriknw** [comment]
@vadimsemenov We will not be able to merge this without the CLA signature. Would you be able to sign that (online at http://www.lightbend.com/contribute/cla)? Otherwise, let us know so that we can close the PR.

**Comment by johanandren** [comment]
Ping @vadimsemenov ? Please sign the CLA or let us know if you don't want to do that so we can merge or close this PR, thanks!

**Comment by vadimsemenov** [comment]
@patriknw, @johanandren, sorry for the delay, guys. Now it's signed.

**Comment by johanandren** [comment]
LGTM

**Pull request merged**
