### PR TITLE
sync artery with latest master (2.4.9++)

### PR DESCRIPTION
**Pull request by patriknw**
Merge of master into artery-dev. I need the Hub.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @longmuir,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by drewhk** [comment]
Was something merged without CLA validation??

**Comment by drewhk** [comment]
https://www.lightbend.com/contribute/cla/check/longmuir

Not signed.

**Comment by patriknw** [comment]
Yes, somehow. I have pinged him here https://github.com/akka/akka/pull/21269
He works for Lightbend, so should not be a problem.

**Comment by patriknw** [comment]
merging, master has the same CLA issue

**Pull request merged**
