### PR TITLE
#24544 Add dispatcher name to names of threads created by AffinityPool 

### PR DESCRIPTION
**Pull request by RafalSumislawski**
(as it is already done for ForkJoin and ThreadPool)

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Comment by johanandren** [comment]
Fixes #24544

**Review by jrudolph — APPROVED** [review]
LGTM

The code is basically copied from the fork join pool code. Would be nice to support this in a more principled way but I guess it's fine for now.

**Pull request merged**
