### PR TITLE
sharding: actively signal 'region stopped' to the coordinator

### PR DESCRIPTION
**Pull request by raboof**
Refs #30401

### CODE REVIEW

**Review by johanandren — APPROVED** [review]

**Review by jrudolph — COMMENTED** [review]
Will rolling upgrades work for this upgrade or do we a staggered approach to introduce the message / serialization / handler for the new message in one version and only activate it in the next (as we've done before)?

**Comment by octonato** [comment]
> Will rolling upgrades work for this upgrade or do we a staggered approach to introduce the message / serialization / handler for the new message in one version and only activate it in the next (as we've done before)?

So the effect will be that old nodes will log deserialization exceptions, but will function as before. Meaning that they will rely on the `Terminate` message. 

Is that a reason to cut two akka releases? I see that as an acceptable annoyance. Maybe a mention in the release notes may suffice. 

As a user, I would prefer once rolling upgrade with some noise in the logs then two releases and to redeployments.

**Review by octonato — APPROVED** [review]
LGTM as is, but also fine we decide to do staggered release as suggested by Johannes.

**Comment by raboof** [comment]
> So the effect will be that old nodes will log deserialization exceptions, but will function as before.

Are you sure? I don't remember if serialization failures will just cause exceptions or also tear down the connection. If it's just logging then I agree having it in one release seems fine to me, but if it tears down the connection we might want to do it in two phases.

**Comment by octonato** [comment]
> Are you sure?

Now I'm not anymore. 

As far as I remember, it will only log the exceptions.

**Comment by octonato** [comment]
https://github.com/akka/akka/blob/e43f2be6cd6bb423da5559b8d410ae9687d3fe13/akka-actor/src/main/scala/akka/serialization/Serializer.scala#L141-L154

So, I think we are on the safe side.

**Comment by octonato** [comment]
Let's merge this as is and make sure that we add a note in the release notes about the serialization error one might get on rolling upgrades.

**Pull request merged**
