### PR TITLE
OSGi: register ActorSystem under ActorFactoryRef interface

### PR DESCRIPTION
**Pull request by barthorre**
By also registering the osgi service under the interface name, it becomes more convenient to retrieve the reference from the osgi registry.

With the current implementation we need to explicitly tell blueprint to allow classes instead of only interfaces to be looked up. eg 
`<reference id="actorSystem" interface="akka.actor.ActorSystem" ext:proxy-method="classes" />` 

could become 

`<reference id="actorSystem" interface="akka.actor.ActorFactoryRef" />`

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @barthorre,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by johanandren** [comment]
It's not obvious to me that this is the right thing to do, the `ActorContext` is also an `ActorRefFactory` (for creating children). I understand this that as you would depend on `ActorRefFactory` and that would implicitly mean you want to be able to spawn actors at the top level, if that is the case I think it is better if that is explicit like it is now.

**Comment by gertv** [comment]
While the OSGi specification allows for the use of class names as service interfaces for the registration of services, things like Blueprint prefer the use of an actual interface over a concrete class. 

The use case here is to bootstrap the actor system using the activator provided by Akka itself, but handle the interaction with the other OSGi services with Blueprint. This pull requests only adds the ActorRefFactory as a more convenient interface for this scenario, users can still use ActorSystem directly if they prefer to do so.

**Comment by johanandren** [comment]
Alright, thanks for the clarification, in that case this change sounds reasonable. Would be good with reviews from people who have previously been involved in OSGi support since we have no expertise on this in the team. Ping @lefou @atooni

**Review by johanandren — APPROVED** [review]
LGTM as far as I understand

**Comment by lefou** [comment]
Looks good to me too. Registering a service under all of it's implementing interfaces is totally fine, and IMHO in most cases best practice.

**Comment by atooni** [comment]
I agree with lefou - looks good to me as well

**Review by lefou — APPROVED** [review]

**Review by ennru — APPROVED** [review]
LGTM.

**Comment by ennru** [comment]
Thank you for making Akka easier to use with OSGi!

**Pull request merged**
