### PR TITLE
=str 20967 print stream state on test failed

### PR DESCRIPTION
**Pull request by agolubev**
Introduced StreamSpec that looks for Supervisors/Their Children and sends print dump messages. Haven't added it to all stream tests yet.

### CODE REVIEW

**Comment by ktoso** [comment]
Nice!

**Comment by ktoso** [comment]
OK TO TEST

**Comment by johanandren** [comment]
LGTM, great idea!

**Comment by ktoso** [comment]
LGTM, very nice!

FYI @drewhk

**Comment by ktoso** [comment]
Shall we make a ticket to add StreamSpec to other tests so we don't forget?

**Comment by ktoso** [comment]
Refs #20967

**Comment by drewhk** [comment]
Thanks great addition!

**Comment by agolubev** [comment]
That was fast! Thanks.
Need another ticket for adding StreamSpec to all stream tests. I'll create one

**Pull request merged**
