### PR TITLE
=doc using PatternsCS.retry in java docs

### PR DESCRIPTION
**Pull request by kun-song**

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Review by ktoso — APPROVED** [review]
Looks good, thanks :)

**Review by raboof — COMMENTED** [review]
I agree with the direction of this change, but this whole page consistently shows how to use Scala futures in Java. I wonder if we shouldn't overhaul the whole page to make it `CompletionStage`/`CompletableFuture`-based when viewing for Java?

**Comment by satansk** [comment]
@raboof I also notice that and I think it's better to use `CompletionStage` and lambdas in the Java view.

When I make this PR, I don't have an IDE at my hand, and I was planning another PR when back home.

**Comment by patriknw** [comment]
I agree with @raboof , but let's merge this small improvement first. The bigger improvement is welcome as a separate PR, @satansk

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
