### PR TITLE
flatMapPrefix stuck on cancellations 

### PR DESCRIPTION
**Pull request by eyalfa**
References #30614 

* introduce several tests demonstrating the issue.
* introduce a fix

### CODE REVIEW

**Comment by eyalfa** [comment]
@johanandren seems like the build failed again (same way) without any useable information

**Comment by octonato** [comment]
It's failing on legit compilation error about non-exhaustive pattern matching

```scala
[info] compiling 203 Scala sources and 29 Java sources to /home/runner/work/akka/akka/akka-stream-tests/target/scala-2.13/test-classes ...                                                                                    │
│2021-09-03T07:05:55.3345603Z [error] /home/runner/work/akka/akka/akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlatMapPrefixSpec.scala:633:9: match may not be exhaustive.                                                                     │
│2021-09-03T07:05:55.3349123Z [error] It would fail on the following input: (x: akka.stream.Attributes.NestedMaterializationCancellationPolicy forSome x not in (EagerCancellation, PropagateToNested))                                                     │
│2021-09-03T07:05:55.3352159Z [error]         att match {                                                                                                                                                                                                   │
│2021-09-03T07:05:55.3353575Z [error]         ^                                                                                                                                                                                                             │
│2021-09-03T07:05:55.3368304Z [error] /home/runner/work/akka/akka/akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlatMapPrefixSpec.scala:651:9: match may not be exhaustive.                                                                     │
│2021-09-03T07:05:55.3371574Z [error] It would fail on the following input: (x: akka.stream.Attributes.NestedMaterializationCancellationPolicy forSome x not in (EagerCancellation, PropagateToNested))                                                     │
│2021-09-03T07:05:55.3374121Z [error]         att match {                                                                                                                                                                                                   │
│2021-09-03T07:05:55.3375507Z [error]         ^                                                                                                                                                                                                             │
│2021-09-03T07:05:55.3387117Z [error] /home/runner/work/akka/akka/akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlatMapPrefixSpec.scala:668:9: match may not be exhaustive.                                                                     │
│2021-09-03T07:05:55.3391888Z [error] It would fail on the following input: (x: akka.stream.Attributes.NestedMaterializationCancellationPolicy forSome x not in (EagerCancellation, PropagateToNested))                                                     │
│2021-09-03T07:05:55.3395781Z [error]         att match {                                                                                                                                                                                                   │
│2021-09-03T07:05:55.3397753Z [error]         ^                                                                                                                                                                                                             │
│2021-09-03T07:05:55.3411420Z [error] /home/runner/work/akka/akka/akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlatMapPrefixSpec.scala:685:9: match may not be exhaustive.                                                                     │
│2021-09-03T07:05:55.3415693Z [error] It would fail on the following input: (x: akka.stream.Attributes.NestedMaterializationCancellationPolicy forSome x not in (EagerCancellation, PropagateToNested))                                                     │
│2021-09-03T07:05:55.3418727Z [error]         att match {                                                                                                                                                                                                   │
│2021-09-03T07:05:55.3420109Z [error]         ^                                                                                                                                                                                                             │
│2021-09-03T07:05:55.5749569Z [error] four errors found
```

**Comment by eyalfa** [comment]
@octonato , thanks for pointing this out!
must sya theres something strange going on with github action's view, searching for '[error]' doesn't find anything!
however searching for 'FlowFlatMapPrefixSpec.scala:633:9' shows couple of [lines](https://github.com/akka/akka/runs/3503452204?check_suite_focus=true#step:5:6892) starting with '[error]': 
```
[error] /home/runner/work/akka/akka/akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlatMapPrefixSpec.scala:633:9: match may not be exhaustive.
[error] It would fail on the following input: (x: akka.stream.Attributes.NestedMaterializationCancellationPolicy forSome x not in (EagerCancellation, PropagateToNested))
[error]         att match {
[error]         ^
[error] /home/runner/work/akka/akka/akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlatMapPrefixSpec.scala:651:9: match may not be exhaustive.
[error] It would fail on the following input: (x: akka.stream.Attributes.NestedMaterializationCancellationPolicy forSome x not in (EagerCancellation, PropagateToNested))
[error]         att match {
[error]         ^
[error] /home/runner/work/akka/akka/akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlatMapPrefixSpec.scala:668:9: match may not be exhaustive.
[error] It would fail on the following input: (x: akka.stream.Attributes.NestedMaterializationCancellationPolicy forSome x not in (EagerCancellation, PropagateToNested))
[error]         att match {
[error]         ^
[error] /home/runner/work/akka/akka/akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowFlatMapPrefixSpec.scala:685:9: match may not be exhaustive.
[error] It would fail on the following input: (x: akka.stream.Attributes.NestedMaterializationCancellationPolicy forSome x not in (EagerCancellation, PropagateToNested))
[error]         att match {
[error]         ^
[error] four errors found
```

This makes it very hard to detect compilation errors

**Review by johanandren — APPROVED** [review]
LGTM

**Review by octonato — APPROVED** [review]

**Pull request merged**
