### PR TITLE
Use full state for ORMap removals, #22631

### PR DESCRIPTION
**Pull request by patriknw**
* at least until we have found a solid solution

Refs  #22631

### CODE REVIEW

**Comment by patriknw** [comment]
This PR is not complete, might be more cases that requires the full state.

**Comment by patriknw** [comment]
Another challenge is how we should deal with future changes, e.g. let's say that we implement the other deltas in 2.5.1 and it should be possible to do a rolling upgrade from 2.5.0. Good thing is that deltas can be dropped, but we need to prepare for it.

**Comment by gosubpl** [comment]
IMHO `ORSet` requires full state too for the time being, see https://github.com/akka/akka/issues/22631#issuecomment-290041448

**Comment by patriknw** [comment]
Yes, I'll add thst. We actually already have a fullstatedelat for OrSet, but it's not used for removal

**Comment by patriknw** [comment]
Another thought, the original idea of using `Option` for the `delta` was that it could be skipped and falling back to full state. That would have been useful here, but it doesn't work.
E.g. remove followed by add. If we skipped delta for the remove the add delta could be applied before the full state gossip representing the remove was received and violating the whole idea of RequiresCasualDelivery.

I think we should bump the delta versions also when None is returned, meaning that the add in the above example would not be applied if arrived before the full state. I'll take a look at that, but need to do some other things first.

**Comment by gosubpl** [comment]
@patriknw can you please reconsider this change, as https://github.com/akka/akka/pull/22654 fixes all tests that were broken

**Comment by patriknw** [comment]
Superseded by https://github.com/akka/akka/pull/22654 and https://github.com/akka/akka/pull/22656

**Pull request closed without merging**
