### PR TITLE
= str #18134 add require assert for WatermarkRequestStrategy

### PR DESCRIPTION
**Pull request by He-Pin**
refs https://github.com/akka/akka/issues/18134

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TES

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
LGTM, thanks!

**Comment by drewhk** [comment]
LGTM

**Pull request merged**
