### PR TITLE
add recover in front of MergeHub, to avoid logging, #21397

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by johanandren** [comment]
LGTM

**Comment by johanandren** [comment]
Refs #21397

**Comment by drewhk** [comment]
We likely need a simpler stage to just turn failure into completion. LGTM for now.

**Comment by patriknw** [comment]
ok, onPush and onPull looks to be as fast as they can, though

**Comment by drewhk** [comment]
Ok, I didn't look at the code, so that can be true.

**Pull request merged**
