### PR TITLE
migrate-SBT-Dependencies 

### PR DESCRIPTION
**Pull request by GKuldeepak-Knoldus**
- Rename Test object to TestDependencies, to avoid duplicate import
- Replaced 'test' with Test

References #27040

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @GKuldeepak-Knoldus,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by johanandren** [comment]
Looks like it needs some formatting with `scalafmtSbt`

**Review by raboof — APPROVED** [review]

**Comment by GKuldeepak-Knoldus** [comment]
> Looks like it needs some formatting with `scalafmtSbt`

Formatted with `scalafmtSbt`

**Review by octonato — APPROVED** [review]
LGTM

**Comment by octonato** [comment]
Thanks @GKuldeepak-Knoldus

**Pull request merged**
