### PR TITLE
feat: Add license key check

### PR DESCRIPTION
**Pull request by patriknw**
* Check license key at startup
* Base62 decoding with validation of invalid strings
* Added Base62 specs
* Added warn on expiry support
* Added license revocation list support.
* Added license supplier
* Adjustments to log messages and termination after expiry
* Mention in docs
* Version and BuildDate as compile time constants
* silence log in tests

### CODE REVIEW

**Review by johanandren — APPROVED** [review]

**Comment by PerWiklander** [comment]
Is it correct that the actor system terminates after 15 minutes if there is no valid key configured?
In a production environment, wouldn't you rather see that it refused to start at all?
15 minutes feels more like a time bomb and long enough to get past smoke tests.

**Comment by TylerJewell** [comment]
Yes, it is correct that it terminates after 15 minutes if there is no valid key configured. 
We have discussed having an optional configuration property that, if activated, would prevent a startup from occurring at all.  We can have that added to the backlog for the next release.

Just to confirm - the purpose of such a mode is to more quickly fail smoke tests in pre-production environments?

**Comment by PerWiklander** [comment]
Or production environments. When rolling out a new release I want it to work or fail fast, not pretend to work for 15 minutes when the error was obvious from the beginning.

Then there's the issue of limited validity time for keys and having to deploy new ones. That whole thing smells like non automated SSL certs all over again.

**Comment by johanandren** [comment]
One note: if there is a key configured, and that key is not valid at the time of startup it will fail the actor system immediately, so this would only be about the scenario where there is no key specified at all.

**Comment by PerWiklander** [comment]
That is both good and bad. Good that it fails fast for the more common case, but worse in the "rare" case that the config value is missing.

I say "rare" because this is also the default case for any system that just bumps the Akka version without reading the change log carefully. A deploy of that newer version of the system would look like it works like normal. Until 15 minutes later.

How about specifying a profile like "dev" or "prod" with different behaviors?

I get it that a new developer who just installed the dependency could want to test something for 15 minutes without getting a key.

**Comment by patriknw** [comment]
Isn't the concern about the expiry of keys? Invalid keys will be rejected immediately. You can easily check for missing key and terminate if that is what you want.
```
if (system.settings.config.getConfig("akka.license-key") != "")
```

For expired keys we could add a way to retrieve the key expiry date and you can write tests or prod/dev code in the way you like. For example, from the returned expiry date you can have a test that fails one month ahead of expiry so that you know that it's time to renew.

**Comment by patriknw** [comment]
Thank you for feedback @PerWiklander 
We have added the license key expiry date to the ActorSystem to make it possible to write tests that fail ahead of time, or terminate immediately if that is desired. https://github.com/akka/akka/pull/32558

**Pull request merged**
