### PR TITLE
StreamTcpDocSpec: Less race, better error if client fails

### LINKED ISSUE #24500: FAILED: jdocs.stream.io.StreamTcpDocTest.actuallyWorkingClientServerApp
https://jenkins.akka.io:8498/job/akka-nightly-2.12/472/testReport/jdocs.stream.io/StreamTcpDocTest/actuallyWorkingClientServerApp/

```
Error Message

java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for Hello world

Stacktrace

sbt.ForkMain$ForkError: java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for Hello world
	at scala.Predef$.assert(Predef.scala:219)
	at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:401)
	at akka.testkit.TestKitBase.expectMsg(TestKit.scala:378)
	at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:378)
	at akka.testkit.TestKit.expectMsg(TestKit.scala:895)
	at jdocs.stream.io.StreamTcpDocTest.actuallyWorkingClientServerApp(StreamTcpDocTest.java:163)
```

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #24500

### CODE REVIEW

**Review by raboof — APPROVED** [review]
Nice improvements. Might be even nicer binding to port 0, but this is 👍

**Comment by johanandren** [comment]
Oh, I think I left some changes in there, that I made before I realized it defines one server/client with specific port and then actually uses another one with the temporary server address (which uses 0). The actual change here is blocking on server bind/client connect.

**Comment by johanandren** [comment]
PLS BUILD

**Review by chbatey — APPROVED** [review]
Excellent

**Pull request merged**
