### PR TITLE
Avoid non-ASCII characters in sources

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by ktoso** [comment]
LGTM I guess ;)

**Comment by ktoso** [comment]
Though we do have the fancy arrows here and there btw.

**Comment by johanandren** [comment]
I don't see why we should be limited to ASCII, I thought the Scala compiler defaults to treat sources as UTF-8?

**Comment by raboof** [comment]
Hm yes, there should be non-ascii characters in many more places. I added this branch because someone on Gitter was running into problems with these, but that appears to have been an sbt-in-intellij problem.

Closing.

**Pull request closed without merging**
