### PR TITLE
Fix log args to actually show the forwarded message

### PR DESCRIPTION
**Pull request by noise64**
Just a small debug log fix. (Or maybe the message is intentionally not used, in that case the pattern should be fixed)

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @noise64,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by raboof — COMMENTED** [review]
Thanks for spotting the inconsistency! I think we want to avoid logging the entire message (as that could be big), so indeed I think we should update that pattern.

**Comment by raboof** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]

**Review by patriknw — APPROVED** [review]
LGTM, thanks

**Pull request merged**
