### PR TITLE
=htp #18999 fix IllegalArgumentException ...

### LINKED ISSUE #18999: getFromFile and getFromResource throw IllegalArgumentException on empty files
Fix is coming shortly.

/cc @jrudolph

### PR DESCRIPTION
**Pull request by sirthias**
in getFromFile/getFromResource when serving empty files

Closes #18999.

/cc @jrudolph

### CODE REVIEW

**Comment by jrudolph** [comment]
:+1: 

Strange that apparently no one tripped on that one yet.

**Comment by sirthias** [comment]
@jrudolph Yes, true. I just did in another project though...
I guess being on dog food really does help with quality.

**Comment by drewhk** [comment]
I also started dogfooding on WS. So far I am really happy (^_^)

**Comment by drewhk** [comment]
LGTM

**Comment by ktoso** [comment]
> I guess being on dog food really does help with quality.

Very glad you're ~~dog fooding~~  drinking your champagne :cocktail: (there's no champagne emoji, wat?)

**Comment by ktoso** [comment]
Great catch, LGTM

**Pull request merged**
