### PR TITLE
jctools mailbox

### PR DESCRIPTION
**Pull request by patriknw**
@viktorklang I created a PR from your branch. Good to have it as part of the jmh tests.
We should also discuss if we should include such mailbox for real, where to put it and the dependency is the only concern.

### CODE REVIEW

**Comment by nitsanw** [comment]
Should I be worried that these tests failed?

**Comment by patriknw** [comment]
PLS BUILD

**Comment by patriknw** [comment]
it was binary compatibility check that failed for unrelated issue, should be fixed now.

**Comment by nitsanw** [comment]
Awesome! Merge!

**Review by chbatey — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
Well, this is just adding it to the benchmark project. We need to discuss how and if we can add it to Akka itself. We try to keep akka-actor free from external dependencies as much as possible. Since this mailbox can't be the default mailbox anyway it's no problem to have it elsewhere since it must anywhere be documented how to enable it. The question is where?

* new module? drawback is that we can't use it as default for Akka Streams where I think it could be a good default.
* add to Akka Streams?

**Comment by nitsanw** [comment]
You can shade it? Like Netty etc

**Comment by patriknw** [comment]
yes, that's also a good option

**Comment by patriknw** [comment]
We can merge this (after validation) as the first step, and then continue with the actual inclusion via ticket https://github.com/akka/akka/issues/25044

**Pull request merged**
