### PR TITLE
Remove duplicate renderIn fields

### LINKED ISSUE #20245: Duplicate renderIn{Request,Response} in custom header docs
The samples has 
```
override val renderInResponses = true
override val renderInRequests = true
```

In both `ModeledCustomheader` and `ModelledCustomHeaderCompanion` but it should only be in `ModeledCustomHeader`

### PR DESCRIPTION
**Pull request by naferx**
Fixes #20245

### CODE REVIEW

**Comment by ktoso** [comment]
The same is in `DifferentHeader` just a few lines below here.

**Comment by ktoso** [comment]
While we're here, could you make the `renderIn...` methods `override def` inside the custom headers (in the right spot), thanks!

**Comment by ktoso** [comment]
OK TO TES

**Comment by ktoso** [comment]
OK TO TEST

**Comment by naferx** [comment]
PR polished now

**Comment by ktoso** [comment]
Excellent, thank you @naferx!

**Pull request merged**
