### PR TITLE
 the highestSequenceNr is not predictable (https://github.com/akka/akka/i…

### PR DESCRIPTION
**Pull request by giena**
…ssues/25321)

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @giena,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by giena** [comment]
https://github.com/akka/akka/issues/25321

**Comment by giena** [comment]
I have signed the sla

**Review by patriknw — APPROVED** [review]
LGTM

**Review by johanandren — APPROVED** [review]
LGTM

**Pull request merged**
