### PR TITLE
Added a Packt video to list of resources

### PR DESCRIPTION
**Pull request by andrewstaveley**
I've added a recently published Packt video to books.rst - might be better if in the long term this is split out into a separate file. For now it's just the one on there, I hope this is okay.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @microstash,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
LGTM, Fun fact - that video material I was actually reviewing while it was worked on

**Comment by johanandren** [comment]
LGTM, please sign the CLA and we can merge it.

**Comment by microstash** [comment]
Done, thanks!

**Comment by patriknw** [comment]
OK TO TEST

**Comment by patriknw** [comment]
LGTM

**Comment by 2beaucoup** [comment]
What's the deal with the tracking params in the URLs?

**Comment by ktoso** [comment]
Oh, good catch. We didn't really agree to any partnership in campaign tracking... I'll remove them.

**Comment by ktoso** [comment]
Thanks for noticing @2beaucoup, I've removed them https://github.com/akka/akka/pull/20609

**Pull request merged**
