### PR TITLE
Issue 24594: Integration with sbt-headers and initial header population.

### PR DESCRIPTION
**Pull request by ktoso**
Follows up https://github.com/akka/akka/pull/24652 and resolves #24594 

Thanks a lot @kelebra

### CODE REVIEW

**Comment by ktoso** [comment]
Will merge once validation passes.

**Comment by ktoso** [comment]
Resolves https://github.com/akka/akka/issues/24519

**Comment by ktoso** [comment]
PR is too big to review in github, however it is fine -- i checked using the command @jrudolph mentioned in other PR

**Comment by ktoso** [comment]
This should now pass; I propose to merge this ASAP as @kelebra already spent some time rebasing it all the time;

There will never be a "good time" to merge this anyway.

cc @patriknw @johanandren

**Comment by patriknw** [comment]
Feel free to merge, I assume that you guys have verified it

**Review by johanandren — APPROVED** [review]
As sure about LGTM as I will get :)

**Comment by ktoso** [comment]
Thanks @kelebra !

**Pull request merged**
