### PR TITLE
Upgrade parboiled 2 internalization to 2.1.0 release

### PR DESCRIPTION
**Pull request by sirthias**
So far the header parsers in akka-http-core were relying on an internalized copy of parboiled2 2.0.0-RC2.
This updates everything to the latest stable parboiled2 release.

### CODE REVIEW

**Comment by ktoso** [comment]
AFAICS that's a repackaged copy-paste of 2.1.0. Ok to take in as is then, don't want to modify anything in it – LGTM

**Comment by sirthias** [comment]
Yes, this is pretty much parboiled2 2.1.0 with all package names changed.
No other modification necessary.
The benefit is that we get all the fixes and other improvements since 2.0.0-RC2 for our use.

**Comment by ktoso** [comment]
Excellent, just wanted to make sure :)

**Pull request merged**
