### PR TITLE
=rem #15007 add ability to bind to a different address than the remoting...

### PR DESCRIPTION
**Pull request by 2m**
This can be used to traverse NATs with the following configuration:

```
akka.remote.netty.tcp {
  ...
  hostname = my-external-address.lt
  bind-hostname = 192.168.1.100
}
```

### CODE REVIEW

**Comment by huntc** [comment]
Just confirming my understanding: this feature will be part of 2.3? There was an earlier mention of 2.3 docs.

**Comment by patriknw** [comment]
@huntc it is only targeted for 2.4, since it is a new feature

**Comment by huntc** [comment]
@patriknw I understand. So what this means then is that for an Akka cluster based application (or one that just uses remoting) to work in a container environment then users must use Akka 2.4. Do we have a timeline for that? There may be an impact on other internal projects of course.

**Comment by patriknw** [comment]
I trust no timelines. Talk with @rkuhn

**Comment by hepin** [comment]
@patriknw this would be nice if backport to 2.3 release.like the 2.3.4 akka-persistent change.
cause akka 2.4 is going to be only support java8,for those who don't want to upgrade to java8 but want to using docker,this could make them happy.
for akka 2.4 will not going to change something about akka-remote,so how about thinking about this?

**Comment by rkuhn** [comment]
@huntc The current planning foresees Akka 2.4.0 in April, but please keep in mind that this universe is not yet fully subjected to my will ;-)

@hepin1989 We currently do not have the bandwidth to port features back to 2.3, and we generally also do not do that—we only backport serious bug fixes. Persistence is different in that it is still under development (sadly stalled due to the Streams & HTTP work, but to be resumed once those are done).

**Comment by hepin1989** [comment]
@rkuhn I will try to backport this to another transport implement.I just worry about the akka remote transport SPI will change in the akka2.4.

Once the https://github.com/akka/akka/issues/16416 implemented,we will going to using the akka-stream.

**Pull request merged**
