### PR TITLE
Move class in javadsl to javadsl.server to keep in release jars

### PR DESCRIPTION
**Pull request by johanandren**
Short term fix for #20556

### CODE REVIEW

**Comment by johanandren** [comment]
Verified `RoutingJavaMapping` is still in there by dry-running release script.

**Comment by johanandren** [comment]
@ktoso please take a look asap

**Comment by drewhk** [comment]
I guess it is OK

**Comment by johanandren** [comment]
It was mostly IntelliJ who did the work. ;)

**Comment by patriknw** [comment]
so, it's about moving one internal class?
LGTM

**Comment by ktoso** [comment]
Yes, it's funnily enough the only class we have in this package, which broke the release...
https://github.com/akka/akka/tree/master/akka-http/src/main/scala/akka/http/javadsl

**Comment by ktoso** [comment]
LGTM, thanks!

**Pull request merged**
