### PR TITLE
+clu #13584 Accept joining to be WeaklyUp during network split 

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by patriknw** [comment]
Refs #13584

**Comment by patriknw** [comment]
@drewhk please take a look at 7267f75 Did you have anything else in mind for the doc additions?

**Comment by drewhk** [comment]
Can WeaklyUp members participate in sharding, or in distributed-data? Maybe that should be clarified as well. Otherwise LGTM

**Comment by patriknw** [comment]
Good point. I have added that. In summary:
singleton: no
sharding: no
pub/sub: yes
metrics: yes
routers: yes
distributed data: currently not, but should be supported as described in #18399

**Pull request merged**
