### PR TITLE
=act - Reinstates the Mailbox optimization reusing the FJT instance b…

### PR DESCRIPTION
**Pull request by viktorklang**
…ut doesn't use FJT.fork() due to unfairness

Refer to #17341

### CODE REVIEW

**Comment by drewhk** [comment]
Thanks, LGTM

**Comment by viktorklang** [comment]
@drewhk Thanks, it's the least I could do given the damage done by `fork()` :(

**Comment by drewhk** [comment]
It was not something that was trivial to see, things like this happen. Debugging fairness is one of the hardest things in concurrency land (the hardest probably being visibility bugs).

**Comment by patriknw** [comment]
LGTM

**Comment by viktorklang** [comment]
@drewhk I'll raise this with Doug when I talk to him this week

**Comment by MQ-EL** [comment]
Could tell me the result when you talked with Doug, @drewhk? :)

**Comment by drewhk** [comment]
that is @viktorklang you are looking for:)

**Comment by MQ-EL** [comment]
I'm so Sorry

**Pull request merged**
