### PR TITLE
Deprecated method used in docs

### PR DESCRIPTION
**Pull request by rch**
Updated example code to use the alternative method provided in v2.5.0

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @rch,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
Nice, thanks! LGTM

**Comment by ktoso** [comment]
OK TO TEST

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
