### PR TITLE
+str #17361: Unified http java/scala projects except marshallers

### PR DESCRIPTION
**Pull request by drewhk**

### CODE REVIEW

**Comment by drewhk** [comment]
refs #17361

**Comment by jrudolph** [comment]
Does this change have a development productivity overhead? I.e. is compilation as fast as before and does anything that compiled in parallel before still do? I'm asking because mixed Java/Scala compilation can be quite slow. For akka-http-core it's already hardly acceptable so hopefully this doesn't spread to other parts with this change.

**Comment by drewhk** [comment]
The tests were fine on my machine. As for compilation speed, I cannot say anything because I compiled from clean state. Otherwise, I delegate this question to @rkuhn

**Comment by rkuhn** [comment]
@jrudolph Your questions intrigued me, so I did some experiments with `akka-http-tests-experimental/test:compile` (inserting a `-java` for the `release-2.3-dev` branch comparison). A clean compile actually got faster with this PR (128s -> 112s), adding a method to the Scala Http extension went slightly up (from 6s for 10 sources to 8s for 14 sources), changing that method was 2s (only that file) in both cases. So, I’d say that this change does not negatively impact productivity AFAICS.

LGTM

**Comment by drewhk** [comment]
It builds for me locally. Hm

**Comment by drewhk** [comment]
PLS BUILD

**Comment by jrudolph** [comment]
Cool, @rkuhn thanks for checking.

**Pull request merged**
