### PR TITLE
update jmh plugin

### PR DESCRIPTION
**Pull request by ktoso**
Which now can work on mac and even generate flamegraphs there!
Details: https://twitter.com/ktosopl/status/939532881797439489

### CODE REVIEW

**Comment by raboof** [comment]
hmm `sbt.librarymanagement.ResolveException: unresolved dependency: pl.project13.scala#sbt-jmh;0.3.0: not found`

**Comment by ktoso** [comment]
Maybe build again, it’s here:
https://bintray.com/ktosopl/sbt-plugins/sbt-jmh

-- 
Cheers,
Konrad 'ktoso <http://kto.so>' Malawski
Akka <http://akka.io/> @ Lightbend <http://lightbend.com/>

On December 10, 2017 at 1:48:38, Arnout Engelen (notifications@github.com)
wrote:

hmm sbt.librarymanagement.ResolveException: unresolved dependency:
pl.project13.scala#sbt-jmh;0.3.0: not found

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka/pull/24131#issuecomment-350488091>, or mute
the thread

**Comment by ktoso** [comment]
PLS BUILD

**Comment by ktoso** [comment]
My bad, forgot to release extras lib :) Will be done now

-- 
Cheers,
Konrad 'ktoso <http://kto.so>' Malawski
Akka <http://akka.io/> @ Lightbend <http://lightbend.com/>

On December 10, 2017 at 11:42:08, akka-ci (notifications@github.com) wrote:

Test FAILed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka/pull/24131#issuecomment-350520907>, or mute
the thread

**Comment by ktoso** [comment]
PLS BUILD

**Review by raboof — APPROVED** [review]

**Pull request merged**
