### PR TITLE
=pr #20439 remove git plugin to avoid jgit version clashes

### PR DESCRIPTION
**Pull request by johanandren**
Refs #20439

### CODE REVIEW

**Comment by drewhk** [comment]
does the release script use this?

**Comment by johanandren** [comment]
The release script seems to be using git directly rather.

**Comment by drewhk** [comment]
ok

**Comment by patriknw** [comment]
I think you should be able to remove the resolver also, at least from looking at where it was added: https://github.com/akka/akka/commit/293ecb09f971ff5e8039a7ccd4cd3cb09f7cddf8#diff-a84f91f20f040218bccd09fed4761fb3R3

**Comment by johanandren** [comment]
Ah, great catch, didn't notice that one.

**Comment by ktoso** [comment]
LGTM

**Comment by drewhk** [comment]
LGTM

**Pull request merged**
