### PR TITLE
=htc #16806 add test demonstrating custom CT and CL in response to...

### LINKED ISSUE #16806: Make sure it is possible to set explicit `Content-Length` header in responses to non-transparent head requests
See spray/spray#965

### PR DESCRIPTION
**Pull request by sirthias**
... non-transparent HEAD request

Closes #16806.

/cc @jrudolph

### CODE REVIEW

**Comment by jrudolph** [comment]
LGTM

**Comment by sirthias** [comment]
Added commit closing #16805 as well.

**Comment by jrudolph** [comment]
While we are at it: is the `TestSetup.transparentHeadRequests` in `ResponseRendererSpec.scala` used anywhere?

**Comment by jrudolph** [comment]
LGTM

**Comment by sirthias** [comment]
> While we are at it: is TestSetup.transparentHeadRequests in ResponseRendererSpec.scala used anywhere?

Nope. I don't think so. I'll remove it.

**Comment by sirthias** [comment]
Removed the obsolete `transparentHeadRequests` member from `TestSetup` in `ResponseRendererSpec`.

**Comment by drewhk** [comment]
LGTM

**Pull request merged**
