### PR TITLE
Fixes for #16839, #17067, #17609

### LINKED ISSUE #16839: Factor out `EOI` in header parsing so that header values won't be accidentally truncated if not parseable
This may be fixed with the new parboiled2-based grammar but we should assure that it really is.

See spray/spray#280

/cc @sirthias

### PR DESCRIPTION
**Pull request by jrudolph**
Seven headers still allowed trailing garbage (#16839).

I added even more implicit def result types (#17552) because the compilation problems came back another time...

/cc @sirthias

### CODE REVIEW

**Comment by jrudolph** [comment]
Added a fix for #17609. @fommil would that suffice for your purposes?

**Comment by fommil** [comment]
@jrudolph the `FlowMaterializer` needs some explanation. what's its purpose here? I thought you were going to add a convenience that only required a source and sink (on the `Flow` object)

**Comment by jrudolph** [comment]
The `FlowMaterializer` is completely unused. Thanks for spotting that!

Wrt adding simple `Flow.wrap` overloads ignoring the materialized values WDYT @drewhk, @rkuhn?

**Comment by jrudolph** [comment]
Removed the materializer everywhere.

**Comment by fommil** [comment]
awesome, thanks @jrudolph !

**Comment by rkuhn** [comment]
Concerning the `Flow.wrap` materialized value transformation, we should probably add a `Keep.none` that you can use instead of the `(_, _) => ()` literal. An overload that does not take that argument list will probably not be legal.

**Comment by drewhk** [comment]
+1 for Keep.none

**Comment by drewhk** [comment]
Added ticket for Keep.none: https://github.com/akka/akka/issues/17702

**Pull request merged**
