### PR TITLE
Cluster Sharding Steps

### PR DESCRIPTION
**Pull request by hungaikev**
Fixing step 4 and 5 on https://doc.akka.io/docs/akka/current/cluster-sharding.html#scenario-1-message-to-an-unknown-shard-that-belongs-to-the-local-shardregion

### CODE REVIEW

**Comment by patriknw** [comment]
PLS WHITELIST

**Comment by patriknw** [comment]
OK TO TEST

**Review by patriknw — APPROVED** [review]
LGTM, thanks

**Review by johanandren — APPROVED** [review]
LGTM, thanks @hungaikev

**Pull request merged**
