### PR TITLE
adjustments for Scala 2.12.0-M4

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by ktoso** [comment]
LGTM, had to do the same comparator manually today too ;)

**Comment by johanandren** [comment]
LGTM

**Comment by SethTisue** [comment]
the Comparator workaround code added here may not be necessary anymore as of 2.12.0-RC1, because scala/scala#5307

**Comment by patriknw** [comment]
thanks for the update, @SethTisue (we'll leave it as is though)

**Pull request merged**
