### PR TITLE
Updated books page with the book by Vaughn Vernon

### PR DESCRIPTION
**Pull request by jamie-allen**
Added Vaughn's book, updated the Akka in Action release date and ordered them by reverse release date.

Thanks, guys!

### CODE REVIEW

**Comment by patriknw** [comment]
OK TO TEST

**Comment by patriknw** [comment]
LGTM, thanks Jamie

**Comment by drewhk** [comment]
LGTM

**Comment by drewhk** [comment]
Btw, shouldn't we move this books sections to the normal akka page? That way we can update the list immediately without waiting for a release.

**Pull request merged**
