### PR TITLE
Use InetSocketAddress.getHostString in favour of getHostName

### PR DESCRIPTION
**Pull request by raboof**
Saves a reverse lookup when the address was initialized as an address.

### CODE REVIEW

**Review by ktoso — APPROVED** [review]
LGTM, nice - ticket or assign this to the right milestone please :)

**Comment by raboof** [comment]
No issue AFAICS, just found this FIXME in the code - what would be the appropriate milestone? `2.5.x`?

**Comment by ktoso** [comment]
The milestone in which this will be included, so 2.5.1 :)

**Review by johanandren — APPROVED** [review]
LGTM!

**Pull request merged**
