### PR TITLE
send PriorityMessage over control stream

### PR DESCRIPTION
**Pull request by patriknw**
- such as cluster heartbeat messages

### CODE REVIEW

**Comment by drewhk** [comment]
Hm, I am not sure this is good. This will change message ordering guarantees since these messages will not travel the same channel as any other message potentially sent by these actors which can cause bugs is someone is not careful. Can we rather treat anything sent from or to under `/system/` to be priority? Then we will not need to worry about ordering.

**Comment by patriknw** [comment]
but that is the semantics that we already have for `PriorityMessage`, it's used for heartbeating

**Comment by drewhk** [comment]
Yes, because there are no separate order-preserving channels, and we have those now. I would feel more comfortable with not messing with actor guarantees.

**Comment by patriknw** [comment]
ok, I think I agree, but then we should configure that in same way as large messages `/system/` is too broad, e.g. cluster sharding is there

**Comment by patriknw** [comment]
@drewhk what do you think? shall I include this in the milestone as a temporary solution or should we skip that?

I have created an issue for the real solution https://github.com/akka/akka/issues/20577

**Comment by drewhk** [comment]
I would skip it for now

**Comment by patriknw** [comment]
okey

**Pull request closed without merging**
