### PR TITLE
=act split ReflectiveDynamicAccess implementation in separate file.

### PR DESCRIPTION
**Pull request by andreaTP**
Split interface and implementation in two files.

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by patriknw** [comment]
I appreciate the contributions. We don't strictly use one file per class and here those two are very much related and I think it is better to keep them in same file.

**Comment by andreaTP** [comment]
@patriknw thanks for the feedback, but ReflectiveDynamicAccess is only an implementation of the general interface of DynamicAccess. The fact that is the only one doesn't justify the stickyness to me.
In Akka.js we are providing a completely different implementation and hope this can be detached.

**Comment by ktoso** [comment]
Refs https://github.com/akka/akka/issues/18234

**Comment by ktoso** [comment]
Superseeded by https://github.com/akka/akka/pull/18239 (thanks!)

**Pull request closed without merging**
