### PR TITLE
Discards HandOverToMe in state End to avoid unhandled message warning

### PR DESCRIPTION
**Pull request by nvollmar**

### CODE REVIEW

**Comment by nvollmar** [comment]
Refs #26793

**Comment by chbatey** [comment]
OK TO TEST

**Comment by chbatey** [comment]
Does this fix its self with an info log like `Timeout in BecomingOldest. Previous oldest unknown, removed and no TakeOver request.`?

I think this is fine as the new oldest node will retry, alternatively we could nack the request avoid having to wait for the retry but likely not worth it.

**Review by chbatey — APPROVED** [review]
LGTM

**Comment by nvollmar** [comment]
> Does this fix its self with an info log like `Timeout in BecomingOldest. Previous oldest unknown, removed and no TakeOver request.`?

Nope, as it is it just suppresses the warn log for the unhandled message.

> I think this is fine as the new oldest node will retry, alternatively we could nack the request avoid having to wait for the retry but likely not worth it.

Was thinking about that but it seems this case is very unlikely and does not occur very often (only noticed it once).

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
I'll backport

**Pull request merged**
