### PR TITLE
=htc #17683 drop already consumed input in `continue` (+ ByteString compaction)

### LINKED ISSUE #17683: HttpMessageParser aggregates input in `continue`
This leads to a temporary memory leak and increasing parsing times for long messages where the `input` ByteString starts to consist of more and more elements leading to bad performance because of linear scanning in `ByteString.slice`.

/cc @sirthias

### PR DESCRIPTION
**Pull request by jrudolph**
Fixes #17683.

/cc @sirthias

### CODE REVIEW

**Comment by jrudolph** [comment]
TlsSpec

**Comment by viktorklang** [comment]
What's the performance impact on the compaction?

**Comment by drewhk** [comment]
The cost of compacting is copying data. The cost of not compacting is accidentally retaining lots of ByteString snippets if a ByteString buffer is consumed in a "sliding" fashion. Theoretically you can retain unbounded number of ByteStrings that you don't even use. Back then when I was toying with streaming byte-oriented parsers I put a threshold of consumed bytes (how many bytes the buffer has been "shifted/sliding" through) after I compacted to amortize the cost.

**Comment by jrudolph** [comment]
@drewhk yes, exactly. Retaining bytes was a real issue in spray at some point. For this reason we then adopted the policy in spray to compact ByteStrings that are likely to retain parts of byte buffers at the API boundary where the ByteString are released out of the control of the implementation layer.

There's a cost involved, no question, but we are already so far from a zero-copy infrastructure that being predictable seems like the more valuable goal in this case.

**Comment by drewhk** [comment]
LGTM

**Pull request merged**
