### PR TITLE
add http api for cluster management, #21172

### PR DESCRIPTION
**Pull request by patriknw**
* reference akka/akka-cluster-management in cluster docs
* deprecate the command line tool, including migration note
* cleanup old migration guides
* remove YourKit as sponsor, since we pay license

### CODE REVIEW

**Comment by patriknw** [comment]
Refs #21172

**Comment by patriknw** [comment]
fyi @hveiga

**Review by 2m — APPROVED** [review]

**Review by johanandren — APPROVED** [review]
LGTM!

**Comment by johanandren** [comment]
Refs #21172

**Pull request merged**
