### PR TITLE
=str #19775 FilePublisher should not report EOF multiple times

### PR DESCRIPTION
**Pull request by kazuhiro**

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Refs https://github.com/akka/akka/issues/19775#issuecomment-184145370

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Could you have a look if this change didn't cause the failure?

```
[info] the uploadedFile directive
[info] - should write a posted file to a temporary file on disk *** FAILED *** (1 second, 61 milliseconds)
[info]   Request was neither completed nor rejected within 1 second (FileUploadDirectivesSpec.scala:35)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at akka.http.scaladsl.testkit.TestFrameworkInterface$Scalatest$class.failTest(TestFrameworkInterface.scala:24)
[info]   at akka.http.scaladsl.server.RoutingSpec.failTest(RoutingSpec.scala:19)
[info]   at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.failNeitherCompletedNorRejected(RouteTestResultComponent.scala:95)
[info]   at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.rawResponse(RouteTestResultComponent.scala:60)
[info]   at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.response(RouteTestResultComponent.scala:41)
[info]   at akka.http.scaladsl.testkit.RouteTest$class.response(RouteTest.scala:59)
[info]   at akka.http.scaladsl.server.RoutingSpec.response(RoutingSpec.scala:19)
[info]   at akka.http.scaladsl.testkit.RouteTest$class.responseAs(RouteTest.scala:68)
[info]   at akka.http.scaladsl.server.RoutingSpec.responseAs(RoutingSpec.scala:19)
[info]   at akka.http.scaladsl.server.directives.FileUploadDirectivesSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcZ$sp(FileUploadDirectivesSpec.scala:37)
[info]   at akka.http.scaladsl.server.directives.FileUploadDirectivesSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(FileUploadDirectivesSpec.scala:35)
[info]   at akka.http.scaladsl.server.directives.FileUploadDirectivesSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(FileUploadDirectivesSpec.scala:35)
[info]   at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[info]   at akka.http.scaladsl.testkit.RouteTest$$anonfun$check$1.apply(RouteTest.scala:54)
[info]   at akka.http.scaladsl.testkit.RouteTest$$anonfun$check$1.apply(RouteTest.scala:54)
[info]   at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.$tilde$greater(RouteTestResultComponent.scala:52)
[info]   at akka.http.scaladsl.server.directives.FileUploadDirectivesSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(FileUploadDirectivesSpec.scala:35)
[info]   at akka.http.scaladsl.server.directives.FileUploadDirectivesSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(FileUploadDirectivesSpec.scala:16)
[info]   at akka.http.scaladsl.server.directives.FileUploadDirectivesSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(FileUploadDirec
```

Thanks!

**Comment by kazuhiro** [comment]
I ran this test (isolated) few times - always passing. No causation found.

**Comment by ktoso** [comment]
PLS BUILD

**Comment by ktoso** [comment]
Let's give it another round on Jenkins though

**Pull request merged**
