### PR TITLE
Update to Lightbend Community Code of Conduct

### PR DESCRIPTION
**Pull request by TimMoore**
https://www.lightbend.com/conduct

### CODE REVIEW

**Comment by TimMoore** [comment]
Ref https://github.com/akka/.github/pull/2

**Review by raboof — APPROVED** [review]
The change is good, but wouldn't it be even better to remove the file here and have it carry over from `.github`?

**Review by patriknw — APPROVED** [review]
LGTM, with same question as Arnout

**Comment by TimMoore** [comment]
@ennru pointed out that there are links to this file in the wild. For example, at the end of https://doc.akka.io/docs/akka-persistence-cassandra/current/overview.html#contributing.

I think I found all of the references (at least within the akka GitHub org) and updated them to point to https://www.lightbend.com/conduct (e.g., in https://github.com/akka/akka-persistence-cassandra/pull/546) but for already published documentation, it seemed simpler to leave the file in place than to try to update all of the links.

**Comment by patriknw** [comment]
ok, makes sense

**Pull request merged**
