### PR TITLE
Explicitly require jdk9+ for javadoc generation

### PR DESCRIPTION
**Pull request by raboof**
Refs #26502

### CODE REVIEW

**Comment by raboof** [comment]
(removed javadoc generation from Jenkins, as it clearly didn't test anything anyway. javadoc problems will eventually be caught by the nightly akka-docs, which seems soon enough)

**Comment by raboof** [comment]
PLS BUILD

**Comment by raboof** [comment]
PLS BUILD

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
