### PR TITLE
HTTP: s/ActorFlowMaterializer/FlowMaterializer where possible

### PR DESCRIPTION
**Pull request by sirthias**
refs #16934.

### CODE REVIEW

**Comment by drewhk** [comment]
LGTM

**Comment by sirthias** [comment]
Looks like this stream test needs to be relaxed a bit more:

```
- must fairly balance between three outputs *** FAILED *** (525 milliseconds)
[info]   7953 was not 10000 plus or minus 2000 (GraphBalanceSpec.scala:139)
```

**Comment by bantonsson** [comment]
I think that behavior is a bug (unrelated to your changes of course) but the test says `waitForAllDownstreams = true`, and it clearly doesn't. Opened a ticket for that #16978

**Comment by drewhk** [comment]
well, strictly speaking the violation of that spec does not mean that it does not wait for all downstreams (it is nondeterministic), but that is one likely explanation.

**Comment by bantonsson** [comment]
@drewhk, `enqueueAndYield` does a `+1` to pick the next port, which I think is a highly deterministic RoundRobin algorithm if all downstreams have connected when it starts. :wink:

**Comment by drewhk** [comment]
No, it is non-deterministic because it picks from the currently available set. Yes, it starts from +1, but it can wrap around and end up in the original position. The test case punches through 10000 elements, while the buffer size is by default 16 AFAIK, so there is plenty of room for non-deterministic races.

**Comment by bantonsson** [comment]
Yes, I know, but since the buffer is the same for all the downstreams I don't think that the spread should be that big, but who knows. Maybe one of the consumers can't keep up with adding the elements.

**Comment by drewhk** [comment]
Maybe we are affected by non-fairness in dispatcher and actor scheduling, who knows. We need to look into it.

**Comment by bantonsson** [comment]
LGTM

**Pull request merged**
