### PR TITLE
+htc #16597 more tests for outgoing connection timeout

### PR DESCRIPTION
**Pull request by ktoso**
Add more tests (and unbind server) for idle timeouts (added for client timeout) 
Refs #16597

### CODE REVIEW

**Comment by drewhk** [comment]
please rebase

**Comment by drewhk** [comment]
PLS BUILD

**Comment by drewhk** [comment]
LGTM

**Comment by drewhk** [comment]
Can I merge?

**Comment by ktoso** [comment]
Yes :)

**Pull request merged**
