### PR TITLE
Add static import convenience methods to Done and NotUsed

### LINKED ISSUE #25083: Add a Done.done() convenience API for Java
[`akka.Done`](https://doc.akka.io/japi/akka/current/akka/Done.html) is quite convenient to use from Scala as a singleton object. In Java, you need to use `Done.getInstance()` instead, which is rather verbose. Statically importing the `getInstance()` method loses clarity.

Proposal: add a `Done.done()` static method that is equivalent to `Done.getInstance()`. Even fully-qualified, it is shorter, and it is friendly to static import.

Question: as part of this, should `Done.getInstance()` be deprecated, or kept as an equal alternative?

### PR DESCRIPTION
**Pull request by TimMoore**
Resolves #25083

As discussed there, I left the documentation alone, but I did update a few tests to use the static imports.

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
PLS WHITELIST

**Review by ktoso — APPROVED** [review]
LGTM, thanks :)

**Review by raboof — APPROVED** [review]
That does seem to read a bit better, thanks!

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
