### PR TITLE
Remove dotty serial version uid plugin second try

### PR DESCRIPTION
**Pull request by johanandren**
Continuing on @andreaTP s original removal, now with silencing of the warning
References #30824

### CODE REVIEW

**Review by octonato — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
@johanandren could you rebase this?

**Comment by andreaTP** [comment]
Feel free to squash the commits if that helps, no need to preserve the attribution 👍 🙂

**Comment by lightbend-cla-validator** [comment]
Hi @andreaTP,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Lightbend Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
