### PR TITLE
Update remoting-artery.rst

### PR DESCRIPTION
**Pull request by ikr0m**
typo fixed

### CODE REVIEW

**Comment by patriknw** [comment]
thanks, then there is probably same typo in `java/remoting-artery.rst` ?

**Comment by ikr0m** [comment]
Yes, fixed same typo in `java/remoting-artery.rst`

**Comment by patriknw** [comment]
OK TO TEST

**Review by patriknw — APPROVED** [review]
LGTM, thanks

**Review by johanandren — APPROVED** [review]
LGTM

**Pull request merged**
