### PR TITLE
Cleaned up the comments and fixed typo

### PR DESCRIPTION
**Pull request by Brideau**

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Review by raboof — APPROVED** [review]
Neat, LGTM if Jenkins agrees

**Comment by raboof** [comment]
OK TO TEST

**Comment by raboof** [comment]
I'm afraid jenkins failed because scalariform isn't agreeing with some of the whitespace.. could you have a look?

**Comment by Brideau** [comment]
Looks like removing the whitespace did the trick!

**Comment by johanandren** [comment]
Thanks!

**Pull request merged**
