### PR TITLE
Add removeInterceptor function to ReceivePipeline and add tests

### PR DESCRIPTION
**Pull request by justinhj**
I've been using a modified version of ReceivePipeline for an actor based load testing system. Interceptors are added and removed to load test actors to modify their behaviour during the test. To facilitate this I added a removeInterceptor function. This pull request includes that function and an updated test spec for ReceivePipeline.

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Comment by justinhj** [comment]
sbt test succeeded for me
Is there a way I can see the output of the CI?

**Comment by raboof** [comment]
Hello Justin, first of all thanks for putting together this PR!

Yes, you can see the CI output by clicking on the "Details" link next to the "Jenkins PR Validation — Test FAILed. No test results found" box. This points to https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/10622/consoleFull , which reveals the compilation failed due to the instability we're tracking in ticket #23859. 

I'll restart the build.

**Comment by raboof** [comment]
PLS BUILD

**Comment by justinhj** [comment]
Hi Arnout

Thanks for the info :)

**Comment by johanandren** [comment]
Hi @justinhj, while we appreciate that you took time to make a contribution, please note that the `ReceivePipeline` is deprecated since 2.5.0 and will be removed in Akka 2.6.0. 

I'm not sure we want to add new functionality to a piece of code that is going away.

**Comment by justinhj** [comment]
Hi @johanandren 

Ah, I didn't realize it was going away so soon. It's fine with me either way since I already work with a copy of the code outside of the Akka library.

**Comment by johanandren** [comment]
I think that was the rationale, it is simple enough a pattern to just copy it if you need it. That and that we want to get rid of the contrib module completely. Thanks anyway!

**Comment by justinhj** [comment]
No problem, thanks for taking a look at it!

**Pull request closed without merging**
