### PR TITLE
test for restarting node, #20639

### PR DESCRIPTION
**Pull request by patriknw**
The issue has already been solved, but adding the test that was used to reproduce it.
We can't have too many of these. ;-)

### CODE REVIEW

**Comment by patriknw** [comment]
Refs #20639

**Comment by patriknw** [comment]
that was SurviveNetworkInstabilitySpec

**Comment by patriknw** [comment]
PLS BUILD

**Comment by patriknw** [comment]
PLS BUILD

**Comment by johanandren** [comment]
Great! LGTM

**Pull request merged**
