### PR TITLE
=doc graphstage sink example (#20955)

### PR DESCRIPTION
**Pull request by svezfaz**
Refs #20955

### CODE REVIEW

**Comment by ktoso** [comment]
Great, thanks!

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Very good example, thanks!
We need the same to be done in `akka-docs/rst/java/stream/stream-customize.rst` and `.. /../code/docs/stream/GraphStageDocTest.java` - thanks in advance for porting the example!

**Comment by svezfaz** [comment]
Sure, it's in now.
Hopefully soon I'll stop forgetting about the Java side of things :D

**Comment by ktoso** [comment]
LGTM, thanks a lot! Great to have this sample in the docs too now :-)

**Pull request merged**
