### PR TITLE
Scalacheck min max range could become max min and fail the test.

### PR DESCRIPTION
**Pull request by johanandren**
Fails 2.12 build

### CODE REVIEW

**Review by patriknw — APPROVED** [review]
LGTM, I guess

**Comment by patriknw** [comment]
PLS BUILD

**Comment by johanandren** [comment]
The reason why we need it is that the Scalacheck version we need for Scala 2.12 became stricter around the ranges and fails if they are inverted (`min > max`).

**Review by 2m — APPROVED** [review]
LGTM

**Pull request merged**
