### PR TITLE
Recommend `new SecureRandom` for an HTTPS server #20908

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by ktoso** [comment]
What's the current recommendation here @wsargent - about which random to use for ssl?

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
refs #20908

**Comment by ktoso** [comment]
LGTM, thanks for noticing!

**Comment by ktoso** [comment]
Would you be able to address Will's comment in this PR @raboof?
We're aiming to cut a release early tomorrow (around noon I think)

**Comment by ktoso** [comment]
Though now that I think of it... `null` is a bit bad for documenting what's going on – and this is our docs example. WDYT about merging as is @wsargent ?

**Comment by wsargent** [comment]
@ktoso as is works!  I don't have a strong preference, and explicit `new SecureRandom` makes it clear that **something** is being used.

**Comment by patriknw** [comment]
LGTM

**Comment by ktoso** [comment]
I think I'm happier with the current version – thanks a lot both of you @raboof and @wsargent :-)

**Pull request merged**
