### PR TITLE
let onReceive throw Throwable, #20231

### PR DESCRIPTION
**Pull request by patriknw**
- I also tried to change the lifecycle methods (e.g. postStop) but
  that would break source compatibility for code that called super.postStop

### CODE REVIEW

**Comment by patriknw** [comment]
2 failures, one was know from before, the other had a long GC

**Comment by patriknw** [comment]
PLS BUILD

**Comment by patriknw** [comment]
hm, that's a really bad GC. What has changed in master (not in this PR)?

```
3998.836: [Full GC (Ergonomics) [PSYoungGen: 517632K->86468K(568832K)] [ParOldGen: 1397765K->1398269K(1398272K)] 1915397K->1484737K(1967104K), [Metaspace: 503865K->503865K(1478656K)], 8.7179499 secs] [Times: user=245.00 sys=1.87, real=8.72 secs] 
[info] - should be able to decode chunk-by-chunk (depending on input chunks) *** FAILED *** (8 seconds, 943 milliseconds
```

**Comment by patriknw** [comment]
PLS BUILD

**Comment by patriknw** [comment]
PLS BUILD

**Comment by patriknw** [comment]
`SupervisorHierarchySpec` - hm, Jenkins doesn't like me when I touch akka-actor :(
can't see that the failure can be related to this though

**Comment by patriknw** [comment]
PLS BUILD

**Comment by patriknw** [comment]
@ktoso please review

**Comment by ktoso** [comment]
>  (e.g. postStop) but that would break source compatibility for code that called super.postStop

Hah yeah, those we won't be able to fix now...

**Comment by ktoso** [comment]
LGTM, changing the receive methods is safe.

**Comment by ktoso** [comment]
Thanks Patrik!

**Comment by ktoso** [comment]
Resolves #20231

**Pull request merged**
