### PR TITLE
replace thin spaces with regular spaces (to make diagrams look good)

### PR DESCRIPTION
**Pull request by aruediger**
They seem to be identical in the web viewer but look weird in IntelliJ.

### CODE REVIEW

**Comment by drewhk** [comment]
Ah, so that's why

**Comment by drewhk** [comment]
OK TO TEST

**Comment by drewhk** [comment]
Thanks for solving this mystery, I never figured out why things look weird there :)

**Comment by ktoso** [comment]
Whoa, so weird... I use a different font so didn't notice I think.
What's a soft space here though... just normal space looks weird you're saying?

**Comment by 2beaucoup** [comment]
I checked with a hex viewer and noticed that they were [this spaces](http://www.fileformat.info/info/unicode/char/2009/index.htm) (0xE2 0x80 0x89) and just replaced them with normal ones. I guess fonts that don't support them just fall back to normal spaces.

Dunno what tool @sirthias used to produce them in the first place.

**Comment by ktoso** [comment]
Interesting, most likely one of those ascii drawing tools :)
Thanks for the fix, LGTM!

**Comment by sirthias** [comment]
Indeed, I used Monodraw.
Didn't notice the problem due to my font setup I guess.
Sorry guys!

**Pull request merged**
