### PR TITLE
+str #17491: Bump Akka version and remove Functions template

### PR DESCRIPTION
**Pull request by drewhk**

### CODE REVIEW

**Comment by drewhk** [comment]
Fixes #17491

**Comment by patriknw** [comment]
Do we still have something in osgi for this package?

**Comment by patriknw** [comment]
LGTM, after checking osgi.

**Comment by ktoso** [comment]
@drewhk The mentioned OSGi thing is this line: https://github.com/akka/akka/blob/release-2.3-dev/project/AkkaBuild.scala#L1437 remove `japi.function` from there.

LGTM otherwise, the new ones have variance (yay!).

**Comment by drewhk** [comment]
okey

**Comment by drewhk** [comment]
another of those pesky TLS failures

**Pull request merged**
