### PR TITLE
=htc #19418 avoid LUB calculation problem, see SI-9621

### PR DESCRIPTION
**Pull request by ktoso**
Resolves https://github.com/akka/akka/issues/19418

// port to master is here https://github.com/akka/akka/issues/19454

### CODE REVIEW

**Comment by drewhk** [comment]
Ok, that was painless. LGTM

**Comment by ktoso** [comment]
duh should have checked MiMa

**Comment by ktoso** [comment]
Problem is not from this PR actually:

```scala
[error]  * class akka.stream.impl.fusing.GraphStages#Breaker is declared final in new version
[error]    filter with: ProblemFilters.exclude[FinalClassProblem]("akka.stream.impl.fusing.GraphStages$Breaker")

```

**Comment by rkuhn** [comment]
This mima thing is really worrisome: Breaker was not in there before, so what exactly is it complaining about? It seems to me that on Jenkins (and only there!) the comparison is made not against 2.0.1 but …

WAIT A SECOND

Please remove all akka-stream artifacts for version 2.0.1 from the maven and ivy caches, they are corrupted due to my mistake when basing the stream-http-2.0 branch on the 2.0.1 tag. That will fix it.

**Comment by rkuhn** [comment]
do we publish nightlies? in that case please check the snapshots repo as well …

sorry about this!

**Comment by ktoso** [comment]
Hmm, I don't quite get how the wrong branch poisoned this...?
I'll clean chackes.

**Comment by ktoso** [comment]
I think I cleaned everything now, will check where else I need to apply the LUB fix and merge / release

**Comment by ktoso** [comment]
Additional fix in ContentTypes now added. Awaiting validation

**Comment by ktoso** [comment]
because removed branch

**Comment by ktoso** [comment]
I need to figure out how to add links to these FAILed messages again...

**Pull request merged**
