### PR TITLE
Add getScheduler and getDispatcher to AbstractActor.

### LINKED ISSUE #24900: add getScheduler to ActorSystem
There should have a `getScheduler` and `getDispatcher` method there.

`getContext().getSystem().scheduler()` seems a little wired.

### PR DESCRIPTION
**Pull request by kun-song**
fix #24900

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Comment by satansk** [comment]
There are many `getContext().getSystem().getScheduler()` and `getContext().getSystem().getDispatcher()` use cases in Java, and I think add `getScheduler()` to `ActorSystem` would make things much easier, since Java itself is verbose enough.

**Comment by raboof** [comment]
For the dispatcher there really is a difference between `context.dispatcher` and `context.system.dispatcher`, though, so it might in fact be good to expose that?

**Comment by johanandren** [comment]
Ah, yes, missed that, to sum it up, wherever it is accessible from, it should have a Java-style getter.

**Review by johanandren — COMMENTED** [review]
Please move/add methods as discussed.

**Review by johanandren — CHANGES_REQUESTED** [review]
Please move/add methods as discussed.

(sorry for double comment, misclicked in ui)

**Comment by Seetaramayya** [comment]
Is someone working on it? or Shall I pick?

**Comment by ktoso** [comment]
Ping @satansk, have you seen: 

> Ah, yes, missed that, to sum it up, wherever it is accessible from, it should have a Java-style getter.

**Comment by satansk** [comment]
@ktoso sorry for my long delay :(, and @Seetaramayya , yes, it's yours :+1:

**Pull request closed without merging**
