### PR TITLE
Enable JoinConfigCompatCheckerSpec again, #30843

### PR DESCRIPTION
**Pull request by patriknw**
* make shutdown errors visible

References #30843

### CODE REVIEW

**Review by raboof — APPROVED** [review]
so we suspect a failure to shutdown would be related to the failure? :+1: to get more insight into that.

**Comment by patriknw** [comment]
The latest fail linked from in the ticket had shutdown issues (running with classic remoting). Those are logged but better to throw if we can.

**Comment by patriknw** [comment]
That said, I don't think it fixes the possible test failures but would like to enable it again. Seems important enough to have enabled.

**Review by johanandren — APPROVED** [review]

**Comment by octonato** [comment]
> That said, I don't think it fixes the possible test failures but would like to enable it again. Seems important enough to have enabled.

Ok, merged, but leaving the issue open for now.

**Pull request merged**
