### PR TITLE
ignore ClosedChannelException when register selector, #16035

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by patriknw** [comment]
Refs #16035

**Comment by johanandren** [comment]
LGTM

**Comment by patriknw** [comment]
The test failure was. 

`[info] - must not thrown on unbind after system has been shut down *** FAILED *** (15 milliseconds)
[info]   akka.stream.StreamTcpException: Tcp command [Connect(localhost/127.0.0.1:35780,None,List(),None,true)] failed
`

I don't think it's related to this change, but I'm not sure. The intention of the change is to only suppress the warning logging. As far as I understood the exception was previously caught, logged and ignored.

**Comment by patriknw** [comment]
PLS REBUILD

**Comment by patriknw** [comment]
PLS BUILD

**Pull request merged**
