### PR TITLE
Adding OSGi settings for akka-actor-typed and persistence-typed.

### PR DESCRIPTION
**Pull request by atooni**
This pull request replaces #25587 !!! 
As the original PR was on hold for some time, I have now recreated the PR on top of the current master. 

Please reject #25587

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]
I guess you have tested this with woq?

**Comment by atooni** [comment]
@raboof I can confirm that the bundles load correctly and work within an OSGi container. I have tested that within our own project.

**Review by patriknw — APPROVED** [review]
LGTM, I guess

It would be welcome to follow up with another PR adding similar OSGi settings to the other `-typed` artifacts.

**Comment by patriknw** [comment]
Merging, thanks @atooni

**Comment by atooni** [comment]
Thx for merging. I will try to make some time in the next couple of weeks as I am working on another feature at the moment. For reference: This is our OSGi project, relying heavily on Akka and all of it's components: https://github.com/woq-blended/blended 

We do have a slightly different approach to sbt. Where akka uses a single Scala file for each feature used in the build and apples that to different modules, we define a single Scala file per submodule which can be configured by constructor parameters. Common Settings are abstracted into their own Settings classes.

**Comment by patriknw** [comment]
This is one of latest OSGi contributions to Akka so I hope some in the Akka OSGi community is still listening here. As you know, in the core Akka team we don't have any OSGi expertise so we rely on the community to support and keep it up to date in Akka. Thanks so much for you help with this.

A related project is [sbt/sbt-osg](https://github.com/sbt/sbt-osgi), which is used by the Akka build. We would appreciate if you can help out with reviewing changes there so that contributions are not breaking things because of our lack of knowledge. Perhaps you could subscribe to notifications in that repository (should be low traffic)?

There is currently one pull request there that we would like such help with: https://github.com/sbt/sbt-osgi/pull/64

**Comment by atooni** [comment]
Hello, 
the PR in sbt-osgi is driven by our team and fixes a bug within the manifest generation. I will head over and comment over there.

**Pull request merged**
