### PR TITLE
=doc fix PoisonPill typo in Actor lifecycle

### PR DESCRIPTION
**Pull request by nordicway**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @nordicway,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by 2m** [comment]
Great, thanks! Just did a quick grep and it seems one test case also has this typo: https://github.com/akka/akka/search?utf8=%E2%9C%93&q=PosionPill

Would you mind fixing that aswell?

**Comment by nordicway** [comment]
sure. I hope that squashed commit worked out.

**Comment by 2m** [comment]
Looking great. Thanks!

**Pull request merged**
