### PR TITLE
Adding ScalaDocs for FlowOps.async

### PR DESCRIPTION
**Pull request by adamw**
With a dedicated section for the behavior when used on SubFlow

As discussed on gitter with @ktoso 
I was thinking about adding something to the docs, but in the end I suppose just having this specified in the scaladocs is more DRY ;)

### CODE REVIEW

**Comment by ktoso** [comment]
Great, thanks for the doc! It's a good place to put it, yeah :)

**Comment by drewhk** [comment]
LGTM

**Comment by johanandren** [comment]
LGTM, thanks!

**Comment by johanandren** [comment]
Refs #21137

**Pull request merged**
