### PR TITLE
Fix scaladoc of getStageActor (fixes #21311)

### LINKED ISSUE #21311: Clarify getStageActor scaladoc
The [scaladoc comment](https://github.com/akka/akka/blob/fa614f0325b786998fb6adbd31c4ae7692613515/akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala#L907) of `GraphStageLogic#getStageActor` is somewhat confusing (to me). It says "_This method **must not** (...) be called after the GraphStageLogic constructor has finished running ..._". While the [documentation](http://doc.akka.io/docs/akka/2.4.9/scala/stream/stream-customize.html#Integration_with_actors) states that "_they cannot be accessed from the constructor of the GraphStageLogic ..._".

It seems to me, that the docstring should say "_This method **must** (...) be called after the GraphStageLogic constructor has finished running ..._". (Although, I realize there could be a misunderstanding on my part due to english not being my first language.)

### PR DESCRIPTION
**Pull request by durban**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @durban,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by johanandren** [comment]
Refs #21311

**Comment by johanandren** [comment]
LGTM, thanks! (But note that you must sign CLA for us to be able to accept the PR)

**Comment by drewhk** [comment]
LGTM

**Comment by ktoso** [comment]
LGTM after CLA signed, thanks @durban !

**Comment by durban** [comment]
I've read the CLA, and the "past, present and future Contributions" phrasing is disturbingly "universal", so I chose not to sign it. Obviously I don't care about this specific one-word (!) commit, so

- I'm releasing my commit a342530 under CC0 (https://creativecommons.org/publicdomain/zero/1.0/legalcode)
- I'm releasing my commit a342530 under the Apache License v2.0 (https://www.apache.org/licenses/LICENSE-2.0). (I can also release under some other open source license, if desired.)

I hope this helps :-)

**Comment by ktoso** [comment]
Too bad that you feel this way about the CLA... We'll of course respect that.
The wording is such in order to allow you to sign once and then send as many PRs as you want.
I don't see how it could be misinterpreted to anything else than willingly contributing a patch to Akka.

We'll make the commit manually, thanks for finding the issue.

**Pull request closed without merging**
