### PR TITLE
20514 - HTTP: Document how a type is marshalled into json

### PR DESCRIPTION
**Pull request by ashugupt**
The type is marshalled into pretty printed json by default. Improve the documentation to elaborate how to bring compact printer into scope.

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Comment by johanandren** [comment]
LGTM

**Comment by ktoso** [comment]
LGTM, thanks - making the snippet an include would be a nice idea though

**Comment by ashugupt** [comment]
Added supporting example code backlinked to documentation.

**Comment by ashugupt** [comment]
Can someone point(hint) me to solution to this, so that I can update the PR accordingly.

**Comment by ktoso** [comment]
Example is good but this does not compile :)

```
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-docs/rst/scala/code/docs/http/scaladsl/SprayJsonCompactMarshalSpec.scala:18: Item is already defined as (compiler-generated) case class companion object Item
[error]     object Item extends DefaultJsonProtocol with SprayJsonSupport {
[error]            ^
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-docs/rst/scala/code/docs/http/scaladsl/SprayJsonCompactMarshalSpec.scala:20: value apply is not a member of object Item
[error]  Note: implicit value itemFormat is not applicable here because it comes after the application point and it lacks an explicit result type
[error]       implicit val itemFormat = jsonFormat2(Item.apply)
[error]                                                  ^
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-docs/rst/scala/code/docs/http/scaladsl/SprayJsonCompactMarshalSpec.scala:32: Item.type does not take parameters
[error]               Item("thing", 42) // will render as JSON
[error]                   ^
```

Please pick some different classname for the example, maybe like Person if it's still available in scope?

**Comment by ashugupt** [comment]
Please build.

**Comment by ashugupt** [comment]
yay

**Comment by johanandren** [comment]
Fixes #20514

**Pull request merged**
