### PR TITLE
docs: typo in "Actor discovery"

### PR DESCRIPTION
**Pull request by jeengbe**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @jeengbe,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by jeengbe** [comment]
image

¯\_(ツ)_/¯

**Comment by johanandren** [comment]
Thanks for letting us know that there was something wrong with the CLA service, we'll look into it.

**Comment by sebastian-alfers** [comment]
@jeengbe Thank you for your contribution. From our end it seems all good regarding your signed CLA. Can you confirm?

**Comment by jeengbe** [comment]
I confirm.

**Review by johanandren — APPROVED** [review]
Thanks!

**Pull request merged**
