### PR TITLE
+str #18840 add of method to predefined Shapes, for nicer Java use

### PR DESCRIPTION
**Pull request by ktoso**
Resolves https://github.com/akka/akka/issues/18840

(Not showing `of` in the migration guide, since it wasn't there yet ofc).

### CODE REVIEW

**Comment by drewhk** [comment]
LGTM

**Comment by drewhk** [comment]
Akka docs Java lambda ;)

**Comment by ktoso** [comment]
Ouch, sorry, will fix

**Comment by ktoso** [comment]
Fixed, merge at will

**Comment by drewhk** [comment]
Hm, zip again. Is your branch already including the fix I merged?

**Comment by ktoso** [comment]
Checking

**Comment by ktoso** [comment]
No it didn't, I rebased now so it should pass if you want to wait for validation; should be OK to merge in any case though (no conflicts during rebase_

**Comment by drewhk** [comment]
I wait, just to be sure. I don't want a Zip bug to slip through in the new release.

**Comment by ktoso** [comment]
:+1:

**Pull request merged**
