### PR TITLE
Avoid ask to sharding guardian if region already cached

### PR DESCRIPTION
**Pull request by chbatey**
Found this when looking at what i thought was a bug with typed cluster sharding.

The `ClusterShardingGuardian` doesn't appear to do anything if it already has a Child that has the right name.

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
LGTM, not sure that it matters much though, given that the "normal" pattern is to call the method once or at most a very small number of times, and then hold on to the reference.

**Review by ktoso — APPROVED** [review]
Hmm, seems good; definitely won't hurt I suppose

**Comment by nvollmar** [comment]
I think this broke our sharding... when we start the application a couple of shards time out on `Await.result(guardian ? startMsg, timeout.duration)` and fail since 2.5.15

**Comment by patriknw** [comment]
@nvollmar That sounds like a serious issue if it's true. I can't see how these `computeIfAbsent` would change anything. Can you describe how we can reproduce the problem?

**Comment by nvollmar** [comment]
@patriknw me neither, I'm trying to reproduce the problem and verify the source of it.

**Comment by nvollmar** [comment]
@patriknw I could write a spec to reproduce the failure and it is in fact `computeIfAbsent`. Reverting this change leads to an expected startup of all shards.

With `computeIfAbsent` some of the shardings will fail with 
```stacktrace
akka.actor.ActorInitializationException: akka://ClusterShardingSpec/user/manager6: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:193)
	at akka.actor.ActorCell.create(ActorCell.scala:669)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [20000 milliseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:167)
	at akka.dispatch.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3641)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:165)
	at scala.concurrent.Await$.result(package.scala:190)
	at akka.cluster.sharding.ClusterSharding$$anon$1.apply(ClusterSharding.scala:239)
	at akka.cluster.sharding.ClusterSharding$$anon$1.apply(ClusterSharding.scala:234)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1719)
	at akka.cluster.sharding.ClusterSharding.internalStart(ClusterSharding.scala:234)
	at akka.cluster.sharding.ClusterSharding.start(ClusterSharding.scala:218)
	at akka.cluster.sharding.ClusterShardingSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$3$$anonfun$4$$anon$1.preStart(ClusterShardingSpec.scala:82)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:528)
	at akka.cluster.sharding.ClusterShardingSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$3$$anonfun$4$$anon$1.aroundPreStart(ClusterShardingSpec.scala:72)
	at akka.actor.ActorCell.create(ActorCell.scala:652)
	... 9 more
```

**Comment by patriknw** [comment]
Then we should revert immediately. We have an upcoming release on Thursday so would be good to fix tomorrow. Can you share test or example code?

**Comment by patriknw** [comment]
Sorry, you linked to it.

**Comment by patriknw** [comment]
I'm looking into this. I completely understand how it can deadlock, but want to understand why it's different with the added computeIfAbsent.

**Pull request merged**
