### PR TITLE
=htc #19361 The Quest for rewriting things from StatefulStage to GraphStage

### PR DESCRIPTION
**Pull request by ktoso**
Refs https://github.com/akka/akka/issues/19361

1 down, 9 to go.

### CODE REVIEW

**Comment by ktoso** [comment]
Added last evening's `FrameOutHandler` rewrite.
2 down 8 to go.

**Comment by ktoso** [comment]
Will include commit to fix https://github.com/akka/akka/issues/19377 here

**Comment by ktoso** [comment]
This is simple and safe @rkuhn

**Comment by rkuhn** [comment]
closed by github due to deletion of the release-2.3-dev branch—please open a new PR against master

**Pull request closed without merging**
