### PR TITLE
Various small improvements

### PR DESCRIPTION
**Pull request by jrudolph**
This is a spin-off from the big upcoming Java DSL PR which should be quickly reviewable.

### CODE REVIEW

**Comment by ktoso** [comment]
LGTM, would like to understand the `:` in tests though :)

**Comment by jrudolph** [comment]
Added a commit that adds even more explicit result types for implicit definitions.

**Comment by drewhk** [comment]
LGTM
(failure is TLS again)

**Comment by drewhk** [comment]
can I merge?

**Comment by jrudolph** [comment]
From my side, yes. @sirthias?

**Comment by sirthias** [comment]
Very nice! LGTM.

**Pull request merged**
