### PR TITLE
=str #19293 fix issues in Sink.seq + minor doc fixes + use Sink.seq

### PR DESCRIPTION
**Pull request by lolski**
Contains fixes for issue https://github.com/akka/akka/issues/19293 (now properly rebased to master branch)
- Sink.seq (Scala DSL) now returns immutable.Seq rather than Seq
- Sink.seq will not silently truncate when incoming elements is > Int.MAX_VALUE
- minor doc fixes
- replacing various grouped(n) / Sink.head with limit(n) / Sink.seq in various tests
- fix inconsistent indentation in RequestParserSpec

### CODE REVIEW

**Comment by drewhk** [comment]
LGTM

**Comment by rkuhn** [comment]
OK TO TEST

**Comment by rkuhn** [comment]
LGTM, great work @lolski !

**Comment by drewhk** [comment]
Failure is known and unrelated

**Pull request merged**
