### PR TITLE
add [openjdk11] to Travis cross build

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by chbatey** [comment]
We have an 11 build it just doesn't compile :) https://jenkins.akka.io:8498/job/akka-nightly-jdk11/

**Comment by hepin1989** [comment]
This is a must:)

**Comment by johanandren** [comment]
For reference it is blocked on a static forwarder methods conflict: https://github.com/scala/bug/issues/11061

**Comment by chbatey** [comment]
@sullis now that 2.12.7 is released want to add it to this PR and see if it works in travis for JDK11?

I've kicked off with 2.12.7 now that genjavadoc has been released

**Comment by raboof** [comment]
@sullis it would be great if you could rebase this one!

**Comment by johanandren** [comment]
Hmm, now it got this: 
```
[error] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[error] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[error] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[error] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[error] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[error] 5 errors found
```

Wasn't that what we saw in the community build? (@SethTisue ?)

**Comment by raboof** [comment]
Hm - might be interesting that it is failing for `[info] Compiling 2 Scala sources and 1 Java source to /home/travis/build/akka/akka/akka-stream/target/CompileJdk9-classes` - those classes should be compiled with `-release 9`

**Comment by SethTisue** [comment]
> Wasn't that what we saw in the community build? (@SethTisue ?)

Um, probably, I have trouble keeping all 180 projects straight in my head :-)

but a recent run is https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk11-integrate-community-build/57/ and it has:

```
[akka] [error] Failed tests:
[akka] [error] 	akka.io.TcpConnectionSpec
[akka] [error] 	akka.io.UdpConnectedIntegrationSpec
```

in our config file we have:

```
      // idk why, but prevents dbuild-only sun.misc.Unsafe compile errors;
      // see https://github.com/scala/community-builds/issues/757
      "set scalacOptions in Compile in actor --= Seq(\"-release\", \"8\")"
```

but anyway actually we're currently frozen at your `v2.15.16` tag, I figured I'd wait for this PR to get resolved, and then try master.

**Comment by johanandren** [comment]
I think this should be working by now, just retriggered the build

**Comment by dwijnand** [comment]
Nope:

```scala
[info] Compiling 2 Scala sources and 1 Java source to /home/travis/build/akka/akka/akka-stream/target/CompileJdk9-classes ...
[error] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[error] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[error] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[error] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[error] Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
[error] 5 errors found
```

**Comment by johanandren** [comment]
We have a nightly jenkins job on JDK 11 which compiles fine (https://jenkins.akka.io:8498/job/akka-nightly-jdk11/ ) so it is not a general compile-on-jdk-11-problem. So I guess it is something about the travis infra and finding JDK versions probably, because of the trix we do to compile the Flow APIs.

**Comment by SethTisue** [comment]
in the context of the community build, where we are building your `v2.5.18` tag, I'm still seeing the "Class jdk.internal.HotSpotIntrinsicCandidate not found" errors. I'm still interested in resolving this somehow, since it's the top blocker (most downstream projects blocked) in the 2.12-on-JDK11 community build

**Comment by SethTisue** [comment]
yeah so Travis went green over at https://github.com/akka/akka/pull/26078

that's good enough for me to get akka-stream green in the Scala 2.12-on-JDK11 community build, so I'd prefer to stop there and not to take this work any further myself. I suggest y'all follow through by dropping support for building on JDK 9 and 10 and make everything consistently 8 and 11

**Comment by patriknw** [comment]
I'm closing this because we have other jobs that are running full tests on JDK 11 and I don't see much value in adding build cycles to Travis build which doesn't do much. And we should use Adopt JDK as in https://github.com/akka/akka/pull/26170

**Comment by jrudolph** [comment]
We are now also seeing this but only on some machines.

> I've been staring at this and fiddling with it all morning, to no avail... but then I finally had a hunch: maybe using `-release 11` instead of `-release 9` would fix it? trying it at #26078

Yes, that seems to work but we don't really know what the exact effect of changing that setting is. Is that explained somewhere, @SethTisue?

> as for what the cause might be, maybe it depends on whether the machine you're on has 9 installed in addition to 11? perhaps the Akka Jenkins has both 9 and 11 but Travis-CI has dropped 9 from the image we're using? (that wouldn't account for why I can reproduce the problem on my laptop inside dbuild but not outside, but there could be some separate cause for that.)

We experimented with that and think that we can rule that out, as least it's not as simple as that.

**Comment by SethTisue** [comment]
> Yes, that seems to work but we don't really know what the exact effect of changing that setting is. Is that explained somewhere, @SethTisue?

see https://github.com/scala/scala/pull/6362

fwiw, I doubt it's worthwhile to get to the bottom of this, there's no reason to use `-release 9` anymore that I can see when you could be using `-release 11` instead; I think it's fine (and in fact, best) to pretend that JDK 9 and JDK 10 never existed, certainly that's what we're doing for Scala itself

**Comment by jrudolph** [comment]
Thanks, @SethTisue, I learned something there.

> fwiw, I doubt it's worthwhile to get to the bottom of this, there's no reason to use `-release 9` anymore that I can see when you could be using `-release 11` instead; I think it's fine (and in fact, best) to pretend that JDK 9 and JDK 10 never existed, certainly that's what we're doing for Scala itself

Agreed.

**Pull request closed without merging**
