### PR TITLE
rename spawnAdapter due to Scala 2.12 compilation error

### PR DESCRIPTION
**Pull request by patriknw**
* and make scaladoc happy ForkJoinPool.ForkJoinWorkerThreadFactory

### CODE REVIEW

**Review by johanandren — COMMENTED** [review]
LGTM, thanks!

**Review by 2m — APPROVED** [review]
LGTM

**Comment by ktoso** [comment]
ScalaDSL remains spawn?

**Comment by patriknw** [comment]
Yes, must be different named. We can investigate more clever alternatives later

**Comment by ktoso** [comment]
Yes, sounds good. LGTM

**Pull request merged**
