### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by bwignall**
Should be non-semantic.

Uses https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings/For_machines to find likely typos, with https://github.com/bwignall/typochecker to help automate the checking.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @bwignall,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by raboof — APPROVED** [review]
nice thanks!

**Comment by raboof** [comment]
OK TO TEST

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
