### PR TITLE
=htc Enable rendering of HTTP/1.0 responses, increase test coverage for connection closing logic

### PR DESCRIPTION
**Pull request by sirthias**
This is a smaller improvement I've been wanting to do for some time already.
A recent discussion with the play team also triggered a more in-depth specification of the somewhat involved logic for when exactly we render a `Connection` response header and close the connection.

### CODE REVIEW

**Comment by rkuhn** [comment]
LGTM; @jrudolph @richdougherty ?

**Comment by richdougherty** [comment]
LGTM

**Comment by jrudolph** [comment]
LGTM

**Comment by bantonsson** [comment]
LGTM

**Pull request merged**
