### PR TITLE
Reduce assert time and increase poll freq PersistentTestKit

### PR DESCRIPTION
**Pull request by chbatey**
This takes this module's test time from 5.5minutes to 40seconds

### CODE REVIEW

**Review by johanandren — APPROVED** [review]

**Comment by johanandren** [comment]
Would be good if it not only was much faster but also all tests passed ;)

**Comment by chbatey** [comment]
haha "works on my machine"

**Review by ennru — APPROVED** [review]
So fast!

**Comment by ennru** [comment]
Travis had a good time with this.

**Pull request merged**
