### PR TITLE
Upgrade jackson-databind to 2.7.6

### PR DESCRIPTION
**Pull request by naferx**

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Good idea, thanks

**Comment by johanandren** [comment]
LGTM

**Comment by ktoso** [comment]
Thanks!

**Comment by guidomedina** [comment]
Could go even further; to 2.8.1

**Comment by patriknw** [comment]
depends on how compatible 2.7 and 2.8 are, if this is in `-experimental` we can do it

when akka-http has separate release cycle we can move faster

**Comment by ktoso** [comment]
This is a great moment to bump it, let's bump to 2.8 while we move off from experimental – @guidomedina could you open a ticket in github.com/akka/akka-http for this?

**Comment by guidomedina** [comment]
Done: https://github.com/akka/akka-http/issues/4

**Pull request merged**
