### PR TITLE
docs: Use apidoc directive in typed/interaction-patterns.md (#22904)

### PR DESCRIPTION
**Pull request by Captain1653**
References #22904

I don't know why, but it was the hard file.

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by Captain1653** [comment]
@patriknw  2.6.20 milestone?

**Comment by patriknw** [comment]
yes, thanks

**Pull request merged**
