### PR TITLE
Compile akka-actor and akka-actor-tests with Scala 3 in PR validation

### PR DESCRIPTION
**Pull request by johanandren**

### CODE REVIEW

**Review by andreaTP — APPROVED** [review]

**Comment by johanandren** [comment]
Hmm, something with jdk target 8 is problematic and failing the build on travis.

**Comment by patriknw** [comment]
> Hmm, something with jdk target 8 is problematic and failing the build on travis.

Could be enough with jdk 11 from my point of view.

**Comment by andreaTP** [comment]
@johanandren my bad, I should have mentioned that `-target:jvm-1.8` is not supported, not sure if there is any replacement available.

**Comment by Sciss** [comment]
Is `-target:jvm-1.8` not the same as `-release 8`? That would be supported in the next milestone, I guess: https://github.com/lampepfl/dotty/issues/8634

**Comment by raboof** [comment]
> Is `-target:jvm-1.8` not the same as `-release 8`? That would be supported in the next milestone, I guess: [lampepfl/dotty#8634](https://github.com/lampepfl/dotty/issues/8634)

Almost, but not quite. Actually `-release 8` would be better, but currently we haven't figured out a way to use that yet, see #27079

**Review by octonato — APPROVED** [review]

**Comment by octonato** [comment]
is there anything missing or is it ready for merge?

**Comment by johanandren** [comment]
Was just waiting for another LGTM, thanks!

**Pull request merged**
