### PR TITLE
Add a Framing.modifiedLengthField function. Fixes #21126.

### LINKED ISSUE #21126: akka-stream Framing.lengthField including size field
I'm working on a steaming protocol which sends (most) messages in the following way:
1. 1 byte message identifier
2. 4 byte length indicator (this length equals to the length of the payload in bytes + 4bytes for the length indicator field)
3. payload

I was hoping that we could modify the `Framing.lengthField(fieldLength, fieldOffset, maximumFrameLength, byteOrder)` function to include a length modifier. This modifier would then indicate the number of byte to be added to the value found in the message.
In my case, this would mean that I'd have to pass -4 to the function.

If desirable, I could submit a pull request this evening(-ish)

### PR DESCRIPTION
**Pull request by irundaia**
Unfortunately, I had to add a new function for this feature. I obviously welcome any comments.

### CODE REVIEW

**Comment by drewhk** [comment]
OK TO TEST

**Comment by irundaia** [comment]
The test fails when checking binary compatibility. I'm not sure but does this mean that I'm not allowed to change the signature of the ```LengthFieldFramingStage``` private class? 

Exception throws is:

```java
java.lang.RuntimeException: akka-stream: Binary compatibility check failed!
	at scala.sys.package$.error(package.scala:27)
	at com.typesafe.tools.mima.plugin.SbtMima$$anonfun$reportErrors$1.apply(SbtMima.scala:96)
	at com.typesafe.tools.mima.plugin.SbtMima$$anonfun$reportErrors$1.apply(SbtMima.scala:78)
	at scala.collection.immutable.Map$Map4.foreach(Map.scala:181)
	at com.typesafe.tools.mima.plugin.SbtMima$.reportErrors(SbtMima.scala:78)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaReportSettings$6.apply(MimaPlugin.scala:43)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaReportSettings$6.apply(MimaPlugin.scala:42)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (akka-stream/*:mimaReportBinaryIssues) akka-stream: Binary compatibility check failed!
[error] Total time: 1084 s, completed Aug 11, 2016 12:30:23 AM
```

**Comment by drewhk** [comment]
Maybe better to move this to https://github.com/akka/akka-stream-contrib instead?

**Comment by irundaia** [comment]
Not sure, I'd be happy to move it though

**Comment by johanandren** [comment]
Refs #21126

**Comment by johanandren** [comment]
This is the actual MiMa output: 
```
[info] akka-stream: found 1 potential binary incompatibilities while checking against com.typesafe.akka:akka-stream_2.11:2.4.2  (filtered 274)
[error]  * method this(Int,Int,Int,java.nio.ByteOrder)Unit in class akka.stream.scaladsl.Framing#LengthFieldFramingStage does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("akka.stream.scaladsl.Framing#LengthFieldFramingStage.this")
```

**Comment by irundaia** [comment]
I'll move this feature to https://github.com/akka/akka-stream-contrib. Thanks for the effort

**Comment by ktoso** [comment]
Thanks, moving to akka-stream-contrib sounds like a great idea - happy to accept it there :)

**Pull request closed without merging**
