### PR TITLE
possibility to select dispatcher for delivery actors

### PR DESCRIPTION
**Pull request by patriknw**
* by using sameAsParent for spawned children

### CODE REVIEW

**Comment by patriknw** [comment]
`akka.cluster.sharding.typed.delivery.DurableShardingSpec` failed:

```
2020-03-25 11:02:35,519 ERROR akka.actor.SupervisorStrategy  - path parameter: Invalid path '..': path has a leading, trailing, or two adjacent period '.' (use quoted "" empty string if you want an empty element) {akkaAddress=akka://DurableShardingSpec@192.168.2.23:56782, akkaSource=akka://DurableShardingSpec/user, sourceActorSystem=DurableShardingSpec}
akka.actor.ActorInitializationException: akka://DurableShardingSpec/user/shardingController-1: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:195)
	at akka.actor.ActorCell.create(ActorCell.scala:657)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:509)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:531)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:294)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.typesafe.config.ConfigException$BadPath: path parameter: Invalid path '..': path has a leading, trailing, or two adjacent period '.' (use quoted "" empty string if you want an empty element)
	at com.typesafe.config.impl.PathParser.parsePathExpression(PathParser.java:170)
	at com.typesafe.config.impl.PathParser.parsePathExpression(PathParser.java:74)
	at com.typesafe.config.impl.PathParser.parsePath(PathParser.java:61)
	at com.typesafe.config.impl.Path.newPath(Path.java:230)
	at com.typesafe.config.impl.SimpleConfig.hasPathPeek(SimpleConfig.java:87)
	at com.typesafe.config.impl.SimpleConfig.hasPath(SimpleConfig.java:99)
	at akka.dispatch.CachingConfig.hasPath(CachingConfig.scala:99)
	at akka.dispatch.Dispatchers.hasDispatcher(Dispatchers.scala:128)
	at akka.remote.RemoteActorRefProvider.actorOf(RemoteActorRefProvider.scala:375)
	at akka.actor.dungeon.Children.makeChild(Children.scala:304)
	at akka.actor.dungeon.Children.actorOf(Children.scala:47)
	at akka.actor.dungeon.Children.actorOf$(Children.scala:46)
	at akka.actor.ActorCell.actorOf(ActorCell.scala:408)
	at akka.actor.typed.internal.adapter.ActorRefFactoryAdapter$.spawn(ActorRefFactoryAdapter.scala:41)
	at akka.actor.typed.internal.adapter.ActorContextAdapter.spawn(ActorContextAdapter.scala:66)
	at akka.cluster.sharding.typed.delivery.internal.ShardingProducerControllerImpl$.$anonfun$askLoadState$1(ShardingProducerControllerImpl.scala:240)
	at scala.Option.map(Option.scala:230)
	at akka.cluster.sharding.typed.delivery.internal.ShardingProducerControllerImpl$.askLoadState(ShardingProducerControllerImpl.scala:239)
	at akka.cluster.sharding.typed.delivery.internal.ShardingProducerControllerImpl$.$anonfun$apply$2(ShardingProducerControllerImpl.scala:111)
```

Something wrong with `sameAsParent`?

**Comment by patriknw** [comment]
That was a real bug in sameAsParent when using cluster provider. Fixed in https://github.com/akka/akka/pull/28843, so let's merge that first.

**Comment by renatocaval** [comment]
PLS BUILD

**Review by octonato — APPROVED** [review]

**Review by johanandren — COMMENTED** [review]
Change looks good, mention in docs dispatcher is "inherited"?

**Comment by patriknw** [comment]
@johanandren added a mention in the Scaladoc. I don't think it's important enough for the reference docs.

**Review by chbatey — APPROVED** [review]

**Pull request merged**
