### PR TITLE
=str Migrate PushStages in InterpreterSpec to GraphStages

### PR DESCRIPTION
**Pull request by naferx**

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Comment by johanandren** [comment]
Failing in `InterpreterSpec`, related?

**Comment by drewhk** [comment]
I actually implemented the same as here, because I made Map a GraphStage

**Comment by patriknw** [comment]
@naferx what's the status here?

**Comment by drewhk** [comment]
I think I actually done these changes accidentally in another PR

**Comment by naferx** [comment]
@drewhk has already made the changes in  https://github.com/akka/akka/pull/21002.
so, please close it.

**Comment by drewhk** [comment]
Sorry for the clash :( thanks for the contribution anyway!

**Comment by naferx** [comment]
No problem. Thanks.

**Pull request closed without merging**
