### PR TITLE
Update AbstractNodeQueue.java to avoid redundant reads of head in peekNode

### PR DESCRIPTION
**Pull request by nitsanw**
Avoid spinning on head when a peek/poll observes a null next but the queue is not empty.

### CODE REVIEW

**Comment by nomagic** [comment]
Shouldn't the comment read:
if tail != head this is not going to change until ~~consumer~~ **the producer** makes progress.
It's the producer that has yet to update `node.next` (hence the loop)
No code change, just left me confused

**Comment by nitsanw** [comment]
@nomagic you are correct :)

**Comment by rkuhn** [comment]
Indeed; do you want to submit a PR? (read: thanks for spotting this!)

**Comment by nomagic** [comment]
Doesn't seem worth it for a comment change.

BTW, You're probably aware of it, but just in case:

     // Extends AtomicReference for the "head" slot (which is the one that is appended to) since Unsafe
    does not expose XCHG operation intrinsically

This is no longer true, was fixed in http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7023898, at least on latest jdk 8 builds, x86_64 emits an XCHG (Yay!!)

**Comment by nomagic** [comment]
@rkuhn Yeah, my comment about Unsafe.getAndSet being intrinsified was more aimed at providing the "opportunity" to have AbstractNodeQueue decoupled from directly extending AtomicReference; I don't know if it's worth it (obviously would get a small memory gain at least), but then again admonitions about "premature optimization" probably don't apply here

**Comment by rkuhn** [comment]
AtomicReference has just a single field, so it should not make a difference whether we extend that or inline the field, or should it?

**Comment by viktorklang** [comment]
@rkuhn AFAIK, that's implementation (JVM) dependent. Any smart (read. production worthy) JVM is going to make inheritance cost 0 extra memory.

**Comment by nomagic** [comment]
It's hard to know frankly, but you guys are going through the trouble of accessing ``_tail`` via ``Unsafe`` (I wouldn't have just automatically assumed that's any faster than a direct volatile read/write - but I'm assuming you guys know better).
The thing I don't fully understand is exactly what has been  intrinsified, i.e. is it just ``Unsafe.getAndSetObject()`` or is ``AtomicReference.getAndSet`` itself being intrinsified;I had always assumed that it was just the ``Unsafe`` methods that were intrinsified, but that bug report I cited suggests otherwise.
The motivation for my bringing your attention to this was the original code comment, that suggested:
 1. since the JVM isn't intrinsifying (i.e. XCHG'ng) ``Unsafe.getAndSet``, then 
 2. might as well extend ``AtomicReference``

which makes sense.
But since 1 no longer holds, then 2 doesn't follow

**Comment by rkuhn** [comment]
Right, it wouldn’t be necessary anymore to inherit on JDK8, but there is also no downside to it that I can see, so no reason to change. But I may of course overlook something.

**Comment by nomagic** [comment]
And it should be pointed out, that if you look all through ``j.u.c`` code, ``AtomicReference`` is definitely being eschewed.
Now, that doesn't mean it should be, but I generally presume Doug Lea and co know what they're doing

**Comment by nomagic** [comment]
@rkuhn just to be clear, it was never **necessary** (``AtomicReference`` just invokes ``Unsafe``), it was just convenient;
i.e. it wouldn't break backwards compatibility to use ``Unsafe`` directly

**Pull request merged**
