### PR TITLE
groupBy pulls upstream when a substream materialization is waiting #2…

### PR DESCRIPTION
**Pull request by anilgursel**
#24353

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Review by johanandren — COMMENTED** [review]
Please add a test case that triggers the bug without this fix in place

**Comment by akara** [comment]
@johanandren We're trying to have a verifiable test case not bound to the production app. At this time we have been successful verifying this fix in our production app but not been successful creating the test case without all the ties to our production app. We're still trying but may need to resort to analysis if all else fails.

**Comment by johanandren** [comment]
Since you figured the bug out, you know the scenario but just can't reproduce it? (TestPublisher and TestSubscriber should be your best friends here to give you full step wise control of what goes in and out of the running stream)

**Comment by anilgursel** [comment]
@johanandren Thanks for pointing `TestPublisher` and `TestSubscriber`!  Updated the PR with the test case.

**Review by johanandren — APPROVED** [review]
Great, thanks for adding that test. LGTM!

**Review by jrudolph — APPROVED** [review]
LGTM

**Comment by jrudolph** [comment]
Thanks a lot, @anilgursel!

**Pull request merged**
