### PR TITLE
Make copyUSAsciiStrToBytes more robust w.r.t. JDK for Java9+ #26286

### LINKED ISSUE #26286: Unsafe.copyUSAsciiStrToBytes fails on OpenJ9/OpenJDK 11
I'm using Akka 2.5.19 together with OpenJ9/OpenJDK11 and encounter the same problem as described in #25161. The solution was replacing `chars.length` with `str.length()`. But this was only [done for the Java 8 case](https://github.com/fjeremic/akka/commit/33b8fb298c4b253f5b7d116d6bc82f27a74d6c2f). Is there any reason why the [Java 9+ case](https://github.com/akka/akka/blob/v2.5.19/akka-actor/src/main/scala/akka/util/Unsafe.java#L49) was not changed accordingly?

Exception for Akka 2.5.19 and OpenJ9/OpenJDK11:
```
2019-01-25 08:47:34,633 ERROR [] a.r.artery.Encoder Encoder(akka://ditto-cluster) - Failed to serialize > message [ActorSelectionMessage(akka.cluster.InternalClusterAction$InitJoin)].
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 94
	at java.base/java.lang.System.arraycopy(Native Method)
	at akka.util.Unsafe.copyUSAsciiStrToBytes(Unsafe.java:49)
	at akka.remote.artery.EnvelopeBuffer.writeLiteral(EnvelopeBufferPool.scala:537)
	at akka.remote.artery.EnvelopeBuffer.writeHeader(EnvelopeBufferPool.scala:433)
	at akka.remote.MessageSerializer$.serializeForArtery(MessageSerializer.scala:76)
```

### PR DESCRIPTION
**Pull request by thjaeckle**
Resolves #26286 by applying same change for Java9+ as was done for Java8 in PR #25165

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Review by johanandren — COMMENTED** [review]
Did you verify it fixes the issue on JDK 11/OpenJ 9?

Do you think you could you add a test so that it is easier to verify that it works on various platforms? Also, there's a `fastHash` a few lines down that I think would need the same change.

**Comment by thjaeckle** [comment]
I did the change also in `fastHash` - did not see that one, sorry.

Regarding adding tests in order to verify that this unsafe operations work for other JVMs: I don't think that I can do that, that exceeds my skills.

**Comment by johanandren** [comment]
Thanks @thjaeckle, I didn't mean anything magic around such a test, just a regular test case that calls the method so that it is easy to try that out on a manually selected JVM. It's fine though, I can add that after this PR has been merged.

**Review by johanandren — APPROVED** [review]
LGTM

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
Thanks @thjaeckle

**Pull request merged**
