### PR TITLE
Remove ActorContext parameter from javadsl.ReceiveBuilder, #27120

### PR DESCRIPTION
**Pull request by patriknw**
* functional style in javadsl
* in Java it's more practical to have an enclosing class to hold
  initialization parameters and ActorContext
* writing behaviors as pure static methods will be unlikely be used in Java
* it's still possible to write behaviors as static methods by passing
  the context around, in same way as all other things
* better to embrace the enclosing class pattern and therefore remove
  the context parameter from the message handlers
* style cleanup of ChatRoom sample

Refs #27120

### CODE REVIEW

**Review by chbatey — APPROVED** [review]
LGTM, makes sense to me

**Comment by chbatey** [comment]
A note in the migration guide for typed?

**Comment by patriknw** [comment]
> A note in the migration guide for typed?

Thanks, forgot. Added in 99a42205dc3eff7db96c4daca79ae65d9eddc82b

**Review by johanandren — APPROVED** [review]
LGTM / I'm ok with this change.

One concern about the 1:1 with the Scala API going away through this change, with what seems like no obvious reason (you can wrap and or close over context in Scala as well), but not sure if that is an important enough thing to _not_ change this.

**Comment by patriknw** [comment]
> One concern about the 1:1 with the Scala API 

In Scala I still think it's motivated to still have it in `Behaviors.receive` since there we have alternatives without it `Behaviors.receiveMessage`. For javadsl it's not practical to have those alternatives since the the message pattern matching infrastructure via the builders is pretty heavy (to maintain several variants of them with small signature differences in the the message handler functions).

**Comment by johanandren** [comment]
I agree, after some more thought to it. Go ahead and merge.

**Pull request merged**
