### PR TITLE
Removes newInstance from StageModule and reduces the noise for implem…

### PR DESCRIPTION
**Pull request by viktorklang**
…enting it

Had this lying around in a local clone.

### CODE REVIEW

**Comment by drewhk** [comment]
LGTM

**Comment by ktoso** [comment]
LGTM, will merge after validation

**Comment by ktoso** [comment]
Amended commit message (`=str ...`) and merged. Thanks @viktorklang !

**Comment by viktorklang** [comment]
Ah, nice catch @ktoso! :)

**Pull request merged**
