### PR TITLE
Minor conflate improvements

### PR DESCRIPTION
**Pull request by ignasi35**
References #25468

### CODE REVIEW

**Comment by hepin1989** [comment]
@ignasi35 I think those commits could be compact to one?

**Comment by ignasi35** [comment]
Will squash them. Thanks for reviewing. :Smile:

**Review by raboof — APPROVED** [review]
Nice to cross-reference like this

**Review by johanandren — APPROVED** [review]

**Comment by raboof** [comment]
travis didn't report back but is happy https://travis-ci.org/github/akka/akka/builds/666326607

**Pull request merged**
