### PR TITLE
=doc #17329 Fixed and normalized spellings in ScalaDoc and comments

### PR DESCRIPTION
**Pull request by kukido**
Additional PR for https://github.com/akka/akka/issues/17329

### CODE REVIEW

**Comment by ktoso** [comment]
Thanks :-) 
LGTM as far as I can see.

The ticket was originally meant for the `release-2.3-dev` branch but makes sense to fixup typos on master as well :-)

**Comment by kukido** [comment]
I looked into release-2.3-dev and it has some spellings like "colour", "behaviour", "standardised", "materialised" and some other - which I would like to change per ticket. Although I can rebase this PR against release-2.3-dev and add those changes, I made some modifications to rst and ScalaDoc in my first commit, which is already merged to master, and I'm afraid the new modifications will cause merge conflicts later on. Please advise.

**Comment by patriknw** [comment]
Sounds good, but be aware that 2.3-dev is only for stream, http and docs-dev

**Comment by kukido** [comment]
@patriknw I did not get that part - "2.3-dev is only for stream, http and docs-dev". If I rebase this PR against `release-2.3-dev`, who will be merging it into `master` and when? My changes are not for `stream`, `http`, or `docs-dev`, they are for other modules: `akka-cluster`, `akka-actor`, `akka-testkit`, and `akka-remote`

**Comment by patriknw** [comment]
Then branch realease-2.3-dev should not be involved here. Fix for master is enough, in my opinion. Possibly it could be backported to release-2.3 branch (i.e. released 2.3.12).

**Comment by drewhk** [comment]
LGTM

**Comment by rkuhn** [comment]
Awesome contribution, thanks!

Concerning Streams & HTTP: you are very welcome to fix things over there as well, just open a new PR (no need to port anything over) and base it on branch `release-2.3-dev`

**Pull request merged**
