### PR TITLE
Upgrade to scala 2.12.7

### PR DESCRIPTION
**Pull request by chbatey**
Let's see if this works with Java11

### CODE REVIEW

**Comment by chbatey** [comment]
Released now

**Comment by chbatey** [comment]
PLS BUILD

**Comment by chbatey** [comment]
The JDK 11 build did compile but failed due to it looking for test output and it didn't run the tests so all is good here for 11.

**Review by johanandren — APPROVED** [review]
LGTM

**Review by raboof — APPROVED** [review]
Nice!

**Comment by dwijnand** [comment]
2.5.18 milestone?

**Pull request merged**
