### PR TITLE
Adding streams to the list of capabilities

### PR DESCRIPTION
**Pull request by broij**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @JulienBroi,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by raboof** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]
Ha, funny oversight, thanks for the improvement!

**Comment by raboof** [comment]
(The test failure is unrelated, `sbtwhitesource.WhiteSourceException: Error communicating with service: Unexpected error. Response data is: Bad Gateway`)

**Comment by raboof** [comment]
PLS BUILD

**Review by ktoso — APPROVED** [review]
Thanks!

**Pull request merged**
