### PR TITLE
delete embedded media files on shutdown, #20779

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by ktoso** [comment]
Hm, LGTM. Though a bit surprising why it would not delete, ok to add the shutdown hook in any case.

**Comment by drewhk** [comment]
LGTM

**Comment by patriknw** [comment]
Sometimes we kill jvm without stopping actor system, I think. It seems to help when I run locally.

**Comment by patriknw** [comment]
Refs #20779

**Comment by ktoso** [comment]
> Sometimes we kill jvm without stopping actor system, I think. It seems to help when I run locally.

I see, that explains it.

**Pull request merged**
