### PR TITLE
=str #16683 fixes NPE in stateful stage example

### PR DESCRIPTION
**Pull request by ktoso**
resolves https://github.com/akka/akka/issues/16683

### CODE REVIEW

**Comment by drewhk** [comment]
Ah, good one, thanks. LGTM

**Comment by patriknw** [comment]
LGTM

**Comment by rkuhn** [comment]
LGTM; this should also be mentioned clearly in the docs because it may seem surprising to users (I mean the scaladoc of the `initial` method)

**Comment by ktoso** [comment]
Good idea, adding docs

**Comment by ktoso** [comment]
```
**Warning:** This method must not be implemented as `val`.
```
Good enough or needs full explanation?

**Comment by drewhk** [comment]
Fine by me, any furhter explanation would need to refer to internals in some way.

**Comment by rkuhn** [comment]
Good enough, I think.

**Pull request merged**
