### PR TITLE
Introduce the onReceiveTimeout hook for SeedNodeProcess

### PR DESCRIPTION
**Pull request by ygree**

### CODE REVIEW

**Review by raboof — APPROVED** [review]

**Comment by ygree** [comment]
We need to know which Akka version will include this change?

**Comment by raboof** [comment]
We'll add a milestone when merging - but it looks like this will be in for 2.6.4.

Do you also want it to be backported to the 2.5 tree?

**Comment by ygree** [comment]
> We'll add a milestone when merging - but it looks like this will be in for 2.6.4.
`2.6.4` sounds good

> Do you also want it to be backported to the 2.5 tree?

Yes. Here it is: #28647

**Review by helena — APPROVED** [review]
LGTM

**Pull request merged**
