### PR TITLE
=str javadsl lazilyAsync to return CompletionStage

### PR DESCRIPTION
**Pull request by naferx**

### CODE REVIEW

**Review by raboof — COMMENTED** [review]
While I agree this would be much better, I don't think we can do this: this would mean any 3rd-party library calling `lazilyAsync` that is compiled with a version of Akka without this change would throw an exception at run time when ran with a version of Akka with this change. That seems a bit too disruptive I think...

**Comment by naferx** [comment]
Yep, I'm aware of that, but why didn't MiMa pop up any errors ?

**Comment by raboof** [comment]
This branch was still on 0.3.0, which did not check generic parameters. This was added in mima 0.4.0 (https://github.com/lightbend/mima/pull/299), which has not yet made it into Akka (this is in progress at #27411)

**Comment by naferx** [comment]
Oh, Got it.
Ideally, it can be changed in a new minor release but from the user perspective, what would be the recommended workaround at this time ?

Here's another issue https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/javadsl/Source.scala#L196

**Comment by johanandren** [comment]
Also note the bigger rework in #26704

**Review by jrudolph — CHANGES_REQUESTED** [review]
Thanks, @naferx. The idea lgtm but it seems this is an incompatible change. We'll have to find a compatible solution.

**Comment by johanandren** [comment]
I think the bigger lazy/async rework solves this, by deprecating and using new names. Was hoping to get that in for 2.6 but now I'm not so sure I will have time.

**Comment by patriknw** [comment]
I agree that this is a bug (oversight) but we have to find a more compatible way to change it. Sounds good to do it as part of #26446

**Comment by johanandren** [comment]
Let's close this and aim for getting #26446 done.

**Pull request closed without merging**
