### PR TITLE
fix: mima filter for 29557-GraphStage-changes

### PR DESCRIPTION
**Pull request by pvlugter**
Refs #31606

#29636 added a binary compatibility exclude against 2.6.19. Move to 2.6.20.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @pvlugter,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Lightbend Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by He-Pin** [comment]
There is a pr for this

**Comment by pvlugter** [comment]
Ah, missed that it was already done.

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
