### PR TITLE
Upgrade ssl-config from 0.2.4 to 0.3.4

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
The failure looks unrelated:

```
error: The last gc run reported the following. Please correct the root cause
and remove .git/gc.log.
Automatic cleanup will not be performed until the file is removed.

error: prune died of signal 15
error: failed to run prune
```

**Comment by patriknw** [comment]
Is it binary backwards compatible?

**Comment by dwijnand** [comment]
Not sure.

https://github.com/lightbend/ssl-config/compare/v0.2.4...v0.3.2

We bumped the minor version because there are at least _some_ behavioural changes, which we wanted to capture in the version bump, but I'm not sure if there are any intentional binary breakages in anything user facing.

**Comment by raboof** [comment]
PLS BUILD

**Comment by raboof** [comment]
PLS BUILD

**Comment by raboof** [comment]
PLS BUILD

**Comment by dwijnand** [comment]
Try asking "pretty pls"?

**Comment by raboof** [comment]
sudo PLS BUILD

**Comment by raboof** [comment]
PLS BUILD

**Comment by dwijnand** [comment]
@patriknw I tested binary compatibility with MiMa against the previous 0.2.4 version, and here are the results for your perusal:

```
> show sslConfigCore/mimaPreviousArtifacts
[info] Set(com.typesafe:ssl-config-core:0.2.4)
> show sslConfigCore/scalaVersion
[info] 2.12.6
> show sslConfigCore/mimaBinaryIssueFilters
[info] *
[success] Total time: 0 s, completed 02-Oct-2018 09:03:05
> sslConfigCore/mimaReportBinaryIssues
[error]  * class com.typesafe.sslconfig.Base64 does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("com.typesafe.sslconfig.Base64")
[error]  * method foldVersion(scala.Function0,scala.Function0)java.lang.Object in object com.typesafe.sslconfig.ssl.package does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("com.typesafe.sslconfig.ssl.package.foldVersion")
[error]  * method foldRuntime(scala.Function0,scala.Function0)java.lang.Object in object com.typesafe.sslconfig.ssl.package does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("com.typesafe.sslconfig.ssl.package.foldRuntime")
[error]  * method DnName()java.lang.String in class com.typesafe.sslconfig.ssl.FakeKeyStore does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("com.typesafe.sslconfig.ssl.FakeKeyStore.DnName")
[error]  * method createSelfSignedCertificate(java.security.KeyPair)java.security.cert.X509Certificate in class com.typesafe.sslconfig.ssl.FakeKeyStore does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("com.typesafe.sslconfig.ssl.FakeKeyStore.createSelfSignedCertificate")
[error]  * method java16RecommendedCiphers()scala.collection.Seq in object com.typesafe.sslconfig.ssl.Ciphers does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("com.typesafe.sslconfig.ssl.Ciphers.java16RecommendedCiphers")
[error]  * method java17RecommendedCiphers()scala.collection.Seq in object com.typesafe.sslconfig.ssl.Ciphers does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("com.typesafe.sslconfig.ssl.Ciphers.java17RecommendedCiphers")
```

What do you think?  If need be I can bring back some of those.  Let me know specifics, please. 🙂

**Comment by patriknw** [comment]
I don't know how much this dependency is used by other libraries or applications depending on Akka. Difficult to say if it would be ok to break bin compat.

I assume you have a reason for updating? Play or gRPC?

We have some sslconfig part in akka-stream, which I think is the reason why we have this dependency. We might want to get rid of that but I don't know how difficult that would be. See https://github.com/akka/akka/issues/21753

@jrudolph Could you help judging here?

**Comment by dwijnand** [comment]
> I assume you have a reason for updating? Play or gRPC?

So it looks like ssl-config started by extracting SSL bits from Play (specifically Play's WS functionality).  Since then, though, it looks like the original bits weren't replaced or forwarders to ssl-config, so they've diverged.  Then some of those (along with swathes of other code) was copy-pasted and diverged more in Lagom.  With akka-grpc, this is happening for the 3rd time.

So we're trying to reconcile everything.  The public, play ticket is https://github.com/playframework/playframework/issues/8587.

The reason for this pull request is that parts of Play depend on ssl-config via Akka, so I thought it would be good to be cohesive and upgrade here too.  But I could just upgrade in Play (and it's what I'm doing while this change is unreleased).

As stated, if you'd like I can put those pieces back.  If you want to be very conservative, I can put them all back.

**Comment by jrudolph** [comment]
The original problem is that ssl-config was too tightly integrated everywhere. It's a good idea to provide helpers to configure ssl but it's not a good idea to make that a dependency everywhere (because providing an SSLContext / SSLSession should mostly suffice).

Now we have the problem that akka and akka-http depend on ssl-config and we cannot easily change that any more.

We should at least make sure that the binary incompatibilities don't affect akka/akka-http directly (it doesn't seem to be the case from the output you posted above). I guess the remaining incompatibilities would mostly affect third-party libraries that depend on ssl-config but I find it unlikely that there would be many of those.

Not bumping the dependency here doesn't make sense, it would only postpone noticing errors later on, when users pull in a newer version of ssl-config.

**Comment by marcospereira** [comment]
> Sounds good to update then. @marcospereira would you be ok with updating sslconfig dependency to 0.3.2, considering any usage from Play and Lagom?

@patriknw ssl-config was updated in Play already (https://github.com/playframework/playframework/pull/8649) and there is a PR to update it in Lagom (https://github.com/lagom/lagom/pull/1610). So I think it will be good to also have it updated here. :-)

**Review by patriknw — APPROVED** [review]
LGTM, thanks for confirming

**Review by johanandren — APPROVED** [review]

**Pull request merged**
