### PR TITLE
added missing space

### PR DESCRIPTION
**Pull request by synox**
yeah, just a space.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @synox,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by synox** [comment]
I signed the Lightbend Contributors License Agreement

**Comment by johanandren** [comment]
Thanks for the space! We are in the progress of migrating our docs to a different tool (paradox) so if you could do a new PR with that space against the new "paradox" docs that are now in master that'd be great.

**Comment by synox** [comment]
Please point me to the new paradox files.

**Comment by raboof** [comment]
They've just been merged to master this morning - so in this case it would be `akka-docs/src/main/paradox/java/stream/stream-composition.md`

**Pull request closed without merging**
