### PR TITLE
OSGI bundle changes. 

### PR DESCRIPTION
**Pull request by briantopping**
This one got dropped with the other PRs in the merge to master.

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Comment by johanandren** [comment]
Note that It should be rebased on master (not have merges from master)

**Comment by briantopping** [comment]
Thanks @johanandren, I was always doing that wrong with a merge. Squashed and rebased.

**Comment by johanandren** [comment]
Great, thanks!

**Comment by johanandren** [comment]
LGTM (with a little help from an OSGi savvy friend)

**Comment by drewhk** [comment]
LGTM

**Comment by briantopping** [comment]
Thanks guys.

**Pull request merged**
