### PR TITLE
Remove the deprecation of Flow#recoverWith

### PR DESCRIPTION
**Pull request by RichardMarto**
Removes @deprecated annotations from Flow#recoverWith at javadsl and scaladsl as required by the issue #31670

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one commit author (iam_rmarto@idcontractors.net, iam_rmarto@idcontractors.net) is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
Hi @RichardMarto,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Lightbend Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by RichardMarto** [comment]
Just signed the CLA.

**Review by johanandren — COMMENTED** [review]
There is a few more in the JavaDSL Source, SubFlow and SubSource as well.

**Comment by johanandren** [comment]
Make sure you author the commits with the same email you signed the claim with, icloud. You can rebase-rewrite author with rebase (here's an example: https://www.git-tower.com/learn/git/faq/change-author-name-email/)

**Comment by RichardMarto** [comment]
Hey @johanandren, just removed it from Source, SubFlow, and SubSource. Also, I already amended the other commits with the right email.

**Review by johanandren — APPROVED** [review]
LGTM, thanks @RichardMarto !

**Pull request merged**
