### PR TITLE
[PREVIEW] groupBy, but with unique per key dynamic sinks

### PR DESCRIPTION
**Pull request by ktoso**
Messy WIP, however this will solve a number of tickets.
Need to decide if we duplicate code or invent some way to share code with groupBy; I guess the latter would be preferable.

Refs https://github.com/akka/akka/issues/18969
And would solve https://github.com/typesafehub/activator-akka-stream-scala/issues/37

### CODE REVIEW

**Comment by johanandren** [comment]
Hey @ktoso I just remember I figured out how to do this with the existing stages:

```
  case class Elem(key: Int, value: Char)
  Source(List(Elem(1, 'a'), Elem(2, 'b'), Elem(3, 'c')))
    .groupBy(maxSubstreams = 7, _.key)
    .to(Sink.lazyInit[Elem, Future[Done]](
      first => Future.successful(Sink.foreach(e => println(s"sink ${first.key} element: $e"))),
      () => ???
    )).run()
```

So maybe no need for a specific stage, but just a bunch of factories?

**Comment by ktoso** [comment]
Oh, that's a pretty smart combination; Seems it took 3 people to finally work out a good way to compose this ;-)

I agree that providing factories would be good.

One down side is that in this impl you won't be able to nicely get the materialized values, you have to side effect them out I guess.

**Comment by johanandren** [comment]
Does that really make sense though, to materialize a stream of materialized values? I'm going to go ahead and guess there was a reason the GroupBy stage does not already do it like that.

**Comment by johanandren** [comment]
I mean, what does back pressure mean in that context? Stop new sub flows from materialising??

**Comment by ktoso** [comment]
Would buffer I guess; or it would be just a callback or something.

**Comment by johanandren** [comment]
Shouldn't that then be the `SubFlow.to` materializing into a stream of materialized values from the sinks?

**Comment by johanandren** [comment]
Just realised this though: it doesn't make sense that a `Source[MatVal]` is materialized, because what does not materializing it mean, or materializing it multiple times? It doesn't obey "normal" stream behaviour.

**Comment by ktoso** [comment]
>  It doesn't obey "normal" stream behaviour.

Just like http entity is a bit weird ;-)

Like I mentioned though, it could have some other type - though Source is pretty good and no one prohibits it to buffer; It's absolutely legal and also safe in this perspective, since bounded by the `maxSubstreams` argument, is fine and expected. Backpressuring or not materializing it should not have any effects on the underlying stream; and it can easily do so safely, since

**Comment by ktoso** [comment]
Another instance of people needing it.
https://twitter.com/manojlds/status/946093630661451778

Will get back to this in January so we can bring it in.

**Comment by patriknw** [comment]
is this really ready for next release? wan't there different opinions that must be aligned first?

**Comment by ktoso** [comment]
The pick next was here from December where I hoped to work on it. Removed

**Comment by ktoso** [comment]
Noticing more need for this for examples again, I'll try to get back to it soon, after next week I guess

**Pull request closed without merging**
