### PR TITLE
Backport: ByteString performance regression toArray on 2.13

### PR DESCRIPTION
**Pull request by johanandren**
Backport of #28419

### CODE REVIEW

**Comment by patriknw** [comment]
I guess that was javafmtCheckAll? pending PR will fix that

**Comment by johanandren** [comment]
Ah, also, the backport brought mima structure which I think 2.5 won't understand

**Comment by johanandren** [comment]
Now it is the javafmt issue :)

**Comment by raboof** [comment]
Let's not merge this until we've diagnosed https://jenkins.akka.io:8498/job/akka-nightly-2.13/406/

**Comment by johanandren** [comment]
We also need to fix #28465 before this goes in

**Comment by patriknw** [comment]
PLS BUILD

**Comment by johanandren** [comment]
No need to build this quite yet, we want the other fix from master (#28468) merged and then pulled into this PR first.

**Comment by johanandren** [comment]
Let's keep this around until we see that nigthlies on 2.13 are green again (tomorrow should be enough)

**Comment by johanandren** [comment]
Nightlies back to green. I'll merge this.

**Pull request merged**
