### PR TITLE
=act #17391 Fix regression in 2.3.10 DirectByteBufferPool

### PR DESCRIPTION
**Pull request by patriknw**
- interim solution until a proper solution can be implemented as described in #17281

### CODE REVIEW

**Comment by patriknw** [comment]
Refs #17391

**Comment by ktoso** [comment]
LGTM, failure was probably due to settings changes in jenkins, I'm working on it.

**Comment by ktoso** [comment]
PLS BUILD

**Comment by rkuhn** [comment]
LGTM

**Comment by drewhk** [comment]
LGTM

**Comment by patriknw** [comment]
@jrudolph does this correspond to the thing you verified Spray performance with? Or would it be possible for you to run a new verification (before we release this time)?

**Comment by jrudolph** [comment]
@patriknw I reran my benchmarks and this PR basically reproduces my attempts before to use synchronized. I.e.

spray with Scala 2.11 and Akka 2.3.9: ~ 185k RPS
spray with Scala 2.11 and Akka 2.3.10: ~ 80k RPS
spray with Scala 2.11 and Akka PR 17394: ~ 175k RPS

**Comment by patriknw** [comment]
thanks!

**Pull request merged**
