### PR TITLE
Update to a working version of Scalariform

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by patriknw** [comment]
@bantonsson I rebased your PR

**Comment by patriknw** [comment]
@bantonsson this is adding the `→` to FSM

```
        // Add arrows for arrow rewrite in new Scalariform
        ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.actor.FSM.→"),
        ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.actor.FSM.akka$actor$FSM$_setter_$→_="),
        ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.persistence.fsm.PersistentFSMBase.→"),
        ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.persistence.fsm.PersistentFSMBase.akka$persistence$fsm$PersistentFSMBase$_setter_$→_="),
```

Is that a safe backwards binary compatible change? See discussion of previously attempt: https://github.com/akka/akka/pull/19746

**Comment by patriknw** [comment]
Failure was in `StreamLayoutSpec` https://github.com/akka/akka/issues/20627

```
2357.321: [GC (Allocation Failure) [PSYoungGen: 593259K->29833K(618496K)] 1925032K->1361613K(2016768K), 0.1259008 secs] [Times: user=1.12 sys=0.02, real=0.13 secs] 
2360.995: [GC (Allocation Failure) --[PSYoungGen: 618121K->618121K(618496K)] 1949901K->2016389K(2016768K), 1.2152092 secs] [Times: user=14.67 sys=7.55, real=1.21 secs] 
2362.210: [Full GC (Ergonomics) [PSYoungGen: 618121K->69251K(618496K)] [ParOldGen: 1398268K->1398243K(1398272K)] 2016389K->1467494K(2016768K), [Metaspace: 372791K->372774K(1368064K)], 3.6699223 secs] [Times: user=89.71 sys=0.77, real=3.67 secs] 
[info]   - when starting from a Source *** FAILED *** (9 seconds, 283 milliseconds)
[info]     A timeout occurred waiting for a future to complete. Queried 20 times, sleeping 15 milliseconds between each query. (StreamLayoutSpec.scala:134)
```

We are working on that test here: https://github.com/akka/akka/pull/20671

And a new failure in OutputStreamSourceSpec. Issue created https://github.com/akka/akka/issues/20676

**Comment by bantonsson** [comment]
@patriknw That's what I get for not keeping up with the akka PRs. It seems like you have been through this whole reformat dance once before, and concluded that the `→` val addition wasn't binary compatible. I'll just drop this for now.

At least it forced some cleanup of the tests 😉

**Comment by patriknw** [comment]
Sorry for not noticing immediately, I was hoping that you had found a way to update scalariform without that FSM change. Thanks.

**Pull request closed without merging**
