### PR TITLE
[Akka 30800] Improve performance of JoinConfigCompatChecker

### PR DESCRIPTION
**Pull request by dragisak**
Fixes https://github.com/akka/akka/issues/30800

When profiling our app, while it's trying to join the cluster, I found that it's spending most of the time in `JoinConfigCompatChecker` doing `List.contains(..)`. 

Converting `JoinConfigCompatChecker.requiredKeys` from `Seq` to `Set` should improve performance.

### CODE REVIEW

**Comment by dragisak** [comment]
Done. Can someone please review it?

**Review by octonato — COMMENTED** [review]
@dragisak thanks for reporting this and for the efforts to fix it. 

I don't think that using a Set will help much. Usually, the number of configurations that are checked are very limited and they are also unique. So moving to a `Set` won't reduced its number. 

I was looking into the code and I think there is easier way to solve this instead of changing the API.  

In the `JoinConfigCompatChecker.filterWithKeys` we have: 

```scala
private[cluster] def filterWithKeys(requiredKeys: im.Seq[String], config: Config): Config = {

    val filtered =
      config.entrySet().asScala.collect {
        case e if requiredKeys.contains(e.getKey) => (e.getKey, e.getValue)
      }

    ConfigFactory.parseMap(filtered.toMap.asJava)
  }
```

The problem is that we are going through all the keys in the `Config` and testing it against the required keys. We should turn it around. 

Instead, we should iterate over the `requiredKeys` (much smaller collection), pick the key/value from the `Config` and build the `filtered` map. We will need to check that the key exists in the `Config` object though. 

The current impl is calling `contains` for every key in `Config` and that's what you are seeing in the profile. 

Btw, we can't change the API as moving from `Seq` to `Set` is a binary incompatible change and the checkers are public API.

**Comment by dragisak** [comment]
The performance bottleneck is doing `contains(...)` on `Seq` repeatedly. Not the size of those collections. If we use Set. Complexity goes down from O(n) to O(1)

**Comment by dragisak** [comment]
Perhaps, I can change those signatures back to `Seq` and just convert them to Set before the loop. Like I initially did here https://github.com/akka/akka/pull/30793/commits/d998e44915ed2673d72ca2b7c678a4bfd914e7ef

**Comment by dragisak** [comment]
Let me give it another stab by doing what you suggested @octonato

**Pull request closed without merging**
