### PR TITLE
Load MiMa filters from file

### PR DESCRIPTION
**Pull request by 2m**
*This PR uses a not yet released feature (https://github.com/typesafehub/migration-manager/pull/174) from sbt MiMa plugin where it is able to load mima filters from files like in akka-http.*

*EDIT: it now uses a new version of MiMa 0.1.15 and can be merged.*

Moves MiMa filters from a mega-list in MiMa.scala to a separate files grouped by a project and a version.

### CODE REVIEW

**Comment by johanandren** [comment]
OMG YES!

**Comment by 2m** [comment]
Updated to the newly released MiMa and rebased from master.

**Comment by johanandren** [comment]
OMG OMG OMG!!!

**Review by johanandren — APPROVED** [review]
LGTM!

**Review by raboof — APPROVED** [review]
Very neat! So we need sbt 0.13.16 for this to work?

**Comment by 2m** [comment]
@raboof yes, because of https://github.com/typesafehub/migration-manager/pull/182

**Comment by ktoso** [comment]
This is awesome:) However please also update the Readme so people know how to deal with the new style: https://github.com/akka/akka/blob/master/CONTRIBUTING.md#binary-compatibility

**Pull request merged**
