### PR TITLE
Avoid pattern-matching on OptionVal since Scala 2.13 allocates when c…

### PR DESCRIPTION
**Pull request by viktorklang**
…hecking the pattern

References #30264

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
Could you combine all your PRs related to this into one PR?
We want to revert all this when it has been fixed in the Scala compiler and it would be easier if we have one PR/commit to keep track of.

**Comment by viktorklang** [comment]
Superseded by #30276

**Comment by viktorklang** [comment]
Superseded by #30276

**Pull request closed without merging**
