### PR TITLE
Missing creation of second actor

### PR DESCRIPTION
**Pull request by vadimjouk**
## Purpose

Added missing line for creation of second actor

## References

References #28171

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @vadimjouk,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by vadimjouk** [comment]
Signed an agreement

**Review by johanandren — APPROVED** [review]
LGTM, thanks for fixing!

**Comment by johanandren** [comment]
OK TO TEST

**Comment by vadimjouk** [comment]
Test will fail becouse of double actor names, but i did not changed it.
Names should be unique, but then we must rename actors in this example

**Comment by helena** [comment]
Just needs a `akka-docs/scalafmtAll`

**Review by raboof — APPROVED** [review]
Thanks! @vadimjouk could you remove the whitespace on line 58? that will make scalafmt happy ;)

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Pull request closed without merging**
