### PR TITLE
Update deploy.md to avoid Maven generating erroneous tags

### PR DESCRIPTION
**Pull request by sypste**
According to [this](https://stackoverflow.com/a/56154292/3715185), adding an id to the execution configuration can help to keep Maven from generating erroneous tags in the effective pom, such as adding a `<resource>` tag to the `ManifestResourceTransformer`.

## Purpose
Update the documentation for building fat jars.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @styks90,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by styks90** [comment]
@raboof Hope this saves somebody some time one day

**Comment by raboof** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]
Yes, thanks!

**Comment by helena** [comment]
I think you will get a merge conflict with this, the doc file has changed quite a bit.

**Comment by helena** [comment]
@styks90 this is where this belongs now, in master is https://github.com/akka/akka/blob/master/akka-docs/src/main/paradox/additional/packaging.md#maven-jarjar-onejar-or-assembly

Thanks!

**Review by helena — COMMENTED** [review]
Great addition, just needs a relocation now to https://github.com/akka/akka/blob/master/akka-docs/src/main/paradox/additional/packaging.md#maven-jarjar-onejar-or-assembly

**Comment by styks90** [comment]
@helena I relocated the change, hope all is as it should be now

**Review by raboof — APPROVED** [review]
Thanks again, sorry about the conflict dance ;)

**Pull request merged**
