### PR TITLE
+doc introduce algolia search box

### PR DESCRIPTION
**Pull request by ktoso**
Trying out http://algolia.com docs search (assisted by their team on setting this up).

Here's a vid how it looks in action: https://www.youtube.com/watch?v=Ox3rDgYwPy0
(video shows me searching on a local version hardcoded to search on 2.4.2 - normally it'd search on the same version as currently browsed)

Now also includes akka version and language detection.

Documentation for the specific feature / offering we're using here is here: https://community.algolia.com/docsearch/documentation/

### CODE REVIEW

**Comment by drewhk** [comment]
LGTM, maybe you should explain the nitty gritty details as well, so we can add more domain specific indexing knowledge?

**Comment by ktoso** [comment]
With the automatic search that feature is we sadly can't inject much more info (other than the version/language) I guess. Currently they've set up an indexing engine that crawls the docs every 24hours, it detects version and language.

They do provide a commercial offering where one has full control over the indexing etc (one has to write the indexing yourself then as I understood it), but I don't think we have the time to fine-tune all search results and work on the indexing to that detail.

**Comment by johanandren** [comment]
LGTM

**Comment by AntoinePlu** [comment]
Hi @ktoso 
Based on your website, there is a design proposal to give you an idea of how you could implement DocSearch on it.

Default state
Input active

**Comment by drewhk** [comment]
This needs a re-release of docs to make it live right?

**Comment by ktoso** [comment]
> This needs a re-release of docs to make it live right?

Yeah, once we merge it'll be out on `/snapshot/` but we'll want to re-publish on older ones (maybe just on 2.4 series?)

**Comment by 2m** [comment]
I tried to run this PR locally. The search box is being displayed, but nothing happens when I enter anything to it.

**Comment by drewhk** [comment]
I think we don't need to republish old docs. They have a warning anyway to point people to the most recent version.

**Comment by ktoso** [comment]
I'll merge this to see it live.

**Pull request merged**
