### PR TITLE
Setup previousVersions for akka-coordination

### PR DESCRIPTION
**Pull request by ignasi35**
## Purpose

Setup MiMa's `mimaPreviousArtifacts` for `akka-coordination`.

## Changes

copy/pasted from changes applied for `akka-discovery`

### CODE REVIEW

**Review by raboof — APPROVED** [review]
Good catch - I wonder why this didn't cause PR's to fail on MiMa errors? Or did they?

**Comment by ignasi35** [comment]
> Good catch - I wonder why this didn't cause PR's to fail on MiMa errors? Or did they?

Well, the MiMaPlugin was disabled.

**Comment by ignasi35** [comment]
Hmmm, actually... this modeul is `.settings(AkkaBuild.mayChangeSettings)` so it doesn't make much sense to check MiMa yet I guess.

**Comment by ignasi35** [comment]
> Hmmm, actually... this module is `.settings(AkkaBuild.mayChangeSettings)` so it doesn't make much sense to check MiMa yet I guess.

I take it back. IMHO, even if this is ÀpiMayChange` it makes sense to check MiMa to have a better alert of breaking changes.

**Comment by raboof** [comment]
> even if this is ÀpiMayChange` it makes sense to check MiMa to have a better alert of breaking changes

Yes, might be good to at least get alerted about incompatible changes, even if we want to be liberal in ignoring them :+1:

**Comment by patriknw** [comment]
PLS BUILD

**Comment by patriknw** [comment]
I have changed target branch to `release-2.5` here since we changed the build in master. I will forward port to master.

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
