### PR TITLE
Fix typo in reference.conf

### PR DESCRIPTION
**Pull request by nickpoorman**
rasio => ratio

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]
Good catch, thanks!

**Review by ktoso — APPROVED** [review]
Thanks

**Comment by ktoso** [comment]
We can merge as soon as the CLA is confirmed, you can sign it online as the bot above linked :)

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by nickpoorman** [comment]
CLA is signed

**Comment by raboof** [comment]
Thanks!

**Pull request merged**
