### PR TITLE
Harden ReplicatorDeltaSpec, #25342

### PR DESCRIPTION
**Pull request by patriknw**
* It was a timing race condition in the test that was exposed
  by the change in PR #25315. Full state is now sent immediately
  when receiving the DeltaNack and that makes the Update complete
  much faster for that case than before.
* That resulted in that the delta propagations from previous
  updates were still in the buffer to be sent out when the
  incr(4) was performed. Those deltas contained the NoDeltaPlaceholder,
  which caused the inrc(4) delta to also be folded into NoDeltaPlaceholder
  and thereby not propagated.
* Before the DeltaNack the buffer had time to be flushed before the incr(4)
  and therefore no NoDeltaPlaceholder.

Refs #25342

### CODE REVIEW

**Comment by patriknw** [comment]
There might be more similar timing issues here. I'll put this branch on repeat.

**Comment by patriknw** [comment]
Updated with better fix. First attempt didn't test same thing.

**Review by ktoso — APPROVED** [review]
Seems good

**Review by johanandren — COMMENTED** [review]
LGTM

**Pull request merged**
