### PR TITLE
change spelling of behaviour to behavior, #24457

### PR DESCRIPTION
**Pull request by patriknw**
Refs #24457

### CODE REVIEW

**Comment by ktoso** [comment]
Aches my heart, but LGTM ;-)

**Review by ktoso — APPROVED** [review]

**Comment by chbatey** [comment]
:-1:

**Review by chbatey — APPROVED** [review]
Most of these weren't me!

**Comment by ktoso** [comment]
> Most of these weren't me!

/me hides

**Review by raboof — APPROVED** [review]
Good to be consistent, already some merge conflicts unfortunately :/

**Pull request merged**
