### PR TITLE
Docs: sort all operators by method name in left-hand menu 

### PR DESCRIPTION
**Pull request by ennru**
* List the operators in alphabetical order by method name.
* Prefix all Sink/Source operators (with Sink or Source) 

Results in

image

The special case `from`/`apply` shows in `from`'s position.

I'm not sure if prefixing the Source & Flow operators improves the experience.

### CODE REVIEW

**Comment by hepin1989** [comment]
Better them grouped into Source/Flow/Sink?

**Comment by ennru** [comment]
> Better them grouped into Source/Flow/Sink?

Theme oriented ordering is what the page itself shows.

**Comment by raboof** [comment]
I agree ordering by theme doesn't make any sense for the left-hand menu.

> I'm not sure if prefixing the Source & Flow operators improves the experience.

For `actorRef` *not* prefixing is weird as well, so I see why you added those. It does make some of the operators quite wide, but it still looks acceptable I think.

> Better them grouped into Source/Flow/Sink?

We're now showing the class name and method name, but order on just the method name - I agree that is not too clear. It would be interesting to order on 'class+method', but that would mean adding the class everywhere, and it's not clear how to do that for pages that describe both Source and Flow with one page.

Perhaps we should include the class only when it is not 'Source' or 'Flow', and then order on class (if any) and method?

**Comment by ennru** [comment]
We could make the sorting more obvious by adding the class after the method name:

* actorRef (Source)
* actorRef (Sink)
* actorRef (ActorSource)
* actorRef (ActorSink)
* ...

**Comment by ennru** [comment]
This looks better. Even the duplicated names are easily distinguishable.

image

**Comment by johanandren** [comment]
That looks nice in the index but quite funky on the individual pages IMO

**Comment by ennru** [comment]
Funky?
image

Quite a time ago I looked into building more control over what's rendered into Paradox `@@index`, but I won't go there now. The index improvement makes this kind of funkiness worthwhile.

**Comment by raboof** [comment]
I'm not sure this feels like a net positive: it improves the left-hand menu but I agree with @johanandren it's at the cost of the page titles - which are more prominent/important.

Maybe the 'prefixed' version is nicer after all, so we could merge this and indeed revisit when we add support for specifying the titles of the index separately?

**Comment by ennru** [comment]
I rolled back the update of the page titles. Just made them consistent.

**Review by raboof — APPROVED** [review]

**Review by ignasi35 — APPROVED** [review]
I love the new index (sorted by operator + category in parens)

> I rolled back the update of the page titles. Just made them consistent.

It took me a bit to understand why some of the titles include the `Sink.`/`Source.` prefix but it makes sense and it'll be more comprehensible.

**Comment by ignasi35** [comment]
Nice changes!

**Pull request merged**
