### PR TITLE
Akka 29784  stateful map concat relax f ret type

### PR DESCRIPTION
**Pull request by eyalfa**
References #29784
relax `statefulMapConcat` and `mapConcat` required return type of `f` such that it can return an `Iterator` instead of an `Iterable`

### CODE REVIEW

**Comment by eyalfa** [comment]
@raboof ,
I've consulted with @johanandren who believes mima-checks are giving falss negative here.
according to his advice I've written a small test program using `mapConcat` and `statefulMapConcat` compiled against akka v2.6.10, I then tweaked the classpath provided when running the program to use a locally published akka-streams jar built from this PR's branch.
The program execution succeeded both for scala 2.12 and scala 2.13.

I believe this proves that there is no real mima issue here, how do u recommend to proceed with this?

**Comment by johanandren** [comment]
I think a mima filter for the warnings is ok given that you manually verified bin comp. 

There's still a deprecated warning that needs to be dealt with though, I think you can just silence it for now using `@silent("deprecated")`

**Comment by eyalfa** [comment]
> I think a mima filter for the warnings is ok given that you manually verified bin comp.
> 
> There's still a deprecated warning that needs to be dealt with though, I think you can just silence it for now using `@silent("deprecated")`

are you refering to `FlowWithContext.mapConcat`? I just fixed it

**Comment by eyalfa** [comment]
@raboof , @johanandren ,
what about Java API? seems like it can gain great deal from this since the exiting `Iterable` based API copies the `Iterable` into a scala immutable collection.

I was able to provide a side-by-side overload of mapConcat taking a `java.util.Iterator`, unfortunately I could not do the same for `statefulMapConcat`.
I think there are several options here:
1. don't support this in the Java-API 
2. introduce couple of new method, i.e. `mapConcatI` and `statefulMapConcatI` delegating to the newly introduced scala API methods.
3. introduce an overload to `mapConcat` and a new method for `statefulMapConcatI`.

how would you like to handle this?

**Comment by johanandren** [comment]
I'd argue for skipping the improvement for java `statefulMapConcat`, but if it is possible to do with an overload for `mapConcat` I think that is fine to add.

**Comment by eyalfa** [comment]
> I'd argue for skipping the improvement for java `statefulMapConcat`, but if it is possible to do with an overload for `mapConcat` I think that is fine to add.

so sou basically suggest adding an additional overload for `mapConcat` and ignore `statefulMapConcat` ?

**Comment by eyalfa** [comment]
> > I'd argue for skipping the improvement for java `statefulMapConcat`, but if it is possible to do with an overload for `mapConcat` I think that is fine to add.
> 
> so sou basically suggest adding an additional overload for `mapConcat` and ignore `statefulMapConcat` ?

turns out I forgot to compile `akka-stream-tests` ehrn evaluating my approach for javadsl `mapConcat`...
long story short I don't have a working (or even compiling) overload to `mapConcat` or `statefulMapConcat`.

I still think this is important for javadsl as well, hence I suggest adding a couple of methods supporting the `Iterator` overload and name them slightly different then the existing ones.

**Comment by johanandren** [comment]
I'm not quite convinced the added API surface is worth it on the Java side given that we have heard no complaints about it before this ticket/PR. So while it would be more efficient I think we should wait until we hear from more people that it is an unacceptable overhead in the Java API.

**Comment by eyalfa** [comment]
> I'm not quite convinced the added API surface is worth it on the Java side given that we have heard no complaints about it before this ticket/PR. So while it would be more efficient I think we should wait until we hear from more people that it is an unacceptable overhead in the Java API.

in this case, can this be considered done? or is there anything else you'd like to see here?

**Review by johanandren — APPROVED** [review]
Yep, I think so. LGTM

**Review by raboof — APPROVED** [review]
Nice to have the more precise type, and indeed I can't come up with a scenario where the different generics would cause run-time trouble.

**Pull request merged**
