### PR TITLE
Don't put temporary actor refs in the heavy hitters table 

### PR DESCRIPTION
**Pull request by johanandren**
References #30212

Draft for now, I'll set up a repeater CI-multi-jvm-job to exercise it a bit.

### CODE REVIEW

**Comment by johanandren** [comment]
Spinning since yesterday in https://jenkins.akka.io:8498/job/(legacy)%20akka-multi-node-repeat-johan/

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by johanandren** [comment]
Mostly green builds for almost two weeks now, seen a couple of failures on the repeat job but haven't had time to investigate if they are related yet. I'll stop the job for now.

**Comment by johanandren** [comment]
Looked at the few failed tests in repeat, nothing that looks related to this fix. 👍

**Review by raboof — APPROVED** [review]

**Pull request merged**
