### PR TITLE
Update building-akka.rst

### PR DESCRIPTION
**Pull request by elegoff**
sbt Has moved thus some loink are deprecated

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @elegoff,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by drewhk** [comment]
OK TO TEST

**Comment by patriknw** [comment]
PLS BUILD

**Comment by patriknw** [comment]
LGTM

**Comment by patriknw** [comment]
CLA has been signed

**Pull request merged**
