### PR TITLE
=htj #16436 add missing Java directives

### PR DESCRIPTION
**Pull request by jrudolph**
Here's the first big block to get Java support on par with the Scala side. Javadoc / Scaladoc are still missing at some places and I'll try to add some more tomorrow morning.

/cc @sirthias

### CODE REVIEW

**Comment by jrudolph** [comment]
(The first 4 commit are already part of #17767, so no need to review them here)

**Comment by ktoso** [comment]
LGTM

**Comment by drewhk** [comment]
@sirthias, will you rebase this, or should I take over?

**Comment by sirthias** [comment]
I'll rebase now.

**Comment by sirthias** [comment]
Rebased. Tests are green for me.

**Comment by sirthias** [comment]
Damn. Another conflict. Hang on.

**Comment by sirthias** [comment]
Now. Done.

**Comment by drewhk** [comment]
argh...
There was a failure just after I merged...

**Comment by drewhk** [comment]
It is very likely a timeout due to the 500ms deadline. I do a couple of test round later though.

**Pull request merged**
