### PR TITLE
=str #19128 #19127 rename Source/Sink factory apply overloads

### LINKED ISSUE #19128: Remove apply methods from Source, Sink
- Source.apply(Future)
 - Source.apply(() => Iterator)

### PR DESCRIPTION
**Pull request by 2m**
Fixes #19128 and #19127

### CODE REVIEW

**Comment by drewhk** [comment]
We should merge this soon to avoid unnecessary merge conflicts. This is costlier to rebase than the smaller concurrent PRs.

**Comment by drewhk** [comment]
LGTM

**Comment by rkuhn** [comment]
merge ASAP; then revalidate all outstanding PRs to avoid compilation errors on release-2.3-dev

**Comment by ktoso** [comment]
Yay!

**Pull request merged**
