### PR TITLE
#20217 If the future in mapAsync is already available, don't dispatch it

### PR DESCRIPTION
**Pull request by Falmarri**
I didn't use FastFuture since that's defined in akka-http-core, but this, I believe, is adequate to accomplish the same thing.

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Good, however let's prepend that match with a comment explaining why we do this.

**Comment by patriknw** [comment]
LGTM, I think the only remaining thing is that comment explaining that we do this for performance reasons

**Comment by Falmarri** [comment]
@patriknw Done

**Comment by ktoso** [comment]
Excellent, thanks a lot!

**Comment by ktoso** [comment]
Resolves https://github.com/akka/akka/issues/20217

**Pull request merged**
