### PR TITLE
=act #17781 Optimize the creation of router actor

### PR DESCRIPTION
**Pull request by MQ-EL**
1. Avoid the unnesscery fallback of deploy object
2. remove the fallback of router object with itself

refs: #17781

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
OK TO TEST

**Comment by MQ-EL** [comment]
I cannot find that the cause is because of my commit. Can Somebody verify it?

**Comment by MQ-EL** [comment]
I think the test mode of akka has some problem, because the first commit failed, the third passed, but they are the same code.

**Comment by ktoso** [comment]
LGTM, could you please squash into one commit and title it like so: `=act #17781 Optimize the creation of router actor`?

**Comment by MQ-EL** [comment]
Ok, I create a new pr. Is it right?

**Comment by ktoso** [comment]
Either works, thanks.
You can easily squash commits by doing:

```
git rebase --interactive HEAD^^^
// make the "to squash" commits "s"quash, and keep one "p"ick
push -f // to update this PR
```

**Comment by ktoso** [comment]
Thanks, moving over to https://github.com/akka/akka/pull/18087 then!

**Comment by MQ-EL** [comment]
Ha Ha, Thank you for sharing

**Pull request closed without merging**
