### PR TITLE
dynamic config path for levelDBJournal and localSnapshotStore #21394

### PR DESCRIPTION
**Pull request by johanandren**
Backport from 2.5/master
Refs #21394

### CODE REVIEW

**Comment by johanandren** [comment]
PLS BUILD

**Comment by johanandren** [comment]
Should cherry pick #22007 in here when merged also, before merging this into 2.4

**Comment by patriknw** [comment]
@johanandren pick the other one also

**Comment by johanandren** [comment]
@patriknw Cannot se that there was a third merge related to LevelDB to cherry-pick?

**Comment by patriknw** [comment]
ah, I was mislead by your comment "Should cherry pick ..."

**Pull request merged**
