### PR TITLE
=per #19221 Eager initialization of persistence plugins

### PR DESCRIPTION
**Pull request by ghost**
- New ~~boolean~~ list configuration keys added (akka.persistence.journal.auto-start and akka.persistence.snapshot-store.auto-start)
- Initialization is performed during Persistence initialization, so for this to work the persistence extension should be specified under akka.extensions

Review by @patriknw

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by talp-traiana** [comment]
@patriknw 
I added the plugin lists and documentation. WDYT?

**Comment by patriknw** [comment]
excellent, LGTM

**Comment by talp-traiana** [comment]
@patriknw 
OK, I rebased and squashed it. Let me know if there's anything else.

**Comment by ktoso** [comment]
Refs #19221

**Comment by ktoso** [comment]
Very good, thanks for the contrib @talp-traiana!

**Pull request merged**
