### PR TITLE
Add color to LogCapturing #31689

### PR DESCRIPTION
**Pull request by jackyscript**
References #31689

As this is my first time, I am happy for any feedback.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @jackyscript,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by jackyscript** [comment]
> Hi @jackyscript,
> 
> Thank you for your contribution! We really value the time you've taken to put this together.
> 
> Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:
> 
> https://www.lightbend.com/contribute/cla

Signed

**Review by johanandren — APPROVED** [review]
LGTM (and verified locally that it does nicely color a fail), thanks @jackyscript !

**Comment by johanandren** [comment]
Failure is formatting, please do a compile which will trigger reformat, and commit/push the changed file.

**Comment by jackyscript** [comment]
> Failure is formatting, please do a compile which will trigger reformat, and commit/push the changed file.

@johanandren Done, looks formatted to me.

**Review by patriknw — APPROVED** [review]
LGTM, thanks

**Pull request merged**
