### PR TITLE
Eager creation of system materializer on system startup

### PR DESCRIPTION
**Pull request by johanandren**
Refs #26850

### CODE REVIEW

**Review by patriknw — APPROVED** [review]
LGTM, that helps but maybe keep the ticket open since the fix is not universal

**Comment by johanandren** [comment]
FYI I derailed into writing that universal fix.

**Comment by johanandren** [comment]
Go look at #27723 instead!

**Comment by johanandren** [comment]
Closing this for now since I think the other PR is better.

**Pull request closed without merging**
