### PR TITLE
#19361 Convert FrameHandler to GraphStage

### PR DESCRIPTION
**Pull request by poojadshende**

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by poojadshende** [comment]
@ktoso @johanandren Need help in replacing few function calls in file.
In below line 
```
private def becomeAndHandleWith(newState: State, part: FrameEvent): Unit = {
```
I get error
```
value not found: state
```
So what should I use for that and for all push statements it gives me type mismatch error.

**Comment by johanandren** [comment]
I'm sorry but there is no simple rewrite-according-to-these-step-by-step-rules with the `StatefulStage` you will have to look at what the stage does, introduce state as needed to do the same with a `GraphStage`.

**Comment by johanandren** [comment]
(Also sorry for the long delay, so much things to do, so little time to do it in)

**Comment by danxmoran** [comment]
@johanandren @poojadshende I can pick this up, if this PR is dead

**Comment by drewhk** [comment]
@danxmoran that would be great help. @poojadshende is that OK for you?

**Comment by ktoso** [comment]
I closed the ticket as obsolete, let us know if you're still on it @poojadshende !

**Pull request closed without merging**
