### PR TITLE
Test that reproduces the issue #16327

### PR DESCRIPTION
**Pull request by skisel**
Added test to master branch according to request by Roland Kuhn:
https://github.com/akka/akka/pull/16744#issuecomment-72010706

It still fails (as well as in 2.3 branch), so the root cause was because sameThreadExecutionContext cannot avoid thread starvation when Batching is used and Await/blocking is called.

### CODE REVIEW

**Comment by rkuhn** [comment]
OK TO TEST

**Comment by rkuhn** [comment]
Thanks for this test case, now we only need a matching patch :-) (but having a reproducer is always a very good start)

refs #16327

**Comment by skisel** [comment]
I removed BatchingExecutor mixing from sameThreadExecutionContext because it may cause starvation problems, moreover it seems it does not add any value to the executor. What do you think?

**Comment by rkuhn** [comment]
Further investigation reveals the following:

* the test failure on master is different from the other tickets, it simply times out (as is expected) due to the deferred evaluation of batchable subtasks—this is perfectly fine and normal (*)
* the fix for the actual issue was done in #1970, but at the time we did not see that this might impact Spray for Akka 2.3.x

The way forward is therefore to port Viktor’s PR to the release-2.3 branch and include that with Akka 2.3.10.

(*) sameThreadExecutor has two choices: either run depth first or breadth first. No matter which we choose we can write a test that fails due to deadlock. Giving the user a choice (via `Batchable.isBatchable`) allows them to configure their tasks appropriately, so we’ll leave things as they are on this front.

**Comment by rkuhn** [comment]
@skisel Do you want to try your hand at this, or shall I?

**Comment by skisel** [comment]
Ok, its clear. Yes, I will try my hand at this. Thanks

**Comment by rkuhn** [comment]
This PR can be closed now that the underlying issue has been fixed otherwise. Thanks for pushing this!

**Pull request closed without merging**
