### PR TITLE
Update to Scala 2.12.10

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by raboof** [comment]
Failure is a `java.lang.OutOfMemoryError`...

**Comment by raboof** [comment]
PLS BUILD

**Comment by raboof** [comment]
Error is #27757

**Comment by raboof** [comment]
PLS BUILD

**Review by helena — APPROVED** [review]
For scala upgrades might there ever be anything in the multi-node code that isn't hit in this validation? I'm thinking not.

**Review by johanandren — APPROVED** [review]

**Pull request merged**
