### PR TITLE
Bumping sbt-git version to avoid Class not found error.

### LINKED ISSUE #20439: Update sbt-git
When starting sbt in the akka master branch for the first time I got the following stacktrace

```
java.lang.NoClassDefFoundError: org/eclipse/jgit/storage/file/FileRepository
	at com.typesafe.sbt.git.DefaultReadableGit.<init>(ReadableGit.scala:23)
	at com.typesafe.sbt.SbtGit$$anonfun$4.apply(SbtGit.scala:78)
	at com.typesafe.sbt.SbtGit$$anonfun$4.apply(SbtGit.scala:78)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jgit.storage.file.FileRepository
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.typesafe.sbt.git.DefaultReadableGit.<init>(ReadableGit.scala:23)
	at com.typesafe.sbt.SbtGit$$anonfun$4.apply(SbtGit.scala:78)
	at com.typesafe.sbt.SbtGit$$anonfun$4.apply(SbtGit.scala:78)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] java.lang.NoClassDefFoundError: org/eclipse/jgit/storage/file/FileRepository
```
Updating the `sbt-plugin` version in `plugins.sbt` to the latest version `addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "0.8.5")` allowed me to continue. I have not tested anything further related to `sbt-git`.

### PR DESCRIPTION
**Pull request by magnusart**
Fixes #20439

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
If jenkins is happy LGTM ;)

**Comment by magnusart** [comment]
Hmmm... not sure how to create tests for this?
Anyhow I thought this was resolved by removing sbt-git so this should be closed in that case.

**Comment by ktoso** [comment]
The failure though is not a git failure but `[error] 	docs.jrouting.ConsistentHashingRouterDocTest` so I guess it's OK.

Can re-run just to be safe

**Comment by ktoso** [comment]
(Needs a rebase)

**Comment by ktoso** [comment]
PLS BUILD

**Comment by magnusart** [comment]
As sbt-git is already removed by [this commit](https://github.com/akka/akka/commit/b5115088252107688f72ae72d36ef77611d34eae) I will close this.

**Pull request closed without merging**
