### PR TITLE
+str #19589 Add autoFlush option to  OutputStream Sinks

### LINKED ISSUE #19589: No flushing in StreamConverters.fromOutputStream
When using `StreamConverters.fromOutputStream` to create a stream from an `OutputStream`, the implementation provides no way to flush after writes. This is a problem, for example, when writing to STDIN of a child process (at least on Windows), where flushing does not automatically take place.

A workaround is to wrap the `OutputStream` in a `PrintStream` using its `autoFlush` feature.
```scala
StreamConverters.fromOutputStream(() => new PrintStream(process.getOutputStream, true))
```

However it would be better if `StreamConverters.fromOutputStream` would provide this option directly.

### PR DESCRIPTION
**Pull request by m-sp**
Fixes #19589

### CODE REVIEW

**Comment by drewhk** [comment]
LGTM, but needs rebase

**Comment by drewhk** [comment]
OK TO TEST

**Comment by m-sp** [comment]
@drewhk rebased onto master

**Comment by johanandren** [comment]
LGTM

**Pull request merged**
