### PR TITLE
=http - 19091 - Removes the buffer(1, Backpressure) from the Http blu…

### PR DESCRIPTION
**Pull request by viktorklang**
…eprint

See #19091

### CODE REVIEW

**Comment by ktoso** [comment]
You're always snatching the easy delete lines tickets :wink: 
Thanks!

LGTM

**Comment by viktorklang** [comment]
@ktoso "A well-kept source tree shouldn't have any low-hanging issue-fruits." — Old Klangian Proverb

**Comment by ktoso** [comment]
I want to pick the fruit too!

**Comment by viktorklang** [comment]
@ktoso IT was ripe for the picking for 20h! :)

**Comment by ktoso** [comment]
A good ticket is like a good wine, needs to ripe for a while ya know :wine_glass: :wink:

**Comment by viktorklang** [comment]
@ktoso No, it's more like an infected wound, the longer you leave it unattended the bigger the risk of having to cut the limb off :)

**Comment by ktoso** [comment]
Sure, agree just messing with you here :wink: 
Merging after validation :)

**Comment by viktorklang** [comment]
@ktoso Thanks! :)

**Pull request merged**
