### PR TITLE
NOT FOR MERGE only forcing build of all projects

### PR DESCRIPTION
**Pull request by bantonsson**
Getting annoyed by the CI build failures in the #20591 , so I'm just trying to figure out if the tests are flaky.

### CODE REVIEW

**Comment by patriknw** [comment]
Hm, why would things be flaky now. I think we have had rather stable builds. Perhaps some wrong timeouts in new stream and http tests.

**Comment by bantonsson** [comment]
@patriknw Stable you say. Yes, predictably failing 😉

**Comment by patriknw** [comment]
hm, that's to bad

We had an issue for StreamLayoutSpec https://github.com/akka/akka/issues/20627 (created yesterday)
and I have created a new for TickSourceSpec now https://github.com/akka/akka/issues/20638

The nightlies have not failed like this (yet).

**Comment by patriknw** [comment]
could it be some memory leak when touching all files?

I have enabled `-XX:+PrintGCDetails -XX:+PrintGCTimeStamps` (it was only for mult-node in the pr validator job). I thought we had that on all jobs. Rerunning.

**Comment by patriknw** [comment]
PLS BUILD

**Comment by patriknw** [comment]
@bantonsson yep, it's a memory issue.
```
3869.622: [Full GC (Ergonomics) [PSYoungGen: 664064K->29956K(674816K)] [ParOldGen: 1397768K->1398222K(1398272K)] 2061832K->1428178K(2073088K), [Metaspace: 505990K->505990K(1480704K)], 4.8297635 secs] [Times: user=130.61 sys=0.94, real=4.82 secs] 
[info] - should be able to decode chunk-by-chunk (depending on input chunks) *** FAILED *** (4 seconds, 927 milliseconds)
```

and there are more of these. We need to profile that build.

**Comment by bantonsson** [comment]
This has filled its purpose.

**Pull request closed without merging**
