### PR TITLE
Fix logic in TestKitUtils.scrubActorSystemName() Resolves #28994

### LINKED ISSUE #28994: Invalid sanitize of ActorSystem name in TestKitUtils
In akka.actor.ActorSystemImpl there is validation of name that allows the following pattern: `^[a-zA-Z0-9][a-zA-Z0-9-_]*$` and it is allowed to use hyphen in names, but according to logic in https://github.com/akka/akka/blob/master/akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/internal/TestKitUtils.scala
( and later this logic was moved to akka-testkit/src/main/scala/akka/testkit/TestKitUtils.scala in this commit
https://github.com/akka/akka/commit/1dbc54b28a0da5bc519b2203a1572de9950c875e#diff-5c099ba6a094171d9104fc162233f0c1 ) sanitization of ActorSystem name was narrowed and now it is not prossible to use hyphen in name anymore as it is being replaced with underscore.

So that if I have ActorSystem name called 'c-wallet' and it is running on production for a long time, I should rename it to 'c_wallet' if I want my tests work properly. 

I would suggest that sanitization should be more weak and do not replace hyphen in ActorSystem name.

### PR DESCRIPTION
**Pull request by andrii-r**
References #28994

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by andrii-r** [comment]
according to https://github.com/akka/akka/issues/29331 and https://github.com/akka/akka/issues/29298 the failing test does not depend on changes in this PR, seems this test is being failed periodically. Is it possible to rerun Jenkins job again to check if all tests are passed?

**Comment by johanandren** [comment]
PLS BUILD

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Review by raboof — APPROVED** [review]

**Pull request merged**
