### PR TITLE
Add NoSerializationVerificationNeeded to TimerMsg #27153

### PR DESCRIPTION
**Pull request by xeppaka**
## Purpose
Fixing issue #27153

## References

References #xxxx

## Background Context

CLA is signed

Not sure how to write tests for this (if needed).

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by raboof** [comment]
I wonder if this isn't superseded by #27517 - if so sorry about not pinging about it in the issue!

**Comment by raboof** [comment]
OK TO TEST

**Comment by xeppaka** [comment]
> I wonder if this isn't superseded by #27517 - if so sorry about not pinging about it in the issue!

Yep, I see, the solution is more common. In that case I can reopen PR for release 2.5 as it happens there.

**Comment by patriknw** [comment]
While we could target this for 2.5.x branch I'm afraid that there will be many more such messages in `-typed` modules. I'm  afraid we have to say that the `serialize-messages` testing features is not supported for Akka Typed in 2.5.x. It  will work in Akka 2.6 and we have published milestones if you want to switch now rather than waiting for upcoming 2.6.0.

**Comment by xeppaka** [comment]
> While we could target this for 2.5.x branch I'm afraid that there will be many more such messages in `-typed` modules. I'm afraid we have to say that the `serialize-messages` testing features is not supported for Akka Typed in 2.5.x. It will work in Akka 2.6 and we have published milestones if you want to switch now rather than waiting for upcoming 2.6.0.

No problem, It's not a big problem, just was annoying during the tests. Thanks for the explanation.

**Pull request closed without merging**
