### PR TITLE
Added markdown file type to MediaType text/markdown entry

### LINKED ISSUE #20138: Missing 'markdown' extension in MediaType text/markdown entry
Currently, only `md` extension is available with the `text/markdown` `MediaType` entry. The RFC document however specifies `markdown` also as an alternate extension.

### PR DESCRIPTION
**Pull request by venilnoronha**
This fixes #20138.

### CODE REVIEW

**Comment by ktoso** [comment]
Thanks, though it seems we already have it https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaType.scala#L428 :-)

**Comment by ktoso** [comment]
Closing as it's resolved already

**Comment by venilnoronha** [comment]
@ktoso the `markdown` entry seems to be present, however, it only supports `md` extension and not `markdown`. Could you please verify?

**Comment by ktoso** [comment]
Have a look at this PR's preview :wink: 

added_markdown_file_type_to_mediatype_text_markdown_entry_by_venilnoronha_ _pull_request__20139_ _akka_akka

**Comment by venilnoronha** [comment]
Doubt
I have a doubt. Just like `css` and `csv` entries, does `markdown` not need to have `markdown` specified 2 times? Markdown supports both `markdown` and `md` file types (As per the RFC document).

**Comment by ktoso** [comment]
Argh, you're right – I'm sorry I did not notice that, reopening and merging.

**Comment by venilnoronha** [comment]
@ktoso thank you!

**Comment by ktoso** [comment]
Thanks _you_! I would have totally missed that by just reviewing via github UI.

**Pull request merged**
