### PR TITLE
Don't initialize Lmdb when rememberEntities not used, #28567

### PR DESCRIPTION
**Pull request by patriknw**
* Sharding defines durable.keys in reference.conf
* That will trigger initialization of LmdbDurableStore for the
  ddata Replicator that is used by Sharding
* but that is only needed if rememberEntities is enabled
* This will optimize startup time for ClusterSharding,
  and reduced runtime complexity of accessing file system

Refs #28567

### CODE REVIEW

**Comment by patriknw** [comment]
I'll run this in a multi-node jenkins job to make sure nothing breaks

**Review by octonato — APPROVED** [review]

**Review by johanandren — APPROVED** [review]
LGTM

**Review by chbatey — APPROVED** [review]
Looks good, ready for merge?

**Comment by patriknw** [comment]
yes, multi-node tests were fine

**Pull request merged**
