### PR TITLE
#1732: Moved splitter and aggregator from Alpakka Docs to Cookbook and …

### PR DESCRIPTION
**Pull request by anthonyhlcheng**
…referenced Alpakka from cookbook

References [#1732](https://github.com/akka/alpakka/issues/1732)

### CODE REVIEW

**Review by johanandren — APPROVED** [review]

**Review by octonato — APPROVED** [review]
LGTM

**Comment by octonato** [comment]
Thanks for the contribution @anthonyhlcheng

**Comment by patriknw** [comment]
This was merged without testing, and that's why invalid format was merged to main.

**Comment by octonato** [comment]
> This was merged without testing, and that's why invalid format was merged to main.

I haven't done a force merge.

**Pull request merged**
