### PR TITLE
Serialization for more Cluster Sharding query messages

### PR DESCRIPTION
**Pull request by patriknw**
* GetClusterShardingStats
* ClusterShardingStats
* GetCurrentRegions
* CurrentRegions

There are 2 queries that are distributed via coordinator:
```
GetCurrentRegions => CurrentRegions(regions: Set[Address])

GetClusterShardingStats => ClusterShardingStats(regions: Map[Address, ShardRegionStats])
  ShardRegionStats(stats: Map[ShardId, Int])
```

Then there are 2 local queries:
```
GetShardRegionStats => ShardRegionStats(stats: Map[ShardId, Int])

GetShardRegionState => CurrentShardRegionState(shards: Set[ShardState])
  ShardState(shardId: ShardId, entityIds: Set[EntityId])
```

Funny enough, serialization for the local `GetShardRegionStats` was added by someone but not the true remote messages.

### CODE REVIEW

**Comment by patriknw** [comment]
This should be backported to support rolling updates. First step would be to add it but not bind the messages for serialization.

**Comment by patriknw** [comment]
Refs https://github.com/akka/akka/issues/26853

**Review by chbatey — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
Prerequisite for https://github.com/akka/akka/pull/27285

**Review by johanandren — APPROVED** [review]

**Pull request merged**
