### PR TITLE
Exposing the shard allocation strategy for the sharded daemon process

### PR DESCRIPTION
**Pull request by AndriusDap**
Exposing a shard allocation strategy for the sharded daemon process as per discussion [in the forum](https://discuss.lightbend.com/t/distribution-of-shardeddaemonprocess-actors/9628)

References #31320

### CODE REVIEW

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by AndriusDap** [comment]
@johanandren @patriknw Thanks for the reviews :) 

Though I see some binary compatibility tests are failing, A new `init` method was added, what's the process to get the CI to pass in this case?

**Comment by patriknw** [comment]
> Though I see some binary compatibility tests are failing, A new init method was added, what's the process to get the CI to pass in this case?

In this case it's fine to add method because the trait is not supposed to be extended by user. Add that exclusion by creating a file

akka-cluster-sharding-typed/src/main/mima-filters/2.6.19.backwards.excludes/issue-31320.excludes:
```
ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.cluster.sharding.typed.javadsl.ShardedDaemonProcess.init")
ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.cluster.sharding.typed.scaladsl.ShardedDaemonProcess.init")
```

**Review by johanandren — APPROVED** [review]

**Pull request merged**
