### PR TITLE
Exception description modified to reflect exclusion of 0 (#19709) timeout.

### PR DESCRIPTION
**Pull request by rbudzko**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @rbudzko,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
Ha! Glad you indeed made it to PR within today as we chatted :-)
Thanks a lot, fix looks good!

We'll need you to sign the CLA and this can go in (it's basically saying that you wrote the code, so people can't randomly sue us – see the Oracle/Google case etc).

Thanks a lot :)

**Comment by ktoso** [comment]
OK TO TEST

**Comment by rbudzko** [comment]
Agreed to the CLA.

**Comment by ktoso** [comment]
LGTM, thanks Robert :-)

**Comment by ktoso** [comment]
Refs #19709

**Comment by ktoso** [comment]
Thanks Robert!

**Pull request merged**
