### PR TITLE
Typo: hotname -> hostname

### PR DESCRIPTION
**Pull request by szarnyasg**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @szarnyasg,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by rkuhn** [comment]
Thanks, @szarnyasg, will merge after CLA is signed.

**Comment by patriknw** [comment]
LGTM after CLA

**Comment by ktoso** [comment]
Hi @szarnyasg, we would love to merge this but we need you to sign our CLA: http://www.typesafe.com/contribute/cla before we can do that.
It's a simple agreement to protect the open source license that Akka lives under.

Thanks!

**Comment by szarnyasg** [comment]
Sorry, I was on holiday -- I'll get back to this ASAP.

**Comment by kukido** [comment]
The typo was corrected as part of https://github.com/akka/akka/pull/17560
@szarnyasg I did not see your PR prior to my submission. I hope you don't mind.

**Comment by ktoso** [comment]
Thanks for pointing that out @kukido! I'll close this issue then.
Thanks a lot to both of your for helping out to keep the docs typo-free!

**Pull request closed without merging**
