### PR TITLE
fix the name of SinkModulePhase

### PR DESCRIPTION
**Pull request by Lbqds**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @Lbqds,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by Lbqds** [comment]
I signed the CLA.

**Comment by ktoso** [comment]
Thanks, LGTM

**Review by ktoso — APPROVED** [review]

**Review by johanandren — APPROVED** [review]

**Comment by johanandren** [comment]
OK TO TEST

**Comment by johanandren** [comment]
Unrelated fail.

**Comment by johanandren** [comment]
PLS BUILD

**Pull request merged**
