### PR TITLE
#20648 encoder now encodes all response types, not only successes

### PR DESCRIPTION
**Pull request by gosubpl**
- a change in Encoder letting it encode also non-successes
- CodingDirectivesSpec capturing new behaviour
- ExecutionDirectivesSpec capturing bug repro case

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Great research in the ticket, will dive into it in the morning, thanks!

**Comment by ktoso** [comment]
Refs #20648

**Comment by ktoso** [comment]
Commented in ticket, I'd personally like this change so LGTM, thanks for the research surounding the fix.
Would like to hear another person chime in though

**Comment by 2beaucoup** [comment]
LGTM

**Comment by ktoso** [comment]
Thanks for chiming in @2beaucoup !

**Pull request merged**
