### PR TITLE
=per #19688 [2.4.1][PersistentFSM] getting StateTimeout for state wit…

### PR DESCRIPTION
**Pull request by leonidb**
…hout timeout after restart

### CODE REVIEW

**Comment by leonidb** [comment]
Calling ```initialize()``` in a constructor of ```PersistentFSM``` is redundant, as it's called after recovery. It also might lead to bugs like the one from #19688.
I've made the ```initialize()``` method package private. This will cause a compilation errors (very easy to fix) during upgrade for users who do use this method in a constructor of ```PersistentFSM```.

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Uff, good that I just remembered that we're experimental here so no trouble in changing this.

Note for reviewers, this class has such note:
`This is an EXPERIMENTAL feature and is subject to change until it has received more real world testing.`

Perhaps adding a `@deprecated` on it as well would be a good idea - for people who used and called it explicitly it would show up as compile error and in the IDEs it'd show up as deprecated use.

**Comment by leonidb** [comment]
@ktoso how about something like:
```scala
@deprecated("Removed from API, called internally", "2.4.4")
```

**Comment by patriknw** [comment]
PLS REBUILD

**Comment by patriknw** [comment]
@leonidb please add that deprecation, otherwise looks good

**Comment by patriknw** [comment]
thanks, @leonidb

**Comment by patriknw** [comment]
Refs #19688

**Pull request merged**
