### PR TITLE
Merge scala & java content for typed-actors.md docs (#23052) 

### PR DESCRIPTION
**Pull request by gosubpl**
As usual, two commits:

1. Unification of content for both scala/typed.md and java/typed-actors.md that allows to clearly see the diff
2. Replacement of java/typed-actors.md with a symlink to scala/typed-actors.md

### CODE REVIEW

**Comment by gosubpl** [comment]
Refs #23052

**Comment by johanandren** [comment]
Java snippets should be added to the Scala markdown?

**Comment by raboof** [comment]
@johanandren I think this is a case of the github 'Files Changed' being broken when replacing files with symlinks - it looks better when you view the commits separately ;).

**Comment by johanandren** [comment]
Ah, thanks for pointing that out Arnout.

**Review by johanandren — APPROVED** [review]
LGTM, thanks a bunch!

**Review by raboof — APPROVED** [review]
Nice work!

**Comment by gosubpl** [comment]
@raboof @johanandren thanks!

**Pull request merged**
