### PR TITLE
 Fix error message when LinearTraversalBuilder module has more than one outlet

### PR DESCRIPTION
**Pull request by marcpiechura**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @marcpiechura,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Review by ktoso — APPROVED** [review]
nice catch, thanks

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Did this have a ticket associated with it?

**Comment by marcpiechura** [comment]
@ktoso I don’t think so, found it while porting the new materializer to Akka.Net

**Comment by ktoso** [comment]
Cool thanks 👍

**Pull request merged**
