### PR TITLE
Fixed Deploy productElement implementation #29104

### LINKED ISSUE #29104: Deploy implementation of Product interface is breaking Product iterator
`Product` iterator fails on `Deploy` with the following error:

```
scala.MatchError: 0 (of class java.lang.Integer)
	at akka.actor.Deploy.productElement(Deployer.scala:122)
	at scala.Product$$anon$1.next(Product.scala:41)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
...
```

I see that Deploy is using 1 based index ([see here](https://github.com/akka/akka/blob/0e4d41ad33dbeb00b598cb75b4d29899371bdc8c/akka-actor/src/main/scala/akka/actor/Deployer.scala#L122-L130
)) for its fields which is breaking contract and default implementation of `Product` iterator that expects 0 based index:

https://github.com/scala/scala/blob/v2.12.2/src/library/scala/Product.scala#L21-L28

### PR DESCRIPTION
**Pull request by klappvisor**
Fixed `Deploy#productElement` implementation to follow `Product` contract. 

References #29104

### CODE REVIEW

**Review by octonato — APPROVED** [review]

**Comment by renatocaval** [comment]
@klappvisor, thanks for that. 

I did a small edition to the descriptions. We avoid using "fixes" and "resolves" as it closes the issue automatically. We prefer to manage it ourselves so we can assign it to milestones when merged.

**Review by johanandren — APPROVED** [review]
LGTM

**Comment by johanandren** [comment]
Thanks @klappvisor

**Comment by johanandren** [comment]
Hmm, the checklist was green when I merged. Not sure what the late arrival of test success was about.

**Pull request merged**
