### PR TITLE
lastSequenceNumber in DurableStateBehavior, #30833

### PR DESCRIPTION
**Pull request by patriknw**
Failing test, but I haven't been able to find the bug yet. Can't see how it is different from EventSourcedBehavior.

References #30833

### CODE REVIEW

**Comment by johanandren** [comment]
It is because the sequence number extractor needs concrete behavior classes (`Running.HandlingCommands`, `Running.PersistingState`) to pick up the sequence number but `Recovering` uses `Behaviors
        .receiveMessage`

**Comment by patriknw** [comment]
Thanks. I didn't spot that difference when trying to compare with EventSourced.

**Comment by patriknw** [comment]
> It is because the sequence number extractor needs concrete behavior classes

I have implemented it like that now, please take a look.

**Review by johanandren — APPROVED** [review]
LGTM!

**Pull request merged**
