### PR TITLE
=doc s/will always by/will always be/  

### PR DESCRIPTION
**Pull request by etaty**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @etaty,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Typesafe Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by 2m** [comment]
Thanks for the PR and signing the CLA!

Could you squash both commits to one and change the commit message to be the same as the title of this PR (which is worded perfectly!)?

**Comment by etaty** [comment]
done

**Comment by 2m** [comment]
Great. Thanks!

**Pull request merged**
