### PR TITLE
!pro #17381 Remove cross build for Scala 2.10

### PR DESCRIPTION
**Pull request by patriknw**
- 2.12 will be added

### CODE REVIEW

**Comment by patriknw** [comment]
Refs #17381

**Comment by hepin1989** [comment]
nice to have 2.12 :)

**Comment by ktoso** [comment]
LGTM

**Comment by 2m** [comment]
LGTM

**Comment by drewhk** [comment]
LGTM

**Comment by hepin1989** [comment]
scala 2.12-m1 is released,so I think it's good to have for akka 2.4-m1.

**Comment by rkuhn** [comment]
LGTM

**Pull request merged**
