### PR TITLE
Fix the multiple invoke issue of JavaPartialFunction.apply in javadsl testkit

### PR DESCRIPTION
**Pull request by Hawstein**
Refs #23045

Since the `JavaPartialFunction.apply(x: A, isCheck: Boolean)` is called in `isDefinedAt` and `apply`, we have to just do nothing when `isCheck == true` because `apply(x, true)` is called in `isDefinedAt`.

### CODE REVIEW

**Comment by Hawstein** [comment]
Can not just 'do nothing' when `isCheck == true`.

Use a `CachingPartialFunction` instead since the methods using it definitely call `isDefinedAt(x)` before `apply(x)` with the same `x`.

**Comment by ktoso** [comment]
>  Can not just 'do nothing' when isCheck == true

Why not? I'd expect such impl to be valid:

```scala
      override def apply(x: Any, isCheck: Boolean): Boolean =
        if (isCheck) true
        else pf.apply(x)
```

this is just like a scala partial function can act like a "total function".

**Comment by Hawstein** [comment]
This is what i do at fist, however it does not act as expected because partial function may throw an `noMatch` exception which make `JavaPartialFunction.isDefinedAt` return false instead of true. 

What `JavaPartialFunction.isDefinedAt` return depends on the specific partial function, so a pre-defined `true/false` can not cover all situations.

**Comment by ktoso** [comment]
Which partial function may throw? We're given a total function from the user.

**Comment by Hawstein** [comment]
Just did a quick search, in `TestKitDocTest`
```scala
      // line 139
      final List<String> out = receiveWhile(duration("1 second"), in -> {
        if (in instanceof Integer) {
          return in.toString();
        } else {
          throw JavaPartialFunction.noMatch();
        }
      });

      // line 119
      final String out = expectMsgPF("match hint", in -> {
        if (in instanceof Integer) {
          return "match";
        } else {
          throw JavaPartialFunction.noMatch();
        }
      });
  ```

**Review by patriknw — APPROVED** [review]
LGTM

**Review by ktoso — APPROVED** [review]
A I see, thanks for digging that up @Hawstein :-)
LGTM

**Pull request merged**
