### PR TITLE
Remove test reliance on application.conf

### PR DESCRIPTION
**Pull request by chbatey**

### CODE REVIEW

**Review by patriknw — APPROVED** [review]
LGTM

**Review by johanandren — APPROVED** [review]
LGTM

**Comment by johanandren** [comment]
(Conflicts now though)

**Comment by ktoso** [comment]
I'd like to suggest trying to resolve merges for people in light of getting things merged more quickly, I mean this issue is:

resolve_conflicts_ _pull_request__25027_ _akka_akka

which we can solve for oneanother actively

**Comment by patriknw** [comment]
@ktoso I have been burned by the web editor, since squashing with the web ui when there are multiple authors will not do the right thing. Yes, I can do such things locally and push to others' branch but it's a bit of a dance (unless I'm doing it in way that's more complicated than necessary?)

**Pull request merged**
