### PR TITLE
=htc #16583 update comment to point to new issue

### LINKED ISSUE #16583: Investigate why HttpServer needs additional buffer
see the FIXME in HttpServer.scala

### PR DESCRIPTION
**Pull request by jrudolph**
Fixes #16583.

/cc @sirthias

### CODE REVIEW

**Comment by jrudolph** [comment]
Error lines in https://jenkins.akka.io/job/pr-validator-per-commit-jenkins/3347/:

```
 11477 Test akka.stream.javadsl.FlowTest.mustBeAbleToRecover failed: java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for 1, took 3.023 sec
 11478     at scala.Predef$.assert(Predef.scala:179)
 11479     at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:338)
 11480     at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:315)
 11481     at akka.testkit.TestKit.expectMsg(TestKit.scala:718)
 11482     at akka.testkit.JavaTestKit.expectMsgEquals(JavaTestKit.java:378)
 11483     at akka.stream.javadsl.FlowTest.mustBeAbleToRecover(FlowTest.java:548)
 11484     ...
 12554 Failed: Total 867, Failed 1, Errors 0, Passed 866, Pending 22
 12555 Failed tests:
 12556 	akka.stream.javadsl.FlowTest
 15923 (akka-stream-tests-experimental/test:test) sbt.TestsFailedException: Tests unsuccessful
 15924 Total time: 834 s, completed Aug 10, 2015 5:39:52 PM
```

**Comment by jrudolph** [comment]
Unrelated test failure.

**Comment by drewhk** [comment]
LGTM

**Comment by ktoso** [comment]
LGTM, thanks

**Pull request merged**
