### PR TITLE
=str #18002 FlowTest#mustBeAbleToRecover timing issue

### PR DESCRIPTION
**Pull request by agolubev**

### CODE REVIEW

**Comment by agolubev** [comment]
Ref #18002

**Comment by ktoso** [comment]
OK TO TEST

**Comment by drewhk** [comment]
Hmm, why did this change fix the issue? What is the underlying timing issue?

**Comment by agolubev** [comment]
Map is throwing exception (on the third element) which is handled as first priority. Consequently, all other messages potentially can be skipped. Fix removes list as source and introduce manual probe to divide good messages from one that throws exception and then recovers.

**Comment by drewhk** [comment]
Hm, but that looks like a bug in recovery. It should not skip elements until the recovery from the previous has been completed.

**Comment by agolubev** [comment]
Flow.recover based on Context.absorbTermination() mechanism which, I believe, stable.
There is a long discussion about treating failure in stream https://github.com/akka/akka/commit/051cf14dd0402848e7cbe7ac60bfc8fd7c46d6ff#commitcomment-8732566
The notion I got is: when failure happens it starts to destroy stream right away. Failure is propagating separately from all other events and can outrun some or all of them. This is exactly the case when recover test failed. The only we can do on failure is to send last event before destroy. 
Per my understanding there is no possibility to send more then one message for recovering, stop destroying stream, recover more then once.

**Comment by drewhk** [comment]
Ah, this is about the recover operation, not about supervision on the stage level. Yes, this is expected behavior then.

**Comment by drewhk** [comment]
LGTM

**Comment by agolubev** [comment]
Thanks

**Pull request merged**
