### PR TITLE
Removed UntypedPropsBehavior

### LINKED ISSUE #24962: remove Typed UntypedPropsBehavior
I don't think we need `UntypedPropsBehavior` any more. It was added for the first impl of persistence. Might be a nice to have, but I'd rather avoid the special cases until there is something more than an imaginary need for it.

### PR DESCRIPTION
**Pull request by jorgesg1986**
Fixes #24962

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Review by ktoso — APPROVED** [review]
LGTM once Jenkins happy; AFAIR we only needed it in initial persistence impl but don't need it nowadays so good to remove

**Review by ktoso — APPROVED** [review]
LGTM

**Comment by ktoso** [comment]
Thanks a lot, not much to debate here, clean removal :)

**Review by patriknw — COMMENTED** [review]
LGTM

**Pull request merged**
