### PR TITLE
Update dependencies and plugins

### PR DESCRIPTION
**Pull request by ElfoLiNk**
Dependencies:
- ssl config
- aeron
- scalacheck
- scalatest
- jctools-core
- lmdbjava
- spray-json
- gson
- commons-io
- commons-codec
- mockito-core

Plugins:
- [github-api](https://github.com/kohsuke/github-api/compare/github-api-1.68...github-api-1.93)
- [sbt-scalariform](https://github.com/sbt/sbt-scalariform/releases) 
- [sbt-mima-plugin](https://github.com/lightbend/migration-manager/releases)
- [sbt-pgp](https://github.com/sbt/sbt-pgp/releases)
- [sbt-unidoc](https://github.com/sbt/sbt-unidoc/releases)
- [sbt-api-mappings](https://github.com/ThoughtWorksInc/sbt-api-mappings/commits/2.1.x)
- [sbt-native-packager](https://github.com/sbt/sbt-native-packager/releases)
- [sbt-updates](https://github.com/rtimush/sbt-updates/releases)
- [sbt-git](https://github.com/sbt/sbt-git/releases)
- [sbt-dependency-graph](https://github.com/jrudolph/sbt-dependency-graph/commit/f4bbf2845966a8d07758e0a3fc00a041edb83e39)

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @ElfoLiNk,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
A bit en masse... but we'll see ;)

**Review by chbatey — APPROVED** [review]
LGTM, the non-test ones look to all be binary compatible

**Comment by johanandren** [comment]
All the sbt plugin updates makes me nervous as many of those only are exercised when we release and aren't covered by the PR validation.

I'd also like to add that in general I think it is better with single dependency/plugin upgrades motivated by some improvement than just upgrading a swoop of things just to be on latest.

**Comment by ElfoLiNk** [comment]
@johanandren  most of the updates are for improved Java 9/10 compatibility

**Comment by johanandren** [comment]
Yah, the mockito one I knew about. Potentially lmbd as well, but do you know about any other improvements in that regard?

**Comment by ElfoLiNk** [comment]
sbt-mima-plugins 0.3.0 fixes a runtime exception on Java 9's new tags, by ignoring them. But they removed also the MiMa Reporter CLI. Is akka using it ?

**Review by johanandren — APPROVED** [review]
MiMa is used in the pr validation so I think that'd fail if it was a problem. Let's merge this.

**Pull request merged**
