### PR TITLE
=doc typo fixes for Akka Streams documentation

### PR DESCRIPTION
**Pull request by hseeberger**

### CODE REVIEW

**Comment by ktoso** [comment]
Thanks Heiko :)

**Comment by hseeberger** [comment]
That was fast!!!

**Comment by ktoso** [comment]
That's what happens when I get enough sleep :-)

**Comment by hseeberger** [comment]
LOL! I wonder what happens if you take a couple of sleeping pills and sleep for two days. Maybe even merge a PR before it has been created?

**Pull request merged**
