### PR TITLE
remove async, #20562

### PR DESCRIPTION
**Pull request by patriknw**
Refs #20562

### CODE REVIEW

**Comment by patriknw** [comment]
No significant difference on CI servers https://jenkins.akka.io:8498/job/akka-artery-perf/plot/

I see improvement locally and this is a better base.

**Comment by drewhk** [comment]
Yep, I have also seen various results. Latency can in theory improve though.

**Comment by drewhk** [comment]
LGTM

**Comment by ktoso** [comment]
LGTM, let's go without the async for now as discussed

**Pull request merged**
