### PR TITLE
[htp] Fix Java RouteTest to not depend on scala DSL in API

### PR DESCRIPTION
**Pull request by jypma**
Fixes https://github.com/akka/akka/issues/20610

@ktoso

### CODE REVIEW

**Comment by ktoso** [comment]
Oh and that's it? :-) Let's hope so 👍

**Comment by ktoso** [comment]
OK TO TEST

**Comment by drewhk** [comment]
LGTM

**Comment by ktoso** [comment]
Uhm, plenty compile failures. Can you attempt to compile locally and get those sorted?
Help on this front would be very appreciated, thanks! 

```
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/HttpAPIsTest.java:24: akka.http.javadsl.HttpAPIsTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class HttpAPIsTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/CompleteTest.java:19: akka.http.javadsl.server.CompleteTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class CompleteTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/HandlerBindingTest.java:15: akka.http.javadsl.server.HandlerBindingTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class HandlerBindingTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/JavaRouteTest.java:28: akka.http.javadsl.server.JavaRouteTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class JavaRouteTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/MarshallerTest.java:18: akka.http.javadsl.server.MarshallerTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class MarshallerTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/UnmarshallerTest.java:16: akka.http.javadsl.server.UnmarshallerTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class UnmarshallerTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/directives/CodingDirectivesTest.java:27: akka.http.javadsl.server.directives.CodingDirectivesTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class CodingDirectivesTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/directives/CookieDirectivesTest.java:13: akka.http.javadsl.server.directives.CookieDirectivesTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class CookieDirectivesTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/directives/ExecutionDirectivesTest.java:20: akka.http.javadsl.server.directives.ExecutionDirectivesTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class ExecutionDirectivesTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/directives/HeaderDirectivesTest.java:17: akka.http.javadsl.server.directives.HeaderDirectivesTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class HeaderDirectivesTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/directives/HostDirectivesTest.java:17: akka.http.javadsl.server.directives.HostDirectivesTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class HostDirectivesTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/directives/MarshallingDirectivesTest.java:23: akka.http.javadsl.server.directives.MarshallingDirectivesTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class MarshallingDirectivesTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/directives/MiscDirectivesTest.java:21: akka.http.javadsl.server.directives.MiscDirectivesTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class MiscDirectivesTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/directives/ParameterDirectivesTest.java:19: akka.http.javadsl.server.directives.ParameterDirectivesTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class ParameterDirectivesTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/directives/PathDirectivesTest.java:18: akka.http.javadsl.server.directives.PathDirectivesTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class PathDirectivesTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/directives/RouteDirectivesTest.java:17: akka.http.javadsl.server.directives.RouteDirectivesTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class RouteDirectivesTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/directives/SchemeDirectivesTest.java:14: akka.http.javadsl.server.directives.SchemeDirectivesTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class SchemeDirectivesTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/directives/SecurityDirectivesTest.java:24: akka.http.javadsl.server.directives.SecurityDirectivesTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class SecurityDirectivesTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/examples/petstore/PetStoreAPITest.java:22: akka.http.javadsl.server.examples.petstore.PetStoreAPITest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class PetStoreAPITest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/examples/simple/SimpleServerTest.java:12: akka.http.javadsl.server.examples.simple.SimpleServerTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class SimpleServerTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/values/FormFieldsTest.java:17: akka.http.javadsl.server.values.FormFieldsTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class FormFieldsTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/akka/http/javadsl/server/values/HeadersTest.java:18: akka.http.javadsl.server.values.HeadersTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class HeadersTest extends JUnitRouteTest {
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-http-tests/src/test/java/docs/http/javadsl/server/HandlerExampleDocTest.java:25: docs.http.javadsl.server.HandlerExampleDocTest is not abstract and does not override abstract method createTestRouteResult(akka.http.javadsl.model.HttpRequest,akka.http.javadsl.server.RouteResult) in akka.http.javadsl.testkit.RouteTest
[error] public class HandlerExampleDocTest extends JUnitRouteTest {
[info] Compiling 2 Java sources to /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenk
```

**Comment by jypma** [comment]
Ah I should take `JUnitRouteTest` along for the ride of course. Will take a look.

**Comment by jypma** [comment]
@ktoso compiles now :)

**Comment by ktoso** [comment]
Just noticed :-)
I'll give it a quick review then right away, thanks!

-- 
Konrad `ktoso` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 30 May 2016 at 15:40:11, Jan Ypma (notifications@github.com) wrote:

@ktoso compiles now :)
On May 30, 2016 3:36 PM, "akka-ci" <notifications@github.com> wrote:

> Test PASSed.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/akka/akka/pull/20615#issuecomment-222494226>, or mute
> the thread
> <
https://github.com/notifications/unsubscribe/AAdgvweh-UPwWpiTjlOccZuzt3aA4lSRks5qGufpgaJpZM4IlcRU
>
> .
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka/pull/20615#issuecomment-222494923>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAHYk-2WNIeMgpyDHHN5oQWUyggBPDAhks5qGuixgaJpZM4IlcRU>
.

**Comment by ktoso** [comment]
LGTM, very sneaky to fix. Thanks a lot @jypma !

**Pull request merged**
