### PR TITLE
Fixing issue(GracefulShutdown empty region) #18762

### PR DESCRIPTION
**Pull request by kpbochenek**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @kpbochenek,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by ktoso** [comment]
Refs https://github.com/akka/akka/issues/18762

**Comment by ktoso** [comment]
OK TO TEST

**Comment by patriknw** [comment]
please squash to one commit and adjust the commit message to something like:

    =cls #18762 fix graceful shutdown of empty region

(this convention is described in https://github.com/akka/akka/blob/master/CONTRIBUTING.md)

**Comment by patriknw** [comment]
LGTM, thanks for contributing!

**Comment by kpbochenek** [comment]
@patriknw squashed and renamed.

**Comment by drewhk** [comment]
@kpbochenek this does not seem to merge cleanly anymore. Can you please rebase it? After that we will merge it.

**Comment by drewhk** [comment]
@ktoso have taken over this: https://github.com/akka/akka/pull/18911

I'll close this PR in favor of that one.

**Comment by ktoso** [comment]
Thanks for the fix @kpbochenek! We'll take it from here and hope to release a version with the fix very soon.

**Pull request closed without merging**
