### PR TITLE
Fix Broadcast examples, as they currently fail.

### PR DESCRIPTION
**Pull request by toshetah**
Use different outputs for broadcast

References #xxxx

### CODE REVIEW

**Review by raboof — APPROVED** [review]
good catch!

**Comment by raboof** [comment]
OK TO TEST

**Comment by toshetah** [comment]
@raboof , do you know anyone else that can approve this PR?

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by toshetah** [comment]
Thanks @patriknw ! Do you think we should merge this change into other branches such as v2.6.14?

**Pull request merged**
