### PR TITLE
Use Sources from akka.stream.io

### PR DESCRIPTION
**Pull request by aruediger**
/cc @jrudolph

### CODE REVIEW

**Comment by ktoso** [comment]
Excellent, LGTM :)

**Comment by ktoso** [comment]
OK TO TEST

**Comment by jrudolph** [comment]
Nice, LGTM.

**Comment by ktoso** [comment]
Thanks @2beaucoup !

**Comment by ktoso** [comment]
Resolves https://github.com/akka/akka/issues/15588

**Comment by drewhk** [comment]
nice!

**Pull request merged**
