### PR TITLE
Upgrade to SBT 1.1.0-RC2

### PR DESCRIPTION
**Pull request by chbatey**
This might be worth trying before the release as it contains a fix for
the NPE

### CODE REVIEW

**Comment by 2m** [comment]
Failure was https://github.com/akka/akka/issues/24119

**Comment by 2m** [comment]
PLS BUILD

**Review by raboof — APPROVED** [review]
Let's go for it :)

**Comment by chbatey** [comment]
:fearful:

**Comment by 2m** [comment]
Note that 1.1.x sports the new unified syntax for sbt keys. The old one is still supported, but the new one is now used in all of the output of sbt, like:
```
[error] (akka-stream-tests / Pr-validation / test) sbt.TestsFailedException: Tests unsuccessful
``` 

So it could be something that an eye is not used to.

**Comment by patriknw** [comment]
before merging, have you tried release dry-run?

**Comment by raboof** [comment]
tried a dry-run, was successful 👍

**Pull request merged**
