### PR TITLE
=htp backport for path traversal fix

### PR DESCRIPTION
**Pull request by jrudolph**
see akka/akka-http#346

Squashed from commits d37fa8ec0243c33cb65d76cb99fa980e3c78e8d5..a30eb85e114f07f5b9e8aae574351add8129ca9e.

### CODE REVIEW

**Comment by ktoso** [comment]
LGTM, thanks for backporting

**Comment by jrudolph** [comment]
Does PR validation  work for PRs against stream-http-2.0? It fails with a mima check:

```
java.lang.Exception: Failed building [/localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-samples/akka-docs-java-lambda] using maven!
	at akka.Maven$.mvnRun(Maven.scala:43)
	at akka.Maven$$anonfun$settings$4$$anonfun$apply$1.apply(Maven.scala:29)
	at akka.Maven$$anonfun$settings$4$$anonfun$apply$1.apply(Maven.scala:29)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at akka.Maven$$anonfun$settings$4.apply(Maven.scala:29)
	at akka.Maven$$anonfun$settings$4.apply(Maven.scala:25)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: akka-http-experimental: Binary compatibility check failed!
	at scala.sys.package$.error(package.scala:27)
	at com.typesafe.tools.mima.plugin.SbtMima$.reportErrors(SbtMima.scala:64)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaReportSettings$3.apply(MimaPlugin.scala:23)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaReportSettings$3.apply(MimaPlugin.scala:23)
	at scala.Function5$$anonfun$tupled$1.apply(Function5.scala:35)
	at scala.Function5$$anonfun$tupled$1.apply(Function5.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (akka/*:mvnExec) java.lang.Exception: Failed building [/localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-samples/akka-docs-java-lambda] using maven!
[error] (akka-http-experimental/*:mimaReportBinaryIssues) akka-http-experimental: Binary compatibility check failed!
```

**Comment by ktoso** [comment]
Wat, MiMa should not check akka-http-experimental and wasn't until recently, has this changed?

**Comment by ktoso** [comment]
Oh it's the 2.0 branch so I guess it could be enabled here, but does not have to - feel free to disable.

**Comment by ktoso** [comment]
And doc the change

**Comment by jrudolph** [comment]
tbh. I don't understand what it is doing there at all. Is the infrastructure still the same as when the branch was still active? 

Why is it doing something with `akka-samples` and maven?

```
java.lang.Exception: Failed building [/localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-samples/akka-docs-java-lambda] using maven!
    at akka.Maven$.mvnRun(Maven.scala:43)
```

**Comment by jrudolph** [comment]
Aha, there it is, somewhere in the middle and hard-to-find:

```
[info] akka-http-experimental: found 2 potential binary incompatibilities
[error]  * synthetic method akka$http$scaladsl$server$directives$FileAndResourceDirectives$$fileSystemPath$default$4()Char in object akka.http.scaladsl.server.directives.FileAndResourceDirectives does not have a correspondent in new version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.http.scaladsl.server.directives.FileAndResourceDirectives.akka$http$scaladsl$server$directives$FileAndResourceDirectives$$fileSystemPath$default$4")
[error]  * synthetic method akka$http$scaladsl$server$directives$FileAndResourceDirectives$$fileSystemPath(java.lang.String,akka.http.scaladsl.model.Uri#Path,akka.event.LoggingAdapter,Char)java.lang.String in object akka.http.scaladsl.server.directives.FileAndResourceDirectives does not have a correspondent in new version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("akka.http.scaladsl.server.directives.FileAndResourceDirectives.akka$http$scaladsl$server$directives$FileAndResourceDirectives$$fileSystemPath")
```

**Comment by jrudolph** [comment]
Why is mima checking private methods at all or maybe these are just some bridge methods the compiler doesn't mark properly? Anyways, added the filters... Revalidating...

**Comment by ktoso** [comment]
LGTM, thanks for blackporting here

**Pull request merged**
