### PR TITLE
Wip improve unfold inf √

### PR DESCRIPTION
**Pull request by viktorklang**

### CODE REVIEW

**Comment by viktorklang** [comment]
@rkuhn retargeted to master

**Comment by drewhk** [comment]
LGTM

**Comment by rkuhn** [comment]
LGTM—waiting for PR validation to actually work with Streams on master

**Comment by johanandren** [comment]
LGTM (even if I'm not agreeing 100% about removing the shortcut method)

**Comment by rkuhn** [comment]
PLS BUILD

**Comment by viktorklang** [comment]
PLS BUILD

**Pull request merged**
